planetarium/NineChronicles

.github/bin/check-libplanet-version.sh

fix github action

---

README.ko.md
README.md

English translation is added. Link to the Korean version will be added after merging.

add readme translation

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs

https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#logsV2:log-groups/log-group/9c-player-logs/log-events/33ddfa5e-6593-4067-9e26-621d48bae572

로깅시 런쳐의 클라이언트 id와 동일한 값을 사용하게 적용

---

.github/workflows/pack.yml

최소 단위는 30분입니다.
- 아사나 링크 1
- 깃헙 링크 2
필수로 확인해야하는 리뷰어의 깃헙 계정을 멘션해주세요.
- 변경된 방법을 방법을 가능한 한 자세히 적어주세요. 아래 두 줄은 예시입니다.
- `EquipmentItemRecipeSheet.csv`의 `required_gold` 값을 100으로 변경합니다.
- 장비를 조합했을때 100골드가 소모되는지 확인합니다.
UI가 변경된 경우 스크린샷을 찍어서 올려주세요.

Delete library cache

---

nekoyume/Assets/_Scripts/Game/Game.cs

1. disable cloud watch log upload

Disable upload log

---

nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - RankingLevel.mat
nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - RankingLevel.mat.meta
nekoyume/Assets/Resources/Font/Materials/English SDF Material - RankingLevel.mat
nekoyume/Assets/Resources/Font/Materials/English SDF Material - RankingLevel.mat.meta
nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - RankingLevel.mat
nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - RankingLevel.mat.meta
nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - RankingLevel.mat
nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - RankingLevel.mat.meta
nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - RankingLevel.mat
nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - RankingLevel.mat.meta
nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - RankingLevel.mat
nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - RankingLevel.mat.meta
nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - RankingLevel.mat
nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - RankingLevel.mat.meta
nekoyume/Assets/Resources/L10nSettings/FontAssetData ChineseSimplified SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData English SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Japanese SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Korean SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Polish SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData PortugueseBrazil SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Thai SDF.asset
nekoyume/Assets/_Scripts/L10n/FontMaterialType.cs

[Design] Font Material Type add

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

SSIA
@planetarium/9c-dev , @planetarium/9c-backend

Send error to Mixpanel

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs

Fix error message popup showing as Alert popup.

---

.github/workflows/pack.yml

Fix key of cache in github actions

---

nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs

Tracking tutorial progress using mixpanel

---

nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/BattleResult.cs

SSIA
- [Link](https://app.asana.com/0/1141562434100787/1200052092882519/f)

Changing dialog output condition

---

nekoyume/Assets/_Scripts/UI/Tutorial/Tutorial.cs

1. Blocks click spamming on tutorial.
1. Enter workshop tutorial.
2. Spam clicking while proceeding.
Already tested in #57, so only code review is required.

Blocking click spamming on tutorial

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/State/Subjects/GameConfigStateSubject.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs

SSIA
[Link](https://app.asana.com/0/1141562434100787/1200047627494672/f)

Fix action point directing using reactiveproperty

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab.meta
nekoyume/Assets/_Scripts/UI/DataLoadingScreen.cs
nekoyume/Assets/_Scripts/UI/DataLoadingScreen.cs.meta
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/Shop.cs

Fix to load shop state in the loading screen when entering the shop.
Open the shop door
[Link](https://app.asana.com/0/1141562434100787/1200059952991337/f)
@Namyujeong, @planetarium/9c-dev

Fix to load shop state in the loading screen when entering the shop.

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/BattleResult.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItem.cs
nekoyume/Assets/_Scripts/UI/Shop.cs

revert update actions

---

nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs

Fix daily bonus unrender

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs

Fix action point loading ui

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab.meta
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/State/Subjects/GameConfigStateSubject.cs
nekoyume/Assets/_Scripts/UI/BattleResult.cs
nekoyume/Assets/_Scripts/UI/DataLoadingScreen.cs
nekoyume/Assets/_Scripts/UI/DataLoadingScreen.cs.meta
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
nekoyume/Assets/_Scripts/UI/Shop.cs
nekoyume/Assets/_Scripts/UI/Tutorial/Tutorial.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs

Merge rc into development

---

.github/bin/check-libplanet-version.sh
nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab.meta
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/State/Subjects/GameConfigStateSubject.cs
nekoyume/Assets/_Scripts/UI/BattleResult.cs
nekoyume/Assets/_Scripts/UI/DataLoadingScreen.cs
nekoyume/Assets/_Scripts/UI/DataLoadingScreen.cs.meta
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
nekoyume/Assets/_Scripts/UI/Shop.cs
nekoyume/Assets/_Scripts/UI/Tutorial/Tutorial.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs

1. Merge branch `rc-v100037` into `main`

Merge rc into main

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

Subject says it all
1. Launch a headless node
2. Run the game.
3. Check the log at the bottom right
[Link](https://app.asana.com/0/1141562434100787/1200079077758565/f)
@planetarium/9c-dev , @planetarium/9c-backend

Initialize the block state at the start of the application

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Popup/ActionFailPopup.cs
nekoyume/Assets/_Scripts/UI/Popup/SystemPopup.cs
nekoyume/Assets/_Scripts/UI/Popup/UpdatePopup.cs

1. Saperate quit logic in `SystemPopup`.
2. `SystemPopup.ShowAndQuit()` method only to quit the game now.

Saperate quit logic in SystemPopup

---

nekoyume/Assets/_Scripts/UI/Combination.cs
nekoyume/Assets/_Scripts/UI/Module/CombinationPanel.cs
nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
nekoyume/Assets/_Scripts/UI/Module/EnhancementPanel.cs

1. Fixes an issue where the button is dimmed when attempting to craft in the Combination UI.
1. It's okay if it's not a tutorial.
2. When you enter the Combination UI in various ways(Lobby, Guided Quest, Workshop Slot) and try to make it, check if the button works well.
1. [튜토리얼에서 장비 제작 버튼이 활성화되지 않아 더이상 진행이 불가능할 때가 있음](https://app.asana.com/0/1141562434100787/1166137970512323/f)

Bug fix/dimmed combination button

---

nekoyume/Assets/Editor/StateViewer.cs
nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/State/ShopProducts.cs
nekoyume/Assets/_Scripts/State/ShopProducts.cs.meta
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Module/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Shop.cs

Initialize shop items from ShardedShopState

---

nekoyume/Assets/_Scripts/UI/Menu.cs

SSIA
1. Enter workshop tutorial and check if workshop button is properly clickable.
@Namyujeong and @planetarium/9c-dev

Prevent NRE when entering workshop in tutorial.

---

nekoyume/Assets/Resources/L10nSettings/FontAssetData ChineseSimplified SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData English SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Japanese SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Korean SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Polish SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData PortugueseBrazil SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Thai SDF.asset
nekoyume/Assets/Resources/Tutorial/Prefab/Item_DialogBox.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
nekoyume/Assets/_Scripts/L10n/FontMaterialType.cs

Fixed a problem where the tutorial dialogue did not come out properly
1. Let's do a tutorial.
- [link](https://app.asana.com/0/1141562434100787/1200167810702257/f)
- @planetarium/9c-dev , @Namyujeong

Fix tutorial dialog prefab

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfo.prefab

SSIA
1. Enter arena and see other player's title text and check if it is properly displayed.
@Namyujeong or @planetarium/9c-dev

Disable RTL Text on FriendInfoPopup's titletext.

---

nekoyume/Assets/Resources/Atlas/Atlas_Common.spriteatlas
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs

bugfix renewal shop

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs

- Delete market item dimming
- Modify button brightening when mouse over disabled Buy button
- [link](https://app.asana.com/0/1141562434100787/1200150904082465/f)
- [link](https://app.asana.com/0/1141562434100787/1200174712312606/f)

Delete market item dimming and  modify button brightening when mouse over disabled Buy button

---

nekoyume/Assets/_Scripts/UI/Menu.cs

SSIA
1. Delete all `PlayerPrefs`.
2. Enter avatar that cleared more than 4 stages and check if tutorial is not playing.

Fix condition on tutorial.

---

nekoyume/Assets/_Scripts/UI/CelebratesPopup.cs

SSIA
1. Make CelebratesPopup appear, and check if its texts are fully localized on appear animation.

Localize continueText in CelebratesPopup on Initialize

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs

Fix BuyMultiple action

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab

Link missing variable

---

nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs

Add a mixpanel event to check the number of items purchased

Add mixpanel event

---

nekoyume/Assets/_Scripts/UI/Cheat.cs

SSIA
- Press the keyboard number button. (1,2,3,4)
@Namyujeong , @plafina2 , @planetarium/9c-dev

Add timeScale Controller to cheat

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/LoginDetail.cs

SSIA
1. [판매 성공시 메일로 안내가 오고 있는지 확인하고, 혹시 오지 않으면 복구하기](https://app.asana.com/0/1141562434100787/1200200941411773/f)

Fix mail bug on successful sell

---

nekoyume/Assets/_Scripts/UI/VersionInfo.cs

Fix IndexOutOfRangeException in VersionInfo

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/State/ShopProducts.cs
nekoyume/Assets/_Scripts/State/ShopProducts.cs.meta
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs

- It uses sharded shop state with the old store state. Later, only sharded shop state will be used.
@planetarium/9c-dev , @ipdae

Apply sharded shop state

---

nekoyume/Assets/Resources/Character/Monster/201000.prefab

Fix 201000 monster prefab

---

nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs

Repeat toggle not pressed when the game starts

---

nekoyume/Assets/_Scripts/State/ShopProducts.cs

Bugfixes that the goods sold are not visible on sell item inventory
@planetarium/9c-dev , @ipdae

Fix ShopProducts

---

nekoyume/Assets/Resources/Tutorial/Animation/Emoji/Tutorial_Emoji_Type_02.anim

Fix tutorial emoji type 2 animation

---

nekoyume/Assets/_Scripts/State/ShopProducts.cs

Change shop state exception handling

---

nekoyume/Assets/_Scripts/State/ShopProducts.cs

Clear products when update product

---

.gitignore

Exclude logs, usersettings folder in version control.

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/UI/Mail.cs

Remove LocalLayerModifier in Read method

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/RecipeCellView.prefab

Asana Link: https://app.asana.com/0/958521740385861/1196299741444142

[Design] notice icon hierarchy change

---

nekoyume/Assets/_Scripts/State/ShopProducts.cs

Fix bug where last sell item were not visible on sell inventory

---

nekoyume/Assets/_Scripts/State/ShopProducts.cs

Merge rc-v100042 into development

---

nekoyume/Assets/_Scripts/State/ShopProducts.cs

Merge rc-v100042 into main

---

nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs

- Fix default value of `CommandLineParser.storageType` to "rocksdb"
- Fix typo
- Fix `NullReferenceException`

Fix default value of `CommandLineParser.storageType` to "rocksdb"

---

nekoyume/Assets/Editor/Module.meta
nekoyume/Assets/Editor/Module/EnumGeneratorEditor.cs
nekoyume/Assets/Editor/Module/EnumGeneratorEditor.cs.meta
nekoyume/Assets/_Scripts/Game/ScriptableObject/ScriptableObjectIncludeEnum.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/ScriptableObjectIncludeEnum.cs.meta
nekoyume/Assets/_Scripts/Game/Util/EnumGenerator.cs
nekoyume/Assets/_Scripts/Game/Util/EnumGenerator.cs.meta

- You can edit enum values ​​in the Unity inspector.
**- Inherit ScriptableObjectIncludeEnum and put the desired Enum Type in the template.**
ex:  
public class YourScriptableObject : **ScriptableObjectIncludeEnum<**YourEnumType**>**
{
}
**- Create editor class for YourScriptableObject
- Inherit EnumGeneratorEditorand put the desired Enum Type in the template.**
ex:
[CustomEditor(typeof(YourScriptableObject))]
public class YourScriptableObject Editor : **EnumGeneratorEditor<**YourEnumType**>**
{
}
**Apply**
- Add values ​​to the Enums list
- Click the `Apply List to Enum` button
**Fix**
- Click the `Get Enum to List` button
- Fix values ​​to the Enums list
- Click the `Apply List to Enum` button

Add enum generator

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BlockChainMessageBoard.prefab
nekoyume/Assets/_Scripts/State/ShopProducts.cs

Apply expired block index to shop products

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BlockChainMessageBoard.prefab
nekoyume/Assets/_Scripts/State/ShopProducts.cs

Merge rc-v100043 into main

---

nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
nekoyume/Assets/_Scripts/UI/FriendInfoPopup.cs

Initialize character order when entering the room

---

nekoyume/Assets/StreamingAssets/Localization/common.csv

Fix Ranking menu text
`RANKING` > `Ranking`
just check the file change.

Fix ranking text

---

nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - Paper.mat
nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - Paper.mat.meta
nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - Paper.mat
nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - Paper.mat.meta
nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - Paper.mat
nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - Paper.mat.meta
nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - Paper.mat
nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - Paper.mat.meta
nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - Paper.mat
nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - Paper.mat.meta
nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - Paper.mat
nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - Paper.mat.meta
nekoyume/Assets/Resources/L10nSettings/FontAssetData ChineseSimplified SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData English SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Japanese SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Korean SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Polish SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData PortugueseBrazil SDF.asset
nekoyume/Assets/Resources/L10nSettings/FontAssetData Thai SDF.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
nekoyume/Assets/_Scripts/L10n/FontMaterialType.cs

FontStlye link Change
[Before]
[After]

[Bugfix] Synopsis FontStlye Change

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab

Fix UI_WorldMap prefab

---

nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs

SSIA
- Repeat battle
- [아바타 타이틀이 몬스터와 섞이는 현상 (칭호 장착여부와는 상관없는듯)](https://app.asana.com/0/1141562434100787/1200332397143104/f)
- [[전투] 몹 체력 바 UI가 출력되지 않는 현상](https://app.asana.com/0/1141562434100787/1200331047514334/f)

Modify hpbar to output normally

---

nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab
nekoyume/Assets/_Scripts/UI/FriendInfoPopup.cs

SSIA
@BBeom06 , @planetarium/9c-dev

Polishing friendinfopopup

---

nekoyume/Assets/_Scripts/State/Modifiers/AgentGoldModifier.cs

1. In Unity editor, try enhancement any equipment with NCG
1. [NCG 사용 강화 구간에서 예외 발생](https://app.asana.com/0/1141562434100787/1200344988120415/f)

Fix bug: change serialize method for `Currency`

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

Bug fix/exception occurred when serialize `Currency`

---

nekoyume/Assets/_Scripts/UI/Module/Button/SubmitWithCostButton.cs

SSIA
- [상점 아이템 팝업 가격에 NCG 문자 제거하기](https://app.asana.com/0/1141562434100787/1200357332425286/f)

Fix price text of button

---

nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

Fix freezing issue when tapping in the shop

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab

[Design] Change image

---

nekoyume/Assets/AddressableAssets/TableCSV/GameConfigSheet.csv

1. This reverts commit 698aff6a84953bddf36235d5c4c49f8214620382.

Revert "[sheet change] GameConfigSheet.csv"

---

nekoyume/Assets/Tests/EditMode/RapidCombinationTest.cs
nekoyume/Assets/Tests/EditMode/StateModifierTest.cs
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
nekoyume/Assets/_Scripts/UI/Popup/CombinationSlotPopup.cs

SSIA
- [[제작] 마켓에 판매 등록되어있는 모래시계의 수량을 포함하여 총 개수가 출력되는 현상 (클라이언트)](https://app.asana.com/0/1133453747809944/1200370704141431/f)
@planetarium/9c-dev , @ipdae , @Namyujeong

Fix the hourglass on sale to not count

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

SSIA
- [[마켓] 구매 알림과 판매 알림이 겹쳐서 노출되는 현상](https://app.asana.com/0/1141562434100787/1200370704141437/f)
@Unengine

Chagne from Notification to OneLinePopup

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/InventoryItemView.prefab
nekoyume/Assets/_Scripts/UI/Model/Inventory.cs
nekoyume/Assets/_Scripts/UI/Model/InventoryItem.cs
nekoyume/Assets/_Scripts/UI/Model/Item.cs
nekoyume/Assets/_Scripts/UI/Module/Item/InventoryItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

1.  Connect ui to tradable item
2. Fix to show only tradable item in the s…
- [[UI] 슬롯 판매불가 표시 추가](https://app.asana.com/0/958521740385861/1200388701375319/f)
- @Namyujeong , @planetarium/9c-dev

Connect UI to tradable item

---

nekoyume/Assets/Resources/UI/Prefabs/UI_OneButtonPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_OneButtonPopup.prefab.meta
nekoyume/Assets/_Scripts/UI/Mail.cs
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/OneButtonPopup.cs
nekoyume/Assets/_Scripts/UI/OneButtonPopup.cs.meta

SSIA
- [[개선] 상점 판매를 취소 하면 수신되는 우편 메시지 받기 시, 노출되는 팝업에서의 버튼 개선 요청](https://app.asana.com/0/958521740385861/1197985787658097/f)
@Namyujeong  , @planetarium/9c-dev

Change sell cancellation popup

---

nekoyume/Assets/Resources/UI/Prefabs/UI_LoginDetail.prefab

- Lable ScrollView add
1. First step.
- Login > Ch change
[Before]
[After]

[Design] Font Spacing Scroll add

---

nekoyume/Assets/Tests/EditMode/StateModifierTest.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/Extension/ItemExtensions.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/Modifiers/AvatarInventoryTradableItemRemover.cs
nekoyume/Assets/_Scripts/UI/BattleSimulator.cs
nekoyume/Assets/_Scripts/UI/EnhanceEquipment.cs
nekoyume/Assets/_Scripts/UI/Mail.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

SSIA
Play
- EnhanceEquipment
- Combination
- Sell
- Sell cancel
- Buy
- Cook
https://github.com/planetarium/NineChronicles/issues/228

Fix LocalLayer Modifier(AvatarInventoryTradableItemRemover)

---

nekoyume/Assets/Tests/EditMode/CombinationEquipmentTest.cs
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/UI/BattleResult.cs

version up list
- MimisbrunnrBattle
- HackAndSlash
- CombinationConsumable
- DailyReward
- ItemEnhancement
- CombinationEquipment

update action version

---

nekoyume/Assets/_Scripts/UI/Model/Inventory.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

Modify force notification when ActiveFunc value changes

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/NotificationCell.prefab
nekoyume/Assets/AddressableAssets/UI/Module/CellView/RecipeCellView.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_OneLinePopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Rank.prefab

- OneLinepopup Area
- Rank titleText

[bugfix] Onelinepopup Area / Rank TitleText Change

---

nekoyume/Assets/StreamingAssets/Localization/common.csv

minor bug fix
just check the file

fix translation

---

nekoyume/Assets/_Scripts/UI/Mail.cs
nekoyume/Assets/_Scripts/UI/Model/Rank.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
nekoyume/Assets/_Scripts/UI/Quest.cs
nekoyume/Assets/_Scripts/UI/Rank.cs

1. Fix toggle tab transition bug in `Mail`, `Quest`.
2. Restore "not implemented" popup on `Rank`.

Fix toggle tab transition bug in `Mail`, `Quest` and restore alert on `Rank`.

---

nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

SSIA
Sell items
- [[마켓] Material 아이템 개별 판매 금액을 소수점 단위로 하여 판매할 경우 남아있는 보유 수량이 비정상적인 현상](https://app.asana.com/0/1133453747809944/1200413250524113/f)
- [[마켓] Material 아이템 판매 시 보유 수량을 모두 판매하지 않을 경우 수량이 차감되지 않고 그대로 노출되는 현상](https://app.asana.com/0/1133453747809944/1200413250524094/f)
@Namyujeong , @Unengine

Remove the local layer when selling materials

---

nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
nekoyume/Assets/_Scripts/UI/Menu.cs

SSIA
#Related Links
- [Link](https://app.asana.com/0/1133453747809944/1200413250524059/f)

Disable hud container when entering tutorial stage 4

---

nekoyume/Assets/_Scripts/UI/Model/Rank.cs

This PR fixes freezing before entering the lobby.
1. First step.

Fix UI freezing before entering the lobby

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Rank.prefab
nekoyume/Assets/_Scripts/UI/Rank.cs

- Fix bug on displaying `UI_RANKING_API_MISSING` message on loading Ranking.

Fix bug on displaying error message in `Rank`.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab

[Bugfix] indicator image Change / Ch>Block

---

nekoyume/Assets/Resources/Atlas/Atlas_Common.spriteatlas
nekoyume/Assets/Resources/Atlas/Atlas_Shop.spriteatlas
nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

Unlock Shop, Add price to purchase info

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Popup/ItemCountableAndPricePopup.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

SSIA
- [[마켓] 특정 스텝 이후 판매 팝업창 내 가격이 소수점 단위로 노출되는 현상](https://app.asana.com/0/1133453747809944/1200413250524086/f)
- [[판매] 재료 아이템(모래시계, AP포션) 판매후 판매불가능한 아이템이 보이는 이슈](https://app.asana.com/0/1133453747809944/1200413701672993/f)
-  [[마켓] 판매 상품 등록 후 Material 탭에서 노출되는 상품이 비정상적인 현상](https://app.asana.com/0/1133453747809944/1200413250524074/f)

Polishing sell popup

---

nekoyume/Assets/_Scripts/UI/AvatarInfo.cs
nekoyume/Assets/_Scripts/UI/FriendInfoPopup.cs
nekoyume/nekoyume.sln.DotSettings

SSIA
1. Check the character spine not disappear when close the avatar information popup.

Bug fix/avatar info popup character spine disappeared

---

nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

Fix TryGetShopItemFormAgentProducts method

---

nekoyume/Assets/AddressableAssets/UI/Module/Button/YellowButton_02.controller
nekoyume/Assets/Resources/UI/Prefabs/UI_QuitPopup.prefab

[hotfix] fix broken prefab link of `QuitPopup`

---

nekoyume/Assets/_Scripts/UI/Popup/ItemCountableAndPricePopup.cs

SSIA
1. Enter shop and go to 'Sell' tab.
2. Try to sell items with checking price inputfield properly gets various input.

Fix bug in editing price value in shop.

---

nekoyume/Assets/_Scripts/UI/AvatarInfo.cs

SSIA
[[소모품] 행동력 포션 사용 후에 남아있는 행동력에 대한 팝업이 나타나지 않아 추가 사용 시 바로 사용되는 현상](https://app.asana.com/0/1133453747809944/1200464312143880/f)

Add refill confirm popup

---

nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

Fix TryGetShopItemFromAgentProducts method

---

nekoyume/Assets/Resources/Atlas/Atlas_Common.spriteatlas
nekoyume/Assets/Resources/Atlas/Atlas_Shop.spriteatlas
nekoyume/Assets/_Scripts/UI/Model/ShopItem.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs

Bug fix/failed to sell cancellation for old shop item in UI

---

nekoyume/Assets/Resources/Atlas/Atlas_Common.spriteatlas
nekoyume/Assets/Resources/Atlas/Atlas_Shop.spriteatlas
nekoyume/Assets/_Scripts/UI/Model/ShopItem.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs

We'll release v100050 from `main` at this time.

Release v100050

---

nekoyume/Assets/_Scripts/UI/Module/Stat/DetailedStatView.cs

SSIA 
- [레시피에 최소 0.83 이상 능력치가 붙는다고 되어 있는데, 실제 장비에는 0.8 능력치가 붙은 현상 조사](https://app.asana.com/0/1141562434100787/1200278832741433/f)
@planetarium/9c-dev , @Namyujeong 
`BEFORE`
`AFTER`

Show stat to two decimal places

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/LoginPopup.cs
nekoyume/nekoyume.sln.DotSettings

[첫 화면에서 뻗어버리는 문제 탐색을 위한 로그 심기](https://app.asana.com/0/1141562434100787/1200496035115205/f)

Add some logs

---

nekoyume/Assets/Resources/UI/Animations/LoadingImageContainerController@Idle.anim
nekoyume/Assets/Resources/UI/Animations/UIMenuController@Show.anim

- menu noti Animation key
- indicator Animation key

[Bugfix] Animation key Change

---

nekoyume/Assets/_Scripts/Nekoyume.asmdef
nekoyume/Assets/_Scripts/UI/FriendInfoPopup.cs
nekoyume/Nekoyume-editor.csproj.DotSettings
nekoyume/Nekoyume.csproj.DotSettings
nekoyume/nekoyume.sln.DotSettings

1. Fix Nekoyume.asmdef to resolving some warns of namespace policy
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200503063341364) by [Unito](https://www.unito.io)

Fix namespace warnings

---

nekoyume/Assets/_Scripts/UI/RankingBoard.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs

SSIA
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200504565637551) by [Unito](https://www.unito.io)

Fix NRE in ArenaRankCell UI when curren AvatarState is not exists in CurrentWeeklyArenaState

---

nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

* Remove what has been blocked from selling materials
* Sell materials
@planetarium/9c-dev , Namyujeong
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200516209298946) by [Unito](https://www.unito.io)

Enable sell material

---

nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs

* Remove magic number in Combination related local layer
* craft equipment
#448 
@planetarium/9c-dev , Namyujeong
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200529760752833) by [Unito](https://www.unito.io)

Remove magic number

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Rank.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/UI/Rank.cs

SSIA
@planetarium/9c-dev Namyujeong
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200530232980111) by [Unito](https://www.unito.io)

Implement refreshing ranking on error.

---

LICENSE

This PR modifies LICENSE for [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) as we decided.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200534270170089) by [Unito](https://www.unito.io)

Licensing (AGPLv3)

---

nekoyume/Assets/_Scripts/State/ReactiveShopState.cs

- Deactive expired products in sell list

Deactive expired products in sell list

---

nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/AvatarTooltip.cs
nekoyume/Assets/_Scripts/UI/Module/Character/VanillaCharacterView.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs

- Fixed the battle result screen to appear
- Fixed to enable item enhancement

Fix how to get avatar state

---

nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs

SSIA
1. Enter arena with unregistered character. (Avatar which haven't performed any battle in current season.)
1. Check if the NRE is not thrown.
@planetarium/9c-dev Namyujeong
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200548290125191) by [Unito](https://www.unito.io)

Fix nre in ArenaRankCell.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Rank.prefab
nekoyume/Assets/_Scripts/UI/Rank.cs

SSIA
1. Enter ranking and check if category buttons working properly.
https://app.asana.com/0/1133453747809944/1200546248627550

Fix bug in changing tabs in ranking.

---

nekoyume/Assets/_Scripts/UI/Model/Rank.cs
nekoyume/Assets/_Scripts/UI/Rank.cs

SSIA
1. Enter world ranking and check if nre is not happening.

Fix NRE in ranking.

---

nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs

SSIA
Enter the shop
[[마켓] 분류 정렬 항목중 rank order 이라는 항목이 노출되는 현상](https://app.asana.com/0/1133453747809944/1200563893585779/f)

When entering the shop, sort filter is initialized in class

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/SpineEditor.cs
nekoyume/Assets/_Scripts/Game/Character/PlayerSpineController.cs

- Validate Player and FullCostume spine assets contains costume slots

Improve `SpineEditor`

---

nekoyume/Assets/_Scripts/L10n/LanguageType.cs

1. [[언어] 인게임 번역이 적용되지 않는 현상](https://app.asana.com/0/1133453747809944/1200563893585803/f)
2. [[국가 전반] 마켓 아이템 검색 UI내 placeholder가 영어로 출력되는 현상](https://app.asana.com/0/1133453747809944/1200563893585773/f)

Consider `pt_BR` in `LanguageTypeWrapper`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DailyRewardItemPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_MonsterCollectionRewardsPopup.prefab

1. Set localization key to buttons of the `MonsterCollectionRewardsPopup` prefab.
1. [데일리 리워드, 몬스터콜렉션 리워드 팝업 버튼 레이블이 안뜸](https://app.asana.com/0/1133453747809944/1200578999172748/f)

Fix button text of `MonsterCollectionRewardPopup`

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Game/ShopProducts.cs
nekoyume/Assets/_Scripts/Game/ShopProducts.cs.meta
nekoyume/Assets/_Scripts/UI/EnhanceEquipment.cs
nekoyume/Assets/_Scripts/UI/ItemInformationTooltip.cs
nekoyume/Assets/_Scripts/UI/Model/Inventory.cs
nekoyume/Assets/_Scripts/UI/Model/Item.cs

SSIA
- @planetarium/9c-dev , @ipdae , @Namyujeong

Fix to display items registered in the old shop state

---

nekoyume/Assets/_Scripts/UI/Mail.cs

Update notification only for reduce UI freeze

---

nekoyume/Assets/_Scripts/UI/Mail.cs

cherry pick mail freeze

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs

Apply `CreateAvatar` "create_avatar3"

---

nekoyume/Assets/_Scripts/UI/Mail.cs

main release v100061

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Game/Stage.cs

SSIA
1. Check if freezing is reduced right before the battle result is shown.

Make updating avatar states async in battle.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Dialog.prefab
nekoyume/Assets/_Scripts/UI/Dialog.cs

SSIA
Just check files and screenshots

fix timer style

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

Bump submodule

---

nekoyume/Assets/Resources/UI/Animations/UICombinationController_Craft.controller
nekoyume/Assets/Resources/UI/Animations/UICombinationController_Craft@Show.anim
nekoyume/Assets/Resources/UI/Animations/UICombinationController_Craft@Show_Equip.anim
nekoyume/Assets/Resources/UI/Animations/UICombinationController_Craft@Show_Food.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Craft.cs
nekoyume/Assets/_Scripts/UI/Module/ToggleDropdown/Toggle.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs

SSIA
1. Switch category tabs randomly in combination window and close it.
2. Join combination window again and check if initial category tab is switched properly.

Fix bug in combination tab transition.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemInformationTooltip.prefab
nekoyume/Assets/_Scripts/UI/ItemInformationTooltip.cs

SSIA
1. Click or drag description area on `ItemInformationPopup` and check if it's not closed.

Prevent closing popup on clicking description of `ItemInformationPopup`.

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Mail.cs

1. Fix subscription target from `CreateAvatar2` to `CreateAvatar`(3)
2. Fix NRE

Bug fix/create avatar subscribe and nre

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/State/Subjects/AgentStateSubject.cs
nekoyume/Assets/_Scripts/UI/Combination.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Module/EnhancementPanel.cs

SSIA
1. Play several battle and check if it is working properly.

Fix bug in handling task on render `BattleResult`.

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/UpgradeEquipment.cs

Bugfix and Change ratio digits

---

nekoyume/Assets/_Scripts/UI/Mail.cs

Fixed NRE issue when reading purchase confirmation email

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/UIResources/Content/Combination/Item_RecipeSlot.prefab
nekoyume/Assets/_Scripts/Helper/RecipeHelper.cs
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/CombinationMain.cs
nekoyume/Assets/_Scripts/UI/Craft.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs

SSIA
1. Create a character and proceed to combination guided quest.
2. Check if indicator is properly displaying.
3. Craft the indicated gear and check if it is updated properly.

Restore guided quest combination indicator.

---

nekoyume/Assets/_Scripts/Game/Character/Player.cs
nekoyume/Assets/_Scripts/UI/AvatarInfo.cs
nekoyume/Assets/_Scripts/UI/FriendInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Model/ItemInformationTooltip.cs

SSIA
1. Check there's no elemental icon in the name of costume.

Remove elemental icon on costumes.

---

nekoyume/Assets/_Scripts/Game/Prologue.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/Battle.cs
nekoyume/Assets/_Scripts/UI/BattleResult.cs
nekoyume/Assets/_Scripts/UI/Craft.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs

SSIA
1. Set `IsEditor` variable to `false` and proceed tutorial.
2. Check prologue and tutorial is working properly with `HeaderMenu` closed.
3. Click on guided quest about equipment combination and check if navigates on the target recipe properly.

Restore guided quest and hide `HeaderMenu` on tutorial.

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/CombinationMaterialView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/ItemView/EnhancementMaterialView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/ItemView/InventoryItemView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/ItemView/RequiredItemView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ShopBuyItemView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ShopItemView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/ItemView/SimpleCountableItemView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/ItemView/SimpleItemView.prefab
nekoyume/Assets/Resources/ScriptableObject/UI_OptionTagData.asset
nekoyume/Assets/Resources/ScriptableObject/UI_OptionTagData.asset.meta
nekoyume/Assets/_Scripts/Game/ScriptableObject/OptionTagData.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/OptionTagData.cs.meta
nekoyume/Assets/_Scripts/Game/ScriptableObject/OptionTagDataScriptableObject.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/OptionTagDataScriptableObject.cs.meta
nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs

SSIA
1. Check if option rank image color is properly displayed.
@planetarium/9c-dev @BBeom06

Use HSV instead of RGB in option rank image.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/Craft.cs
nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs

SSIA
1. Check if clicking on unsubmittable contents shows error popup.

Add one line popups on `Craft` ui.

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/Hourglass.prefab
nekoyume/Assets/_Scripts/UI/Module/Hourglass.cs
nekoyume/Assets/_Scripts/UI/Module/Hourglass.cs.meta

SSIA
- [[메뉴] 모래시계 수량 실 수량으로 보여주도록](https://app.asana.com/0/958521740385861/1200700251978524/f)

Display hourglass

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ItemInformationTooltip.prefab
nekoyume/Assets/_Scripts/UI/Mail.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
nekoyume/Assets/_Scripts/UI/Module/ItemInformation.cs

SSIA
1. Check if option count is properly displayed in `ItemInformation`.
https://app.asana.com/0/958521740385861/1200719002569202

Show option count in `ItemInformation`.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
nekoyume/Assets/_Scripts/UI/CombinationLoadingScreen.cs
nekoyume/Assets/_Scripts/UI/CombinationMain.cs
nekoyume/Assets/_Scripts/UI/Craft.cs
nekoyume/Assets/_Scripts/UI/SpeechBubble.cs

SSIA
1. Check if polishes of 'Related Links' are applied properly.
https://app.asana.com/0/958521740385861/1200703786388674
https://app.asana.com/0/958521740385861/1200659889320120
https://app.asana.com/0/958521740385861/1200693422660170

Minor polishing of `UI_Craft`.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemInformationTooltip.prefab
nekoyume/Assets/_Scripts/UI/ItemInformationTooltip.cs

Revive double click in ItemInformationTooltip

---

nekoyume/Assets/_Scripts/BlockChain/StorePath.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/Model/Inventory.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

https://github.com/planetarium/lib9c/pull/541

Introduce inventory lock 

---

nekoyume/Assets/_Scripts/UI/Mail.cs

1. Check inventory when receive `CombinationMail` or `ItemEnhanceMail`
1. [[결과화면] 메일로 아이템을 받고 결과화면까지 본 이후에도 인벤토리에 아이템이 즉시 들어오지 않음](https://app.asana.com/0/958521740385861/1200728314415802/f)

Bug fix/local layer task of `CombinationMail` and `ItemEnhanceMail`

---

nekoyume/Assets/Resources/UI/Animations/UIDialogController@Show.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_StageProgressBar.prefab
nekoyume/Assets/_Scripts/UI/BattleResult.cs
nekoyume/Assets/_Scripts/UI/Craft.cs
nekoyume/Assets/_Scripts/UI/StageProgressBar.cs

SSIA
1. Check if issues in 'Related Links' are resolved.
https://app.asana.com/0/958521740385861/1200666243035451
https://app.asana.com/0/958521740385861/1200666243035465
https://app.asana.com/0/958521740385861/1200744717346137

Minor bug fixes

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/RecipeCellView.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
nekoyume/Assets/_Scripts/UI/CelebratesPopup.cs

SSIA
1. Check if `CelebratesPopup` shows updated recipe view properly.

Update `CelebratesPopup` to show new recipe view.

---

nekoyume/Assets/_Scripts/UI/CombinationLoadingScreen.cs
nekoyume/Assets/_Scripts/UI/Craft.cs

SSIA
1. Check if crafting premium of mimir recipe displays proper amount of block index in speech bubble.

Fix mismatching blockindex in craft.

---

nekoyume/Assets/_Scripts/UI/UpgradeEquipment.cs

Disable Option UI when enhancement result value is zero
- @planetarium/9c-dev

Disable Option UI when enhancement result value is zero

---

nekoyume/Assets/Resources/UI/Prefabs/UI_MimisbrunnrPreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
nekoyume/Assets/_Scenes/Game.unity
nekoyume/Assets/_Scripts/UI/RankingBoard.cs

SSIA
- [[NPC] 일부 NPC 다시 거대해짐](https://app.asana.com/0/958521740385861/1200744717346139/f)

Resize spine raw image

---

nekoyume/Assets/Resources/UI/Prefabs/UI_MimisbrunnrPreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPreparation.prefab
nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs
nekoyume/Assets/_Scripts/UI/StageInformation.cs

SSIA
- [[전투준비] 미미르, 월드 전투준비 페이지 타이틀 수정 {월드이름} {stageNo}로 수정](https://app.asana.com/0/958521740385861/1200757969884724/f)

Set the backbutton label in battle preparation

---

nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapWorld.cs

Fix toggle enable state to match map page count

---

nekoyume/ProjectSettings/UnityConnectSettings.asset

Enable unity cloud diagnostics

---

nekoyume/Assets/_Scripts/EnumType/CloseKeyType.cs
nekoyume/Assets/_Scripts/EnumType/CloseKeyType.cs.meta
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Alert.cs
nekoyume/Assets/_Scripts/UI/AvatarInfo.cs
nekoyume/Assets/_Scripts/UI/ChatPopup.cs
nekoyume/Assets/_Scripts/UI/CombinationResultBackup.cs
nekoyume/Assets/_Scripts/UI/CombinationSlots.cs
nekoyume/Assets/_Scripts/UI/EnhancementResultBackup.cs
nekoyume/Assets/_Scripts/UI/LoginPopup.cs
nekoyume/Assets/_Scripts/UI/Mail.cs
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/Popup/ActionFailPopup.cs
nekoyume/Assets/_Scripts/UI/Popup/ItemCountableAndPricePopup.cs
nekoyume/Assets/_Scripts/UI/PopupWidget.cs
nekoyume/Assets/_Scripts/UI/Quest.cs
nekoyume/Assets/_Scripts/UI/Rank.cs
nekoyume/Assets/_Scripts/UI/Widget.cs

- **Escape widget list**
- [[기타] 팝업닫기는 esc로 매핑하고, 아무 팝업도 떠있지 않은 상태에서 esc를 누르면 종료팝업이 뜨도록](https://app.asana.com/0/958521740385861/1200757969884751/f)

link escape key

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/Craft.cs

SSIA
1. Click on craft guided quest and check if category is properly changed on showing craft window.
2. Check if no error occurred on showing craft window.
https://app.asana.com/0/958521740385861/1200799603199355
https://app.asana.com/0/958521740385861/1200799644541001

Implement changing equipment tab on clicking guided quest.

---

nekoyume/Assets/_Scripts/UI/Mail.cs

1. SSIA
2. Submodule: https://github.com/planetarium/lib9c/pull/564

Bug fix/mail disapear

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSimulator.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSimulator.prefab.meta
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Cheat.cs
nekoyume/Assets/_Scripts/UI/CombinationSimulator.cs
nekoyume/Assets/_Scripts/UI/CombinationSimulator.cs.meta

- A tool to verify crafting and enhancement probabilities
- This tool references table sheets in the 9c repository (not a lib9c table sheet)
- The meaning of the percentages in the log is as follows: `expected value` --> `result value`
- [제작, 강화 대성공/성공/실패 확률 검증용 테스트 짜기](https://app.asana.com/0/958521740385861/1200757969884740/f)
- @planetarium/9c-dev , @Namyujeong , @plafina2

Add combination simulator

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
nekoyume/Assets/_Scripts/UI/CombinationLoadingScreen.cs

SSIA
1. Check if npc on `CombinationLoadingScreen` is displaying properly.

Appear crafting npc on `RenderTexture`.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSimulator.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_VanilaTooltip.prefab
nekoyume/Assets/_Scripts/UI/Module/VanilaTooltip.cs
nekoyume/Assets/_Scripts/UI/Popup/ItemCountableAndPricePopup.cs
nekoyume/Assets/_Scripts/UI/QuitPopup.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

SSIA
- [Sell에서 아이템 판매 팝업을 esc로 닫은 후 인벤토리 아이템 포커스가 안풀리는 문제 수정](https://app.asana.com/0/958521740385861/1200799644540993/f)

Polishing and bugfix

---

nekoyume/Assets/_Scripts/UI/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/Module/AvatarStats.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs

SSIA
[[캐릭터] 캐릭터 선택&인벤토리에서 캐릭터 기본스탯에 (+n)값을 합하여 보여주고 (+n) 임시로 숨기기](https://app.asana.com/0/958521740385861/1200703786388866/f)
- @Namyujeong , @planetarium/9c-dev

Modified to show sum of basic stats and additional stats

---

nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs

SSIA
- [[공방] 제작 슬롯으로 공방 진입 시 workshop 씬이 아닌 craft 씬으로 이동되는 현상](https://app.asana.com/0/1133453747809944/1200807881396798/f)
- 

Link combination slot to combination  main

---

nekoyume/Assets/_Scripts/Helper/ResourcesHelper.cs

SSIA
equip weapon
[[아이템] 무기 이펙트가 10강 이상부터 쭉 나와야 하는데, 10강만 나오고 11강부터 안나옴](https://app.asana.com/0/958521740385861/1200815461319500/f)
@planetarium/9c-dev . @Namyujeong

Modified the weapon level 10 or higher to show effect.

---

nekoyume/Assets/_Scripts/UI/CodeReward.cs
nekoyume/Assets/_Scripts/UI/CombinationMain.cs

Manage exceptions

---

nekoyume/Assets/_Scripts/UI/EnhancementResult.cs

Fix `EnhancementResult` UI always `GreatSuccess`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/_Scripts/UI/Menu.cs

Fix button of `CombinationMain` in lobby

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfo.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenu.prefab
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/Module/EquipmentInventory.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs

- Fixed to show sum of basic stats and additional stats (MimisbrunnrPreparation, QuestPreparation)
- Fixed to AvatarInfo stencil object
- [[기타] 아이템 장착할 때 기본스탯 + 추가스탯 합산해서 보여야함](https://app.asana.com/0/958521740385861/1200817569914206/f)
- [[기타]캐릭터창 위아래 스텐실 이미지(흰색) 보이는 이슈](https://app.asana.com/0/958521740385861/1200817854225518/f)
- [[강화] 인벤토리 필터를 건 후 다른 장비 카테고리로 넘어갔을 때 필터가 적용되지 않음](https://app.asana.com/0/958521740385861/1200815461319503/f)
- [[기타] 행동력 충전 후 데일리 리워드 받을때 데일리 리워드 팝업이 메일보다 뒤에 그려짐](https://app.asana.com/0/958521740385861/1200817626103730/f)
- [[메뉴] 번영도 클릭 시 스태미너 획득 연출 없어짐](https://app.asana.com/0/958521740385861/1200817672250847/f)

Bugfix and polishing

---

nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RecipeListview.prefab
nekoyume/Assets/_Scripts/UI/ItemSheetExtension.cs
nekoyume/Assets/_Scripts/UI/LocalizationExtension.cs
nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeRow.cs

SSIA
Check if issues in 'Related Links' below are resolved.
https://app.asana.com/0/958521740385861/1200815462027441
https://app.asana.com/0/958521740385861/1200817626103700
https://app.asana.com/0/958521740385861/1200815462027432

Minor bug fixes of craft label.

---

nekoyume/Assets/_Scripts/UI/UpgradeEquipment.cs

SSIA
- [[UI] 강화  화면에서 우측 능력치 보여주는곳에  전체 능력치 보이도록](https://app.asana.com/0/1133453747809944/1200834378488588/f)

Fixed to always show options

---

nekoyume/Assets/StreamingAssets/Localization/common.csv

1. After `{0}` add NCG, this script shows ...NCGG
2. Remove G from original market mail script
1. Check Mailbox
None
@Namyujeong

Remove unnecessary G on the market script

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs

Update rpc interface for remote rpc mode. see also https://github.com/planetarium/NineChronicles.Headless/pull/653

Update rpc interface

---

nekoyume/Assets/Resources/UI/Animations/UICombinationResult@GreatSuccess.anim
nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapStage.cs

- Worldmap image change
- Combination animation fix
Test
- Build Test = O
- unity Test = O

[Bugfix] Worldmap Stage image Change

---

nekoyume/Assets/_Scripts/UI/Quest.cs
nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs

1. SSIA
1. Receive rewards of any quest.
2. Check notification.
[[퀘스트] 퀘스트 보상 획득 시에도 퀘스트 탭 UI에 빨콩 표시가 출력되는 현상](https://app.asana.com/0/0/1200851193239814/f)

Fix issue that quest category notification does not close

---

nekoyume/Assets/RenderTexture/DialogueSpineRenderTexture.renderTexture
nekoyume/Assets/RenderTexture/DialogueSpineRenderTexture.renderTexture.meta
nekoyume/Assets/Resources/UI/Prefabs/UI_PrologueDialog.prefab
nekoyume/Assets/_Scenes/Game.unity
nekoyume/Assets/_Scripts/UI/CombinationResult.cs
nekoyume/Assets/_Scripts/UI/PrologueDialog.cs

1. [[프롤로그] 다이얼로그 스파인 오더 정리](https://app.asana.com/0/958521740385861/1200814851909841/f)
2. [[공방] 제작 완료 후 아이템 획득 시 노출되는 이펙트가 잘못 설정된 현상](https://app.asana.com/0/1133453747809944/1200859412957727/f)

Bug fix/prologue spine order

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StageLoadingScreen.prefab
nekoyume/Assets/_Scripts/UI/BattleResult.cs
nekoyume/Assets/_Scripts/UI/StageLoadingScreen.cs
nekoyume/Assets/_Scripts/UI/StageTitle.cs

SSIA
1. Play any stage in MimisBrunnr
[[미미르의 샘] 다음 스테이지 로딩 텍스트와 인디케이터 위치가 겹치는 현상](https://app.asana.com/0/1141562434100787/1200904787622234/f)
**before**
**after**

Fix stage title and id string, ui position of MimisBrunnr

---

nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/State/Modifiers/AgentGoldModifier.cs
nekoyume/Assets/_Scripts/State/Modifiers/AvatarActionPointModifier.cs
nekoyume/Assets/_Scripts/State/Modifiers/AvatarDailyRewardReceivedIndexModifier.cs

1. NCG
2. Actipn Point
3. Daily Reward received block index
1. [강화 후에 골드 잔액이 잘못 표시됩니다.](https://app.asana.com/0/1141562434100787/1200193332087229/f)
2. [골드 -로 표기될 때가 여전히 있음](https://app.asana.com/0/1141562434100787/1200703786388769/f)
3. [AP potion doesn't sync properly with UI](https://app.asana.com/0/1141562434100787/1200502991561614/f)
4. [AP충전 이후 AP Meter에 반영 안됨](https://app.asana.com/0/1141562434100787/1200896148579234/f)
5. [번영도 사용이 안 되는 제보](https://app.asana.com/0/1141562434100787/1200877153459515/f)

Ignore some of local state modifiers

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfo.prefab

SSIA
[[개선] 캐릭터 정보 UI에 닫기 버튼이 보이도록 건의](https://app.asana.com/0/1141562434100787/1192493017001467/f)

Add close button to avatar info ui

---

nekoyume/Assets/_Scripts/UI/AnimatedGraphics/MessageCat.cs
nekoyume/Assets/_Scripts/UI/MessageCatManager.cs
nekoyume/Assets/_Scripts/UI/Module/Button/CategoryButton.cs
nekoyume/Assets/_Scripts/UI/Module/Button/CategoryTabButton.cs
nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
nekoyume/Assets/_Scripts/UI/Module/MainMenu.cs

SSIA
1. Hover mouse cursor on object that show message cat.
2. Check message cat.
[안내 고양이 툴팁이 인게임 카메라 움직일 때마다 사라지는 현상](https://app.asana.com/0/1141562434100787/1200446907799085/f)

Fix message cat turning off at the wrong timing

---

nekoyume/Assets/_Scripts/Extension/ItemExtensions.cs
nekoyume/Assets/_Scripts/UI/LocalizationExtension.cs
nekoyume/Assets/_Scripts/UI/Module/ItemInformation.cs

SSIA
1. Check food or material in item information or mail.
[[UI] 음식과 재료에는 아이템 이름과 아이템 정보에 속성정보 없도록](https://app.asana.com/0/0/1200833998719781/f)

Do not show elemental type of material and food

---

nekoyume/Assets/_Scripts/UI/BattleResult.cs

Fix repeat mimisbrunnr battle bug

---

nekoyume/Assets/Resources/UI/Prefabs/UI_MimisbrunnrPreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPreparation.prefab
nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs

SSIA
1. Click quest start button.
2. Try to interact any UI.
[전투 시작 버튼 누른 후에 장비를 장착할 수 있는 문제](https://app.asana.com/0/1141562434100787/1183842825139329/f)

Block interact when after enter to quest

---

nekoyume/Assets/_Scripts/UI/Model/Item.cs
nekoyume/Assets/_Scripts/UI/Module/ItemInformation.cs

1. Display old equipment's option tags.
1. Check if old equipment's `ItemView` properly displays option tags.
2. Check if test styles of `Tradable` and `Untradable` are properly applied.
https://app.asana.com/0/958521740385861/1200888226950622
https://app.asana.com/0/958521740385861/1200807286941951

Fix bug in displaying option tag.

---

nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RecipeSlot.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SpeechBubble.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SpeechBubbleWithItem.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/UI/CombinationMain.cs
nekoyume/Assets/_Scripts/UI/SpeechBubble.cs

SSIA
Enter to combination main UI.
[[제작] 제작 메인에서 고양이 말풍선 UI 추가 필요](https://app.asana.com/0/958521740385861/1200833060744671/f)

Add speech bubble to combination main

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

1. Revert timeout criteria from 3600 to 360 seconds.
2. Do not ignore error 27 anymore.

Revert timeout criteria

---

scripts/update-libplanet.ps1

This PR adds a script to build and update Libplanet in handy.

Add build script for libplanet

---

nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/OneButtonPopup.cs
nekoyume/Assets/_Scripts/UI/TwoButtonPopup.cs

Change depth of `OneButtonPopup` and `TwoButtonPopup`

---

nekoyume/Assets/Editor/Builder.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Cheat.cs
nekoyume/Assets/_Scripts/UI/Login.cs

- **Consider broken `AvatarState`**
- Improve builder script
- Fix cannot create a avatar to empty slot
- Fix useless line
- Comment speed cheat

Consider broken `AvatarState` in `UI_Rank`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab

SSIA
1. Enter to Arena
before
after

Fix issue that can not resizing speech bubble in arena

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

Fix RenderBlock

---

nekoyume/Assets/_Scripts/UI/AvatarInfo.cs
nekoyume/Assets/_Scripts/UI/FriendInfoPopup.cs

SSIA
[[아레나] 전투 후 캐릭터 정보 창 UI에서 아바타를 불러오지 못하는 현상](https://app.asana.com/0/1133453747809944/1200991032273805/f)
@Namyujeong , @Unengine

Clear player when close info popup

---

nekoyume/Assets/_Scripts/UI/LocalizationExtension.cs
nekoyume/Assets/_Scripts/UI/Mail.cs

Bug fix/invalid casting exception in mail

---

nekoyume/Assets/_Scripts/UI/BattleResult.cs

SSIA
1. Clear stage which is the last stage of the world. (ex : stage 50, 100, etc...)
https://app.asana.com/0/1133453747809944/1200995614264032
@Namyujeong @planetarium/9c-dev (optional)

Turn off `BattleWinVFX` on dialog.

---

nekoyume/Assets/_Scripts/Extension/AvatarExtensions.cs
nekoyume/Assets/_Scripts/Extension/AvatarExtensions.cs.meta
nekoyume/Assets/_Scripts/UI/RankingBoard.cs

Bump submodule to `rc-v100079`

---

nekoyume/Assets/_Scripts/UI/Mail.cs

Consider non sub recipe craft when receive mail

---

nekoyume/Assets/_Scripts/UI/RankingBoard.cs

Increase the list so that users can target more opponents.
1. First step.

[hotfix] raise arena list

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs

Fixed to show enhancement effect only for level 10 or higher
sell item
[10강 이상만 아이템 아이콘 이펙트 뜨도록 재수정](https://app.asana.com/0/1141562434100787/1201083991970190/f)

Fix enhancement effect enable condition

---

nekoyume/Assets/_Scripts/UI/Widget.cs

Refactor code about managing state of Widget

---

nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs

Separate workshop slot caching space by avatar
1. Send combination action.
2. Change avatar 
3. Check combination slot
https://app.asana.com/0/1133453747809944/1201086111224405/f

Separate workshop slot caching space by avatar

---

nekoyume/Assets/_Scripts/UI/Module/EquipmentInventory.cs

SSIA
Upgrade item
[[공방] 강화 시도 시 슬롯 스크롤이 상단으로 초기화 되는 현상](https://app.asana.com/0/1133453747809944/1201074248891290/f)

Maintain inventory scroll position when enhancing items

---

nekoyume/Assets/_Scripts/Extension/ItemExtensions.cs
nekoyume/Assets/_Scripts/UI/Alert.cs
nekoyume/Assets/_Scripts/UI/Blur.cs
nekoyume/Assets/_Scripts/UI/Confirm.cs
nekoyume/Assets/_Scripts/UI/LocalizationExtension.cs
nekoyume/Assets/_Scripts/UI/Model/Item.cs
nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs

SSIA
1. Check if issues in 'Related Links' are resolved.
https://app.asana.com/0/1133453747809944/1201052373468536
https://app.asana.com/0/1133453747809944/1201074248891268

Minor bug fixes.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab

1. SSIA
2. Add mask to spine image.
1. Enter to Shop-Buy menu.
2. Click items on the right.
[마켓>구매 우측 아이템들 클릭을 할 수가 없어서 구매가 불가. NPC가 클릭됨](https://app.asana.com/0/1141562434100787/1201083686768318/f)

Fix issue that can't buy items on the right at the shop

---

nekoyume/Assets/_Scripts/UI/RankingBoard.cs

Merge `rc-v100080` into `main`

---

nekoyume/Assets/Resources/Tutorial/Animation/Single.anim
nekoyume/Assets/_Scripts/UI/Menu.cs

SSIA
1. Check if tutorial progresses properly.
https://app.asana.com/0/1133453747809944/1201074248891280

Fix tutorial infinite loop.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_UpgradeEquipment.prefab

Change scroll direction top to bottom
Try scrolling your inventory on the upgrade page
[[UI] 공방 강화창에서 스크롤 바를 아래로 내렸는데 반대로 스크롤이 위로 올라가는 현상 (반대로 동작)](https://app.asana.com/0/1133453747809944/1201108741174397/f)

Change scroll direction top to bottom

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

[bugfix] tutorial Guide Area Change

---

nekoyume/Assets/_Scripts/Extension/AvatarExtensions.cs
nekoyume/Assets/_Scripts/UI/Module/Character/VanillaCharacterView.cs
nekoyume/Assets/_Scripts/UI/RankingBoard.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs

1. SSIA
1. #800 
2. [[UI] 코스튬을 장착한 캐릭터의 초상화가 아레나 화면에서는 코스튬을 장착하지 않은 상태의 초상화가 노출되는 현상](https://app.asana.com/0/1141562434100787/1200457522197598/f)

Bug fix/consider fullcostume when draw portrait in ranking board

---

nekoyume/Assets/_Scripts/UI/BattleResult.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs

1. Add one line popup in booster button
2. Move result VFX to UI from Game scene
1. Try to run the booster on a stage that is not completely cleared.

Improve battle booster

---

nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenu.prefab
nekoyume/Assets/_Scripts/UI/AvatarInfo.cs
nekoyume/Assets/_Scripts/UI/HeaderMenu.cs
nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs

SSIA
1. Try to use AP potion when while charging AP.
2. Or, Try to get Daily bonus when while charging AP.
[번영도 클릭, AP포션 사용 등 행동력 충전중 상태일 때 프론트에서 막기](https://app.asana.com/0/1133453747809944/1201038445462383/f)

Block charge AP when charging AP

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/IAgent.cs
nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
nekoyume/Assets/_Scripts/Helper/ArenaHelper.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Model/Rank.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Module/Character/VanillaCharacterView.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/MailCell.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/AvatarTooltip.cs

1. resolve #905 
2. introduce `GetBalanceAsync`
1. First step.

use GetStateAsync & introduce GetBalanceAsync

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs

- Bump lib9c
- Wait https://github.com/planetarium/lib9c/pull/713

Bump submodules

---

nekoyume/Assets/Resources/UI/Animations/UIWidgetController.controller

[bugfix] menu animation Addtive > override

---

nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs

SSIA
1. Enter to any stage.
2. Check speech bubble of player character.
[[UI] 스테이지 이동 모션 중에 화면이 과도하게 흔들리는 현상](https://app.asana.com/0/1133453747809944/1193593499144043/f)
@planetarium/9c-dev @Namyujeong 
Before
After

Fix shaking Speech bubble

---

nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

SSIA
1. Enter the game
2. Click any menu fastly
[[UI] 플레이어 실행 후 메인 진입 즉시 타 메뉴 진입할 경우 UI가 비정상적으로 출력되는 현상](https://app.asana.com/0/1133453747809944/1201283809917481/f)

Add interaction blocking when showing menu widget

---

nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs

SSIA
Buy multiple products at the shop

Fixed an issue where BuyMultiple freezes

---

README.ko.md
README.md
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
tools/Updater/README.md
tools/Updater/Updater.Common/LauncherSettings.cs
tools/Updater/resources/launcher.json

Opening a new PR without bumping [lib9c] since #937 failed to build (possibly due to unrelated updates).
[lib9c]: https://github.com/planetarium/lib9c

Remove unused optional argument minimum difficulty.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs

SSIA
1. Enter to workshop menu.
2. Try to touch npc.
[[공방] 공방 메뉴에서 드베르그를 클릭해도 특수 모션이 노출되지 않음](https://app.asana.com/0/1133453747809944/1201283809917493/f)
[NPC에 터치/클릭 애니메이션을 추가하기](https://www.notion.so/planetarium/NPC-219b88ee6f654d6e92b2cba3aec75113)

Add click animation to npc of conbination main UI

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_MimisbrunnrPreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPreparation.prefab

- inventory/Friend CP text bugfix
- world/mimir Character Area Down
- Font Rebundling

Bugfix/add costume UI

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab

[Design] RawImage Size 600 > 400

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

Change `States.SetAgentState()` to ` SetAgentStateAsync()`

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/IAgent.cs
nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
nekoyume/Assets/_Scripts/Helper/ArenaHelper.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Model/Rank.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Module/Character/VanillaCharacterView.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/MailCell.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/AvatarTooltip.cs

Merge `rc-v100085` into `main`

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

1. resolve #942 
2. use UniTask.Run instead of getStateAsync call.
1. First step.

fix ui freezing

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SpeechBubble.prefab
nekoyume/Assets/_Scripts/UI/Widget/Hud/SpeechBubble.cs

SSIA
1. Check any speech bubble.
[일부 언어에서 문장이 말풍선을 빠져나가는 문제](https://app.asana.com/0/1141562434100787/1201344147839811/f)

Fix resizing logic of speech bubble

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab

SSIA
1. Turn on the game.
2. Enter to character UI.
3. Check CP.
[[UI] CP값이 0으로 출력되는 현상](https://app.asana.com/0/1133453747809944/1201363577476555/f)

Fix a issue that CP appears to be 0

---

nekoyume/Assets/_Scripts/UI/Model/Item.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs

SSIA
1. Check if item option tags are properly displayed on items in shop.
https://app.asana.com/0/1133453747809944/1201269644395190

Add option tag on `ShopItemView`.

---

nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

- Logic refactoring to automatically select avatars. Save slot index instead avatar address.
- Change ranking board display count from 10 to 100
- [메인화면 캐릭터 안나타나는 문제](https://app.asana.com/0/1133453747809944/1201366117666910/f)
- [[랭킹] 랭킹보드 유저 리스트가 10위까지만 보이는 현상](https://app.asana.com/0/1133453747809944/1201374400486137/f)
- @planetarium/9c-dev

Logic refactoring to automatically select avatars

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemInformationTooltip.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv

- ItemTooltip Area Change
[https://app.asana.com/0/1133453747809944/1201357578102875](url)

[Bugfix] itemtooltip Area Change

---

nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

Fix stuck in synopsis

---

nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab

[bugfix] tutorial guide Area change fix

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

1. [[전투] (220 이후 스테이지에서만) 220 스테이지를 클리어한 기록이 있는데 221 스테이지가 열려있지 않은 현상](https://app.asana.com/0/1133453747809944/1201388967923079/f)

Bug fix/enter invalid stage

---

nekoyume/Assets/_Scripts/UI/Model/EquipmentInventory.cs

SSIA
1. (Unity Editor only) Go to `Order.cs` and change `ExpirationInterval` field value to 1 and reset chain.
2. Sell item and wait till it's expired. (Don't retrieve it.)
3. Go to workshop and proceed to Upgrade menu.
4. Check if not retrieved expired equipment is not displaying.
https://app.asana.com/0/1133453747809944/1201393053861154

Block displaying not retrieved expired equipment.

---

nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs

[[퀘스트] 아직 해금될 예정이 없는 장비제작 퀘스트가 노출됩니다.](https://app.asana.com/0/1133453747809944/1201391724175316/f)

Change ref from quest to table sheet when ordering the quest list

---

nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

SSIA
Click guide quest button
[[UI] 메인퀘스트 UI 터치되지 않는 현상](https://app.asana.com/0/1133453747809944/1201398508893254/f)

add `ERROR_ACTION_POINT` msg popup

---

nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs

SSIA
1. Modify `ConsumableRecipeGroup.json`'s content as following.
- Replace any `RecipeIds`' element with recipe id which is not existing. (any random numbers are ok.)
2. Launch game and check if `KeyNotFoundException` is no longer thrown.

Prevent `KeyNotFoundException` on loading `RecipeGroup`.

---

nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs

SSIA
1. Modify `ConsumableRecipeGroup.json`'s content as following.
- Replace any `RecipeIds`' element with recipe id which is not existing. (any random numbers are ok.)
2. Launch game and check if `KeyNotFoundException` is no longer thrown.

(v100087-b) Prevent `KeyNotFoundException` on loading `RecipeGroup`.

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ShopBuyItemView.prefab
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Model/EquipmentInventory.cs
nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

Merge rc-v100087 into development

---

nekoyume/Assets/AddressableAssets/UI/Module/Text/MaskedTextDisplay.prefab
nekoyume/Assets/_Scripts/UI/Tween/MaskedRectTransformXRoller.cs

1. Fix start position.
2. Add pause feature. (The pause function operates only in `isInfinite` is `True`.)
3. Add using animation speed option. (animation Time = `text.Length * animationSpeed`)
4. Add `isSelected` option. This option for `Toggle`.
5. Add text setter.
[텍스트 롤러 개선 및 버그수정](https://app.asana.com/0/958521740385861/1201200786778972/f)
@planetarium/9c-dev @Namyujeong @BBeom06

Improve MaskedRectTransformXRoller

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Lib9c/Lib9c.asmdef

1. relate from https://github.com/planetarium/lib9c/pull/742
2. Replay RankingBattle result in client like HackAndSlash
1. First step.

Use MessagePackDeserialize instead of BinaryFormatter

---

nekoyume/Assets/_Scripts/BlockChain/Agent.cs

Fix default ice server url

---

nekoyume/ProjectSettings/EditorSettings.asset

- SpritePacker Option Change
- Always Enabled > Enabled For Builds

[Design] SpritePacker Option Change

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DialogPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ItemInformationTooltip.prefab

- Dialog popup fix
- item tooltip Font Area fix

[Design] Dialog popup bugfix

---

nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs

1. [아레나 로딩화면에서 타임아웃 날 경우에도 메인으로 돌려보내야 합니다.](https://app.asana.com/0/1141562434100787/1201406778349288/f)

Consider `ArenaBattleLoadingScreen` when room entering

---

nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/WorldMapStage.prefab
nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapStage.cs

[Design] Stage image Change

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab

Season1 arena text change

---

nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs

Fix compile error in build

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
nekoyume/Assets/_Scripts/UI/Tween/DOTweenGroupAlpha.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs

1. It fixed the problem that animation runs in duplicate.
1. Try to make any item.
2. One more try to make any item too.
[뚱땅창에서 OK버튼만 먼저 한번뜨고 그 다음 전체 뚱땅창이 나옴. 동시에 한번만 떠야함.](https://app.asana.com/0/1141562434100787/1201450176916776/f)

Fix playing animation bug in CombinationLoading

---

nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

SSIA
1. Unlock any recipes.
2. Exit workshop and re-enter.
3. Check if recipe unlock VFX is now showing.
https://app.asana.com/0/1141562434100787/1201052690054149

Fix bug in displaying recipe unlock VFX.

---

nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs

SSIA
1. Try to make any item.
[뚱땅창에서 워크샵으로 들어가는 것을 뚱땅창 연출 후에 보여주는 방식으로 변경 건의](https://app.asana.com/0/958521740385861/1201470663071736/f)

Move squence of item moving animation

---

nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs

SSIA
Check if issues in 'Releated Links' are resolved.
https://app.asana.com/0/1133453747809944/1201392367298231
https://app.asana.com/0/1133453747809944/1201425663841530
https://app.asana.com/0/1133453747809944/1201392367298225

Add various subscription in craft button.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_IconAndButtonSystem.prefab
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionTimeoutException.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
nekoyume/Assets/_Scripts/BlockChain/IAgent.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs

1. [에러 메시지 문제](https://app.asana.com/0/1141562434100787/1201470667497089/f)
2. [에러 팝업에서 txid 복사할 수 있게 기능 추가](https://app.asana.com/0/958521740385861/1201316991018547/f)

Fix message of error code 27

---

nekoyume/Assets/_Scripts/BlockChain/ClientFilter.cs
nekoyume/Assets/_Scripts/BlockChain/ClientFilter.cs.meta
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

- resolve #987 
1. run local headless with rpc configuration
2. set `Thread.Sleep` in headless [GetState](https://github.com/planetarium/NineChronicles.Headless/blob/v100089/NineChronicles.Headless/BlockChainService.cs#L87-L94) before return  
3. build 9c client

Prevent crash when stream hang

---

nekoyume/Assets/_Scripts/UI/Model/Rank.cs

1. reduce headless rpc request
1. First step.

Use Agent.GetAvatarStates in Rank

---

nekoyume/Assets/_Scripts/BlockChain/ClientFilter.cs

Retry rpc request

---

nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/Widget/Battle.cs

1. SSIA
1. Enter to any stage.
2. Click `Mimis brunnr` UI fastly.
[[UI] 스테이지(월드맵, 미미르) 씬 진입 시 UI가 깨지는 현상](https://app.asana.com/0/1133453747809944/1201398508893244/f)

Destroy background when close `UI_Battle`

---

nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type1.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type3.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type4.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type5.prefab
nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - Button MainDisable.mat
nekoyume/Assets/Resources/UI/Prefabs/UI_DailyRewardItemPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_UpgradeEquipment.prefab
nekoyume/Assets/UIResources/Font/Black Drama SDF Material - BtnMainDisable.mat
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalButton.cs
nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs

SSIA
1. Check if combine button's cost text color is separated from material/slot condition in workshop.
https://app.asana.com/0/1133453747809944/1201471168399153
@planetarium/9c-dev @Namyujeong @BBeom06

Seperate cost text color in `ConditionalButton`.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
nekoyume/Assets/_Scripts/UI/Widget/Battle.cs

SSIA
1. Check if stage text is shown in tutorial.
https://app.asana.com/0/1133453747809944/1201407038170467

Show stage text in tutorial.

---

nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs

1. SSIA
2. Due to this [PR](https://github.com/planetarium/NineChronicles/pull/1067), there was a problem of breaking the background.
3. Fixed it.
1. Play any stage.
2. Do not exit, go to next stage.
@planetarium/9c-dev @Namyujeong 
Broken
Fixed

Move calling position of DestoryBackground()

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
nekoyume/Assets/_Scripts/UI/Model/Rank.cs
nekoyume/Assets/_Scripts/UI/Model/RankCategory.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs

SSIA
1. Check if clicking ability ranking category shows maintenance popup.
https://app.asana.com/0/958521740385861/1201512091436995

Block ability ranking temporarily.

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSellItems.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1639543970034900?thread_ts=1639543729.034300&cid=CC7BWJYTZ
- [GetOrder() 호출 횟수 줄이기](https://app.asana.com/0/958521740385861/1201512535666757/f) 
@planetarium/9c-dev , @ipdae

Optimize getState() related to shop and mail

---

nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Tutorial/Base/TutorialScenario.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs

- Add Checkpoints to Tutorial Scenarios
- Refactoring releated to tutorial
https://github.com/planetarium/NineChronicles/wiki/Manuals#tutorial
- delete playerPrefs
- make genesis block
[[튜토리얼] 대장간 튜토리얼 중간에 게임을 재실행할 경우 대장간 튜토리얼이 스킵되는 현상](https://app.asana.com/0/1133453747809944/1201491359790129/f)

Add Checkpoints to Tutorial Scenarios

---

nekoyume/Assets/_Scripts/UI/Widget/QuestPreparation.cs

1. SSIA
1. Use all of your ap.
2. Refill your ap in quest preparation UI.
3. Check quest button.
[[행동력] 행동력 리필 후 전투 진입 시도 시 행동력이 부족한 상태로 보임](https://app.asana.com/0/1141562434100787/1200937999314478/f)

Add setting condition of button by action position

---

nekoyume/Assets/AddressableAssets/Character/CharacterAnimator.controller
nekoyume/Assets/AddressableAssets/Character/NPC/300000/300000.controller
nekoyume/Assets/AddressableAssets/Character/NPC/300001/300001.controller
nekoyume/Assets/AddressableAssets/Character/NPC/300001/ReferenceAssets/Idle.asset
nekoyume/Assets/AddressableAssets/Character/NPC/300001/ReferenceAssets/Idle.asset.meta
nekoyume/Assets/AddressableAssets/Character/NPC/300002/300002.controller
nekoyume/Assets/AddressableAssets/Character/NPC/300003/300003.controller
nekoyume/Assets/AddressableAssets/Character/NPC/300004/300004.controller
nekoyume/Assets/Planetarium/Nekoyume/Editor/SpineEditor.cs
nekoyume/Assets/Resources/Character/NPC/300000.prefab
nekoyume/Assets/Resources/Character/NPC/300001.prefab
nekoyume/Assets/Resources/Character/NPC/300002.prefab
nekoyume/Assets/Resources/Character/NPC/300003.prefab
nekoyume/Assets/Resources/Character/NPC/300004.prefab
nekoyume/Assets/Resources/Character/NPC/300005.prefab
nekoyume/Assets/Resources/Character/NPC/300006.prefab
nekoyume/Assets/Resources/Character/NPC/dialog_03.prefab
nekoyume/Assets/Resources/Character/NPC/dialog_05.prefab
nekoyume/Assets/Resources/Character/NPC/dialog_10.prefab
nekoyume/Assets/_Scenes/Game.unity

Bug fix in creating ReferenceAsset folder.

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

Add analyze events about rpc connection

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSellItems.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

Revert "Optimize getState() related to shop and mail"
@planetarium/9c-dev  , @ipdae

Revert "Optimize getState() related to shop and mail"

---

nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/State/States.cs

1. [[UI] 캐릭터 선택 화면 진입 시 start 버튼이 노출되지 않는 현상 (1회 발생)](https://app.asana.com/0/1133453747809944/1201530071102672/f)
2. [[플레이어] 튜토리얼 캐릭터 스테이지 진입 시 플레이어 프리징 발생
](https://app.asana.com/0/1133453747809944/1201537642553951/f)
3. [[캐릭터] 신규 캐릭터 3분이 지나도 생성되지 않는 현상(간헐 발생)](https://app.asana.com/0/1133453747809944/1201530071102656/f)
4. [[UI] 인트로씬을 불러오지 못하는 현상, 프리징 현상](https://app.asana.com/0/1133453747809944/1201530071102648/f)
5. [[전투] 스테이지 진입 시 캐릭터 무한 달리기 현상 (간헐 발생)](https://app.asana.com/0/1133453747809944/1201530071102738/f)

Try catch get states in `BlockRenderHandler`

---

README.md

docs: fix typo `Navigate` at `README.md`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/_Scripts/UI/Module/MainMenu.cs

- Separately group locked and unlocked objects
- Disable event objects
[[UI] 메인화면 컨텐츠 잠김 표현 구현 확인](https://app.asana.com/0/958521740385861/1201478530080919/f)
@planetarium/9c-dev , @BBeom06

Separately group locked and unlocked objects

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/NotificationCell.prefab

SSIA
[[UI] 한줄 팝업이 터치를 막아서 뒤에 있는 오브젝트 터치 등이 안되는 현상](https://app.asana.com/0/1141562434100787/1201604142856946/f)

Set block raycast option to false in notification cell

---

nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs

SSIA
1. Enter to shop.
2. Try to input backspace during searching.
[[마켓] 마켓 - 검색 입력 중 백스페이스 입력할 경우 메인로비 상단 UI가 노출되는 현상](https://app.asana.com/0/1133453747809944/1201392367298205/f)

Fix an issue about backspace input during searching in Shop

---

nekoyume/Assets/_Scripts/UI/BlockTimer.cs
nekoyume/Assets/_Scripts/UI/Model/ShopBuyItems.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemInformationTooltip.cs

Fix to button to be disabled when item was expires
[[마켓] 1블록 남은 아이템이 1블록이 지나도 사라지지 않는 현상](https://app.asana.com/0/1133453747809944/1201546092114332/f)

Fix to button to be disabled when item was expires

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/Model/Item.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItem.cs
nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
nekoyume/Assets/_Scripts/UI/Model/ShopSellItems.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

- Fix to import shop item tag information at once
- Caching order digests
https://www.notion.so/planetarium/2021-12-23-tf-9c-get-state-af309699ce184ebdb43dfe8c71ed2874
@planetarium/9c-dev , @planetarium/9c-backend

optimize shop using bulk

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/Modifiers/AvatarQuestReceivableSetter.cs
nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CelebratesPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

Bump lib9c

---

nekoyume/Assets/Resources/Character/NPC/300000.prefab
nekoyume/Assets/Resources/Character/NPC/300001.prefab
nekoyume/Assets/Resources/Character/NPC/300002.prefab
nekoyume/Assets/Resources/Character/NPC/300003.prefab
nekoyume/Assets/Resources/Character/NPC/300004.prefab
nekoyume/Assets/Resources/Character/NPC/300005.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/PrologueDialogPopup.cs

- change npc animator
- change fenrir appear position
[강화,제작 NPC애니메이션이 안나오는 현상](https://app.asana.com/0/1141562434100787/1201628229611272/f)

Change npc animator

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab

Season1 Arena close

---

nekoyume/Assets/_Scripts/State/States.cs

Reverts planetarium/NineChronicles#1072

Revert "Improve/refactorinng states"

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

1. reduce grpc request time
2. see also https://github.com/planetarium/NineChronicles.Headless/pull/1015
1. First step.

reduce grpc request time

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemInformationTooltip.cs

1. There was a problem that the confirmation button was deactivated every time the block came out even though it was not an item to be purchased in the item tool tip.
2. Fixed it.
1. Try to open item tooltip in avatar info UI and wait until get new block..
2. Try to open item tooltip in Shop and wait until get new block..
[툴팁 확인 버튼이 매 블록 갱신될 때마다 꺼짐](https://app.asana.com/0/1141562434100787/1201649758573086/f)

Fix bug about submit button disabling

---

nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs

SSIA
1. Clear keystore and launch game.
2. Check if text is properly displaying on retyping passphrase while creating account.
@planetarium/9c-dev @BBeom06

Fix text bug in `LoginSystem`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs

- In the loading screen, the tooltip's letters change when who click it.
[전체로딩창에서 클릭하면 랜덤으로 다른 도움말 나오게 하기](https://app.asana.com/0/958521740385861/1201450176916766/f)

Add changing tooltip in loading screen

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
nekoyume/Assets/_Scripts/UI/Widget/Animation/ItemMoveAnimation.cs
nekoyume/Assets/_Scripts/UI/Widget/Hud/HpBar.cs
nekoyume/Assets/_Scripts/UI/Widget/Hud/SpeechBubble.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CodeRewardPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
nekoyume/Assets/_Scripts/UI/Widget/UpgradeEquipment.cs

Fix warning log

---

nekoyume/Assets/_Scripts/Game/Entrance/NestEntering.cs
nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/Game/Trigger/MonsterSpawner.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/ExpRankCell.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/LevelUpCelebratePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/AvatarTooltip.cs

Fix how to find player
see link [[전투] 무한달리기 현상 재현](https://app.asana.com/0/1133453747809944/1201690393623302/f)
[[전투] 무한달리기 현상 재현](https://app.asana.com/0/1133453747809944/1201690393623302/f)

Fix how to find player

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

SSIA
Buy item
- https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1642667670156300

Fix how to get buy error list

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

SSIA
@planetarium/9c-dev @Namyujeong @BBeom06 
Fixed it! ⬇️

Remove animator in shop menu notification mark

---

nekoyume/Assets/_Scenes/Game.unity

Add UI camera
[UI Camera 분리하기](https://app.asana.com/0/958521740385861/1201690646327008/f)
@planetarium/9c-dev , @BBeom06

Add UI camera

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs

Add `Big cat's year` event banner
[호랑이해 배너를 적용해주세요](https://app.asana.com/0/958521740385861/1201720452482562/f)

Add event banner

---

nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs

Reduce get `WeeklyArenaState`

---

nekoyume/Assets/_Scripts/UI/Widget/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BoosterPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/QuestPreparation.cs

Increase HAS boosting max count from 12 to 24

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/L10n/Editor/LanguageTypeInspectorDisplayDrawer.cs
nekoyume/Assets/_Scripts/L10n/Editor/LanguageTypeInspectorDisplayDrawer.cs.meta
nekoyume/Assets/_Scripts/L10n/Editor/Nekoyume.L10n.Editor.asmdef
nekoyume/Assets/_Scripts/L10n/LanguageTypeInspectorDisplayDrawer.cs.meta

Fix compile errors which is occurred from #1162

Fix compile errors

---

nekoyume/Assets/_Scenes/Game.unity
nekoyume/ProjectSettings/TagManager.asset

Fix UI Sorting Layer settings

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extension/GameActionExtensions.cs
nekoyume/Assets/_Scripts/Extension/GameActionExtensions.cs.meta

Track `Unity/ActionRender` event with `ActionType` and `Elapsed` value

---

nekoyume/Assets/Resources/AddressableAssetsContainer.asset

Add `ItemRequirementSheet` on `AddressableAssetsContainer`

---

nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs

- resolve #1196 
Except when the rpc disconnected, there are no miss matching state in client.  
1. First step.

Reduce GetState called in BlockRenderer

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab

- Setting TextArea fix
- Asana: https://app.asana.com/0/1133453747809944/1201799339339574

[bugfix] RedeemCodeButton Text fix

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

1. see with https://github.com/planetarium/NineChronicles.Headless/pull/1082
1. First step.

Decompress action evaluation

---

nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Model/EnhancementInventoryItem.cs
nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
nekoyume/Assets/_Scripts/UI/Module/ItemTooltipDetail.cs
nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs

1st -> notification target
2nd -> level requirement <= my level
3rd -> left things
[인벤토리 아이템 정렬 수정하기](https://app.asana.com/0/958521740385861/1201869821990644/f)

Add equipment inventory ordering

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Event.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

- resolve #1193 
- based by https://github.com/planetarium/NineChronicles.Headless/pull/1033
- caching state when call `GetState` or action render.
1. First step.

Introduce Caching state & balance

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/DataExporter.cs
nekoyume/Assets/Planetarium/Nekoyume/Editor/DataExporter.cs.meta
nekoyume/Assets/Planetarium/Nekoyume/Editor/Nekoyume-editor.asmdef

1. [Shop Item List  파일저장하기](https://app.asana.com/0/958521740385861/1201933285036309/f)
> You can click the "Shop" button in play mode and you should enter to shop before use this.

Introduce `DataExporter`

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/DataExporter.cs
nekoyume/Assets/Planetarium/Nekoyume/Editor/StoreDownloader.cs
nekoyume/Assets/Planetarium/Nekoyume/Editor/StoreDownloader.cs.meta
nekoyume/Assets/Planetarium/Nekoyume/Editor/ZipUnzip.cs
nekoyume/Assets/Planetarium/Nekoyume/Editor/ZipUnzip.cs.meta

- Introduce "ZipUnzip"
- Introduce "StoreDownloader"
- Store: This job takes 30 mins in my local env.(zip file size: 27.4GB)

Introduce `StoreDownloader` editor menu

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_tooltip.prefab
nekoyume/Assets/RenderTexture/CostumeTooltipSpineCamera.renderTexture
nekoyume/Assets/RenderTexture/CostumeTooltipSpineCamera.renderTexture.meta
nekoyume/Assets/Resources/Character/FullCostumeCutscene/40100001.prefab
nekoyume/Assets/Resources/Character/FullCostumeCutscene/40100005.prefab
nekoyume/Assets/Resources/Character/FullCostumeCutscene/40100006.prefab
nekoyume/Assets/Resources/ScriptableObject/SpineTooltipData.asset
nekoyume/Assets/Resources/ScriptableObject/SpineTooltipData.asset.meta
nekoyume/Assets/_Scenes/Game.unity
nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipData.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipData.cs.meta
nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipDataScriptableObject.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipDataScriptableObject.cs.meta
nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs

1. SSIA
1. Open tooltip of costumes. (available lists : 40100000, 40100001, 40100005, 40100006)
2. Check if previews are working properly.
https://app.asana.com/0/958521740385861/1201904461222045
@planetarium/9c-dev @BBeom06

Show preview spine object in costume tooltip.

---

nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs

SSIA
[재료아이콘 클릭시 아이템 상세정보(툴팁) 표시](https://app.asana.com/0/958521740385861/1201804271527287/f)
@planetarium/9c-dev , @jaeho0103

link material popup to item view

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

1. add acquisition place(arena) at normal material.
[엠블렘, 메달 등의 아이템 획득처 아레나로 등록](https://app.asana.com/0/958521740385861/1201968362779139/f)

Improve acquisition place UI

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

Bump lib9c and add url

---

nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs

fix banner url

---

nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs

1. Add exception handling 
2. Change url  linked to notice popup

Polishing for v100140

---

nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs

1. Change url (item requirement notice popup).
2. Nump lib9c (table changed)

Change url of notice popup and bump lib9c

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

Fix GetStageByOrder in acquisition place

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
nekoyume/Assets/_Scripts/UI/Module/Item/CountableItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/RequiredItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/StageRewardItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs

SSIA
https://planetariumhq.slack.com/archives/C0358KRU0CB/p1647437076335889

Add disposable to touchHandler

---

nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs

- Fix dummy Notice Info to correct date value

Fix notice info

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

SSIA
1. Click material item icon.
[아이템 획득처 스테이지가 1개밖에 안나오는 경우에 대한 수정](https://app.asana.com/0/958521740385861/1201981779796300/f)

Remove returning, add not cleared stage next cleared stage

---

.gitmodules

SSIA
1. [Check build CI](https://github.com/planetarium/NineChronicles/runs/5637339536?check_suite_focus=true)
https://planetariumhq.slack.com/archives/CBREBL15F/p1647851435589879

Change url of submodules ssh to https

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs

fix `DateTime` parsing bug

---

nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

SSIA
https://planetariumhq.slack.com/archives/CBU2JFAF3/p1647927892387849
https://discord.com/channels/539405872346955788/653951482395361301/955719466619121684

Cherry pick #1274 to rc-v100141

---

nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs

change playerfrabs key format for `NoticePopup`

---

nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

Merge rc-v100141 to main

---

nekoyume/Assets/_Scripts/Game/Character/Player.cs

- Set `Player.Costume, Equipments` default value from `Model.Player` 
1. First step.

Fix invalid equipment in Arena

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs

SSIA
[[캐릭터] 캐릭터 생성이 오랜시간 안되는 현상](https://app.asana.com/0/1133453747809944/1202023403020025/f)

fix NRE when create avatar

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab

cherry picked from commit 65eb55bfdca963b81bb59310f2ecc19116d0e44e
https://github.com/planetarium/NineChronicles/pull/1288
@BBeom06 , @planetarium/9c-dev

[Design] font fix

---

nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
nekoyume/Assets/_Scripts/UI/Module/Item/RequiredItemView.cs
nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

SSIA
[툴팁 보여지는 위치에 대한 기능 확장](https://app.asana.com/0/958521740385861/1201869821990661/f)
@planetarium/9c-dev @tyrosine1153 
This is a screen that was directed.

Make target in Tooltip to optional and if target is null, panel move to center

---

nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
nekoyume/Assets/_Scripts/Analyzer.cs
nekoyume/Assets/_Scripts/Game/Game.cs

SSIA
1. [[analyze] 에러 등에 rpc-host 추가하기](https://app.asana.com/0/958521740385861/1202031091941999/f)

`Analyzer` contains rpc server host data

---

nekoyume/Assets/_Scripts/Game/Character/Player.cs

SSIA
play rankingbattle action 
[[아레나] 캐릭터가 우측으로 달려가서 상대와 떨어진 상태로 전투하는 현상](https://app.asana.com/0/1133453747809944/1202060204438890/f)

Fix the problem of ignoring the enemy.

---

hooks/pre-commit

- The changed C# code are automatically cleaned up in pre-commit.
- If there are more than 100 changed C# codes, the action is canceled.
- Code clean-up configs have not yet been defined. - It should be defined along with the code convention.
- ❗Dependency : .NET Core 2.1 SDK and later versions.
- If you don't want to execution, you can delete the file(`/hooks/pre-commit`) to exclude execution.
- If you commit on Github Desktop, it may can not work.
1. Break any C# code in repository. (break white spaces)
2. Commit the crumbled codes.
3. Check the committed script has been refactoring. 
[유니티 coding convention & style 공유시키기](https://app.asana.com/0/958521740385861/1201981607031559/f)
- Before
- After

Share Code Convention

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs

SSIA
1. Click any item icon.
@planetarium/9c-dev @BBeom06 
before
after

Fix sequence of tooltip moving logic 

---

nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs

1. default preset for previewnet arena
before 448,000 index
after 448,000 index & before execute RankingBattle
1. First step.

Set default preset for arena

---

nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

1. Fix method invoking in `MaterialTooltip.Show(InvoentoryItem ...)` -> base.Show to overrided Show
1. Click material item in inventory.

Fix material tooltip for previewnet

---

nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs

SSIA
1. try to buy any items in shop.
[[Previewnet] 아이템 구매 문구 중 NCG가 2번 반복되어 나오는 현상](https://app.asana.com/0/1133453747809944/1202077560125787/f)
before
after

Fix XXX NCG NCG text

---

nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs

Reverts planetarium/NineChronicles#1315

Revert "Set default preset for arena"

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab

[Design] RankingBoard info Text Delete

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab

fix broken prefab: `UI_RankingBoard > UI_RankingInfo`

---

nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs

SSIA
1. Enter to Craft menu.
2. Click recipe of Mimisbrunnr.
3. Check requirement level.
[공방 제작 미미르 레시피의 착용 레벨 제한 표시 문제](https://app.asana.com/0/1133453747809944/1202091111966592/f)

Add handling about mimisbrunnr recipe in SubRecipeView

---

nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs

- [[획득처] 미미르 재료 획득처 표시 오류](https://app.asana.com/0/1133453747809944/1202097850125825/f)

fix acquisition button ui bug

---

nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs

Reset cancellationTokenSource on purchase page display

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

- [[미미르] 획득 경로UI로 미미르 진입 시 스테이지 정보가 잘못 표시된 현상](https://app.asana.com/0/1133453747809944/1202098904856138/f)

fix mimisbrunnr battle preparation stage text bug

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlots.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs

SSIA
[[전투] 전투 진행 불가 현상 (99에러 발생)](https://app.asana.com/0/1133453747809944/1202097882556709/f)

Block battle action in client

---

nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

- [[미미르] 획득 경로UI로 미미르 진입 시 전투 진행이 불가능한 현상](https://app.asana.com/0/1133453747809944/1202098904856131/f)
- [[아레나] 획득 경로UI로 아레나 진입 후 전투 진입 시 전투화면이 뜨지 않고 메인로비 화면이 나오는 현상](https://app.asana.com/0/1133453747809944/1202098904856152/f)
- [[스테이지] 획득 경로UI로 스테이지 진입 후 전투 진입 시 전투화면이 뜨지 않고 메인로비 화면이 나오는 현상](https://app.asana.com/0/1133453747809944/1202098904856145/f)

Bug fix/acquisition button

---

nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

(cherry picked from commit f5386ab9e4f0e58ca62d9d04f35397854acc23c5)
(cherry picked from commit d6c8c8904a629848e0e455164b9e24d7451ffd94)
SSIA
[[마켓] sell 탭 진입 시 프리징 발생 현상](https://app.asana.com/0/1141562434100787/1202105868099160/f)
s

show ui first when entering the shop sell

---

nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

Merge the `rc-v100171` branch into the `main` branch

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab

Reverted and Reopen this pull request https://github.com/planetarium/NineChronicles/pull/1336
to another branch.
- [[로딩 페이지] 상점과 아레나 로딩 씬 중 화면 터치 시 랜덤 도움말 텍스트가 작동하지 않는 현상](https://app.asana.com/0/1133453747809944/1202098904856167/f)
- https://github.com/planetarium/NineChronicles/pull/1336
- https://github.com/planetarium/9c-launcher/pull/1327
- https://github.com/planetarium/NineChronicles/pull/1338

Fix data loading screen

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs

- Edited the type conversion method in button ui.
[판매 금액에 소숫점이 입력된 경우, +10 버튼이 의도대로 동작하지 않습니다.](https://app.asana.com/0/1141562434100787/1200453793172475/f)

Edit UI button action

---

nekoyume/Assets/_Scripts/UI/RankingInfo.cs
nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs

1. Fix invalid current avatars arena info
2. Fix ui freezing end of battle.
1. First step.

Fix ranking board

---

nekoyume/Assets/_Scripts/Game/Character/PlayerSpineController.cs

SSIA
1. Check if tail costume is changed properly when full costume is equipped.
https://app.asana.com/0/1141562434100787/1202077507155884

Add null check when costume tail is changed.

---

nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs

1. Fix a bug where the Challenge button was enabled when tickets were low.
1. Use arena ticket until ticket count is zero.
2. Check challenge button in Arena UI.
[아레나 도전 버튼 활성화 문제](https://app.asana.com/0/1141562434100787/1202113754970041/f)

Fix UpdateContent of ArenaRankCell

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

- Text add
- Menu object / position Change

UI/add common UI 6

---

nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

SSIA
open avatar information popup
[인벤토리 정렬 순서 이상](https://app.asana.com/0/1141562434100787/1202127264201151/f)

add inventory sort condition

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

1. bump lib9c.
2. add handling about Grind action, temporary.
Added action handling in #1362 .

Bump lib9c for Grind Action

---

nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab

SSIA
https://planetariumhq.slack.com/archives/C01D7N32V55/p1650274473343089

change  url linked to popup

---

nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

SSIA
open your inventory
[[Previewnet] 판매 화면의 인벤토리 내 재료 아이템 리스트 순서가 기획의도와 다른 현상](https://app.asana.com/0/1133453747809944/1202077560125810/f)
@jaeho0103 , @planetarium/9c-dev 
- shop
- avatarInfo
- battlePreparation

organize materials

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab

[bufgix] Combinationslot button text Area fix

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ConsumableTooltip.prefab

[bugfix] Text Area fix

---

nekoyume/Assets/_Scripts/EnumType/ShopSortFilter.cs
nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
nekoyume/Assets/_Scripts/UI/Shop/SellView.cs

SSIA
enter the shop
[샵 기본 sorting 을 CP 로 변경](https://app.asana.com/0/958521740385861/1202145127839308/f)
@planetarium/9c-dev , @jaeho0103

change shop sort filter order

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/StoreDownloader.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

Bump `lib9c:rc-v100180`

---

nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs

Chunk address list

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab

[bugfix] Season Text Change

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab

Release rc-v100181 to main

---

nekoyume/Assets/Resources/UI/Animations/Sweep_Result.anim

update sweep result anim

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

Bug fix/action point guage

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldClear_03.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldClear_04.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldClear_05.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

SSIA
[[스윕] 스윕 진행 시 결과 대기 화면이 무한 로딩 상태인 현상](https://app.asana.com/0/1133453747809944/1202200726991547/f)

fix to refresh ap stone count every time

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipBuy.cs

Set submit button text on show buy tooltip (ItemTooltipBuy)
[구매 버튼 레이블이 Buy가 아니라 Combine 으로 되어 있음](https://app.asana.com/0/958521740385861/1202190854547538/f)

Fix buy tooltip button label

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

Modified to show the available ap stones normally in the sweep popup.
[[스윕] AP포션 구매 처리 중 스윕 기능 이용 시 남은 AP포션이 비정상적으로 표시되는현상](https://app.asana.com/0/1133453747809944/1202201726656467/f)
@boscohyun

Fixed so that usable ap stones are displayed properly in sweep popup

---

nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs

Change `ConfirmCallback` invoking sequence in `IconAndButtonSystem`

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

lib9c : https://github.com/planetarium/lib9c/pull/987
slack : [1](https://planetariumhq.slack.com/archives/C01D7N32V55/p1651633141878509) , [2](https://planetariumhq.slack.com/archives/C01KB9AQTUN/p1651637370770819?thread_ts=1651636136.054209&cid=C01KB9AQTUN)

Add sweep exception handling

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

Merge rc-v100193 to main

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

1. SSIA
1. Try Grinding with zero AP.
[그라인딩 클라이언트에서 AP 충전 할 수 있도록 추가](https://app.asana.com/0/958521740385861/1202210782711059/f)
@Unengine @jaeho0103

Add AP charge in Grinding 

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/CompileHelper.cs

SSIA
https://github.com/planetarium/NineChronicles/pull/1427

Update missing changes from #1427

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs

1. Burn all crystals.
2. Check if recipe unlock button is still showing when unlockable recipe exists.
@sonohoshi @jaeho0103

Show recipe unlock button regardless of current balance.

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs.meta
nekoyume/Assets/_Scripts/State/IAsyncUpdatableReadOnlyRxProp.cs
nekoyume/Assets/_Scripts/State/IAsyncUpdatableReadOnlyRxProp.cs.meta
nekoyume/Assets/_Scripts/State/RxProps.cs
nekoyume/Assets/_Scripts/State/RxProps.cs.meta

-  `IAsyncUpdatableReadOnlyRxProp<T> : IReadOnlyReactiveProperty<T>`: `IReadOnlyReactiveProperty<T>.Value` 를 비동기 업데이트하는 인터페이스를 포함합니다.
-  `AsyncUpdatableRxProp<T> : ReactiveProperty<T>, IAsyncUpdatableReadOnlyRxProp<T>`: `IAsyncUpdatableReadOnlyRxProp<T>`를 구현하는 `ReactiveProperty<T>` 입니다.
-  `RxProps`: `Necoyume.State` namespace에 포함되는 새로운 상태 참조 객체입니다.
지금까지 `States`나 `XxxSubject`를 통해서 `XxxState` 류의 상태 자체에 대한 참조가 이루어져 왔습니다.
또한 클라이언트용으로 변환하고 캐싱해서 참조 해오기도 했는데요.
각 UI에 조금 나누어져 있는 상태 참조문을 `RxProps`에 모아서 `ReactiveProperty(이하 RxProp)` 혹은
`AsyncUpdatableRxProp` 형으로 사용해보고자 합니다.
~~~ cs
class RxProps {
// ReactiveProperty를 초기화할 때에는 ReactiveProperty.Value에 할당될 기본값을 넣었습니다.
public ReactiveProperty StringRxProps = new ReactiveProperty<string>("hello");
// AsyncUpdatableRxProp을 초기화할 때에는 비동기 업데이트 함수를 할당합니다. …

Introduce `RxProps`

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

Implement `Read(GrindingMail)` in previewnet

---

nekoyume/Assets/_Scenes/Game.unity

SSIA, Fix NRE in ItemMoveAnimationFactory invoking in Grinding...

Add ItemMoveAnimation pull to AnimationLayer

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs

CombinationEquipment to 10, ItemEnhancement to 9

Drop action version about Crystal

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab

SSIA
1. Enable grinding mode in Avatar info.
2. Try to click item in the upper-right.
[https://www.notion.so/planetarium/22q2-previewnet-check-0527-ca198defdf5e47b380d2b7228df180e2#43ad374b6d394f679d92ac7adede389a](https://www.notion.so/planetarium/22q2-previewnet-check-0527-ca198defdf5e47b380d2b7228df180e2#43ad374b6d394f679d92ac7adede389a)

Disable raycast target in avatarinfo-reward text

---

nekoyume/Assets/_Scripts/Analyzer.cs
nekoyume/Assets/_Scripts/Game/Game.cs

Improve the `Analyzer` do not track in editor mode, debug mode and run with development option.

Improve the `Analyzer`

---

nekoyume/Assets/_Scripts/Analyzer.cs
nekoyume/Assets/_Scripts/Game/Game.cs

Improve the `Analyzer` to `2022q2` branch

---

nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs

Change value of StakingBonus level to States.StakingLevel

---

nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

Fix arena battle graphics

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Widget/Hud/SpeechBubbleWithItem.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs

Bug fix/stack over flow and other

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs

SSIA
[https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1654153497695409](https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1654153497695409)

Add Stake action rendering and avoid InvalidCastException

---

nekoyume/Assets/Resources/AddressableAssetsContainer.asset
nekoyume/Assets/_Scripts/Game/TableSheets.cs

Apply crystal fluctuation sheet

---

nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs

Avoid ArgumentNullException with Bencodex.Null

---

nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs

Change CharacterBase.CoTimeout logic

---

nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs

SSIA
1. Try to grind and check reward.

Fix grinding reward text

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

SSIA
1. Unlock recipes and check if previously unlocked recipes are not locked.

Bug fix on rendering unlocked recipes.

---

nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab.meta
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

[bugfix] Tutorial Guide Area fix

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extension/UniRxExtension.cs
nekoyume/Assets/_Scripts/Game/Game.cs

Rename and modify argument order minor

---

nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs

Add condition to CopyToClipboard in `IconAndButtonSystem`

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs

SSIA
1. Select any item in Grinding UI.
2. Grind selected item in avatar info popup - grind mode.
3. Try to grind selected item in Grinding UI.
[[Previewnet] 공방에서 그라인딩 장비 선택 후 인벤토리 그라인딩으로 그라인딩 후 공방에서 그라인딩이 가능한 현상](https://app.asana.com/0/1133453747809944/1202402217651509/f)

Move SetProgressCircle invoking to GrindModule.PushAction

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/State/States.cs

1. Add rendering about `Stake` and `ClaimStakeReward`.
2. Add caching to `StakeState`, `StakedBalanceState`, `StakingLevel`. (In `States.cs`)
[몬스터 콜렉션 개편 구현 MVP - 9c client](https://app.asana.com/0/958521740385861/1202410687355593/f)
@planetarium/9c-dev @tyrosine1153

Add action rendering about renewed Stake(Monster Collection)

---

nekoyume/Assets/_Scripts/Game/Game.cs

(cherry picked from commit aba91df0f18fad6a04aa62b6f655dcb91b8df516)
#1545 into the `development` branch.

Fix sync table from chain in initializing

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

- Fix NRE in render of `BattleArena`
- Fix arena simulating bug
- Fix the header menu state in `ArenaJoin` UI

Fix several bugs related to arena

---

nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs

1. Sometimes... `Animator.Play` is not working.
2. So I fixed it in #1517 .
3. But it would not set `_forceQuit`, it made **'SKIPPING ATTACK ANIMATION'**.
4. So I fixed it again.
[[전투] 캐릭터 타격 타이밍이 어색하여 모션이 캔슬되는 현상](https://app.asana.com/0/1133453747809944/1202411981983205/f)

Fix `CoTimeout()` logic in CharacterBase

---

.github/bin/inject-mixpanel-client-data.sh
.github/workflows/build.yml
nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs

Cherry picking #1520 to the `2022q2` branch

---

.github/workflows/build.yml

Correct `TARGET_BRANCH` swith-case expression

---

nekoyume/Assets/_Scripts/BlockChain/Agent.cs

1. Apply libplanet changes
1. See whether it passed or not

Apply libplanet bump

---

nekoyume/Assets/_Scripts/BlockChain/Agent.cs

Correct `LoadIceServer`

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

[hotfix] Fix arena render bug

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

(cherry picked from commit 748fde06e9033762492b5a3a987049d374208411)

Fix arena render bug

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopupNone.prefab

[Design]UI_StakingPopupNone_Prefab_Edit

---

nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs

Add missing value in `Analyzer`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab

[Design] Button off

---

nekoyume/Assets/_Scripts/Game/Game.cs

Fix debug analyzer option

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/EquipmentSlot.prefab
nekoyume/Assets/Resources/UI/Animations/UILobbyController@BoxCatLoop.anim
nekoyume/Assets/Resources/UI/Animations/UILobbyController@Combination_XmasLoop.anim
nekoyume/Assets/Resources/UI/Animations/UILobbyController@MimirLoop.anim
nekoyume/Assets/Resources/UI/Animations/UILobbyController@Quest_XmasLoop.anim
nekoyume/Assets/Resources/UI/Animations/UILobbyController@RankingLoop.anim
nekoyume/Assets/Resources/UI/Animations/UILobbyController@Shop_XmasLoop.anim
nekoyume/Assets/Resources/UI/Animations/UILobbyController@bg_XmasLoop.anim
nekoyume/Assets/Resources/UI/Animations/UIMenuController@Close.anim
nekoyume/Assets/Resources/UI/Animations/UIMenuController@Show.anim
nekoyume/Assets/Resources/UI/Animations/UI_ArenaJoin@Show.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

- Menu Animation Key add
- Loop Animation bugfix
- Arenajoin Text Position down

[Bugfix] AfterRevomonContainer Animation add

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

SSIA
1. Check if mixpanel trackers are working properly.

Add mixpanel trackers of crystal related actions.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab

[Design] Disable not implemented crystal reward object

---

nekoyume/Assets/AddressableAssets/UI/Module/Grinding/GrindModule.prefab

Disable not implemented object (second try)

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopupNone.prefab

Add missing L10N key in StakingPopupNone

---

nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EnhancementResultPopup.cs

Reflect on ItemEnhancement9 & 10

---

nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

Fix NRE in checking registry value

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs

Fix `BalanceDoesNotExistException`

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

Back to lobby when `BattleArena` action failed

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

Fix rewards of championship on `ArenaJoin` UI

---

nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

Fix not initialize the staking level in `States` when run on rpc mode

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs

Add exception handling about find level by staked amount

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/State/RxProps.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardBillboard.cs

Fix arena data cache bug

---

nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

Fix arena medal resource getter

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerScroll.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab

- ArenaBoard None Text add
- ArenaBoard UserList Rank Text add

[Design] ArenaBoard text add

---

nekoyume/Assets/Resources/ScriptableObject/UI_StakeIconData.asset
nekoyume/Assets/Resources/ScriptableObject/UI_StakeIconData.asset.meta
nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
nekoyume/Assets/_Scripts/Game/ScriptableObject/StakeIconDataScriptableObject.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/StakeIconDataScriptableObject.cs.meta
nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

1. Fix bug in loading stake icon image.
2. Update event banner date time.
1. Check if event banner is displaying banners properly.
2. Check if stake icon images are displaying properly.
https://app.asana.com/0/1133453747809944/1202492050251341

Fix bug in loading stake icon image.

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/Extension/AvatarStateExtensions.cs

SSIA
improving of https://github.com/planetarium/lib9c/pull/1183

Introduce UpdateAvatarStateV2

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
nekoyume/Assets/_Scripts/Animation.meta
nekoyume/Assets/_Scripts/Animation/AnimationFinisher.cs
nekoyume/Assets/_Scripts/Animation/AnimationFinisher.cs.meta

1. SSIA
1. Click `Grinding` button rapidly in inventory.
2. After serveral clicking, check if grinding ui is displaying properly after show animation.
https://app.asana.com/0/1133453747809944/1202492054765164

Fix animation bug in inventory grinding.

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

- [[아레나] 전투 결과씬 점수가 1018점으로 고정되어 출력되는 현상](https://app.asana.com/0/1133453747809944/1202492188588962/f)

Fix result score on result popup of arena battle

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

- Add l10n key; UI_ARENA_BOARD_EMPTY

Update the `GameObject` activation on the `UI_ArenaBoard`

---

nekoyume/Assets/Tests/EditMode/Extensions/ArenaSheetExtensionsTest.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
nekoyume/Assets/_Scripts/Extension/ItemSheetExtension.cs
nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

- [아레나 메달 아이콘 처리](https://app.asana.com/0/1133453747809944/1202493468831123/f)

Fix arena medal bugs

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
nekoyume/Assets/_Scripts/UI/Module/Character/DetailedCharacterView.cs

1. Fix bug in displaying buff button.
2. Fix RankPopup prefab
https://app.asana.com/0/1133453747809944/1202493373748709
https://app.asana.com/0/1133453747809944/1202494687839659

Fix bug in displaying buff button.

---

.github/workflows/build.yml

https://github.com/planetarium/NineChronicles/pull/1640

Add Linux CI Build

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extension/ItemExtensions.cs

Fix arena battle reward bug

---

nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
nekoyume/Assets/_Scripts/UI/Module/Gold.cs

Fix ncg and crystal text

---

nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs

SSIA
1. Check if bonus buff button is shown properly `CrystalRandomBuffState` is null.

Show bonus buff button on state is null

---

nekoyume/Assets/Tests/EditMode/State/AsyncUpdatableRxPropTest.cs
nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

- Fix `UniTask` to `Task` in `AsyncUpdatableRxProp`
- Fix async loading of `ArenaJoin`
- Fix async loading of `ArenaBoard`

Bug fix/async loading for arena

---

nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs

Enable world unlock effect by first unlock condition

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab

[Hotfix] Change banner order

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
nekoyume/Assets/Tests/EditMode/State/AsyncUpdatableRxPropTest.cs
nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
nekoyume/Assets/_Scripts/UI/Module/Gold.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

Merge `rc-v100231` into `main`

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

Fix NRE on `ArenaBoard`

---

nekoyume/Assets/_Scripts/State/States.cs

Empty `CrystalRandomSkillState` when switching to new avatar.

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

Fix compile error

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
nekoyume/Assets/AddressableAssets/UI/Module/Inventory.prefab
nekoyume/Assets/Resources/ScriptableObject/CostIconData.asset
nekoyume/Assets/Resources/UI/Animations/Item_MoveAnimation@show_Crystal.anim
nekoyume/Assets/Resources/UI/Animations/UICombinationController_Grind@Show.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Login.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
nekoyume/Assets/Resources/UI/Prefabs/item_CrystalGetAnimation.prefab

- Effect bugfix
- Resources Change

Bugfix UI/add effect

---

nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

SSIA
[[신규 월드 오픈] 월드를 오픈 후 월드맵에 진입 시 자물쇠 이펙트가 계속 출력되는 현상](https://app.asana.com/0/1133453747809944/1202515747791540/f)
[월드맵에서 처음에 크리스탈 잔액과 월드 해금 가격에 따라 텍스트 색깔이 바뀌지 않는 현상](https://app.asana.com/0/1141562434100787/1202516266356260/f)
@planetarium/9c-dev @BBeom06

Fix WorldMap button UI bugs

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

- [[아레나] 아레나 보드 리스트 진입시 자기가 보이도록 최초 스크롤 위치 변경](https://app.asana.com/0/1133453747809944/1202529573166852/f)
- [Fix some prefabs which is contains DetailedCharacterView](https://github.com/planetarium/NineChronicles/commit/1f90230e9bf4f9532a38528bc84dd12568055356)
- [Updage activation of mission button's game objects](https://github.com/planetarium/NineChronicles/commit/bad875c280371d91199f3ae0fc7e59bd066444d5)

Improve arena stuffs

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/Crystal.cs

- [[아레나] 아레나 대전 플레이후 헤드 부분의 크리스탈 수량이 0 으로 변하는 현상](https://app.asana.com/0/1133453747809944/1202515928855913/f)

Fix the crystal update timings

---

nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
nekoyume/Assets/_Scripts/Game/Character/CharacterAnimator.cs

- Change how to get Spine animation time
- Wear a full costume and fight against an opponent who is weaker than you and win.
- I fight an opponent who is stronger than me and is wearing a full costume and I lose
- Put on buff skills and fight.
- Battle with opponents who have buff skills
- [[아레나] 전투가 체력에 상관없이 종료되는 현상](https://app.asana.com/0/1133453747809944/1202522590392809/f)
- [Slack](https://planetariumhq.slack.com/archives/CBU2JFAF3/p1656411409690619)

Change how to get Spine animation time

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab

Fixed line breaks when pressing 'Enter`
Search for items in the store
- @planetarium/9c-dev 
-

Change InputField line type

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs

- [[아레나] 아레나 대전 플레이후 헤드 부분의 크리스탈 수량이 0 으로 변하는 현상](https://app.asana.com/0/1133453747809944/1202515928855913/f)

Check updated fungible assets when update crystal

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab

Change URL of claim x2 banner

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab

Enable ap fill area

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab

Reverts planetarium/NineChronicles#1680

Revert "Enable ap fill area"

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab

SSIA. Re-open of #1682, that is Re-opened PR of #1680

Enable ap slider

---

nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs

SSIA
1. Check if selecting skill on `BuffBonusResultPopup` changes `BonusBuffButton`'s icon.

Bugfix: Update `BonusBuffButton`'s icon on every skill selection via ui.

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs

- [[Previewnet] 아레나 전투 준비 화면에서 장비 변경 시 좌측 인벤토리에서 장착 표시가 변경되지 않는 현상](https://app.asana.com/0/1133453747809944/1202462131236836/f)

Bug fix/update inventory on arena battle preparation

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab

Enable AP slider (cherry-pick of #1683)

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Game/Arena.cs
nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

Optimize handling the render of `BattleArena`

---

nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs

SSIA
1. Check if selecting skill on `BuffBonusResultPopup` changes `BonusBuffButton`'s icon.

Bugfix: Update BonusBuffButton's icon on every skill selection via ui.

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Game/Arena.cs
nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

Merge `rc-v100241` into `main`

---

nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
nekoyume/Assets/_Scripts/Extension/ItemSheetExtension.cs

- [이전 아레나 메달들의 아이콘이 8시즌 메달 아이콘으로 고정되는 현상](https://app.asana.com/0/1141562434100787/1202580578529754)

Fix arena medal item bug

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/UI/Module/Item/StakingItemView.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

SSIA
[[몬스터콜랙션] 시스템 보상이 인게임에 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1202492054765130/f)

Add system reward to staking reward UI

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

1. Update nft page url to https://dcc.nine-chronicles.com/

Update NFT page url.

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs

- [[메인로비[ 아레나 잔여 티켓이 8장으로 표시되는 현상](https://app.asana.com/0/1133453747809944/1202578059628327/f)

Fix `ArenaMenu`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab

Disable block raycast in ItemTooltip, effect texture

---

nekoyume/Assets/Resources/UI/Animations/UIEnhancementResult@Loop.anim
nekoyume/Assets/Resources/UI/Animations/UIEnhancementResult@Loop_Fail.anim
nekoyume/Assets/Resources/UI/Animations/UIEnhancementResult@Success.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab

- Enhancement Animation bugfix

[Bugfix] Enhancement Animation fix

---

nekoyume/Packages/manifest.json
nekoyume/Packages/packages-lock.json

SSIA
reference:[https://github.com/openupm/openupm/commit/efe54bbd84bdd9b55547ff4d21a3e929994944e1#comments](https://github.com/openupm/openupm/commit/efe54bbd84bdd9b55547ff4d21a3e929994944e1#comments)

Fix broken CI by OpenUPM & DOTween

---

nekoyume/Packages/manifest.json
nekoyume/Packages/packages-lock.json

Fix broken CI by OpenUPM & DOTween (same with #1711, To branch`rc-v100250`)

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

Fix arena ticket synchronizing bug

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

SSIA
1. Use acquisition place button.
[[획득처UI] 획득처 UI를 통해 스테이지로 이동 시 이동전 화면의 재화가 표시되는 현상](https://app.asana.com/0/1133453747809944/1202565831033942/f)
before
after

Fix header ui not updated bug

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab

SSIA
[[상점] 판매 매대 아이템 상세 정보의 버튼이 눌리지 않는 현상](https://app.asana.com/0/1133453747809944/1202603451704586/f)

Disable raycast target in ItemTooltip

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/EventDungeonTickets.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Currency/EventDungeonTickets.prefab.meta
nekoyume/Assets/AddressableAssets/UI/Module/GuidedQuest.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
nekoyume/Assets/_Scripts/UI/Module/EventDungeonTickets.cs
nekoyume/Assets/_Scripts/UI/Module/EventDungeonTickets.cs.meta
nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

All modified game objects are inactivated.
- Introduce `EventDungeonTickets` UI module
- Modify `GuidedQuest` UI module
- Modify `UI_HeaderMenuStatic`
- Modify `UI_Menu`
- Modify `UI_WorldMap`
Related with https://github.com/planetarium/NineChronicles/issues/1718

Apply event dungeons UI specs to several prefabs

---

nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

- Fix `UI_BattlePreparation` prefab
- Fix `ConditionalButton_Type2` prefab
- Fix `QuestBtn` prefab
- Fix `UI_Menu` prefab

Fix UI/battle preparation and button

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Currency/ArenaTickets.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonus.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Currency/EventDungeonTickets.prefab

- Ticket image Change
- Count material add

[Design] image change / Count Material add

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab

Fix `UI_BattlePreparation` widget

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

Fix `QuestBtn` module and `UI_Menu` widget

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs

1. SSIA
https://app.asana.com/0/958521740385861/1202609937522532

Track used hourglass count in `RapidCombination`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

- Fix `UI_Menu`
- Fix `UI_WorldMap`

Fix UI prefabs

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab

- Arenajoin Text Change
- Combination NPC Shadow add

Bugfix/add UI

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs

Fix `UI_Craft` prefab

---

nekoyume/Assets/AddressableAssets/UI/Module/GuidedQuest.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeRow.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs

- Fix `UI_Craft` prefab
- Fix `GuidedQuest` prefab

Fix UI/craft and guided quest

---

nekoyume/Assets/_Scripts/ActionExtensions/HackAndSlashExtensions.cs
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

Bump lib9c and reflect version up of HAS

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab

- Text Bugfix
https://app.asana.com/0/1133453747809944/1202665547820471

[Bugfix] Actionpoint Text fix

---

nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BlockPeriod.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BlockPeriod.prefab.meta
nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab

[Design] Prefab add

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

- Hard fork arena helper - Add limit to offseason user by score.
[아레나 오프시즌에도 validatation 추가 체크](https://app.asana.com/0/958521740385861/1202695992585401/f)

Add validatation to Arena OffSeason

---

nekoyume/Assets/Resources/ScriptableObject/EventData.asset

Remove revomon event data.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab

[Design] MultiResult add

---

nekoyume/Assets/_Scripts/Extensions/EventDungeonExtensions.cs
nekoyume/Assets/_Scripts/Extensions/StageSheetExtensions.cs
nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

SSIA
[이벤트 스테이지 보상 재료 툴팁 획득처 숏컷 개발](https://app.asana.com/0/958521740385861/1202712724131360/f)

Add acquisition place about event dungeon

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs

SSIA
1. Tru to use booster in mimis brunnr.
[[미미르] 부스터 사용 후 클리어 시 캐릭터가 앞으로 계속 달리는 현상](https://app.asana.com/0/1133453747809944/1202781012145338/f)
[[미미르] 부스터 사용 후 최종 결과화면 확인 시 마지막으로 사용한 Repeat의 결과가 출력되는 현상](https://app.asana.com/0/1133453747809944/1202781012145345/f)

Fix bugs about mimis brunnr with booster

---

nekoyume/Assets/Resources/ScriptableObject/CostIconData.asset
nekoyume/Assets/Resources/ScriptableObject/UI_Palette.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_TicketPurchasePopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_TicketPurchasePopup.prefab.meta
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
nekoyume/Assets/_Scripts/EnumType/ColorType.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/TicketPurchasePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/TicketPurchasePopup.cs.meta
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

- Fix `UI_WorldMap`
- Add `UI_TicketPurchasePopup`
- Register `TextElement06` to `UI_Palette`
- Register event dungeon ticket image to `CostIconData`

Fix several assets

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs

Fix `UI_Craft` to add the main stat text will be multiple

---

nekoyume/Assets/UIResources/Content/Effect/Material/Distortion_SubTab_Craft.mat

[bugfix] Material Noise size down

---

nekoyume/Assets/Resources/ScriptableObject/EventData.asset
nekoyume/Assets/_Scripts/EnumType/EventType.cs
nekoyume/Assets/_Scripts/Game/Event/EventManager.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/EventScriptableObject.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs

The `EventData` scriptable object contains below.
- `Default`: default settings
- `Events`: UTC time based event settings
- `ArenaSeasons`: UTC time based arena season event settings
- `Default Settings`: same with `Default` before
- `Time Based Events`: same with `Events` before
- `Block Index Based Events`
- `EventDungeonIdBasedEvents`

Improve `EventData`

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

Set default tab to repeat in SweepPopup

---

nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs

Fix recipe scroll disappear bug on craft

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab

Change world6 value

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs

Set mainstat view in SubRecipeView

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/ReportAnything.cs

You can use the `Tools/Report Anything/All of sheet addresses` menu.
The result will be print to the unity editor console log.
```
========== All of sheet addresses ==========
[001]                               ArenaSheet: 0x85cf3445D6d7980600fAC2a175e2579E6f64dc18
[002]                      CharacterLevelSheet: 0x00daFaa4414D63bE46965F442619406f692e2690
[003]                           CharacterSheet: 0x68b1cC1Edc7D84477C6679eA7828c2A4B2dA7fef
[004]                     EnhancementCostSheet: 0xfAA2511e4193D1C16dAeDF67210a64250c8dAA8B
[005]                   EnhancementCostSheetV2: 0x8f743474CA978069d7f23E1df0070f5cD4039048
[006]                          GameConfigSheet: 0x46Bedb51Dab9b41243b0372940586E051c308769
[007]                ConsumableItemRecipeSheet: …
```

Implement to report all of sheet addresses to unity console log

---

nekoyume/Assets/_Scripts/State/RxProps.Craft.cs

Avoid `InvalidCastException` about HammerPointState

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

SSIA
[[미미르] 스테이지 진행 시 스테이지 정보가 잘못 출력되는 현상](https://app.asana.com/0/1133453747809944/1202819766429506/f)

Fix Bugs from not-set `StageType`

---

nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

Add world button unlock condition

---

nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs

Resolve [[상점] 이벤트 전용 음식이 ATK 항목에서 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1202819833912168/f)

Bug fix/consider all of consumable stats on shop

---

nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

SSIA
Resolve https://app.asana.com/0/1133453747809944/1202827831679519/f

Fix bug about can not enter new world

---

nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

-Button, Tab Area bugfix
###AsanaBugLink
https://app.asana.com/0/1133453747809944/1202159167869976

[bugfix] Tutorial Craft Area fix

---

nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

Resolve [[월드맵] 스테이지 선택 창에서 뒤로가기를 할 경우 월드맵에서 상단UI가 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1202827627918876/f)

Fix state of `HeaderMenuStatic` on `WorldMap`

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs

SSIA
[[공방] 슈퍼 크래프트로 제작 시 애니메이션에서 20블록으로 표시하지 않는 현상](https://app.asana.com/0/1133453747809944/1202827628141684/f)

Set block index of super craft to 20

---

nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs

Disable super craft in mimis brunnr recipe

---

nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_1.prefab
nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab
nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab
nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab
nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_5.prefab

Update event banner prefabs

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

Resolve [이벤트 아이템 제작시 슬롯에서 시간이 줄어들지 않음](https://app.asana.com/0/1133453747809944/1202819010229401/f)

Fix event crafts gauge

---

nekoyume/Assets/_Scripts/UI/Widget/Development/Cheat.cs

Optimize UI minor

---

nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab
nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab
nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab

Update url of event banner

---

nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs

- SSIA
- https://github.com/planetarium/NineChronicles/pull/1827

FIx Monster Collection Ingame UI

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

Bump `lib9c:rc-v100281` into `rc-v100281`

---

nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs

- Fix to syncronize shop requirment filter and toggle ui
[[상점] 사용가능한 아이템 보기 항목 체크 후 다시 상점에 들어갈 경우 항목이 초기화 되지 않는 현상](https://app.asana.com/0/1133453747809944/1202350473096125/f)

Fix shop requirement filter

---

nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs

Change menu illustrates path
before
after

Change path

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

for Fix NullReferenceException in StakingPopup.cs
@planetarium/9c-dev @tyrosine1153

Change invoking timing of SetBenefitsListViews()

---

nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_StakingBenefits.prefab
nekoyume/Assets/Resources/AddressableAssetsContainer.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
nekoyume/Assets/_Scripts/Game/TableSheets.cs
nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

SSIA
[몬스터콜렉션 시스템 보상 HAS AP 변경 9c](https://app.asana.com/0/958521740385861/1202890553734409/f)
@planetarium/9c-dev @tyrosine1153

Add ActionPoint changing rate by Staking

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

Change costAp with Staking bonus

---

nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs

Resolve [전투 결과 팝업 보상 안 보임](https://app.asana.com/0/1133453747809944/1202903449163609/f)

Fix `BattleResultPopup` rewards bug

---

nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab

Cherry pick the pull request #1883

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
nekoyume/Assets/Resources/UI/Shaders/UIBlur_ShaderGraph(Unit).mat
nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossRank.cs
nekoyume/Assets/_Scripts/UI/Widget/System/OneLineSystem.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldBossDetail.cs

- [[9c 폴리싱] 룬조각 팝업에서 여러 룬조각 빠르게 클릭하면, 시스템 메시지가 클릭한 횟수만큼 계속 출력됨](https://app.asana.com/0/0/1202919100109494/f)
- [[9c 버그] 오프 시즌에서는 메인화면에서 티켓 ui가 출력되지 않아야 함](https://app.asana.com/0/0/1202919100109501/f)
- [[9c TDL] 정보 업데이트 버튼 연속 클릭 막기](https://app.asana.com/0/0/1202919100109513/f)
@planetarium/9c-dev , @crkim88

Bugfix and Polishing the World Boss

---

tools/Updater/Updater/Program.cs

[Chore] Update updater's download url

---

nekoyume/Assets/_Scripts/Helper/Util.cs

- Fix Shop sell material level limit filter.
[마켓의 Material은 '착용 가능한 아이템만 보이기' 필터에 영향을 받지 않아야 함](https://app.asana.com/0/1141562434100787/1202711883406464/f)

Fix Shop sell material level limit filter

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/WorldBossBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Model/WorldBossModel.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossQuery.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossReward.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossRewardPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldBossDetail.cs

Introduce World Boss Season Rewards.
[[9c 폴리싱] 시즌 보상 받기 적용](https://app.asana.com/0/0/1202911604887961/f)

Introduce World Boss Season Rewards.

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

1. Fix nre on new avatar creation of new agent.

Fix NRE on new agent

---

nekoyume/Assets/_Scripts/UI/Model/WorldBossRankItem.cs
nekoyume/Assets/_Scripts/UI/Module/Item/WorldBossRankItemView.cs

Fix world boss ranking view

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Model/WorldBossRankItem.cs
nekoyume/Assets/_Scripts/UI/Module/Item/WorldBossRankItemView.cs

Merge development into previewnet-worldboss

---

nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab

Add loading indicator to NoticePopup

---

nekoyume/Assets/AddressableAssets/NoticeInfo.meta
nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset
nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset.meta
nekoyume/Assets/AddressableAssetsData/AddressableAssetSettings.asset
nekoyume/Assets/AddressableAssetsData/AssetGroups/RemoteAssets.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs.meta
nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs

Rc v100291 to main

---

nekoyume/Assets/AddressableAssets/UI/Module/Blur.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab

- QuestBtn, RaidBtn image Change

[Design] image change

---

nekoyume/Assets/AddressableAssets/UI/Module/Blur.prefab

[Design] material delete

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs

(cherry picked from commit 2aa359f25f363b76b9dd95fd1f2e7ac964c5506a)

Update crystal balance when rewarded

---

nekoyume/Assets/_Scripts/Game/ActionCamera.cs
nekoyume/Assets/_Scripts/Game/RaidCamera.cs
nekoyume/Assets/_Scripts/Game/RaidStage.cs

SSIA
1. Play raid.
2. Enter stage battle and check is camera is working properly.

Rerun action camera fsm on end of raid battle.

---

.github/workflows/release.yaml

chore: Remove update launcher submodule CI

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab

Change raid button string key
[[9c 폴리싱] 메인 로비에서 월드 보스 메뉴명 스트링 키 수정](https://app.asana.com/0/0/1202923839886759/f)

Change raid button string key

---

nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset
nekoyume/Assets/_Scripts/Helper/Util.cs

use "yyyy-MM-ddTHH:mm:ss" format at `Util.cs` too.
and change format of Addressable assets.
1. Delete all of PlayerPrefs.
2. Check notice popup in `improve/change-datetime-noticepopup` branch.
It checked on local player.
@planetarium/9c-dev @tyrosine1153

Use `DateTime.TryParseExact` and new datetime format

---

nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Reward.prefab

Cherry pick 88f256b0ecadcdf6dc4efd30bdaa293d12d84aef
@boramqo83

Cherry pick

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab

RaidBtn_Prefabs_Edit
https://app.asana.com/0/1202059563287942/1202923839886751/f

[Design]RaidBtn_Prefabs_Edit

---

nekoyume/Assets/Resources/ScriptableObject/UI_WorldBossData.asset
nekoyume/Assets/_Scripts/Game/ScriptableObject/WorldBossScriptableObject.cs
nekoyume/Assets/_Scripts/Helper/WorldBossFrontHelper.cs
nekoyume/Assets/_Scripts/UI/Module/Item/WorldBossRankItemView.cs

SSIA
@planetarium/9c-backend , @BBeom06 , @boramqo83

Add world boss rank effect

---

nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab

WorldBossRankCell_Prefabs_Edit

[Design]WorldBossRankCell_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

Add missing code

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossQuery.cs

SSIA
@planetarium/9c-dev , @ipdae

Pull out onboarding hosts and port

---

nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossBattleRewardItem.prefab
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossBattleRewardItem.cs

Change world boss reward rank icons

---

nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab

Tabs_Rank_Prefab-Edit
https://app.asana.com/0/958521740385861/1202968451323297

[Design]Tabs_Rank_Prefab-Edit

---

nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossRank.cs

Add objects of none status to world boss leaderboards

Add objects of none status to world boss leaderboards

---

nekoyume/Assets/Resources/UI/Prefabs/UI_TicketPurchasePopup.prefab

- Blur add
https://app.asana.com/0/1133453747809944/1202976523491431

[bugfix] Blur add

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepResultPopup.cs

Bump `lib9c:development` into `development`

---

nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Reward.prefab
nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossGradeRewardItem.prefab
nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab

WB_localizing_Edit
https://app.asana.com/0/958521740385861/1202984262099883

[Design]WB_Localizing_Edit

---

nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

- Apply this lib9c PR to 9c https://github.com/planetarium/lib9c/pull/1378
(Migrate Required Appraise Block value to GameConfigState)
[[크래프팅 개선] Identifying 블록 줄이기](https://app.asana.com/0/958521740385861/1202968688182083/f)

Apply GameConfigState

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

SSIA
[아레나보드 리스트가 없을때, none 오브젝트 안켜져 있는 현상](https://app.asana.com/0/1141562434100787/1202921504498746/f)

Fix none object in ArenaBoard

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossBattle.prefab
nekoyume/Assets/_Scripts/UI/Module/RaidProgressBar.cs

SSIA
1. Check if raid progress bar is filled properly.
https://app.asana.com/0/958521740385861/1202896339908895

Fill current wave on raid progress bar.

---

nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs

Add error code

---

nekoyume/Assets/_Scripts/Game/Game.cs

[Bugfix] Play mouse click VFX based on current camera position

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/AddressToolWindow.cs

Derive related address hexes from agent address hex.
Click `Tools > Address Tool`!

Improve `AddressTool`

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs

SSIA
[[월드 보스] 전투 준비 화면에서 상단 인벤토리 UI를 제외하는 작업이 모든 준비 화면에 적용된 현상](https://app.asana.com/0/1133453747809944/1203010887980258/f)

Revert preparation widgets

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs

- Fixed to the world boss unlock function to work properly
- @planetarium/9c-dev

Fixed to the world boss unlock function to work properly

---

nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs

Modify the prefab to be changed only when boss id is changed

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs

Show practice text on raid practice mode

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs

Add exception handling to raid button

---

nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs

- Fix bug in lifecycle of bleed vfx
- Fix bug in updating claim button on off-season
https://app.asana.com/0/1133453747809944/1203004830509578

Fix bug in lifecycle of bleed vfx

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossRewardScreen.prefab

Modify reward count text options
[[월드 보스] 1등 시즌 보상 획득 시 크리스탈 수량이 UI를 벗어나는 현상](https://app.asana.com/0/1133453747809944/1203019741554118/f)
@boramqo83 , @crkim88

Modify reward count text options

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
nekoyume/Assets/_Scripts/Game/Character/Character.cs
nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
nekoyume/Assets/_Scripts/UI/Widget/RuneStoneItem.cs

https://app.asana.com/0/1133453747809944/1203010887980294
https://app.asana.com/0/1133453747809944/1202942960640220
https://app.asana.com/0/1133453747809944/1203013413430623

Fix bugs in raid

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs

1. Add item slot caching when use super craft.
2. Not remove materials when use super craft.
1. Try to super craft.
2. Check materials and combination slot before rendering action.
[슈퍼크래프트 폴리싱](https://app.asana.com/0/958521740385861/1203027135764135/f)

Improve SuperCraft

---

nekoyume/Assets/_Scripts/Animation/RaidTimelineContainer.cs
nekoyume/Assets/_Scripts/Game/Character/Character.cs
nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
nekoyume/Assets/_Scripts/Game/RaidStage.cs

1. Fix hud position
2. Fix animation cancel glitch in raid.

Fix animation cancel glitch in raid

---

nekoyume/Assets/_Scripts/ActionExtensions/CombinationConsumableExtensions.cs
nekoyume/Assets/_Scripts/ActionExtensions/CombinationEquipmentExtensions.cs
nekoyume/Assets/_Scripts/ActionExtensions/ItemEnhancementExtensions.cs
nekoyume/Assets/_Scripts/ActionExtensions/RapidCombinationExtensions.cs
nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

- Fixed a bug where the workshop was not displayed properly when changing the avatar.

Bugfix workshop

---

nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs

SSIA
1. Check random skill state of last stage.
2. Use shortcut, or do anything... check random skill button.
3. Change to other character and check random skill button too.
[아바타 교체시 스테이지 1회성 버프 상태갱신 싱크 맞추기](https://app.asana.com/0/1141562434100787/1203027135764139/f)

Fix bug about unneccessary enabling random skill button

---

nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs

1. Past: It was showing all the rewards could get.
2. FIX: Show valid rewards.
1. Try to use repeatting at stage that can not clear.
2. Check rewards in BattleResultPopup.
[Repeat 결과의 보상과 실제 얻는 보상이 다른 현상](https://app.asana.com/0/1141562434100787/1203027135764147/f)

Fix get rewards logic of `GetHackAndSlashReward()`

---

nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/StageRewardItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs

- Fix VanillaItemView for UntradableMaterial.
1. Buy AP Stone.
2. Check sended Mail.
3. Make sure that the color of item view background is **purple**.
[[마켓] 교환 가능 AP 포션 수령 시 교환 불가 AP포션 이미지가 출력되는 현상](https://app.asana.com/0/1141562434100787/1202201059708748/f)
Before
After

Fix mail item view background

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs

1. SSIA
2. now, you can select sub recipe in Super craft popup.
1. Check super craft popup.
2. Charge hammer point by craft.
3. Try to Super craft.
[슈퍼크래프트 디자인 변경 및 폴리싱](https://app.asana.com/0/958521740385861/1203044970472091/f)

Apply new design of Super craft

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs

Hide banner in world boss main

---

nekoyume/Assets/_Scripts/UI/Model/SkillView.cs

Delete duplicated percent character

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
nekoyume/Assets/_Scripts/UI/RequestManager.cs

Add request condition

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
nekoyume/Assets/_Scripts/UI/RequestManager.cs

Merge rc-v100302 into main

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
nekoyume/Assets/_Scripts/UI/RequestManager.cs

Merge v100302 into dev

---

nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs

1. SSIA
2. Can check it at battle preparation menu about stage, mimis brunnr, world boss.
1. Enter to any preparation menu about stage or mimis or world boss.
2. Try to use food.
[장착한 음식에 E 마크 붙이는 기능 추가](https://app.asana.com/0/958521740385861/1203077857871348/f)

Add equipped notification to Foods

---

nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs

SSIA
1. Use any skill in arena.
**Area attack skill**
**Blow attack skill**
**Double attack skill**

Fix skill animation and damage text sync in Arena

---

nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs

This exception occurred by the changes of https://github.com/planetarium/NineChronicles/pull/2035.
There is no case to occurred this exception now.

Fix `InvalidCastException`

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
nekoyume/Assets/UIResources/Content/Effect/Grade/Distortion_Result_Success.mat

- Enhancement Active Effect fix

[bugfix] Enhancement Effect fix

---

nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs.meta
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

1. It works like `LocalLayerModifier`. But not use LocalLayer.
2. It helps to add mail for local client.
*example*

Introduce `LocalMailHelper`

---

nekoyume/Assets/UIResources/Content/Common/Prefab/item_TextStyle_06.prefab

[bugfix] TextArea 115 > 160

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonBarScroll.prefab

- Apply missing changes from last [PR](https://github.com/planetarium/NineChronicles/pull/2073) 
[챔피언 쉽 구성(시즌 단위) 변경](https://app.asana.com/0/958521740385861/1203198517168802/f)
Original feature pr : https://github.com/planetarium/NineChronicles/pull/2073

Fix ArenaJoinSeasonBarScroll prefab

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Prologue.cs

Remove avatar address logging in prologue

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Prologue.cs

Merge rc-v100311 to main

---

.github/auto_assign.yml

SSIA
@tyrosine1153 @ipdae @planetarium/9c-dev

Update `auto_assign.yml`, add new maintainer

---

nekoyume/Assets/AddressableAssets/Character/Monster/900001/900001_Material_TintBlack.mat.meta
nekoyume/Assets/AddressableAssets/Character/Monster/900001/900001_Material_URP.mat.meta
nekoyume/Assets/Resources/AddressableAssetsContainer.asset
nekoyume/Assets/Tests/EditMode/Battle/RankingSimulatorTest.cs
nekoyume/Assets/_Scripts/ActionExtensions/HackAndSlashExtensions.cs
nekoyume/Assets/_Scripts/ActionExtensions/MimisbrunnrBattleExtensions.cs
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/Agent.cs
nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs
nekoyume/Assets/_Scripts/Game/Character/Player.cs
nekoyume/Assets/_Scripts/Game/TableSheets.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/Cheat.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BoosterPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs

1. Apply rune stats in `HackAndSlash` without checking ownership check.

Apply rune stat

---

nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs

Fix notice popup
Play 9c
https://app.asana.com/0/1141562434100787/1203257618065248/f

Fix notice popup
