planetarium/NineChronicles

- nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
SSIA
[슈퍼 크래프트 팝업 기본 옵션을 프리미엄으로](https://app.asana.com/0/958521740385861/1203174833907785/f)
> Set default toggle to premium recipe in Super craft popup

- nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
- ViewDetail Button Delete
- ViewDetail Button Touch Area fix
> [bugfix] ViewDetail Button Area fix

- .github/workflows/build.yml
> Change dotnet version of ci

- nekoyume/Assets/StreamingAssets/Localization/common.csv
> Added rune ticker string key

- nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
SSIA
https://app.asana.com/0/1133453747809944/1203291108090018/f
> Add SetWorldInformation in ShortcutActionForStage()

- nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPurchasePopup.cs
subscribe update PurchasedCountDuringInterval
> Fix ArenaTicketPurchasePopup

- nekoyume/Assets/Tests/EditMode/ChargeActionPointTest.cs
- nekoyume/Assets/_Scripts/ByteSerializer.cs
- nekoyume/Assets/_Scripts/ByteSerializer.cs.meta
> Restore `ByteSerializer` on 9c

- nekoyume/Assets/Tests/EditMode/ChargeActionPointTest.cs
> V100321 merge dev

- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBossResult.spriteatlas
- Atlas Option Check
https://app.asana.com/0/1141562434100787/1203359372010885
> [bugfix] Alllow Rotation option / Read/write option Check

- nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
- Add Errorcode CoolDownBlockException
[[아레나] 반복하여 전투를 진행 시도 시 에러가 뜨며 진행이 불가능한 현상 ](https://app.asana.com/0/1133453747809944/1203291108090027/f)
> Add ErrorCode CoolDownBlockException

- nekoyume/Assets/_Scripts/UI/Module/GrandFinaleJoin.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
- nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
> Add null checking to GrandFinaleScheduleSheet

- nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
> Bump lib9c and handle ClaimStakeReward rendering as interface

- nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeView.cs
> Add check not level requirement item in recipe view

- nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
> Add check row in staking popup

- nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
> Filter not arena avatar state in GrandFinaleStates

- nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
- nekoyume/Assets/_Scripts/Extensions/ArenaSheetExtensions.cs
- nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Edited to set required item image by medal material's arena type
> Fix required item view for event material craft

- nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
> Fix bug about not set recipe id at event metarial

- nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_ArenaMedalCountcell.prefab
Fix inputfield size and character limit in ArenaMedalCountcell
> Fix inputfield in ArenaMedalCountcell

- nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
- Craft Text fix
- RightArea ButtonGroup L10 Object add
> [bugfix] Craft Material Text fix

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
Fixed inventory-equipped display to work properly after sweep action
[[버그] 스윕 화면 종료 시 착용 장비에 e 마크 미표시 버그](https://app.asana.com/0/0/1203470263399475/f)
> Fixed inventory-equipped display to work properly after sweep action

- nekoyume/Assets/Resources/SpriteAtlases/Background/MainMenu.spriteatlas
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas.meta
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Lobby_com.spriteatlas
- nekoyume/ProjectSettings/EditorSettings.asset
- Optimizing draw calls
- before
- after
> graphics optimization

- nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
> detour NRE

- nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
> Change rune enhancement success vfx

- .github/workflows/build.yml
> Test using 8cores on build job

- nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset
> Fix rune ticker in ui

- nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
- Bugfix
- Split `get state bulk` 
https://planetariumhq.slack.com/archives/C011716SDTM/p1670378633831329
> Split `get state bulk` and Bugfix

- nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
not ignore '(info.ClearedStageId == RxProps.EventDungeonRow.StageEnd)'
[이벤트 스테이지 가이드 퀘스트 동작 수정](https://app.asana.com/0/958521740385861/1203488775482685/f)
> Change logic of `GetTargetEventDungeonQuest()`

- nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
SSIA
[이벤트 스테이지에 노티 띄우기](https://app.asana.com/0/958521740385861/1203488775482681/f)
> Add notification at event stage

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/NotificationCell.prefab
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
- nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
- nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
- nekoyume/Assets/_Scripts/UI/Scroller/NotificationCell.cs
[[룬] 번영도를 통해 AP 충전 시 변경된 플로우가 적용되지 않은 현상](https://app.asana.com/0/1133453747809944/1203407981826426/f)
[[룬] 황금 잎사귀 룬에 스킬 효과가 비정상적으로 적용된 문제.](https://app.asana.com/0/1133453747809944/1203506499867030/f)
[[인벤토리] 룬 장착 및 해제 시 CP 변경 이펙트가 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1203521212905023/f)
> Bugfix 100340 rc4

- nekoyume/Assets/_Scripts/Extensions/StatExtensions.cs
- nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
- nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
- nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
- nekoyume/Assets/_Scripts/UI/Module/Stat/DetailedStatView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/Tooltip/RuneTooltip.cs
> Apply new format of DRR

- nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
- nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
> Fix error for Language Type Changing

- nekoyume/Assets/_Scripts/UI/Module/Slider/SweepSlider.cs
- nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
Change Sweep Slider Initial Value
[[스윕] 스윕 진입 시 AP 포션 기본 값이 10개인 현상](https://app.asana.com/0/1133453747809944/1203551460877899/f)
> Change Sweep Slider Initial Value

- nekoyume/Assets/_Scripts/Helper/Util.cs
> Fix DateTime prefix in `Util.IsInTime`

- nekoyume/Assets/Resources/UI/Prefabs/UI_EventReleaseNotePopup.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
> bugfix: SetActive event view on first Show

- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldClear.spriteatlas
> [bugfix] Atlas option fix

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
- nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
- nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
[동일한 CP를 가진 장비에 녹색 화살표 표시되는 현상](https://app.asana.com/0/1141562434100787/1203558947281755/f)
[번영도박스 Refill시 CONFIRM 메세지가 잘못 출력되는 현상](https://app.asana.com/0/1141562434100787/1203551322030738/f)
> fix inventory

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/State/States.cs
Fix to update only selected status
> Caching item&rune slot state

- nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv
Update Event Dungeon L10n
- Event Dungeon Name Change
> Update 10030001 Event Name L10n Change

- nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
Increased the height of skill object in rune enhancement result screen
[[공방] 스킬룬 강화 결과화면 확인 시 스킬명이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1203561861824528/f)
@planetarium/9c-dev , @BBeom06
> Increased the height of skill object in rune enhancement result screen

- nekoyume/Assets/_Scripts/Game/Character/LobbyCharacter.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
[[아레나] 아레나 상세리스트의 CP가 높게 출력되는 현상](https://app.asana.com/0/1133453747809944/1203551460877906/f)
> Fix friend popup / Modify the lifecycle of lobby character title

- nekoyume/Assets/Resources/Prefab/Background/Chapter_04_01.prefab
> [bugfix] size 1.06 > 1

- nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
SSIA
[QA - [BGM] 로비와 스테이지 선택창에서 여름 BGM이 나옵니다.](https://app.asana.com/0/1133453747809944/1203566605457198/f)
> Fix playing event main bgm

- nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
- nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
[[아레나] 아레나 상세리스트의 CP가 높게 출력되는 현상](https://app.asana.com/0/1133453747809944/1203551460877906/f)
https://planetariumhq.slack.com/archives/C016RR80TK9/p1671156968608039?thread_ts=1671155556.316839&cid=C016RR80TK9
> Fix initial setting bugs in the arena

- nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
- nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
- nekoyume/Assets/_Scripts/Helper/Util.cs
- nekoyume/Assets/_Scripts/Helper/WorldBossFrontHelper.cs
- nekoyume/Assets/_Scripts/UI/RequestManager.cs
- nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
- nekoyume/Assets/_Scripts/UI/Widget/RuneStoneItem.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
> tidying up the code

- nekoyume/Assets/Resources/ScriptableObject/UI_BonusBuffViewData.asset
1. Check if stage buff and its icon is matched properly.
> Fix buff view data

- nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
- nekoyume/Assets/_Scripts/Game/Character/Player.cs
- nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
> Resolve the cause of duplicate titles

- nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
SSIA
1. Click guide quest
2. Check material acquisition place
[게임 처음 켜고 월드맵 들어가기 전에는 스테이지 가이드 퀘스트와 재료 획득처가 정상 동작하지 않음](https://app.asana.com/0/1133453747809944/1203605199668698/f)
> Change worldInformation reference of shortcut to current avatar

- nekoyume/Assets/Resources/ScriptableObject/EventData.asset
- nekoyume/Assets/Resources/ScriptableObject/NoticeEndpoint.asset
- nekoyume/Assets/_Scripts/Game/Event/EventManager.cs
- nekoyume/Assets/_Scripts/Game/Notice/NoticeManager.cs
- nekoyume/Assets/_Scripts/Helper/Util.cs
SSIA
[이벤트 배너, 팝업이 정상적인 날짜에 맞게 보여져야함](https://app.asana.com/0/1133453747809944/1203605723151756/f)
> Bug fix about `DateTime` format

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
- Quest bg fix
- Worldmap fix
[월드맵 배경에 디스토션이 과도하게 들어간 현상](https://app.asana.com/0/1141562434100787/1203600417734063)
[퀘스트 선택 효과가 영역에 벗어나는 현상](https://app.asana.com/0/1141562434100787/1203600430840987)
> [bugfix] Worldmapbg / Questbg

- nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Add auto scroll for last unlocked consumable recipe
[공방 - 음식 제작 탭도 장비 탭과 동일한 조건으로 자동스크롤 적용](https://app.asana.com/0/1133453747809944/1203605612434786/f)
> Add auto scroll for last unlocked consumable recipe

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/State/States.cs
- nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Item slot status is also cached when caching avatar status.
Enter the game using Unity Editor.
https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1672193092853259
@sonohoshi
> Item slot status is also cached when caching avatar status.

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
SSIA
[월드보스 티켓 구매시 NCG 갱신 안되는 현상](https://app.asana.com/0/1141562434100787/1203615087362917/f)
> Fix gold to be updated when purchasing tickets

- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
- nekoyume/Assets/StreamingAssets/Localization/common.csv
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/ArenaInformationExtensions.cs
- nekoyume/Assets/_Scripts/Extensions/InventoryExtensions.cs
- nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
- nekoyume/Assets/_Scripts/State/RxProps.Common.cs
- nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
Update arena battle button to disable if it is not pass interval index blocks in the previous battle.
[아레나 연속 진행 폴리싱](https://app.asana.com/0/958521740385861/1203638432731042/f)
> Update arena battle button for interval index

- nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
[게임 시작시 스토리부분 자동 skip 기능 추가](https://app.asana.com/0/1141562434100787/1203646483435465/f)
> Skip synopsis

- nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
SSIA, Not show item tooltip.
Try to grind.
> Change Grinding UI to one click working

- nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs
> Block duplicate clicks

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/State/States.cs
- [[공방] 장착 중인 장비 강화 후 전투 진입 시 에러가 뜨며 진행이 불가능한 현상](https://app.asana.com/0/1133453747809944/1203755445440651/f)
> Check item slot status

- nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset
- nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
- nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
1. Fix typo in worldboss (serimnir -> saehrimnir)
2. Update world boss name on off-season
1. Check if boss name is properly displaying on off-season.
> Fix typo and bug in world boss

- nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
- nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
> Add forceClose() in widget

- nekoyume/Assets/_Scripts/BlockChain/Agent.cs
> Apply libplanet changes

- nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
- nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
> Change Close ()to ForceClose()

- nekoyume/Assets/_Scripts/Game/Game.cs
> Logging APV

- nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
- nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossSeason.cs
- nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
- bugfix
- bump lib9c
[월드보스 인트로의 보스 이름이 잘못 표시되어 있습니다.](https://app.asana.com/0/1141562434100787/1203818054656282/f)
> bugfix and bump lib9c

- nekoyume/Assets/_Scripts/UI/Module/GrandFinaleJoin.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
- Handle exception in `GrandFinaleJoin` UI module.
- Fix minor.
> Handle exception and fix minor

- nekoyume/Assets/Resources/ScriptableObject/EventData.asset
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Fury.playable
- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
1. Fix raid timeline activation track to set vfx deactivated after play
2. Change intro screen sprite
> Fix raid timeline activation track, change intro screen

- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_1.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_2.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_3.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_4.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Fury.playable
- Fury Effect fix
- RunAway MotionFrame fix
https://app.asana.com/0/1141562434100787/1203833953211410/f
> [bugfix] Fury Effect / RunAway MotionFrame fix

- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Fury.playable
> [bugfix] fury Effect fix

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
- nekoyume/Assets/Resources/UI/Animations/UIMenuController@Show.anim
- nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
- Rank CP Text fix
https://app.asana.com/0/1133453747809944/1203835628748347
> [bugfix] CP Text Style fix

- nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusResultPopup.cs
1. Draw a stage buff and switch character.
2. Proceed a stage with switched character and check if stage buff is not applying.
https://app.asana.com/0/1133453747809944/1203856909785585
> [Bugfix] Prevent applying stage buff on switched character

- nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
> Update rune stat display

- nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
- Text fix
https://app.asana.com/0/1133453747809944/1203856909785597
> [Design] add

- nekoyume/Assets/Editor/Builder.cs
> Consider QA build for `macOS`

- nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Close.anim
- nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Loop_Fail.anim
- nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
- CP Text fix
https://app.asana.com/0/1141562434100787/1203770444794618
> [bugfix] RuneResult CP fix

- nekoyume/Assets/Resources/UI/Animations/UIArenaBattleContoller.controller
- nekoyume/Assets/Resources/UI/Animations/UIArenaBattleContoller.controller.meta
- nekoyume/Assets/Resources/UI/Animations/UIArenaBattleController@Close.anim
- nekoyume/Assets/Resources/UI/Animations/UIArenaBattleController@Close.anim.meta
- nekoyume/Assets/Resources/UI/Animations/UIArenaBattleController@Show.anim
- nekoyume/Assets/Resources/UI/Animations/UIArenaBattleController@Show.anim.meta
- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
> [Design] ArenaBattle Fix

- nekoyume/Assets/Resources/Prefab/Background/Chapter_04_03.prefab
- bg fix
https://app.asana.com/0/1141562434100787/1203853170865513
> [bugfix] Chapter4 Background fix

- nekoyume/Assets/Resources/AddressableAssetsContainer.asset
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Game/TableSheets.cs
- nekoyume/Assets/_Scripts/State/PetStates.cs
- nekoyume/Assets/_Scripts/State/PetStates.cs.meta
- nekoyume/Assets/_Scripts/State/States.cs
- nekoyume/Assets/_Scripts/UI/Model/RuneItem.cs
- nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossRuneStoneInventory.cs
- nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
- nekoyume/Assets/_Scripts/UI/Widget/RuneStoneItem.cs
1. SSIA
2. Add sheets(PethSheet, PetOptionSheet, PetCostSheet)
3. Render PetEnhancement action
4. Add PetStates(pet of current avatar) at States.cs
> Handle lib9c model & action about pet, PetEnhancement

- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- Combination / Shop btn Raycast fix
> [bugfix] Raycast Target fix

- nekoyume/Assets/StreamingAssets/url.json
- nekoyume/Assets/StreamingAssets/url.json.meta
- nekoyume/Assets/_Scripts/Game/Dcc.cs
- nekoyume/Assets/_Scripts/Game/Dcc.cs.meta
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
- nekoyume/Assets/_Scripts/Helper/Url.cs
- nekoyume/Assets/_Scripts/Helper/Url.cs.meta
- nekoyume/Assets/_Scripts/UI/Model/DccAvatars.cs
- nekoyume/Assets/_Scripts/UI/Model/DccAvatars.cs.meta
- nekoyume/Assets/_Scripts/UI/RequestManager.cs
https://www.notion.so/planetarium/DCC-Connect-9C-CLIENT-GUIDE-7ca13ab2e8af4ccea2a74d3ceeb2accb?pvs=4
> Introduce dcc api

- nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
1. Wearing the title costume and fighting in the arena
2. go to character select page
https://planetariumhq.slack.com/archives/CBU2JFAF3/p1676385085636639
> Delete title when GameObject is deactivated

- nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
- Change connect method to async.
- Null check.
> Fix initialization of `RPCAgent`

- nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
> fix bug about rpc agent logging

- nekoyume/Assets/Resources/Character/UI_Avatar.prefab
- nekoyume/Assets/Resources/Character/UI_Avatar.prefab.meta
- nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
- nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs
- nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Update synopsis
[시놉시스에서 캐릭터 스파인 나올때(시놉시스16, 17~) 전체 파츠 이어진 스파인 파일 없어서 진행 불가](https://docs.google.com/spreadsheets/d/1_nkvTFipD4mQF8_dfcpizssK52rxTtgaW9BUhkG4BiA/edit#gid=1912991679)
[무기 이펙트가 코스튬착용시에도 활성화 되어있음](https://docs.google.com/spreadsheets/d/1_nkvTFipD4mQF8_dfcpizssK52rxTtgaW9BUhkG4BiA/edit#gid=1912991679)
> bugfix synopsis

- .github/workflows/build.yml
- .github/workflows/new-build.yml
- nekoyume/Assets/Editor/Builder.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
Close https://github.com/planetarium/NineChronicles/issues/2359
This new build action has been tested in the [feature/android-ci](https://github.com/planetarium/NineChronicles/actions/workflows/new-build.yml) branch
The old build.yml action will be replaced by the new-build.yml action.
> [Feature] Introduce new build CI (Only for android)

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/State/States.cs
- nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
- nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
SSIA
1.  Check if game is working properly.
> Update `RuneState` and `RuneStoneBalance` on updating avatar

- .github/workflows/build.yml
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
> fix mailbox serialize bug about local mail

- nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
- nekoyume/Assets/_Scripts/Helper/PetRenderingHelper.cs
- nekoyume/Assets/_Scripts/UI/MainCanvas.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/DccMenu.cs
- nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotView.cs
- nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotViewModel.cs
- nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
https://app.asana.com/0/1133453747809944/1204004696820681/f
https://app.asana.com/0/1133453747809944/1204004384097220/f
https://app.asana.com/0/1133453747809944/1204009886813869/f
https://app.asana.com/0/1133453747809944/1204009886813816/f
https://app.asana.com/0/1133453747809944/1204004384097204/f
> Improve D:CC collection UI

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
remove Forget()
[[튜토리얼] 3스테이지 클리어 후 강제로 메인로비로 내보내지 않는 현상](https://app.asana.com/0/1133453747809944/1204036282081339/f)
> UpdateCurrentAvatarState to async-await

- nekoyume/Assets/Resources/UI/Prefabs/UI_Alert.prefab
> link missing object in Alert popup

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
> [Design]RankCell_Prefabs_Edit

- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
[Design]UI_Menu_Prefabs_Edit
speed down
> [Design]UI_Menu_Prefabs_Edit

- nekoyume/Assets/_Scripts/UI/Widget/ArenaBattle.cs
- nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
SSIA
https://app.asana.com/0/1133453747809944/1204062377684209/f
> add Status and EventBanner closing to battle ui

- nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
> handle not updated ncg at GetBalance()

- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
> Add PetButton in menu

- nekoyume/Assets/Editor/Builder.cs
Close https://github.com/planetarium/NineChronicles/issues/2370
> feat: Contain readme and oss in build result

- nekoyume/Assets/AddressableAssets/UI/Module/Currency/Mileage.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Currency/Mileage.prefab.meta
- nekoyume/Assets/Resources/HelpPopupData/HelpPopupData.json
- nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
- nekoyume/Assets/StreamingAssets/Localization/common.csv
- nekoyume/Assets/StreamingAssets/url.json
- nekoyume/Assets/_Scripts/Helper/Url.cs
- nekoyume/Assets/_Scripts/UI/Module/Mileage.cs
- nekoyume/Assets/_Scripts/UI/Module/Mileage.cs.meta
- nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
[[D:CC] D:CC / D:CC Collection 화면 재화에서 크리스탈 대신 마일리지 출력되야 함](https://app.asana.com/0/1133453747809944/1204009886813935/f)
[[D:CC] D:CC 메인화면의 메뉴명 변경](https://app.asana.com/0/1133453747809944/1204020418987824/f)
[[D:CC] help popup 2종 미출력](https://app.asana.com/0/1133453747809944/1204009886813834/f)
[[D:CC] 소환 또는 레벨업이 가능한 펫이 존재할 경우 D:CC Collection 메뉴에 레드닷이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204004384097204/f)
> Improve dcc UI

- nekoyume/Assets/AddressableAssets/Character/PetAnimator.controller
- nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
- nekoyume/Assets/Resources/Character/Pet/Pet.prefab
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Fix pet bugs
[[펫] 최초 펫 소환 후 메인 로비 진입 시 펫이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204004386614301/f)
[[펫] 빛의 발키리 특수 모션 후 멈추는 현상](https://app.asana.com/0/1133453747809944/1204004386614233/f)
[[월드보스] 펫이 좌상단이 아닌 좌중단에 출력되는 현상](https://app.asana.com/0/1133453747809944/1204004386614285/f)
[[펫] 메인로비에서 펫 클릭 시 상호작용 모션이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204004386614219/f)
> Bugfix pet

- nekoyume/Assets/StreamingAssets/url.json
- nekoyume/Assets/_Scripts/Game/Dcc.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/Url.cs
- nekoyume/Assets/_Scripts/UI/Module/Mileage.cs
- nekoyume/Assets/_Scripts/UI/RequestManager.cs
Add dcc eth chain header  : 
- **eth-chain-id**
- mainnet : 1
- testnet : 5
- @planetarium/9c-dev
> Add dcc eth chain header

- nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeView.cs
- nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeViewItem.cs
- nekoyume/Assets/Plugins/StateViewer/Editor/StateViewer.cs
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- Improve data readability of `State Viewer`.
- Improve render for `ManipulateState` action.
- (WIP) Add edit buttons for each rows in `State Viewer`.
> feat: Improve `State Viewer`

- nekoyume/Assets/Plugins/ModelViewer.meta
- nekoyume/Assets/Plugins/ModelViewer/Editor.meta
- nekoyume/Assets/Plugins/ModelViewer/Editor/ModelViewerWindow.cs
- nekoyume/Assets/Plugins/ModelViewer/Editor/ModelViewerWindow.cs.meta
- nekoyume/Assets/Plugins/ModelViewer/Runtime.meta
- Introduce `ModelViewerWindow`.
- Add `Tools/Lib9c/Model Viewer` menu.
> feat: Model Viewer

- nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
- nekoyume/Assets/_Scripts/Game/Character/FriendCharacter.cs
SSIA
[[펫] 프로필을 통해 다른 유저의 펫 확인 시 자신과 동일한 펫이 출력되는 현상](https://app.asana.com/0/1133453747809944/1204103032988303/f)
> Fix pet for friend character

- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
Edit `UI_ArenaBattle` prefab to fix profile
[UI_ArenaBattle 깨짐](https://app.asana.com/0/1141562434100787/1204143319314349/f)
> Fix arena battle profile

- nekoyume/Assets/Resources/Character/Pet/Pet.prefab
- nekoyume/Assets/_Scenes/Game.unity
SSIA
[[어드벤쳐] 캐릭터의 버프로 인하여 펫이 가려지는 현상](https://app.asana.com/0/1133453747809944/1204114152997415/f)
- Stage
- Arena
- World Boss
> Fix ingame pet position

- nekoyume/Assets/_Scripts/UI/Widget/System/TwoButtonSystem.cs
> Fix TwoButtonSystem NRE

- nekoyume/Assets/Plugins/ModelViewer/Editor/ModelViewerWindow.cs
- nekoyume/Assets/Plugins/ModelViewer/Runtime/ModelFactory.cs
- nekoyume/Assets/Plugins/ModelViewer/Runtime/ModelFactory.cs.meta
> feat: Improve Model Viewer

- nekoyume/Assets/_Scripts/UI/Widget/Popup/ProfileSelectPopup.cs
Fix invalid avatar address conversion in ProfileSelectPopup
> Fix ProfileSelectPopup for dcc connected

- nekoyume/Assets/_Scripts/UI/Module/ArenaStatus.cs
- nekoyume/Assets/_Scripts/UI/Module/RaidPlayerStatus.cs
- nekoyume/Assets/_Scripts/UI/Scroller/RankCellPanel.cs
- nekoyume/Assets/_Scripts/UI/Widget/Status.cs
> change address.ToHex() to ToString()

- nekoyume/Assets/AddressableAssets/Character/AvatarAnimator.controller
Fix `Touch->Idle` Transition in AvatarAnimator
[[캐릭터] 게임 실행 후 캐릭터 클릭 시 상호작용 애니메이션 후 캐릭터가 멈추는 현상](https://app.asana.com/0/1133453747809944/1204172051496772/f)
> Fix AvatarAnimator

- nekoyume/Assets/Resources/UI/Prefabs/UI_ProfileSelectPopup.prefab
SSIA
[[프로필] My Profile팝업에서 Locked 버튼에 마우스 오버하면 반짝이는 효과 제거](https://app.asana.com/0/1133453747809944/1204176011013216/f)
> Fix ProfileSelectPopup button animation

- nekoyume/Assets/Plugins/StateViewer/Editor/StateViewer.cs
- nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
- Re-layouting.
- Separate a state and balances.
> feat: Improve State Viewer

- nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs
> Fix pet sort order

- nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
- nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
1. Improve description of `BlockPerHourglass`
1. Check if pet effect description is changed properly.
https://app.asana.com/0/1133453747809944/1204200281250303
> Improve description blockperhourglass

- nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
> Remove applying pet effect on ItemEnhancement

- nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
- nekoyume/Assets/_Scripts/UI/Module/Pet/PetInfoView.cs
1. add subscribing address for current avatar. (RPC agent)
2. fix dcc collection ui
[[D:CC] D:CC 사이트에서 아이템 전송 시 시스템 메시지가 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204172051496953/f)
[영혼석 게이지가 이상하게 나옴](https://app.asana.com/0/1133453747809944/1204212950923602/f)
> fix rendering transfer asset and etc.

- nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
- nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
- nekoyume/Assets/_Scripts/UI/Shop/IShopView.cs
- nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
> Market Bugfix

- nekoyume/Assets/Resources/URP/URP_2d_Sprite.mat
- nekoyume/Assets/Resources/URP/URP_2d_Sprite.mat.meta
- nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs
https://app.asana.com/0/1133453747809944/1204222021853227
https://app.asana.com/0/1133453747809944/1204222802601987
> Minor bugfixes in 380rc2

- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/MimisbrunnrBtn.prefab
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
- nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
https://app.asana.com/0/1133453747809944/1204172051496744
https://app.asana.com/0/1133453747809944/1204222023874553
> Fix minor issues

- nekoyume/Assets/Resources/Character/UI_Avatar.prefab
- nekoyume/Assets/_Scripts/Game/Avatar/AvatarWeapon.cs
- nekoyume/Assets/_Scripts/Game/Avatar/AvatarWeapon.cs.meta
[[UI] 프롤로그 이후 캐릭터 생성 씬으로 넘어가는 화면에서 캐릭터의 무기가 깨진 현상 ](https://app.asana.com/0/1133453747809944/1204172051496707/f)
> Add AvatarWeapon for UI avatar.

- nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
- nekoyume/Assets/_Scripts/Game/Character/CharacterAnimator.cs
[[아레나] 첫 공격 후 다음 공격까지 캐릭터가 멈추는 현상](https://app.asana.com/0/1133453747809944/1204172051496930/f)
> Adjust the length of the attack animation

- nekoyume/Assets/Resources/UI/Prefabs/UI_CostTwoButtonPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
- nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/CostTwoButtonPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
- nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipSell.cs
- Fix conditional cost button submittable
- Disable animation of conditional cost button in shopsell
[[상점] 아이템 등록 시 AP<5일 경우 메시지 팝업에서 AP 포션 사용 시 회수, 재등록이 불가능한 현상](https://app.asana.com/0/1133453747809944/1204222803325235/f)
> Fix conditional cost button submittable

- nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattleLoadingScreen.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
- nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
- nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab
- nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerCell.cs
- nekoyume/Assets/_Scripts/UI/Module/Character/CharacterProfile.cs
- nekoyume/Assets/_Scripts/UI/Module/Item/WorldBossRankItemView.cs
- nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/ArenaBattleLoadingScreen.cs
- Fix character view for dcc profile issue
- Edit ArenaBattleLoadingScreen for apply character view, dcc profile
- Fix character view size
[[D:CC] 특정 컨텐츠에서 D:CC Profile이 적용되지 않은 현상](https://app.asana.com/0/1133453747809944/1204222023874482/f)
> Fix character view for dcc profile issue

- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
[[상점] 검색 기능이 작동하지 않는 현상](https://app.asana.com/0/1133453747809944/1204223697093950/f)
[[상점] 사용가능한 아이템만 보기 버튼이 작동하지 않는 현상](https://app.asana.com/0/1133453747809944/1204226664396911/f)
> Bugfix shop search

- nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
[[상점] 룬 조각 탭 진입 후 장비 탭 진입 시 별이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204222803325256/f)
> Fix the bug related to store option tags

- nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
[[인벤토리] 룬 상세 정보에 장착 및 업그레이드 버튼이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204223697093933/f)
> Fix soul stone ticker

- nekoyume/Assets/Resources/UI/Prefabs/UI_RuneTooltip.prefab
[[인벤토리] 룬 상세 정보에 장착 및 업그레이드 버튼이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204223697093933/f)
> Active `button` gameObject

- nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
- nekoyume/Assets/StreamingAssets/url.json
- nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
- nekoyume/Assets/_Scripts/Helper/Url.cs
- nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ProfileSelectPopup.cs
1. change dcc shortcut url.
2. add url about 'dcc mileage shop'
3. add analyzer tracking about `PetEnhancement`
https://app.asana.com/0/1133453747809944/1204172026299686/f
https://app.asana.com/0/1133453747809944/1204222023874541/f
https://app.asana.com/0/1133453747809944/1204235540077461/f
> fix dcc url and etc.

- nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
- nekoyume/Assets/_Scripts/Extensions/AvatarStateExtensions.cs
- nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
https://app.asana.com/0/1133453747809944/1204223697093917
https://app.asana.com/0/1133453747809944/1204223695811672
https://app.asana.com/0/1133453747809944/1204223695811664
https://app.asana.com/0/1133453747809944/1204223695811680
https://app.asana.com/0/1133453747809944/1204223697093925
> Fix bug in updating world information

- nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
https://app.asana.com/0/1133453747809944/1204222023874667/f
https://app.asana.com/0/1133453747809944/1204222023874541/f
> fix dcc bug

- nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
- nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
###
- Delete unused costume tabs
- Fix rune slider value type
[[상점] Hair/Ear/Eye/Tail Costume 탭 눌렀을 때, Weapon list가 출력됨](https://app.asana.com/0/1133453747809944/1204222783924733/f)
[룬 강화시 gauge가 0 으로 변경되는 현상](https://app.asana.com/0/1133453747809944/1204243837568508/f)
> Delete unused costume tabs

- nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
ssia
https://app.asana.com/0/1133453747809944/1204243837568490/f
> handling minus exp at sweep popup

- nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
SSIA
[아레나 멀티 사용시 Lose 대신 Defeat로 표시되는 현상](https://app.asana.com/0/1133453747809944/1204243840679758/f)
> Fix ArenaBattleResultPopup text

- nekoyume/Assets/_Scripts/UI/Model/ItemCountPopup.cs
- nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs
[[상점] 아이템 등록 시 룬조각/영혼석의 배경과 글씨가 노멀 등급으로 출력되는 현상](https://app.asana.com/0/1133453747809944/1204222023874606/f)
> Add a Soulstone condition to fav sell popup

- nekoyume/Assets/Resources/UI/Prefabs/UI_PetLevelUpResultScreen.prefab
- nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/PetLevelUpResultScreen.cs
https://app.asana.com/0/1133453747809944/1204244136327805
> Apply improved description on pet levelup result popup.

- nekoyume/Assets/_Scripts/UI/Widget/Screen/PetSummonResultScreen.cs
https://app.asana.com/0/1133453747809944/1204244136327805
> Fix pet summon description

- nekoyume/Assets/StreamingAssets/url.json
> bump lib9c and update url

- nekoyume/Assets/_Scripts/Game/Character/MecanimAnimator.cs
SSIA
[[아레나] Repeat를 사용해 전투 진입 시 HP가 잘못 출력되는 현상 ](https://app.asana.com/0/1133453747809944/1204278125782666/f)
> Delete throw exception in MecanimAnimator

- nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipBuy.cs
https://app.asana.com/0/1133453747809944/1204267485845072
> Subscribe blockIndex only on item which has expiration date.

- nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
- nekoyume/Assets/_Scripts/L10n/L10nManager.cs
- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
- nekoyume/Assets/_Scripts/UI/Shop/SellView.cs
[[[우편] Stone류 아이템 판매 완료 시, 우편함에서 수수료를 제외하지 않은 금액을 수령했다고 뜸+재접해야 금액 업데이트 되는 오류]](https://app.asana.com/0/1133453747809944/1204269663523021/f)
[[상점] Stone 탭에서 검색 기능이 작동하지 않는 현상](https://app.asana.com/0/1133453747809944/1204278126103275/f)
> Bugfix/fix shop 

- nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
and remove button component too
[스윕/리핏 팝업에 블러가 없음](https://app.asana.com/0/1141562434100787/1204287588055258/f)
> enable blur at sweep popup

- nekoyume/Assets/_Scripts/UI/Scroller/GridScroll.cs
> fix logic about fillWithNullToEmptyCellGroup

- nekoyume/Assets/Planetarium/Nekoyume/Editor/LibplanetEditor.cs
- nekoyume/Assets/_Scripts/BlockChain/Agent.cs
- nekoyume/Assets/_Scripts/BlockChain/BlockManager.cs
> fix: adjustment bump lib9c

- nekoyume/Assets/Resources/UI/Animations/DccCollection@Close.anim
- nekoyume/Assets/Resources/UI/Animations/DccCollection@Close.anim.meta
- nekoyume/Assets/Resources/UI/Animations/DccCollection@Show.anim
- nekoyume/Assets/Resources/UI/Animations/DccCollection@Show.anim.meta
- nekoyume/Assets/Resources/UI/Animations/DccCollectionController.controller
- nekoyume/Assets/Resources/UI/Animations/DccCollectionController.controller.meta
- nekoyume/Assets/Resources/UI/Animations/DccMain@Close.anim
- nekoyume/Assets/Resources/UI/Animations/DccMain@Close.anim.meta
- nekoyume/Assets/Resources/UI/Animations/DccMain@Show.anim
- nekoyume/Assets/Resources/UI/Animations/DccMain@Show.anim.meta
- nekoyume/Assets/Resources/UI/Animations/DccMainController.controller
- nekoyume/Assets/Resources/UI/Animations/DccMainController.controller.meta
- nekoyume/Assets/Resources/UI/Animations/UI_DccMain.controller
- nekoyume/Assets/Resources/UI/Animations/UI_DccMain.controller.meta
- nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
1. SSIA
2. add empty animation
[[D:CC] D:CC Collection 화면 최초 진입 시, D:CC 버튼 점멸하는 현상](https://app.asana.com/0/1133453747809944/1204176011013259/f)
[[D:CC] D:CC Collection에서 리스트 사이 간격 세팅 필요](https://app.asana.com/0/1133453747809944/1204172025893997/f)
> Update UI of Dcc collection

- nekoyume/Assets/_Scripts/Game/Dcc.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/UI/RequestManager.cs
SSIA
[메인로비진입 시 유저정보등이 기본 정보로 표시되는 현상](https://app.asana.com/0/1141562434100787/1204296235934751/f)
> add yield return to CoInitDccAvatar()

- nekoyume/Assets/_Scripts/Analyzer.cs
> enable Mixpanel tracking

- nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
SSIA
[[가이드퀘스트] 이벤트 탭 클릭 후 가이트 퀘스트 진입 시 하단의 레시피가 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204036280897303/f)
> Fix Recipe Scroll row

- nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
SSIA
[[상점] ap 사용하는 동안 상단 ap바에 로딩 상태가 표시되지 않음](https://app.asana.com/0/1141562434100787/1204267485845083/f)
> Add LocalLayerModifier, AP loading in ShopSell actions

- nekoyume/ProjectSettings/ProjectSettings.asset
SSIA
before:
after:![image](https://user-images.githubusercontent.com/48484989/229745940-b37ee137-b5ed-4dd6-aeee-a2d165499e02.png)
> change stack trace option to script only from full

- nekoyume/Assets/Planetarium/Nekoyume/Editor/LibplanetEditor.cs
- nekoyume/Assets/_Scripts/BlockChain/Agent.cs
- nekoyume/Assets/_Scripts/BlockChain/BlockManager.cs
1. Enables unity editor testing.
1. Generate new genesis block by unity menu in Screenshot.
2. Run game in editor
> Propose blocks in unity editor

- nekoyume/Assets/Plugins/BalanceTool/Editor/BalanceToolWindow.cs
- nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.PlayData.cs
- nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeView.cs
- nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerWindow.cs
- nekoyume/Assets/Plugins/StateViewer/Runtime/BlacksmithMaster.cs
- nekoyume/Assets/Plugins/StateViewer/Runtime/StateTreeViewItemModel.cs
- Remove `wave count` input field.
- Improve expanded state of tree items.
- Add `Source From` option.
- Base64 Encoded Bencodex Value: Get base64-encoded bencodex value and decode it.
- Hex Encoded Bencodex Value: Get hex-encoded bencodex value and decode it.
- Get State From Play Mode Agent: The feature that is already present.
- Refactor minor.
> Fix and improve editor tools

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs
1. add param out AvatarState outAvatarForRendering, set outAvatarForRendering to the pre-simulate state of the first winning avatar.
2. change spec of out StageSimulator firstStageSimulator(outSimulator) set outSimulator to first simulator or first winning simulator. 
[Repeat 이용 중 클리어한 전투 있을 경우 해당 전투 렌더](https://app.asana.com/0/958521740385861/1203205806003658/f)
> change signature of `GetHackAndSlashReward()` and logic

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Modify to update the fav when the action fails
https://planetariumhq.slack.com/archives/C01SY622W9E/p1681015337922339
> Modify to update the fav when the action fails

- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
> Fix Shop page reset

- nekoyume/Assets/StreamingAssets/Localization/common.csv
> Fix l10n value

- nekoyume/Assets/StreamingAssets/Localization/common.csv
> Fix l10n typo

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs
re- request
https://github.com/planetarium/NineChronicles/pull/2597
> Fix rpc/agent condition check logic (re request)

- nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Add Dict with ItemSubTypeFilter for toggleTypes, toggleSubTypes
[[상점] Stone 목록에 Price per Unit 정렬기준이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204476673878104/f)
> Fix Shop sort filter

- nekoyume/Assets/_Scripts/Helper/Util.cs
SSIA
[[아레나] 티켓 리필 시간이 0분으로 출력되는 현상](https://app.asana.com/0/1133453747809944/1204476676881833/f)
> Fix arena ticket block to time

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/Util.cs
- nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
Fix LiveAssetManager.instance.GameConfig.SecondsPerBlock NRE in Game Init
> Fix util block to time

- nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
> fix bug about local mail helper

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/UI/Shop/SellView.cs
> Fix Shop sell update

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/Url.cs
> handling to load `url.json` at android os

- nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs
Fix usage of `Agent.cs` and `RPCAgent.cs` condition logic.
> Fix agent and RPC conditoin checking logic

- nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_StageBuff.prefab
SSIA
[[1회성 버프] 버프 리스트의 아이콘이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204476676881891/f)
> Fix buff list icon image

- nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
> fix using origin mail box

- nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
- nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
SSIA
[[상점] Stone 카테고리에서 검색이 제대로 동작하지 않습니다.](https://app.asana.com/0/1133453747809944/1204486077310806/f)
> Fix Shop Search filter in Stone

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
> Fix casting exception when tracking actions.

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Reverts planetarium/NineChronicles#2618
> Revert "Fix casting exception when tracking actions."

- nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
- nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
- Improve https://github.com/planetarium/NineChronicles/pull/2613
- Apply market service https://github.com/planetarium/market-service/pull/47
> Fix shop search filter to multiple ticker

- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
- Fix shop bugs
- level filter, loading ui
[사용가능한 장비 필터가 정상적으로 동작하지 않는 문제](https://app.asana.com/0/1141562434100787/1204520372382302/f)
> Fix shop bugs

- .github/workflows/build.yml
- nekoyume/Assets/Editor/Builder.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
ssia, export android build to .aab from .apk
> add androidAppBundle value to true

- nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
- Edit IsMimisbrunnrSubRecipe in SubRecipeView
- Edit increasePoint in subRecipeView
Refer commits
Apply this pr https://github.com/planetarium/lib9c/pull/1898
> Bugfix SubRecipeView

- nekoyume/Assets/_Scripts/BlockChain/Agent.cs
- nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
- nekoyume/Assets/_Scripts/Helper/Util.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
1. LocalMailHelper
2. StakingPopup
3. Apv
> remove noisy bug logging

- nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
> Fix SubRecipeView(crystal equipment) bug

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs
- Prevent NRE when every battle is lost in repeat
- Bump lib9c
> Prevent NRE when every battle is lost in repeat.

- nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Edit supercraft ui to fix default tab for normal recipe
[[공방] 슈퍼크래프트 진입 시 디폴트로 프리미엄 레시피가 선택되지 않는 현상](https://app.asana.com/0/1133453747809944/1204608056739142/f)
> Fix supercraft default tab

- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_BossStatus.prefab
- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/UI/Module/BuffLayout.cs
1. Remove extra field in arena.
2. Add more buff icons in `BuffLayout` to prevent NRE.
3. Bump lib9c.
> Remove extra field in arena.

- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationResultPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
- Fix workshop result popup for more than 3 options
- CombinationResultPopup
- EnhancementResultPopup
[[메일] 서브 옵션이 서로 다른 3가지일 경우 제작 및 강화 성공 화면에서 3번째 옵션이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204627454773910/f)
- CombinationResultPopup
- EnhancementResultPopup
Just check
> Fix workshop ResultPopup options

- nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
> Get state from Agent on arena render

- nekoyume/Assets/Resources/Recipe/EquipmentSubRecipeTab.json
- nekoyume/Assets/_Scripts/Helper/Util.cs
Fix equipment recipe id to reflect this pr https://github.com/planetarium/lib9c/pull/1928
[[공방] 해금된 레시피가 잠겨있는 현상](https://app.asana.com/0/1133453747809944/1204644049131708/f)
> Fix equipment recipe id

- nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
> change initializing value of LocalMailHelper

- nekoyume/Assets/Resources/UI/Materials/Distortion_Additive_Maskable.shader
> fix Distortion_Addtive_Maskable shader for rect mask 2d

- nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Make GetBonusOptionProbability work in supercraft
> Bug fix in supercraft pet.

- nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/EnhancementResultSkillOptionView.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/EnhancementResultSkillOptionView@Show.anim
- nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
- nekoyume/Assets/_Scripts/UI/Module/ItemOption/ItemOptionView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/EnhancementResultPopup.cs
> add masking scroll text to skill option

- nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
> Hide zero skill power on enhancement.

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
do not load rocksdb native library
> change android version to 31 and fix bug

- nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
SSIA
[[상점] Show only available items.체크 시 레벨에 상관 없이 미미르 장비가 출력되는 현상](https://app.asana.com/0/1133453747809944/1204719299906188/f)
> Edit `BuyView.GetSortedModels` to check mimir level

- nekoyume/Assets/StreamingAssets/Localization/DirectoryForAndroid.txt
Reverts planetarium/NineChronicles#2699
> Revert "improve something about l10n"

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
> Create arena digest from `OutputStates` on render `BattleArena`

- nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
1. Remove/Disable MimisbrunnrBattle related UI elements.
2. Make `mimisbrunnr_battle13` obsolete.
1. Check if mimisbrunnrBattle related UI elements are blocked/disabled properly.
https://app.asana.com/0/958521740385861/1204791556422022
> Block mimisbrunnr for v200030

- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
- nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
1. Fix blocker on `CreateAvatar`.
2. Change some layouts in `UI_SettingsPopup`
> Fix blocker on `CreateAvatar`.

- nekoyume/Assets/_Scripts/UI/Login/LoginDetailCostume.cs
- to fix bug - costume color palette doesn't init
> Fix HairToggle init in LoginDetail

- .github/workflows/build.yml
> fix extract internal trigger

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
> assemble EnemyAvatarState for BattleArena rendering

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/BlockRenderHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
- nekoyume/Assets/_Scripts/State/RxProps.cs
- nekoyume/Assets/_Scripts/State/States.cs
- nekoyume/Assets/_Scripts/State/Subjects/AgentStateSubject.cs
- nekoyume/Assets/_Scripts/UI/Model/RuneItem.cs
- nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
- nekoyume/Assets/_Scripts/UI/Module/Pet/PetInfoView.cs
- nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossRuneStoneInventory.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
- nekoyume/Assets/_Scripts/UI/Widget/RuneStoneItem.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
And.. cleanup a couple of scripts.
> Handle the render of `UnloadFromMyGarages` action

- nekoyume/Assets/_Scripts/UI/Login/DeepLinkHandler.cs
> Add new param to portal open url

- nekoyume/Assets/_Scripts/Game/Game.cs
> Fix platform exception

- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> chore: bump `lib9c` development head

- nekoyume/Assets/_Scripts/Game/Game.cs
> Fix check clo rpc client

- .github/workflows/build.yml
- nekoyume/Assets/Editor/Builder.cs
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
- Block input handling at Loginsystem
- Change company name to `Planetariumlabs`
- Change product name to `Nine Chronicles`
- Enable build option `Split Application Binary`
> develop something for mobile

- nekoyume/Assets/_Scripts/Game/ActionCamera.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/UI/CapturedImage.cs
apply static android aspect ratio to (1136/640)
> Fix Android aspect ratio diynamic to static

- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductSchema.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
- feat: add `PurchaseCount` to `ProductSchema`
- feat: apply `ProductSchema.PurchaseCount` to `IAPShopView`
> feat: apply changes of IAP `ProductSchema`

- nekoyume/Assets/Plugins/Android/AndroidManifest.xml
> add android manifest ADID permission

- nekoyume/Assets/_Scripts/UI/CapturedImage.cs
change background blur texture copy size
> fix change background blur texture copy size

- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
- `Unity/Lobby/ShopButton/Click`
- `Unity/Shop/IAP/Tab/Click`
- `product-id`
- `Unity/Shop/IAP/PurchaseButton/Click`
- `product-id`
- `Unity/Shop/IAP/PurchaseResult`
- `product-id`
- `result`
- `transaction-id`
- `Unity/MailBox/UnloadFromMyGaragesRecipientMail/ReceiveButton/Click`
> feat: track more events related to `Shop` UI

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/StreamingAssets/Localization/common.csv
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> improve l10n for mobile

- nekoyume/Assets/_Scripts/Game/RaidCamera.cs
fix RaidCamera ratio
https://app.asana.com/0/1133453747809944/1205066404170562
> fix RaidCamera ratio dynamic to static

- nekoyume/Assets/Editor/Builder.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> fix: toggle value change at mobile shop

- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Editor/IAPServiceToolWindow.cs
- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> fix: disable cache of `IAPServiceManager`

- nekoyume/Assets/Resources/UI/Prefabs/UI_DialogPopup.prefab
Design]UI_DialogPopup_Prefabs_Edit
> Design]UI_DialogPopup_Prefabs_Edit

- nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
ui synopsis textarea fix
https://app.asana.com/0/1133453747809944/1204993181887422
> fix ui synopsis size fix

- nekoyume/Assets/StreamingAssets/Localization/common.csv
- nekoyume/Assets/StreamingAssets/Localization/elemental_type.csv
Restore translation to originality
add l10n
> edit local data rc

- nekoyume/ProjectSettings/ProjectSettings.asset
> fix pakage name

- nekoyume/Assets/Planetarium/Nekoyume/Editor/CloSettingToolWindow.cs
- nekoyume/Assets/Planetarium/Nekoyume/Editor/CloSettingToolWindow.cs.meta
-How to Open tool
-tools -> CLO_Setting
> add CommendLineOption Setting tool Add

- nekoyume/Assets/Resources/UI/Prefabs/UI_GrindingLoadingScreen.prefab
- nekoyume/ProjectSettings/ProjectSettings.asset
> fix: disable raw image of grinding loading screen

- nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationResultSkillOptionView.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationResultStatOptionView.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationSlotPopupCombinationSkillOptionView.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationSlotPopupCombinationStatOptionView.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationResultPopup.prefab
https://app.asana.com/0/1133453747809944/1205071038791341/f
> Add missing l10n component to tmp

- nekoyume/Assets/Resources/UI/Prefabs/UI_VersionSystem.prefab
- nekoyume/Assets/_Scripts/UI/Widget/System/VersionSystem.cs
application version view exception handling
change wrapmode application version view text
> fix application version view exception handling

- nekoyume/Assets/Tests/EditMode/Battle/AttackCountHelperTest.cs
- nekoyume/Assets/Tests/EditMode/Battle/AttackCountHelperTest.cs.meta
- nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
- nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
ssia, revert 7f547404c797d9e40747d30befe74cb3bf0bc424
> hotfix: stuck on self buff of enemy

- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Status.cs
https://app.asana.com/0/0/1205081206189990/f
> Obsolete dcc ui for mobile

- nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopView.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
fix iap purchase btn loading animation add
https://app.asana.com/0/958521740385861/1205081206910749
> fix iap purchase btn loading animation add

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
guest button-edd
https://app.asana.com/0/958521740385861/1205098502094321
> [Design]UI_IntroScreen_Prefabs_Edit

- nekoyume/Assets/_Scripts/Game/Stage.cs
> chore: log more info of `Stage`

- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_PrologueDialogPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
block-hash_test_overlap_Prefabs_Edit
https://app.asana.com/0/958521740385861/1205081206910756
> [Design]block-hash_test_overlap_Prefabs_Edit

- nekoyume/Assets/StreamingAssets/clo-local-network-test.json
- nekoyume/Assets/StreamingAssets/clo-local-network-test.json.meta
> add local network clo setting

- nekoyume/Assets/Resources/UI/Prefabs/UI_StageLoadingEffect.prefab
UI_StageLoadingEffect_Prefabs_Edit
https://app.asana.com/0/958521740385861/1205041689885120
> [Design]UI_StageLoadingEffect_Prefabs_Edit

- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> feat: remove if branching at already has keystore

- nekoyume/Assets/Resources/Worldboss/Prefab/Item_WorldBossWave_01.prefab
fixed worldboss effect scale fix
https://app.asana.com/0/1141562434100787/1205071038791294
> fixed worldboss effect scale fix

- nekoyume/Assets/_Scripts/Animation/RaidTimelineContainer.cs
fix skipbtn position
https://app.asana.com/0/1141562434100787/1205071038791304
> fix worldboss skipbtn flip issue

- .gitignore
- nekoyume/Assets/Plugins/StateViewer/Editor/Features/StateAndBalanceFeature.cs
- nekoyume/Assets/Plugins/StateViewer/Editor/Features/TrackStateFeature.cs
- nekoyume/Assets/Plugins/StateViewer/Editor/Features/TrackStateFeature.cs.meta
- nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerWindow.cs
- nekoyume/Assets/Plugins/StateViewer/Runtime/StateProxy.cs
- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
- nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- This feature only supports the specific case now.
- The source CSV must have the following columns:
- index, block_index, block_hash, tx_id, signer_addr, prev_block_index, prev_block_hash
- Take source csv from [here](https://gist.github.com/boscohyun/7ea824c8264920f1eb650b6ee66360c5).
> feat: implement `TrackState` feature on `StateViewer`

- nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab
- nekoyume/Assets/StreamingAssets/Localization/common.csv
- nekoyume/Assets/_Scripts/UI/MainCanvas.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
\+ add l10n keys
```
UI_INVALID_CREATED_PASSWORD,"The entered password is not in the conditions
Please use a stronger password.",,,,,,,,,,
UI_INVALID_RETYPE_PASSWORD,"The entered password is not incorrect
Please check your password.",,,,,,,,,,
```
https://app.asana.com/0/0/1205081206189997/f
> Edit LoginSystem ui, add alert popup

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
- nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
- nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/CelebratesPopup.cs
> Update questReward interface

- nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Currency/ArenaTickets.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonus.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Currency/EventDungeonTickets.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Currency/WorldBossTickets.prefab
- nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
[Design]TimeRelated_Prefabs_Edit
https://app.asana.com/0/958521740385861/1204791556422024
> Fix block time match

- nekoyume/Assets/_Scripts/Game/Game.cs
> Add mixpanel track pledge success

- nekoyume/Assets/_Scripts/Game/Game.cs
ssia
---
- https://app.asana.com/0/0/1205181366612739
> feat: change store option to Google from GoogleTest

- .gitignore
- nekoyume/Assets/StreamingAssets/Localization/mail.csv
- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
- nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
ssia
---
- https://app.asana.com/0/0/1205178149530217
> Revert "feat: improve `UnloadFromMyGaragesRecipientMail` UI"

- nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
ssia
---
- https://app.asana.com/0/0/1205177934360483
> chore: disable rayCastTarget of text at StakingPopup

- .gitignore
- nekoyume/Assets/StreamingAssets/Localization/mail.csv
- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
- nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
- nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> revert #2840 and fix async

- nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
- nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
https://app.asana.com/0/1133453747809944/1205168764948315/f
> Fix block time ui space

- nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
ssia
---
- https://app.asana.com/0/0/1205177934360508
> chore: reduce font size and change vertical alignment at LoginSystem

- nekoyume/Assets/_Scripts/Game/Game.cs
https://app.asana.com/0/958521740385861/1205188607913462
> fix arena push notification content not matched

- .editorconfig
- .github/workflows/build-via-workflow-dispatch.yaml
This pull request resolves #2789.
> feat(GitHub Actions): introduce Build via Workflow Dispatch

- .github/workflows/build-via-workflow-dispatch.yaml
https://github.com/planetarium/NineChronicles/actions/runs/5781647615
> fix(github-actions): Build via Workflow Dispatch

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
https://app.asana.com/0/958521740385861/1205178662132774/f
> Add Skip button to intro video

- .github/workflows/build-via-workflow-dispatch.yaml
> feat(github-actions): set `clo.json` file at `Build via Workflow Dispatch`

- nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_DialogPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Popup/DialogPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/ProjectSettings/TimeManager.asset
- fix blur bug about CelebratesPopup
- speed up DialogPopup
- Time scale to 1.25
> improve ux for 30

- nekoyume/Assets/_Scripts/Game/Stage.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
- nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
- nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
- nekoyume/Assets/_Scripts/UI/Widget/Login.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ChatPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
- nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
- nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
ssia
---
- https://app.asana.com/0/0/1205229458597611
> feat: remove using HelpTooltip.Helpme with showOnceForEachAgentAddress

- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/_Scripts/Game/Prologue.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
- nekoyume/Assets/_Scripts/UI/Tween/HoverScaleTweener.cs
- nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
- show menu name when anytime.
- etc
---
- https://app.asana.com/0/0/1205209318560947
> improve menu ui

- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
1. First step.
---
- https://app.asana.com/0/0/1205209318560926
> feat: revert removed hackandslash tutorial code

- nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
https://app.asana.com/0/1133453747809944/1205177934361580/f
> Fix broken text ui

- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
change loading timing
https://app.asana.com/0/1204953038735453/1205081206910758/f
> change loading timing

- nekoyume/Assets/_Scripts/Analyzer.cs
> fix(Analyzer): replace "/" to "_" of event name and key for Firebase Analystics

- nekoyume/Assets/Plugins/StateViewer/Editor/Features/TrackStateFeature.cs
> bump(lib9c): release/0.5.0

- nekoyume/Assets/_Scripts/Analyzer.cs
For the sake of intermediate releases, this PR backports https://github.com/planetarium/NineChronicles/pull/2874 via cherry-picking.
---
- https://app.asana.com/0/0/1205254209627254
> Backport #2874

- .github/workflows/build-misc.yml
- .github/workflows/build.yml
> chore(github-actions): add more trigers to build workflow

- nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
Arena-test_edit
https://app.asana.com/0/1133453747809944/1205228460716082
https://app.asana.com/0/1133453747809944/1205177934361580
> [Design]UI_ArenaJoin_Prefabs_Edit

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
ssia
---
- https://app.asana.com/0/0/1205209319875040
> change push notification limit for craft, upgrade

- nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab.meta
- nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs
ssia
---
- https://app.asana.com/0/0/1205209318560932
> feat: add receive all feature and button to QuestPopup

- nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
- nekoyume/Assets/UIResources/Content/Shop/Prefab/IAP_ProductTab.prefab
ssia
---
- https://app.asana.com/0/0/1205066832579029
> feat: add toggle sfx to MobileShop

- nekoyume/Assets/_Scripts/Game/Stage.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
https://app.asana.com/0/958521740385861/1205229458598652/f
> Disable repeat button on failed

- nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
- nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs
- nekoyume/Assets/_Scripts/UI/Module/Item/StakingInterestBenefitsView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
ssia
https://app.asana.com/0/1133453747809944/1205264919576382/f
https://app.asana.com/0/1133453747809944/1205264919576374/f
> fix apply changed staking rewards to monster collection render

- nekoyume/ProjectSettings/ProjectSettings.asset
- tools/pack/pack.py
> chore: change product name to "NineChronicles"

- .github/bin/install-bundletool.sh
- .github/workflows/build.yml
> [CI] Upload apk in android build

- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
https://app.asana.com/0/1133453747809944/1205289861109119/f
> Add Check Keystore in IntroScreen, Portal Deeplink

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
https://app.asana.com/0/1133453747809944/1205282330287767/f
> Fix Intro background

- nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
- set timeout to 10 seconds.
- try catch HTTP networking exceptions.
> fix: failure of MarketServiceClient networking

- nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
ssia
https://app.asana.com/0/1204953038735453/1205282330287759/f
> bugfix stakingpopup render issue

- nekoyume/Assets/Planetarium/Nekoyume/Editor/Nekoyume-editor.asmdef
- nekoyume/Assets/Planetarium/Nekoyume/Editor/ScreenEditorMenus.cs
- nekoyume/Assets/Planetarium/Nekoyume/Editor/ScreenEditorMenus.cs.meta
- nekoyume/Assets/_Scripts/Game/ActionCamera.cs
- nekoyume/Assets/_Scripts/Game/RaidCamera.cs
add unity editor command to change screen ratio settings
> add screen ratio editor commands

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
> Prepare/release 40.0.0

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
https://app.asana.com/0/1133453747809944/1205282330287804/f
> Fix loading indicator duplication

- nekoyume/Assets/Resources/UI/Prefabs/UI_OneButtonSystem.prefab
SSIA
https://app.asana.com/0/1133453747809944/1205282330287775/f
> Edit OneButtonSystem bg

- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
https://app.asana.com/0/1133453747809944/1205290719527514/f
> Add api re-request code

- .github/workflows/android-googleplay-release.yml
add new github action for test
> add googleplay release git action workflow

- .github/workflows/build.yml
> [CI] Handle semver versioning in internal deploy

- .github/workflows/build.yml
> cherry-pick: c63cd6c

- .github/workflows/build.yml
> merge "release/40.0.1" into "main"

- .github/workflows/android-build-and-release.yml
- .github/workflows/build.yml
Change aws credential config method to assume role
> [CI] Change aws credentials

- .github/workflows/android-googleplay-release.yml
> add googleplaystore deploy

- .github/workflows/android-googleplay-release.yml
> reflecting af4bf(commit ref) changes

- .github/workflows/android-googleplay-release.yml
> remove checkout step

- .github/workflows/android-build-and-release.yml
> add android versioncode to workflows/android-build-and-release.yml

- .github/workflows/android-build-and-release.yml
> add manual build option for android-build-and-release.yml

- nekoyume/Assets/StreamingAssets/Localization/item_description.csv
- nekoyume/Assets/StreamingAssets/Localization/item_name.csv
BNB Costeme L10n Add
- item_name
- item_description
> Update BNB Costeme Add

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- Delete loop video in introscreen
- Edit start button in introscreen to open portal
> Edit intro screen to improve ui

- nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
https://app.asana.com/0/1133453747809944/1205362519782269/f
> Fix craft recipe filtering

- nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab
- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
https://app.asana.com/0/1133453747809944/1205375566033937/f
> Fix tutorial CombineEquipmentCategory position

- nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
- nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
https://app.asana.com/0/1133453747809944/1205384410670316/f
https://app.asana.com/0/1133453747809944/1205384411839188/f
> Fix recipe scroll

- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
> 2023q3 aura

- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
ssia
before: any
after: count > 1
---
- https://app.asana.com/0/0/1203863020824773
> fix: change mail all receive button condition

- nekoyume/Assets/_Scripts/L10n/L10nManager.cs
Reopen https://github.com/planetarium/NineChronicles/pull/2969
1. First step.
> [Fix] L10nManager filename split error

- nekoyume/Assets/AddressableAssets/UI/Module/EnhancementInventory.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
> add aura in upgrade inventory

- nekoyume/Assets/Resources/AddressableAssetsContainer.asset
- nekoyume/Assets/_Scripts/Game/TableSheets.cs
- bump lib9c:development which was merged lib9c:feat/revice-staking branch.
- apply StakePolicySheet to TableSheets and AddressableAssetsContainer.
> feat: revice staking

- nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
- nekoyume/Assets/_Scripts/UI/Module/Stat/EnhancementSkillOptionView.cs
> change new skill description

- .gitignore
- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/StreamingAssets/Localization/common.csv
- nekoyume/Assets/_Scripts/Blockchain/BlockManager.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
- nekoyume/Assets/_Scripts/Helper/ResourcesHelper.cs
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/Settings.cs
- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
- nekoyume/Assets/_Scripts/UI/MainCanvas.cs
- nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
- nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/DccMenu.cs
- nekoyume/Assets/_Scripts/UI/Shop/CartView.cs
- nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/GrayLoadingScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
ssia
---
- https://app.asana.com/0/0/1205441217544248
> re-revert 40.1.0, add analyzer event

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/StreamingAssets/Localization/common.csv
- nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
ssia
---
- https://app.asana.com/0/0/1205454905164919
- https://app.asana.com/0/0/1205454905164917
> Improve/intro UI

- .gitignore
- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/StreamingAssets/Localization/common.csv
- nekoyume/Assets/_Scripts/Blockchain/BlockManager.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
- nekoyume/Assets/_Scripts/Helper/ResourcesHelper.cs
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/Settings.cs
- nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
- nekoyume/Assets/_Scripts/UI/MainCanvas.cs
- nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
- nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/DccMenu.cs
- nekoyume/Assets/_Scripts/UI/Shop/CartView.cs
- nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/GrayLoadingScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
- nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> Fast track/50.3.0

- nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs
- nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
SSIA
https://app.asana.com/0/1133453747809944/1205464180759289/f
---
- https://app.asana.com/0/0/1205464180759289
> bugfix Enhancement effect

- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
---
- https://app.asana.com/0/0/1205464180759198
> chore: add lock object to shop menu ui

- nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/Assets/_Scripts/Extensions/StakeStateUtilsForClient.cs
- nekoyume/Assets/_Scripts/Extensions/StakeStateUtilsForClient.cs.meta
- nekoyume/Assets/_Scripts/State/States.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
- Nekoyume.States
- Nekoyume.UI.StakingPopup
- stake3 action render handler
> feat: consider StakeStateV2 in client

- nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
- bump lib9c:release/1.1.0
- use AuraSummon.SimulateSummon() directly in Summon UI
> chore: bump lib9c:release/1.1.0

- nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
> bugfix aura equipmenet bug when equip costume

- nekoyume/Assets/_Scripts/UI/Scroller/GridScroll.cs
- nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
> bugfix enhancement matrialscrollview position refresh limit

- nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
SSIA
[https://app.asana.com/0/1133453747809944/1205473403807541/f]
> fix conditionalCostButton legacy functional

- nekoyume/Assets/Resources/UI/Animations/UI_SummonResult@Hide.anim
- nekoyume/Assets/Resources/UI/Animations/UI_SummonResult@Normal.anim
- nekoyume/Assets/Resources/UI/Animations/UI_SummonResult@ShowButton.anim
- nekoyume/Assets/Resources/UI/Animations/UI_SummonResultPopup.controller
- nekoyume/Assets/Resources/UI/Prefabs/UI_SummonResultPopup.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
SSIA
+ fix result animation
https://app.asana.com/0/1133453747809944/1205473403807522/f
https://app.asana.com/0/1133453747809944/1205473403807560/f
> Update UI for summon count bonus

- nekoyume/Assets/_Scripts/UI/Module/Stat/EnhancementSkillOptionView.cs
SSIA
[https://app.asana.com/0/1133453747809944/1205473403807607/f]
> bugfix endhancement skill description

- nekoyume/Assets/Resources/Prefab/PlayerPlace.prefab
> player place renderoder and position change

- nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
- use StakeStateV2.Contract.RewardInterval or StakeState.RewardInterval in StakingPopup
- bump lib9c:release/1.1.0
> fix StakingPopup and bump lib9c:release/1.1.0

- nekoyume/Assets/_Scripts/UI/Module/Stat/RecipeOptionView.cs
SSIA
https://app.asana.com/0/1133453747809944/1205496877529812/f
> fix recipe skillOption ratio

- nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
https://app.asana.com/0/958521740385861/1205497145430587/f
> Fix submit button font asset

- nekoyume/Assets/_Scripts/AOTGenerated/MagicOnion.Generated.cs
Bump `NineChronicles.RPC.Shared` for `IBlockChainService.GetBlockHash`
> feat: bump `NineChronicles.RPC.Shared`

- nekoyume/Assets/AddressableAssets/UI/Module/Skill/SkillView_Enhancement.prefab
SSIA
---
- https://app.asana.com/0/0/1205497940298481
> fix font setting

- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
---
- https://app.asana.com/0/0/1205495748210053
> fix: change mobile shop price to iso currency code

- nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
SSIA
---
- https://app.asana.com/0/0/1205505153976045
> fix grind Inventory best item notification

- nekoyume/ProjectSettings/ProjectSettings.asset
> fix AndroidBundleVersionCode 52->53

- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
ssia
---
- https://app.asana.com/0/0/1205505058998029
> fix: disable signin button

- nekoyume/Assets/StreamingAssets/Localization/common.csv
> Update Aura Sub Type L10n Add

- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
> Cherry-pick pull request #3057 into fast-track/50.4.0

- nekoyume/Assets/Editor/TutorialTestingEditor.cs
- nekoyume/Assets/Editor/TutorialTestingEditor.cs.meta
- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
- nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
---
- https://app.asana.com/0/0/1205486018159450
> fix tutorial guide highlighting

- nekoyume/Assets/_Scripts/Analyzer.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
ssia
---
- https://app.asana.com/0/0/1205526738983289
> fix: uniqueId to uuid

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
ssia
---
- https://app.asana.com/0/0/1205526516621898
> fix: set GoogleSigninBehaviour state to Canceled when task fault

- nekoyume/ProjectSettings/ProjectSettings.asset
> chore: update app bundleVersion to 50.4.0

- nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> fix battle tutorial bug

- nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
- nekoyume/Assets/_Scripts/PushNotifier.cs
- nekoyume/Assets/_Scripts/Settings.cs
- nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
> add patrol reward push notification

- nekoyume/Assets/Resources/ScriptableObject/Avatar.asset
> add costume data

- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> Bump lib9c dev

- nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
SSIA
https://app.asana.com/0/1204953038735453/1205517050442621/f
> fix grid sort order

- nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
Fix patrol reward
- unregistered avatar model initialization
- initialization for changed avatar
- notification time
> Fix patrol reward model

- nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
> Delete dummy code for test

- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
> fix mailbox notification rule

- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
- nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> Fix renderer not work

- nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> Prepare/70.0.0 to Release/70.0.0

- nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
> Fix interval text in patrol reward popup

- nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
SSIA
---
- https://app.asana.com/0/0/1205566148223896
> change price formatting

- nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
SSIA
---
- https://app.asana.com/0/0/1205566139277158
> fix skill description exception handle

- nekoyume/Assets/AddressableAssets/UI/Module/ItemView/RequiredItemView.prefab
... for materials over 1000
---
- https://app.asana.com/0/0/1205579183327595
> Edit RequiredItemView text size

- nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
SSIA
---
- https://app.asana.com/0/0/1205566148224954
> Add blur to patrol reward popup

- nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
logic on change avatar
---
- https://app.asana.com/0/0/1205566148224962
> Fix patrol reward claim

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
SSIA
---
- https://app.asana.com/0/0/1205566148223912
> Bugfix/70.0.0 patrol crystal UI fix

- nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
ssia
---
- https://app.asana.com/0/0/1205526479862396
> chore: add analyzer tracking about synopsis skip

- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/MenuOpen_Obj.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
- nekoyume/Assets/_Scripts/Game/Stage.cs
ssia
---
- https://app.asana.com/0/0/1205459309650233
> Redesign contents unlock UI

- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
ssia
---
- https://app.asana.com/0/0/1205566148224946
> fix: change all receive button condition

- nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
- nekoyume/Assets/_Scripts/UI/Module/IAP/IAPRewardView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
SSIA
---
- https://app.asana.com/0/0/1205579189969149
- https://app.asana.com/0/0/1205579189969141
> fix mobile shop item tooltip and itemvisible

- nekoyume/Assets/Resources/UI/Animations/UILevelUpCelebratePopup@Show.anim
- nekoyume/Assets/_Scripts/Game/VFX/LevelUpVFX.cs
vfx, animation time (enable : 2s -> 3s)
---
- https://app.asana.com/0/0/1205459309650231
> Edit Levelup vfx, animation time

- nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
- nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
> add loadingScreen when download detail productBgImages

- nekoyume/ProjectSettings/ProjectSettings.asset
> chore: update app bundle version to 60.1.0

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab
- nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
SSIA
---
- https://app.asana.com/0/0/1205589166890210
- https://app.asana.com/0/0/1205589166890202
> fix buy limit product count, and dim

- nekoyume/Assets/_Scripts/Game/Game.cs
> fix: remove disabling unity logger

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
[[방치 보상] 방치 보상 획득 시 크리스탈의 수량이 즉시 적용되지 않는 현상](https://app.asana.com/0/1133453747809944/1205648186869885/f)
> Fix Currency update on UnloadFromMyGarage

- nekoyume/Assets/_Scripts/Game/Game.cs
cherry-pick this pr https://github.com/planetarium/NineChronicles/pull/3131
> remove disabling unity logger

- nekoyume/Assets/AddressableAssets/UI/Module/Reward/BattleReward.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
- nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
[[튜토리얼] 1스테이지 클리어 결과화면에서 2별 항목의 보상과 문구가 겹치는 현상](https://app.asana.com/0/1133453747809944/1205647348275129/f)
> Fix battle result popup

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab
SSIA
---
- https://app.asana.com/0/0/1205655395293925
> fix ShopListCell.prefab mask issue

- nekoyume/Assets/_Scripts/Game/TableSheets.cs
> Bump lib9c 1.3.0

- nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs
> fix: several side effects on non-rpc play with `libplanet 3.4.0`

- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
ssia
---
- https://app.asana.com/0/0/1205674276066367
> feat: block staking menu on android

- nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
ssia
---
- https://app.asana.com/0/0/1205639364996680
> feat: save accelToggle.isOn to local registry

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
> fix: action rendering in non-RPC play

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
- nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
SSIA
---
- https://app.asana.com/0/0/1205564900801277
> add portal reward tutorial

- nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
SSIA
disappear release note popup untile complete stage 10
> change release note popup limit

- nekoyume/ProjectSettings/ProjectSettings.asset
> chore: update version to 70.1.0, android code 70

- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> feat: implement `RPCAgent.GetBalanceAsync(address, currency, stateRootHash)` method

- nekoyume/Assets/Resources/AddressableAssetsContainer.asset
> fix: stuck at create avatar action on unity editor

- nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
- nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ConsumableTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CostumeTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_EquipmentTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs
SSIA
---
- https://app.asana.com/0/0/1205564900801274
> add equipment tutorial

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
- nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
- nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
- Add summon tutorial at cleared stage 10
- Fix Tutorial CheckPoint Logic
- Update CheckPointKey to avatar index
- Add MinimumClearStageId for open notice popup
---
- https://app.asana.com/0/0/1205564900801289
> Add tutorial after stage10

- nekoyume/Assets/Resources/Tutorial/Animation/Item_GuideArrow.controller
- nekoyume/Assets/Resources/Tutorial/Animation/Item_GuideArrow_Idle.anim
- nekoyume/Assets/Resources/Tutorial/Animation/Item_GuideArrow_Idle.anim.meta
- nekoyume/Assets/Resources/Tutorial/Prefab/Item_GuideArrow.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
[튜토리얼 진행 중 화살표가 사라지지않는 현상](https://app.asana.com/0/958521740385861/1205685183357573/f)
> Fix Tutorial Guide Arrow not disabled

- nekoyume/Assets/_Scripts/UI/Widget/Screen/RewardScreen.cs
> fix: change PlaySfx timing to Show

- nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
- nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
SSIA
---
- https://app.asana.com/0/0/1205697260229524
- https://app.asana.com/0/0/1205697265277006
- https://app.asana.com/0/0/1205697265277010
> Bugfix/70.1.0 tutorial sequence fix to Fast-Track/70.1.0

- nekoyume/Assets/_Scripts/Game/Character/Player.cs
SSIA
---
- https://app.asana.com/0/0/1205706553136090
> fix level up portal noti calculate

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
fix loading screen animation
fix loading screen video
Add reward item view to GuidedQuestCell
---
- [로딩 화면 게이지가 움직이지 않음](https://app.asana.com/0/0/1205685183682029)
- [로딩 출력시 이전 로딩과 간섭되어 로딩화면이 2종 출력되는 현상](https://app.asana.com/0/0/1205697265277018)
- [10스테이지 가이드 퀘스트에 실버더스트 보상이 보이지 않는 현상](https://app.asana.com/0/0/1205688231474511)
> Fix Loading Screen animation

- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
> fix portal reward popup ok button to close

- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
SSIA
---
- https://app.asana.com/0/0/1205688231474501
> bugfix equipment tooltip disappear issue

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
- nekoyume/Assets/_Scripts/Game/Character/Player.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> Hotfix/70.1.1 to Main

- nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
> edit tutorial

- nekoyume/Assets/_Scripts/UI/Widget/StageLoadingEffect.cs
ssia
---
- https://app.asana.com/0/0/1205714952618220
> fix: disable first stage clear video

- nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
- nekoyume/Assets/_Scripts/UI/Widget/StageLoadingEffect.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> release 70.1.2(for android)

- nekoyume/Assets/Tests/EditMode/Blockchain/BlockHashCacheTest.cs
- nekoyume/Assets/Tests/EditMode/Blockchain/BlockHashCacheTest.cs.meta
- nekoyume/Assets/_Scripts/Blockchain/BlockHashCache.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> refactor: BlockHashCache

- nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
- nekoyume/Assets/_Scripts/UI/RequestManager.cs
merge from feature/mobile-clo-switch-platform branch to feature/ios
> add mobile clo switch for platform

- nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- remove `Game.CachedBalance`.
- use `BlockchainCache` in `RPCAgent`.
- no more caching state in `ActionHandler`.
- fix compile warnings in `RPCAgent`.
> feat: use `BlockchainCache` in `RPCAgent`

- nekoyume/ProjectSettings/ProjectSettings.asset
> Update version for 80.0.0

- nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
> fix mobile platform condition

- nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
- nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
- nekoyume/Assets/_Scripts/State/States.cs
- nekoyume/Assets/_Scripts/UI/MainCanvas.cs
- nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
[접속했을 때 방치보상 받을 수 있는 상황이면 바로 방치보상 팝업창 띄우기](https://app.asana.com/0/958521740385861/1205679248703132/f)
- Refactor EventReleaseNotePopup, unread check
- Update show patrol popup at room entering
- Refactor patrol reward popup (refer commit description)
- Add mixpanel analyzer
> Update show patrol popup at room entering

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
[포털 안내 7스테이지 클리어 후로 옮기기](https://app.asana.com/0/958521740385861/1205726965972341/f)
- portal tutorial : 5->7 (cleared stage id)
[summon 튜토리얼 5스테이지 클리어 후로 옮기기](https://app.asana.com/0/958521740385861/1205726965972336/f)
- summon tutorial : 10->5 (cleared stage id)
> Update tutorial condition stage id

- nekoyume/Assets/_Scripts/UI/Widget/Screen/RewardScreen.cs
ssia
---
- https://app.asana.com/0/0/1205723257023289
> fix: move PlaySfx invoking to PlayAnimation

- nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs
- change `ActionHandler.GetGoldBalanceState` to `GetAgentNCG`.
- change `StateGetter.GetGoldBalanceState` to `GetAgentNCG`.
> fix: `feat/enhanced-game-state-management` branch

- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
- nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> feat: introduce `IAgent.GetBalanceBulkAsync` method

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
- nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
- nekoyume/Assets/_Scripts/State/States.cs
- nekoyume/Assets/_Scripts/UI/Model/RuneItem.cs
- nekoyume/Assets/_Scripts/UI/Module/Pet/PetInfoView.cs
- nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossRuneStoneInventory.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
- nekoyume/Assets/_Scripts/UI/Widget/RuneStoneItem.cs
This pull request based on #3221.
- introduce and apply `States.CurrentAvatarBalances`.
- introduce `States.GetCurrentAvatarBalance` and `TryGetCurrentAvatarBalance` methods.
- rename `States.SetBalanceAsync` to `UpdateCurrentAvatarBalanceAsync`.
> feat: introduce `States.CurrentAvatarBalances`

- nekoyume/Assets/Resources/ScriptableObject/Portal_Reward.asset
> change portal reward level condition

- nekoyume/Assets/_Scripts/Game/Stage.cs
- nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
> feat: enable header and guide quest when clear stage 3

- nekoyume/Assets/_Scripts/Game/Stage.cs
> skip animation wating battle result

- nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
SSIA
[summon 튜토리얼 5스테이지 클리어 후로 옮기기](https://app.asana.com/0/958521740385861/1205726965972336/f)
> Add Tutorial Dummy for patrol reward tutorial

- nekoyume/Assets/_Scripts/UI/Widget/System/VersionSystem.cs
> add application version to PC

- nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
- add Patrol reward initialized check to delete unnessesary NRE
> Fix Patrol Reward data NRE

- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/LockObjects.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/LockObjects.prefab.meta
- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/PatrolBtn.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
- nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
upgrade: 35 stage, grind: 40 stage, craft: 3 stage
---
- https://app.asana.com/0/0/1205811152002232
> feat: add locking ui of workshop

- nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab
ssia
---
- https://app.asana.com/0/0/1205723257023302
> feat: add UIOnClockSound to receive all button

- .gitignore
- nekoyume/Assets/StreamingAssets/planets.meta
- nekoyume/Assets/StreamingAssets/planets/0x000000000000.meta
- nekoyume/Assets/StreamingAssets/planets/0x000000000000/genesis.meta
- nekoyume/Assets/StreamingAssets/planets/0x000000000001.meta
- nekoyume/Assets/StreamingAssets/planets/0x000000000001/genesis.meta
- nekoyume/Assets/_Scripts/Blockchain/BlockManager.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- add genesis block for planet 0x000000000000(Odin).
- add genesis block for planet 0x000000000001(Heimdall).
- consider several genesis blocks in `BlockManager`.
---
- https://app.asana.com/0/0/1205698971357142
> feat: genesis block injection for `Multiplanetary`

- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
- nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
require 23
---
- https://app.asana.com/0/0/1205802636106678
> add locking to ActionPoint and Rune menu

- nekoyume/Assets/_Scenes/Game.unity
- nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
> fix clear screen boader in android platform

- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
- nekoyume/Assets/_Scripts/Planet/Planets.cs
- remove `RPCAgent.InitializeWithoutPrivateKey()` method.
- fix `PlanetSelector` to consider non-rpc agent in Unity editor.
> refactor: `IAgent` initialization

- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
SendMixPanel when tutorial is in start point id...
but where are some edge case, before stage 5
Stage 1 : tutorial id 1
Stage 3 : tutorial id 2, in playing tutorial, id 30000 is played.
> Fix analyzer in tutorial

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- re-link serialized fields of `IntroScreen` component.
> update: `UI_IntroScreen` prefab

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- cherry picking #3284.
- re-link serialized fields of IntroScreen component.
> cherry picking #3284

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
- nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/_Scripts/UI/Tutorial/GuideArrow.cs
before: copy anchor, pivot, etc.
now: copy world corners and rect size
---
- https://app.asana.com/0/0/1205765181171041
> Improve guide arrow position&rect size setting logic

- nekoyume/Assets/Editor/TutorialScenarioScriptableObjectEditor.cs
- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
- nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialScenarioScriptableObject.cs
Add new Structure to tutorial SO - TutorialScenarioWithComment
Apply TutorialScenarioWithComment to Tutorial Controller
> Add new Structure to tutorial SO

- nekoyume/Assets/_Scenes/Game.unity
- nekoyume/Assets/_Scripts/Game/ActionCamera.cs
- nekoyume/Assets/_Scripts/Game/RaidCamera.cs
- nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
SSIA
---
- https://app.asana.com/0/0/1205790455651005
> fix screen clearing

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
> 🔧  fix: Freezing when `BattleArena` action rendering 

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
> fix(prefab): invoke `IntroScreen.ShowMobile()` in `DMXReader.BackButton`

- nekoyume/Assets/Plugins/ModelViewer/Runtime/ModelFactory.cs
- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
- nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
- nekoyume/Assets/_Scripts/Game/Stage.cs
- nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
- nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
- nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
- nekoyume/Assets/_Scripts/UI/Scroller/RecipeCellView.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/EnhancementResultPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
- Add GameConfig variables to client from lib9c
bump lib9c and this feature https://github.com/planetarium/lib9c/pull/2195
- Update contents unlock stage id at GameConfig Client
related Combination -> 1, Arena 25 -> 15
- Add notification condition to AvatarInfoPopup
is content unlocked by cleared stage id
---
- https://app.asana.com/0/0/1205723257023414
- https://app.asana.com/0/0/1205781543210975
> Update GameConfig variables

- nekoyume/Assets/_Scripts/Helper/Util.cs
- nekoyume/Assets/_Scripts/L10n/L10nManager.cs
- nekoyume/Assets/_Scripts/UI/MainCanvas.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> Run download shop image task in background

- nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
1. First step.
---
- https://app.asana.com/0/0/1205834350029249
> Track cancel event

- nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
- nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
- nekoyume/Assets/_Scripts/Game/Stage.cs
- nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
- nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
- nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
- nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
- nekoyume/Assets/_Scripts/UI/Scroller/RecipeCellView.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
SSIA
클라이언트로 옮긴 김에 네이밍, 필요 없는 값 정리했습니다.
new variable
- Charge AP : required stage when show charge ap popup with AP header menu (23)
- ShowPopupRoomEntering : required stage when show popup at room entering (51)
> Rename GameConfig client variables

- nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
- nekoyume/Assets/_Scripts/UI/Model/Rank.cs
- nekoyume/Assets/_Scripts/UI/Model/RankCategory.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs
SSIA
---
- https://app.asana.com/0/0/1205834350029245
> Delete Mimisburnnr tab in rank popup prefab

- nekoyume/Assets/_Scenes/Game.unity
- nekoyume/Assets/_Scripts/Game/ActionCamera.cs
- nekoyume/Assets/_Scripts/Game/RaidCamera.cs
- nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
스크린 해상도 크기에 맞춰 레터박스로 가리는 사이즈가 바뀌도록 수정.
> bugfix letter box size

- nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
- nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
> change ap charge tutorial to stage 24

- nekoyume/Assets/_Scripts/L10n/L10nManager.cs
1. First step.
---
- https://app.asana.com/0/0/1205853791431185
> Convert korean language in PC

- nekoyume/Assets/_Scripts/GraphQL/NineChroniclesAPIClient.cs
> Add try-catch to gql request

- nekoyume/ProjectSettings/ProjectSettings.asset
bundle code: 84, version: 80.0.0
> chore: update bundle version to 80.0.0

- nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
> Fix to call SetPushNotification on main thread

- nekoyume/Assets/_Scripts/GraphQL/NineChroniclesAPIClient.cs
> cherry-pick Add try-catch to gql request #3325

- nekoyume/ProjectSettings/ProjectSettings.asset
> chore: update version to 80.0.1

- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> 🔧  fix: less ping check

- nekoyume/Assets/_Scripts/Game/Game.cs
> SeasonPassServiceManager has to initialized

- nekoyume/ProjectSettings/ProjectSettings.asset
> chore: update bundle code

- nekoyume/Assets/_Scripts/State/States.cs
립플레닛 스레드 호출시점이 바뀌면서 유니티스레드가 아닌곳에서 유니티 호출부르는 부분 수정.
> Modified Unity calls to proceed on the Unity thread.

- nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
- nekoyume/Assets/_Scripts/UI/Widget/StageLoadingEffect.cs
SSIA
---
- https://app.asana.com/0/0/1205264862444951
> feat: remove disabling headermenu when battle end

- nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
ssia
---
- https://app.asana.com/0/0/1205892427659671
> chore: change guide rect position about accel button

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/Url.cs
- nekoyume/Assets/_Scripts/PushNotifier.cs
에디터 안드로이드 플렛폼에서도 진입및 테스트하도록수정.
- 에디터일경우
- 로컬 Clo를 보도록 수정
- 푸쉬노티 초기화하지않도록 수정
- IAP서비스 초기화 하도록 수정
> Modified to enable testing on Unity Editor Android platform

- nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
ssia
---
- https://app.asana.com/0/0/1205892584158044
> fix: enable/disable tutorial skip button when play/close timing

- nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab
> notch adjust add

- nekoyume/Assets/_Scripts/Game/Game.cs
> fix: remove UNITY_EDITOR compile flag about IAP initializing

- nekoyume/Assets/_Scripts/UI/Tutorial/GuideBackground.cs
ssia
---
- https://app.asana.com/0/0/1205802636106685
> feat: tutorial bg disabling if target is null

- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab
> notch ui apply

- nekoyume/Assets/_Scripts/Game/Game.cs
(kor)
- `Game.CurrentPlanetId`에 `PlanetContext.SelectedPlanetInfo.ID`를 저장합니다.
- `Game.CurrentPlanetId`는 아직 모바일 플랫폼에서만 초기화됩니다.
- 스탠드얼론 플랫폼을 위한 후속 PR을 올리겠습니다.
(eng)
- store `PlanetContext.SelectedPlanetInfo.ID` to `Game.CurrentPlanetId`.
- `Game.CurrentPlanetId` only initialized on mobile platforms yet.
- I'll make follow-up pull request for standalone platform.
---
- https://app.asana.com/0/0/1205912720216519
> store `PlanetContext.SelectedPlanetInfo.ID` to `Game.CurrentPlanetId`

- nekoyume/Assets/_Scripts/GeneratedApi/SeasonPassServiceClient.cs
- nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
- nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
시즌패스 조회요청시 플레닛ID 기입하도록 API 수정 대응.
> seasson pass planet api apply

- nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
L10n 파일 자체를 파싱하지 못하더라도 블로커가 되지않도록 수정.
> revert csv edit to develop play

- nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
> NRE exception handle

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
- nekoyume/Assets/_Scripts/UI/Tutorial/GuideArrow.cs
ssia
---
- https://app.asana.com/0/0/1205892427659707
> set guide arrow position with delay

- nekoyume/Assets/AddressableAssets/UI/Module/SeasonPassBtn.prefab
- nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
- nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassNewPopup.cs
시즌패스 아바타 정보 갱신해오지 못할경우 시즌패스페이지 접근 불가하도록 수정.
> seasonpass enter exception handle

- nekoyume/Assets/_Scripts/Game/ActionCamera.cs
- nekoyume/Assets/_Scripts/Game/RaidCamera.cs
최소 16/9 최대 21/9의 범위를 넘을경우 레터박스 나오도록 기능추가.
---
- https://app.asana.com/0/0/1205907471038787
> add screen ratio limit 16/9 ~ 21/9

- nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
SSIA
---
- https://app.asana.com/0/0/1205912551311619
> arena repeat text fix

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
> [Design]UI_shopListPopup_Prefabs_Edit

- nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
- nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossResult@Show.anim
[Design]WorldBossResult@Show_anim_Edi
https://app.asana.com/0/1133453747809944/1205912551311609/f
> [Design]WorldBossResult@Show_anim_Edi

- nekoyume/Assets/StreamingAssets/Localization/button.csv
- nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
- nekoyume/Assets/StreamingAssets/Localization/sentence.csv
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
- nekoyume/Assets/_Scripts/Permissions.meta
- nekoyume/Assets/_Scripts/Permissions/PermissionState.cs
- nekoyume/Assets/_Scripts/Permissions/PermissionState.cs.meta
- nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
- nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/OneButtonSystem.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/TwoButtonSystem.cs
- 소셜 로그인 취소 처리
- QR코드 가져오기 단계에서 카메라 권한 요청 취소 처리
권한 재요청과 관련하여 후속 PR을 올릴 계획입니다.
(eng)
- Handling social login cancellation.
- Handling canceled camera permission requests in the Get QR Code step.
I'll raise a follow-up PR regarding the permission re-request.
> fix[Android]: handle back button event in login context

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
- nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
- nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
- nekoyume/Assets/_Scripts/Planet/Planets.cs
> fix: `PlanetId?` as a `string` in `CommandLineOptions`

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/CellView/RuneStoneInventoryCell.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RuneListview.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Item/RuneListItem.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Item/RuneStakingListItem.prefab
- nekoyume/Assets/Resources/Audio/Sfx/Prefabs/sfx_notice.prefab
- nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_BossStatus.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_DialogPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_PrologueDialogPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_RewardScreen.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_StageProgressBar.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_StageTitle.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
- nekoyume/Assets/_Scripts/UI/Widget/CodeRewardEffector.cs
- 폰트 사이즈 추가수정
- 에셋 사이즈 조정
- 제작 화면에서 모든 옵션 스크롤 없이 다 보이게 수정
Just check the screenshots
그 외 기타등등..
> Fix various prefab

- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
전처리기 누락으로 Unity IAP서비스가 초기화되지않던문제 수정.
> add preprocessor

- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
> fix start button anchor

- nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
> fix: add yield return null without mobile compiling env

- nekoyume/Assets/_Scripts/Game/Game.cs
> Add platform to check tokens

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
> tutorial: remove guide offset

- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
> Fix typo at refresh token

- nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
- nekoyume/Assets/_Scripts/Game/ActionCamera.cs
- nekoyume/Assets/_Scripts/Game/RaidCamera.cs
- nekoyume/Assets/_Scripts/UI/Module/Common/NotchAdjuster.cs
튜도리얼 오브젝트 노치 대응되도록 수정.
런타임중 스크린사이즈가 변경될경우 스크린설정들(다이나믹, 스테틱, 노치)다시 갱신되도록 수정.
---
- https://app.asana.com/0/0/1205934579862162
> fix tutorial ui notch and runtime change screen size

- nekoyume/Assets/_Scripts/Extensions/BigIntegerExtensions.cs
[재화별 K M B 숫자 표기기준 모두 맞추고, 잘못 적용되어 있는 문제 해결하기](https://app.asana.com/0/958521740385861/1205706553136126/f)
value - result
123 - 123
1234 - 1.23K
12345 - 12.34K
123456 - 123.45K
1234567 - 1.23M
...
1204567 - 1.2M
> Update Currency format

- nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
- nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
[월드보스 로딩 이미지 적용](https://app.asana.com/0/958521740385861/1205879958167394/f)
> Add world boss image to loading screen

- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
- nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
[재화 팝업 버튼 내 등등 NCG 거래소, DCC로 이동시키는 코너케이스 모두 막기](https://app.asana.com/0/958521740385861/1205781518204774/f)
[[D:CC] D:CC 컨텐츠 UI 클릭 시 D:CC 진입이 불가능한 현상](https://app.asana.com/0/958521740385861/1205840978794229/f)
> Fix mobile dcc, shop route

- nekoyume/Assets/_Scripts/UI/Scroller/EnhancementInventoryScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/EnhancementSelectedMaterialItemScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/InventoryScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/PetSlotScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/RuneListScroll.cs
그리드스크롤 초기화시에 스크린사이즈에 맞춰서 셀카운트 수정하도록 추가.
(런타임 해상도변경에는 대응안됨)
---
- https://app.asana.com/0/0/1205772359281271
> GridScroll initialized with screen size

- nekoyume/Assets/Resources/ScriptableObject/UI_CharacterTitle.asset
Fixed title costume textstyle
just check the screenshots
https://app.asana.com/0/958521740385861/1205903409203934/f
이걸
고양이 얼굴 나오는 이 스타일로 수정함
> change title costume textstyle

- nekoyume/Assets/_Scripts/Game/Stage.cs
ssia
---
- https://app.asana.com/0/0/1205934579862174
> disable celebrate opening shop on mobile

- nekoyume/Assets/_Scripts/Game/Prologue.cs
- nekoyume/Assets/_Scripts/Game/RaidStage.cs
- nekoyume/Assets/_Scripts/Timeline/TimeScale/TimeScaleBehaviour.cs
- nekoyume/Assets/_Scripts/Timeline/TimeScale/TimeScaleTrack.cs
- nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
ssia
---
- https://app.asana.com/0/0/1205934580543929
- https://app.asana.com/0/0/1205834350029302
> fix: set timeScale at Menu.Show()

- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
IAP 서비스의 구매요청에 PlanetID 추가되도록 수정.
---
- https://app.asana.com/0/0/1205937825977360
> add planet id into iap PurchaseRequestAsync

- nekoyume/Assets/Editor/OpenAPIGenerator.cs
- nekoyume/Assets/_Scripts/GeneratedApi/SeasonPassServiceClient.cs
- nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
- nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs
시즌패스 보상수령문제 수정(제너레이션된 PlanetID Enum타입 직렬화문제)
시즌패스 UI 동작이상부분 수정.
---
- https://app.asana.com/0/0/1205936083483578
- https://app.asana.com/0/0/1205935969355213
- https://app.asana.com/0/0/1205912551311653
> Bugfix/seasonpass UI fix

- nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
아바타 인포창 Notch수정 적용되도록 컴포넌트 추가.
> add notch apply

- nekoyume/Assets/_Scripts/UI/Scroller/RuneListScroll.cs
SSIA
---
- https://app.asana.com/0/0/1205946175524087
> remove cell count fix in RuneListScroll

- nekoyume/Assets/StreamingAssets/Localization/common.csv
> fix wrong text

- nekoyume/Assets/_Scripts/L10n/L10nManager.cs
안드로이드 플렛폼에서도 CSV파일 파싱실패시 로드 스킵하고 넘어갈수있도록 수정.
> csv parsing failed skip load

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
- nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
- nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassNewPopup.cs
SSIA
---
- https://app.asana.com/0/0/1205912834349470
> move seasonpass tutorial popup

- .github/workflows/android-build-and-release.yml
- .github/workflows/build.yml
- nekoyume/Assets/Resources/Tutorial/Prefab/Item_GuideArrow.prefab
> improve many something

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
- nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
reflect about...
- battle_arena15(new BattleArena action)
- ClaimItems mail
> bump lib9c to release/1.5.0

- nekoyume/Assets/AddressableAssets/UI/Module/Grinding/GrindModule.prefab
- nekoyume/Assets/_Scripts/UI/Scroller/EnhancementInventoryScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/EnhancementSelectedMaterialItemScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/InventoryScroll.cs
SSIA
---
- https://app.asana.com/0/0/1205946478628750
> fix cell count buffer

- nekoyume/Assets/Resources/UI/Prefabs/UI_GrayLoadingScreen.prefab
[타이틀 게이지바가 터치 되는 현상](https://app.asana.com/0/958521740385861/1205935951357998/f)
> Fix GrayLoading slider

- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/InviteFriendsPopup.cs
> Fix InviteFriendsPopup

- nekoyume/Assets/_Scripts/Game/Arena.cs
> feat: add animation accel to arena

- nekoyume/Assets/_Scripts/Game/Arena.cs
> fix arena accel value to 2.5f

- nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
> seasonpass-premium pricetext apply

- nekoyume/Assets/_Scripts/Game/Arena.cs
- nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
> fix fix fix fix fix fix timescale at arena

- .github/workflows/android-build-and-release.yml
- .github/workflows/build.yml
> fix concurrency

- .github/workflows/android-build-and-release.yml
- .github/workflows/build.yml
> change concurrency group to github.ref_name from github.ref

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
> fix PrepareClaimItems about update avatar state and handling crystal

- nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
> price error fix

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
ssia
---
- https://app.asana.com/0/0/1205907466106291
- https://app.asana.com/0/0/1205955314830409
> fix ClaimItems rendering and patrol reward mail

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
at ResponseUnlockWorld
---
- https://app.asana.com/0/0/1205934580544016
> fix UpdateAgentStateAsync invoking with run on thread pool

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
ssia
---
- https://app.asana.com/0/0/1205934580543975
> fix default language and using system language

- nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
스테이지클리어시 Again이아니라 스테이지버튼이뜨도록 수정.
---
- https://app.asana.com/0/0/1205934579862177
> change battle result show button by stage clear

- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
- nekoyume/Assets/TextMesh Pro/Resources/TMP Settings.asset
폰트 폴백 추가(IAP서비스 메일 글자깨지는것수정)
시즌패스 IAP상품 결제 실패 로그 추가.
> add fallback font and debug log

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
- nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
- nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
- nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs
- nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
- nekoyume/Assets/_Scripts/UI/Scroller/EnhancementInventoryCell.cs
- nekoyume/Assets/_Scripts/UI/Scroller/EnhancementInventoryScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/InventoryCell.cs
- nekoyume/Assets/_Scripts/UI/Scroller/InventoryScroll.cs
- nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
TutorialController.SetTutorialTarget 라는 메소드가 생겼습니다. 컨트롤러가 튜토리얼 타겟 저장하고있던걸 강제로 set하는 메소드입니다. 이걸 통해서 더미 오브젝트를 강제로 실제 오브젝트로 바꿉니다.
인벤토리 스크롤과 인핸스먼트 스크롤의 Context가 Dictionary 형태로 모든 cell을 갖고있도록 했습니다. 메모리 누수가 걱정되긴 하는데, 일단 dispose랑 Clear는 추가했으니 실제로 돌아가는걸 보고 보완해보고싶습니다.
> improve tutorial

- nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_Navigation.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ConsumableTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CostumeTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_EquipmentTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
[아이템 정보 획득처 영역 높이가 고정되어 내용이 거의 안보이는 버그](https://app.asana.com/0/958521740385861/1205907471038718/f)
> Fix item tooltip layout

- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
> add conditional accessor to planetContext

- nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
- nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
일본어 등 대응 위해 폰트 크기 조정
- 인벤토리 카테고리
- 메인 메뉴
- 워크샵
캡쳐 참조
> Fix font size

- nekoyume/Assets/StreamingAssets/Localization/worldboss_info.csv
Update World info Change
- worldboss_info
---
- https://app.asana.com/0/0/1205935969355197
> Bug worldboss info

- nekoyume/Assets/_Scripts/UI/Widget/Screen/MailRewardScreen.cs
메일 모두받기, 퀘스트 모두받기 팝업에 sfx 추가
파일 체크
https://app.asana.com/0/958521740385861/1205949762632748/f
> add sfx to all receive popup

- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_LoginDetail.prefab
케릭터 생성창 노치대응
---
- https://app.asana.com/0/0/1205954855116579
- https://app.asana.com/0/0/1205945654018991
> login detail notch fix

- nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
> fix UI_AvatarInfoPopup for parsing yaml

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
> add rendering about `MintAssets` action

- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Editor/IAPServiceToolWindow.cs
- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
- nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
IAP 상품정보 갱신시 플레닛아이디도 같이 보내도록 요청 수정.
---
- https://app.asana.com/0/0/1205958619902720
> apply planet id to get iap product

- nekoyume/Assets/_Scripts/Helper/Util.cs
- nekoyume/Assets/_Scripts/UI/Scroller/EnhancementInventoryScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/EnhancementSelectedMaterialItemScroll.cs
- nekoyume/Assets/_Scripts/UI/Scroller/InventoryScroll.cs
> adjust scroller width

- nekoyume/Assets/StreamingAssets/Localization/common.csv
> add Ui key about seasonpass

- nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
> hide price tag while loading

- nekoyume/Assets/_Scripts/Game/ActionCamera.cs
- nekoyume/Assets/_Scripts/Game/RaidCamera.cs
Modified camera aspect on iOS
1. Launch the app on iOS and Android
2. Compare the screen aspect of each device.
> fix: camera aspect on iOS

- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> remove Testcode

- nekoyume/Assets/_Scripts/UI/Model/InventoryItem.cs
- nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
- nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
> Delete GameConfig from lib9c

- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Appear.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_FallDown_Defeat.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_FallDown_Victory.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_1.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_2.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_3.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_4.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Bite.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Claw.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Enrage.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Wrath.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_FallDown_Defeat.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_FallDown_Victory.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_1.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_2.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_3.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_4.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Corrosion.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Enrage.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Fury.playable
- nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Multistrike.playable
[월드보스 달려갈때 캐릭터가 안 달리고 미끄러지듯이 가고 있음](https://app.asana.com/0/958521740385861/1205834350029300/f)
> Fix WorldBoss Timeline Spine animation

- nekoyume/Assets/_Scripts/Game/Game.cs
ssia
---
- https://app.asana.com/0/0/1205765181171034
> remove skip synopsis condition about avatar level

- nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
SSIA
---
- https://app.asana.com/0/0/1205958620210135
- https://app.asana.com/0/0/1205819094797345
- https://app.asana.com/0/0/1205958620210148
> fix wrong find product for render

- nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
> fix iap product render issue

- nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
SSIA
---
- https://app.asana.com/0/0/1205958620210157
> season pass apple purchase fix

- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
ssia
---
- https://app.asana.com/0/0/1205949762632763
> handle non tradable item locallayer at receive all

- nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassCouragePopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassCouragePopup.cs.meta
> change seassonpass new popup flow

- nekoyume/Assets/_Scripts/Extensions/GraphQlHttpClientExtensions.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AgentAndPledgeGraphType.cs
- nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AgentAndPledgeGraphType.cs.meta
- nekoyume/Assets/_Scripts/GraphQL/GraphTypes/PledgeGraphType.cs
- nekoyume/Assets/_Scripts/GraphQL/GraphTypes/PledgeGraphType.cs.meta
- nekoyume/Assets/_Scripts/Planet/PlanetAccountInfo.cs
- nekoyume/Assets/_Scripts/Planet/PlanetContext.cs
- nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
(한글)
- 재접속 + 신규 플래닛 진행 시 플렛지 버그 수정
- 게임 시작 시 배경음악 재생
- 인트로 로딩 시 일러스트만 남기기
(English)
- Fixed a pledge bug on reconnect + new planet progression
- Play background music at game startup
- Leave only illustration when loading intro
---
- https://app.asana.com/0/0/1205973842471116
- https://app.asana.com/0/0/1205758790622466
- https://app.asana.com/0/0/1205934580544096
> [PDX-137]fix: edge case of pledge

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
ssia
---
- https://app.asana.com/0/0/1205964349664309
> remove delay(*1.15) interval about push noti

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/EnhancementInventoryCell.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_EnhancementInventory.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
- nekoyume/Assets/StreamingAssets/Localization/common.csv
제발 진짜 마지막 l10n 삽입
1. First step.
> add text and l10n key

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
- nekoyume/Assets/_Scripts/UI/Login/SigninContext.cs
- nekoyume/Assets/_Scripts/UI/Login/SigninContext.cs.meta
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Delete duplicated token handling method at this pr https://github.com/planetarium/NineChronicles/pull/3536
@boscohyun
> Fix tokens handling from portal

- nekoyume/Assets/AddressableAssets/UI/Module/EnhancementInventory.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
> add missing l10n

- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
> iap mailbox render

- nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
- nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
> remove premium context

- nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs
> popup wait show

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
- nekoyume/Assets/StreamingAssets/Localization/button.csv
- nekoyume/Assets/StreamingAssets/Localization/sentence.csv
- nekoyume/Assets/_Scripts/UI/Login/SigninContext.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
SSIA
---
- https://app.asana.com/0/0/1205940036875333
> feat: enable twitter&discord buttons and connect to portal

- nekoyume/Assets/AddressableAssets/UI/Module/LoadingModule.prefab
- nekoyume/Assets/Resources/UI/Animations/LoadingImageContainerController@Idle.anim
- nekoyume/Assets/Resources/UI/Animations/LoadingImageContainerController@Start.anim
- nekoyume/Assets/Resources/UI/Animations/LoadingModule.controller
- nekoyume/Assets/Resources/UI/Animations/LoadingModule.controller.meta
- nekoyume/Assets/Resources/UI/Animations/LoadingModule@Idle.anim
- nekoyume/Assets/Resources/UI/Animations/LoadingModule@Idle.anim.meta
- nekoyume/Assets/Resources/UI/Animations/LoadingModule@Show.anim
- nekoyume/Assets/Resources/UI/Animations/LoadingModule@Show.anim.meta
- nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
- nekoyume/Assets/_Scripts/Game/Stage.cs
- nekoyume/Assets/_Scripts/UI/Module/LoadingModule.cs
- nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
[캐릭터 목록 -> 캐릭터 선택 때에는 UI에서 로딩 안그려야함](https://app.asana.com/0/958521740385861/1205964349664331/f)
[캐릭터 생성시 다른 캐릭터들 단상 더 밑으로 내려서 아우라 잔상 안보이게 하기](https://app.asana.com/0/958521740385861/1205964349664256/f)
> Fix login detail

- nekoyume/Assets/_Scripts/Blockchain/Agent.cs
> Avoid NotImplementedException

- nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
UnityWebRequest bug in GetReferralInformation()
Changed UnityWebRequest to HttpClient
> fix: invite friends on iOS platform

- nekoyume/Assets/_Scripts/Game/TableSheets.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> back merge Release/90.0.17 to development

- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> fix runtime error

- nekoyume/Assets/_Scripts/Blockchain/ClientFilter.cs
- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> prepare 90.0.18

- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
Reverts planetarium/NineChronicles#3589
> Revert "fix runtime error"

- nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
인트로스크린 에셋 사이즈 조정
- Your Planet쪽 크기 너무 큰 것 수정
- 소셜로그인 버튼 너무 큰 것 수정
@boscohyun 크기 및 미세 포지션 수정 외 다른 변경점이 있으면 안됩니다. 체크 한 번 부탁드립니다.
> fix introscreen font size

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
SSIA
---
- https://app.asana.com/0/0/1205974567906731
> add force update feature

- nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
- nekoyume/Assets/_Scripts/UI/Widget/Popup/InviteFriendsPopup.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
- nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
- Fix avatar spine fade animation at synopsis
[맨 처음에 시놉시스 후 캐릭터 디졸브돼서 사라질때 검은색이 덮이도록 처리하여, 캐릭터 조각조각 사라지지 않도록 처리](https://app.asana.com/0/958521740385861/1205934580544103/f)
- Fix loading screen freezing
[로딩 화면에서 프로그레스 70%쯤에서 멈추던 버그 재발](https://app.asana.com/0/958521740385861/1205974568908537/f)
- Fix invite friends popup
[메인에서 친구초대 팝업을 한번 띄운 후, 다른 화면에 갔다가 메인화면에 돌아오면 친구초대 팝업이 자동으로 뜸](https://app.asana.com/0/958521740385861/1205974568908545/f)
> Fix UI bugs

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
> bump lib9c and reflect it about changes of ArenaSimulator and ArenaCharacter

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
- nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
> Bugfix/mail UI fix

- nekoyume/Assets/_Scripts/Game/Game.cs
SSIA
---
- https://app.asana.com/0/0/1205988295506581
> update target frame rate to 30 on mobile env

- nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
> add worldboss tutorial scenario type

- nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs
SSIA
---
- https://app.asana.com/0/0/1205988172306123
> fix seasonpass last item refresh

- nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
- nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
- nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
- nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
- nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
- nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs
[아이템 정보창의 별표 누르면 강화 언락 전에도 강화하러 갈 수 있음. 35스테이지 클리어 전까지 클릭 막아야함.](https://app.asana.com/0/958521740385861/1205974567906736/f)
> Add reqired stage to ui

- nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type1.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
- nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationResultPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassNewPopup.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
Reverts planetarium/NineChronicles#3603
> Revert "UI/UI polishing 231120"

- .github/workflows/android-build-and-release.yml
- nekoyume/Assets/Editor/Builder.cs
- tools/pack/pack.py
> Change product name at mobile

- nekoyume/Assets/StreamingAssets/Localization/common.csv
구매 완료 레이블 대응
@jonny-jeahyunchoi 혹시 모르니 눈체크 한번만 같이 부탁드려요.
> fix purchase l10n

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
> force equipments by item slot states at render has

- nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
> Fix skip button

- nekoyume/ProjectSettings/ProjectSettings.asset
> backmerge Release/90.0.22 to Prepare/90.0.x

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
- nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
ssia
---
- https://app.asana.com/0/0/1203863020824788
> backup keystore when importing keystore QR code

- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ChatPopup.cs
Must : obsolete DiscordLink at lib9c.GameConfig
[메뉴-디스코드 링크가 만료된 링크임.](https://app.asana.com/0/958521740385861/1203863020824786/f)
> Add Discord Link to GameConfig at LiveAsset

- nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs
ssia
---
- https://app.asana.com/0/0/1205987797361653
> fix GetKeystore() on runtime

- nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
SSIA
---
- https://app.asana.com/0/0/1205982150412043
> check null exception to 90.1.0

- nekoyume/Assets/Resources/UI/Prefabs/UI_ConsumableTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_CostumeTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_EquipmentTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_FungibleAssetTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
- nekoyume/Assets/Resources/UI/Prefabs/UI_RuneTooltip.prefab
- nekoyume/Assets/_Scripts/Game/Game.cs
[35 스테이지 강화 레벨언락 센터메시지 때문에 아이템 정보 안닫히는 문제](https://app.asana.com/0/958521740385861/1205987797361625/f)
- Fix error popup - to close on click button
- Fix EquipmentTooltip - element area broked
- Fix MaterialTooltip - enhancement button enabled
- Fix Item Tooltip touch event
- enable detail(modal) image raycast target.
- disable image(is not interactable) raycast target
- add event trigger(same with detail) to scroll view, footer
- Apply changed to RuneTooltip, FungibleaAssetValueTooltip also
---
- https://app.asana.com/0/0/1205987797361625
> Fix itemTooltip, error popup

- nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
ssia
---
- https://app.asana.com/0/0/1206008773223221
> change korean live asset data to eng on mobile platform

- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
> change UnmarshalBlock invoking to thread pool

- nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
> fix: do not re-create `Keystore` in `LoginSystem`

- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
> add pending purchase

- nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
> fix notice json url at korean and pc

- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
> add iap pending and repurchase flow

- nekoyume/Assets/Editor/Builder.cs
Missing export compliance information
added ITSAppUsesNonExemptEncryption to Info.plist
> fix: added ITSAppUsesNonExemptEncryption

- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
- nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
- nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
- nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
> Feature/90.1.2 iap safe to prepare/90.2.0

- nekoyume/Assets/AddressableAssets/UI/Module/Inventory.prefab
- nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
- Fix costume inventory reddot
- Fix equipment sort error?
---
- https://app.asana.com/0/0/1205988121943677
- https://app.asana.com/0/0/1205987797361709
> Fix inventory red dot (notification)

- nekoyume/Assets/_Scripts/UI/Module/Item/RuneStoneInventoryItemView.cs
- nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossInformation.cs
- nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
> Fix world boss l10n key

- nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
get avatar state and etc... at `PrepareHackAndSlash()`
---
- https://app.asana.com/0/0/1206015068627418
> change PrepareHackAndSlash to really prepare state for updating

- nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
ui/upgrade_button-edit
https://app.asana.com/0/958521740385861/1206021464054670
> [Design]UI_Enhancement_Prefabs_Edit

- nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
- nekoyume/Assets/_Scripts/Settings.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
- add `float: MasterVolume` property to `Settings`
- it return `volumeMaster` if isVolumeMasterMuted is false.
- else, return `0f`.
---
- https://app.asana.com/0/0/1205974123218674
> introduce `Setting.MasterVolume`

- nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
- nekoyume/Assets/_Scripts/Game/Dcc.cs
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/UI/RequestManager.cs
1. update dcc timeout by 10sec(default: 30sec)
2. add handling about dcc timeout
---
- https://app.asana.com/0/0/1205987796732151
> add timeout handling to dcc GetParts

- nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
- nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs
SSIA
---
- https://app.asana.com/0/0/1205988497201444
- https://app.asana.com/0/0/1205988497201452
- https://app.asana.com/0/0/1205987797361727
> seasonpass ui bug fix

- nekoyume/Assets/AddressableAssets/UI/Module/CellView/SelectPlanetCell.prefab
planet_selection_popup-edit3
https://app.asana.com/0/958521740385861/1206031420543453
> [Design]SelectPlanetCell_Prefabs_Edit

- nekoyume/Assets/_Scripts/Game/ActionCamera.cs
> letterbox max ratio limit change 21:9 -> 22:9

- nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
shop_sell_popup-edit
https://app.asana.com/0/958521740385861/1206031420543442
> [Design]UI_ItemCountableAndPricePopup_Prefabs_Edit

- nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs
- nekoyume/Assets/Planetarium/Nekoyume/Editor/LibplanetEditor.cs
- nekoyume/Assets/Tests/EditMode/Extensions/PrivateKeyExtensionsTest.cs
- nekoyume/Assets/Tests/EditMode/Extensions/PrivateKeyExtensionsTest.cs.meta
- nekoyume/Assets/_Scripts/Extensions/PrivateKeyExtensions.cs
- nekoyume/Assets/_Scripts/Extensions/PrivateKeyExtensions.cs.meta
- nekoyume/Assets/_Scripts/Game/Game.cs
- nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
- introduce `PrivateKey.ToHexWithZeroPaddings()` as an extension method.
> fix: private key hex with zero paddings

- nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
- nekoyume/ProjectSettings/ProjectSettings.asset
> remove getTipTask.Forget() and wait getTipTask by coroutine

- nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
when enter worldboss ui from lobby menu
> Fix missing worldboss loading image

- nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
to display only buyable in lobby
---
- https://app.asana.com/0/0/1206021378847065
> Fix shop list popup

- nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
- nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
로그심고 테스트해보아야합니다.
---
- https://app.asana.com/0/0/1206031536512753
> add log and fix claimitem ReceiveAll process
