nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

refresh shop goldendust when receive reward actions

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/ProjectSettings/ProjectSettings.asset

back merge Release/90.2.7 to dev

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/ProjectSettings/ProjectSettings.asset

back merge Release/90.2.7 to prepare/90.3.x

---

nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab

action_point_gauge-edit
https://app.asana.com/0/958521740385861/1206044053054240

[Design]ActionPoint_Prefabs_Edit

---

nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
nekoyume/ProjectSettings/ProjectSettings.asset

back merge Release/90.2.8 to Prepare/90.3.x

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
nekoyume/Assets/_Scripts/UI/Module/CenteredGridLayout.cs
nekoyume/Assets/_Scripts/UI/Module/CenteredGridLayout.cs.meta

SSIA
---
- https://app.asana.com/0/0/1206032606713416

apply CenteredGridLayout

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

SSIA
---
- https://app.asana.com/0/0/1206061853814660

add fav item in garage when receiveAllButton

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/SummonDetailCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SummonResultPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs

- Update background to new image
- Fix SummonDetailCell Font size

Fix/summon UI

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab

add notch adjust to tab position

---

nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab

LoadingScreen-edit
https://app.asana.com/0/958521740385861/1206089627912346

[Design]UI_LoadingScreen_Prefabs_Edit

---

nekoyume/Assets/_Scripts/Game/Arena.cs
nekoyume/Assets/_Scripts/Game/RaidStage.cs

fix Vampiric rendering at Arena and Raid

---

nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs

fix debug log and loading hide flow

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SummonResultPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Summon.cs

ui/summon-edit-231207
https://app.asana.com/0/958521740385861/1206089630093556

[Design]UI_Summon_Prefabs_Edit

---

nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset

Update Rune Sorting Order Change
---
- https://app.asana.com/0/0/1206117918833595

Update Rune Sorting Order Change

---

nekoyume/Assets/_Scripts/Game/Arena.cs
nekoyume/Assets/_Scripts/Game/RaidStage.cs
nekoyume/Assets/_Scripts/Game/Stage.cs

https://app.asana.com/0/1133453747809944/1206126297587104/f
https://app.asana.com/0/1133453747809944/1206126297587096/f
https://app.asana.com/0/1133453747809944/1206126297587088/f

fix IStage.CoCustomEvent implementation about Tick skill info

---

nekoyume/Assets/_Scripts/UI/Widget/Rune.cs

SSIA
---
- https://app.asana.com/0/0/1206127012860004

refresh rune enhancement value

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/SummonSkillsCell.prefab

summon_skill_info-edit
https://app.asana.com/0/1133453747809944/1206127836437654/f

[Design]SummonSkillsCell_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab

SSIA
---
- https://app.asana.com/0/0/1206128377287731

fix delete account button hide in window

---

nekoyume/Assets/_Scripts/Extensions/SkillExtensions.cs
nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs

1. change Stun power(description text) to `100%`.
2. change Vampiric power(description text) to `Math.Round(value / 100, 2)%`
https://app.asana.com/0/1133453747809944/1206126296471989/f
https://github.com/planetarium/NineChronicles/pull/3800

change rune skill description about vampiric and stun

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/Rune.cs

1. remove `PreResponseRuneEnhancement`
2. move UpdateStates to `PreRuneEnhancement`
3. move Game UI rendering to `ResponseRuneEnhancement`
---
- https://app.asana.com/0/0/1206147494172076

fix rune enhancement rendering about update states

---

nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopDynamicGridLayoutView.cs
nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs

change dynamic grid sort order

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab

shop_tab_button_scroll-edit
https://app.asana.com/0/1133453747809944/1206075970329603/f

[Design]UI_ShopBuy_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Module/Common/PositionTooltip.cs

cus coroutine stop when gameobject is inactivate
---
- https://app.asana.com/0/0/1206137747894885

fix position tooltip do not inactivated

---

nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs

SSIA
---
- https://app.asana.com/0/0/1206136783593021

refresh dim fist check product buyable state

---

nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab

quest-edit231212
https://app.asana.com/0/1133453747809944/1206021383310223/f

[Design]UI_QuestPopup_Prefabs_Edit

---

nekoyume/Assets/Resources/ScriptableObject/LiveAssetEndpoint.asset

using raw.githack.com
related: https://github.com/planetarium/NineChronicles.LiveAssets/pull/97
---
- https://app.asana.com/0/0/1206118564961084

change live asset image root url

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs
nekoyume/Assets/_Scripts/State/States.cs

Fix to UpdateItemSlotState with evaluation.OutputState
[배틀시 장착하고 들어간 장비가 종료후에 장착되어져 있어보이지 않는 현상](https://app.asana.com/0/958521740385861/1206053159283036/f)

Fix to UpdateItemSlotState with evaluation.OutputState

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs

[공지팝업 하루에 한번만 뜨게 바꾸기](https://app.asana.com/0/958521740385861/1206100533413794/f)

Edit HasUnread condition at EventReleaseNotePopup

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
nekoyume/Assets/_Scripts/L10n/L10nImage.cs
nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs
nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs.meta

- Add Promotion Container component
[강화 이벤트 강조 미니배너&팝업 제거](https://app.asana.com/0/958521740385861/1206134955288352/f)

Edit Promotion UI

---

nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs

unity web camera sometimes flipping... with rendering engine... or platform... or etc...
---
- https://app.asana.com/0/0/1205987797361627

flip webcam texture when verticallyMirroed

---

nekoyume/Assets/Resources/ScriptableObject/EventData.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab

Update Event Dungeon Settings
- EventData.asset
- UI_WorldMap.prefab
---
- https://app.asana.com/0/0/1206099280735082
- https://app.asana.com/0/0/1206147371188513

Update Event Dungeon Add

---

nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs

[제작 블록 수를 최소~ 최대 형태로 변형](https://app.asana.com/0/958521740385861/1206053489408796/f)

add max value to required block index text at SubRecipeView

---

nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv

Event Dungeon Name L10n ID Change

---

nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs

[행동력 렌더링 버그 수정](https://app.asana.com/0/958521740385861/1206032606713460/f)

Fix action point render

---

nekoyume/Assets/Resources/ScriptableObject/EventData.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab

Update Event Dungeon Change
- EventData
- WorldMap

EventData, WorldMap Change

---

nekoyume/Assets/_Scripts/UI/Module/Item/RuneSlotView.cs

SSIA
---
- https://app.asana.com/0/0/1206179426066891
- https://app.asana.com/0/0/1206179442220029

Fix crystal cost at rune slot unlock

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab

SSIA
---
- https://app.asana.com/0/0/1206179426066815
- https://app.asana.com/0/0/1206179426066827

DCC ui position fix

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs

SSIA
---
- https://app.asana.com/0/0/1206179439202975

fix iteminfo eventdungeon

---

nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
nekoyume/Assets/_Scripts/UI/Module/IAP/IAPRewardView.cs
nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs

SSIA
---
- https://app.asana.com/0/0/1206178218273333

apply fav tooltip for iap reward soulstone and crystal

---

nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab

mobileshop_banner-edit
https://app.asana.com/0/958521740385861/1206237823620981

[Design]UI_CombinationMain_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab

rank_position-eidt
https://app.asana.com/0/958521740385861/1205984336236247

[Design]UI_RankPopup_Prefabs_Edit

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab

rune_reddot-edit
https://app.asana.com/0/958521740385861/1206192047093788

[Design]ItemView_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab

battle_result-edit
https://app.asana.com/0/958521740385861/1206022762993494

[Design]UI_BattleResultPopup_Prefabs_Edit

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

ssia
---
- https://app.asana.com/0/0/1205998261618927

reorder arena participants for current avatar address

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

merge #3849 into development

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab

craft_gauge-edit
https://app.asana.com/0/958521740385861/1205965144521329

[Design]UI_Craft_Prefab_Edit

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab

shop_mobile_button-eidt
https://app.asana.com/0/958521740385861/1205964990418911

[Design]ShopListCell_Prefab_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_IconAndButtonSystem.prefab

IconAndButtonSystem_popup_text-edit
https://app.asana.com/0/958521740385861/1205973865710755

[Design]UI_IconAndButtonSystem_Prefab_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Category.prefab

shop-craft-tabbutton-eidt
https://app.asana.com/0/958521740385861/1205984336633101

[Design]UI_MobileShop_Prefabs_Edit

---

nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
nekoyume/Assets/_Scripts/Game/Stage.cs

remove Animator.Idle() and do not add with ActionParams. ActionParams has unnecessary waiting time.
https://github.com/planetarium/NineChronicles/assets/48484989/94abc8a5-5dcc-44ca-acdd-784b58808f47
---
- https://app.asana.com/0/0/1206269368189840

improve animation about healing tick from vampiric

---

README.ko.md
README.md

This pull request attaches the devforum link badge on the README.

Add devforum badge to README

---

nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs

apply fav ticker l10n in mail box exception
---
- https://app.asana.com/0/0/1206295690902623

apply fav ticker l10n in mail box exception

---

.github/workflows/ios-build-and-release.yml

change ios build runner to linux 8cores, change branch condition

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs

rune_cp-add
https://app.asana.com/0/958521740385861/1206277189590346

[Design]UI_Rune_Prefabs_Edit

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

1. check avatar address when render AuraSummon, RuneSummon
2. refactor ap charging action
https://app.asana.com/0/958521740385861/1205934601638210/f
https://github.com/planetarium/NineChronicles/assets/48484989/e297389b-a51c-4136-a03a-52f396e1badd

improve rendering actions about avatar state updating

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs

1. SSIA
2. 이제 타 에이전트에 의해(signer != my agent) NCG, 크리스탈 등이 변동되었을때도 NCG나 크리스탈 등이 정상적으로 업데이트됩니다.
https://app.asana.com/0/958521740385861/1206307658153040/f

remove signer checking at update agent state

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassNewPopup.cs

SSIA
---
- https://app.asana.com/0/0/1206169412745603

show newseasonpass popup by seasonpass id

---

nekoyume/Assets/Resources/UI/Prefabs/UI_FungibleAssetTooltip.prefab

EventTrigger 컴포넌트가 인풋을 막고있어서 스크롤이 안됬던 문제 수정.
---
- https://app.asana.com/0/0/1206324363742299

remove event trigger component

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/RxProps.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

f9578e7 - remove States.InitRuneStoneStates()
031220c - remove UpdateCurrentAvatarBalance and combine to SetCurrentAvatarBalance
2715e23 - remove States.InitRuneStoneBalance()
5b21076 - remove States.UpdateRuneStoneBalance()
- add `UpdateCurrentAvatarRuneStoneBalance()` to ActionHandler.
- remove invoking GetState() at States.cs about RuneStone.
https://app.asana.com/0/958521740385861/1206315577987605/f

♻ Refactor States.cs

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaTicketPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab

arena_repeat_text-edit
https://app.asana.com/0/958521740385861/1206297527078960

[Design]UI_ArenaTicketPopup_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab

craft_select_button-edit
https://app.asana.com/0/958521740385861/1206297527078957

[Design]UI_Craft_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab

worldmap-eventdungeon-edit
https://app.asana.com/0/958521740385861/1205984336633253

[Design]UI_WorldMap_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab

avatarinfo_grind_text-edit
https://app.asana.com/0/958521740385861/1206297527078959

[Design]UI_AvatarInfoPopup_Prefabs_Edit

---

nekoyume/Assets/_Scripts/Multiplanetary/PlanetInfo.cs
nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs

override guild config from planet registry
---
- https://app.asana.com/0/0/1206357561831731

Add guild arguments in planetRegistry

---

nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentInventoryItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/InventoryItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/MailRewardItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ShopCartItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/SweepItemView.cs
nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/RuneStoneEnhancementInventoryCell.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

룬 레드닷 표시가 다른곳에서도 나타나는 문제 수정.
---
- https://app.asana.com/0/0/1206306345701517

initalize rune notification state

---

nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs

iap 문제 확인용 로그 추가 작업입니다. endpoint 잘못된부분과 로그상태를 알수있도록 변경하였습니다.

fix log endpoint and add log status

---

nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs

delete useless log

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

ssia
https://app.asana.com/0/1133453747809944/1206378610608650/f

remove OnRoomEnter.Invoke(true) at Raid action render

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/RxProps.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs

threading mistake
---
- https://app.asana.com/0/0/1206378987676575

resolve issue#3977, stuck at create avatar

---

nekoyume/Assets/_Scripts/Helper/Url.cs

ssia
---
- https://app.asana.com/0/0/1206075208216269

change Url.Load logic about ios for native file reading

---

nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs

[[정찰보상] 이벤트 기간이 줄바꿈되어 문구가 겹치는 현상](https://app.asana.com/0/1133453747809944/1206378987676541/f)
---
- https://app.asana.com/0/0/1206182774736556

Fix patrol reward popup date text

---

nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs

모바일이 아닌 환경에서  ShopListPopup을 열지않도록 수정
위젯이 생성되지않기 때문에 에러남.

hide mobile shop list popup by platform

---

nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs

SSIA
---
- https://app.asana.com/0/0/1206262846436749

fix RuneOptionView

---

nekoyume/Assets/_Scripts/UI/Module/Character/VanillaCharacterView.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBattle.cs

resolve #3991
---
- https://app.asana.com/0/0/1206378610608676
- https://app.asana.com/0/0/1206378610608668

Fix full costume wasnt displayed at character view

---

nekoyume/Assets/Editor/Builder.cs

Update Builder.cs to remove UNITY_IOS defines

---

nekoyume/Assets/_Scripts/State/States.cs

change type of CurrentAvatarBalances to ConcurrentDictionary

---

fastlane/Fastfile

Description
Problems to solve.
Crash on iOS when trying to sign in to Google
Features to add.
Update Fastfile to update Info.plist
ref https://github.com/planetarium/NineChronicles/pull/4002

fix google sign crash error

---

nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs

improve: retry PlanetRegistry initialization more

---

nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs

Fix failed build

---

nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetCardSlot.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab

refer issues
---
- https://app.asana.com/0/0/1206378987676517

Fix ui prefab text size

---

nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
nekoyume/ProjectSettings/ProjectSettings.asset

fix build failed

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Summon.cs

PC환경에서 MobileShop위젯이없을때 에러가발생해서 이후스크리트가 스킵되어 메일노티가 정상적으로 출력되지않는문제 수정.

change Find to TryFind

---

nekoyume/Assets/Resources/UI/Icons/Item/40100026.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/40100027.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/40100028.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/40100029.png.meta

fix costume item icon meta file

---

nekoyume/Assets/Resources/UI/Icons/Item/49900014.png.meta

Update Title meta Change
- 49900014

Update Title meta Change

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab

upgrade_text_area-edit 
https://app.asana.com/0/1133453747809944/1206460775330122

[Design]UI_Enhancement_Prefab_Edit

---

nekoyume/Assets/Editor/KeyStoreEditor.cs

add generate keystore by raw pk feature to KeystoreEditor

---

nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
nekoyume/ProjectSettings/ProjectSettings.asset

filter raw pk string at debug logging

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab

시즌패스 프리미엄상품 아이탬 품목 최대 랜더링 개수 수정 5-> 6

change season pass producdt render limit 5 -> 6

---

nekoyume/Assets/_Scripts/Blockchain/Agent.cs

1. Cannot launch game when chain is reset.
1. Reset chain, and run in editor with empty clo.

fix: Agent to create new agent state if not exits

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionRegistrationPopup.prefab
nekoyume/Assets/Resources/VFX/Prefabs/PraiseVFX.prefab

collection_ui-edit
https://app.asana.com/0/958521740385861/1206344388858920

UI/collection UI edit

---

nekoyume/Assets/StreamingAssets/Localization/common.csv

Update L10n Change
- common.csv

Update L10n Change

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/MathematicsExtensions.cs
nekoyume/Assets/_Scripts/UI/Model/InventoryItem.cs
nekoyume/Assets/_Scripts/UI/Module/Item/RuneStoneInventoryItemView.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/WorldBossRewardScreen.cs

BigIntiger 가 int형으로 형변환되면서 오버플로우날때 UI동작이 틀어지는부분 예외처리한내용입니다.
최대 최소값을 초과했을때 int.max나 int.min으로 덮어쓰도록 조치했는데요 추가 이팩트가 없을지 확인해주시면 좋을것같습니다~!

exception handle for overflow

---

nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs

네임스페이스에 동일한 키워드(debug)중복문제로 빌드에러나는문제 수정.

fix build compile error

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab

seasonpass_last_reward_hide
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=51848286

[Design]UI_SeasonPass_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab

ingame_boss_frame-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=51975742

[Design]UI_Battle_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab

super_craft_popup_button-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=51833183
---
- https://app.asana.com/0/0/1206297527079066

[Design]UI_SuperCraftPopup_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup_2.prefab

popup_title_language_response
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=51843466
---
- https://app.asana.com/0/0/1206297527079089

[Design]Popup_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ConfirmConnectPopup.prefab

dcc_homepage_popup_language_response
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=51832885

[Design]UI_ConfirmConnectPopup_Prefabs_Edit

---

nekoyume/Assets/_Scenes/Game.unity

move letterbox pos

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab

shop_sell_text_sort-edit
https://github.com/orgs/planetarium/projects/97/views/9?pane=issue&itemId=53984682

[Design]UI_ShopSell_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Summon.cs

1. resolve #4203 
1. First step.

Forced SetMaterialAssets when result closed

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_Shop.prefab

1. resolve #4198 
2. enable price text obj at ItemView_Shop

enable price text obj at ItemView_Shop

---

nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene.atlas.txt
nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene_Atlas.asset
nekoyume/Assets/AddressableAssets/Character/Cutscene/cutScene_Material.mat
nekoyume/Assets/_Scripts/Game/Character/Player.cs

1. area attack cutscene을 활성화합니다
1. 전투 연출에서 컷씬이 제대로 나오는지 봅니다

enable area attack Cutscene

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_Sweep.prefab

1. resolve #4206 
2. enable countText at ItemView_Sweep
1. Use sweep and check item view UI.

enable countText at ItemView_Sweep

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattleLoadingScreen.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab

fix DetailedCharacterView level text

---

nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs

mobileshop의 cell의 정보를 다시 갱신할때  같은 상품의 다른 카테고리 정보가 갱신되며 Recommend아이콘이 사라지는 현상 제거.

fix mobile shop recommend icon

---

nekoyume/Assets/AddressableAssets/UI/Module/Collection/CollectionCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionRegistrationPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionResultPopup.prefab
nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionResultPopup.cs

- delete collection in CelebratesPopup 
resolve #4194
- fix lines pivot between stats
resolve #4188
- fix collection material validation
resolve #4174
- add OneLineSystem when failed ActivateCollection action
resolve #4175
- fix CollectionResultPopup 
resolve #4207

fix collection bugs

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_EnhancementInventory.prefab

1. enable optionTag obj at ItemView_EnhancementInventory
2. resolve issue #4187 
1. enter to Upgrade menu

enable optionTag obj at ItemView_EnhancementInventory

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
nekoyume/ProjectSettings/GraphicsSettings.asset

DccMain 프리팹 스파인 캐릭터의 셰이더와 렌더링옵션을 변경합니다
인게임 (특히 윈도우 빌드) 로비에서 dcc 위젯을 활성화시킵니다
https://github.com/planetarium/NineChronicles/issues/4197

fix cat eyes in dcc main prefab

---

nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
nekoyume/Assets/_Scripts/UI/Module/CollectionInventory.cs

fix collection material validation

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionEffectPopup.cs

add isInWorld check to GoToCollection button

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs

fix arena mission button text

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

resolve #4236
wait update state when render Summon***

wait update state when render Summon***

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionRegistrationPopup.cs

edit equipped item warning popup icon, label

---

nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

1. resolve #4236 
2. remove LocaloLayerModifier at summon action.

remove LocaloLayerModifier at summon action

---

nekoyume/Assets/_Scripts/UI/Module/CollectionInventory.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionRegistrationPopup.cs

fix GetModels method to filter food, material in CollectionInventory
refer issue
- #4261

Fix collection inventory filtering

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

delete override on RaidBtn from `UI_Menu`
- #4256

Fix worldboss promotion container not working

---

nekoyume/Assets/_Scripts/UI/Module/CollectionMaterialInfo.cs
nekoyume/Assets/_Scripts/UI/Widget/Collection.cs

fix to deselect material on click close button in CollectionMaterialInfo
- #4267

Fix to close CollectionMaterialInfo

---

nekoyume/Assets/_Scripts/Blockchain/BlockManager.cs
nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs

1. fix guest login flow
2. resolve #4276

fix guest login flow

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

fix arena simulator

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/ProjectSettings/ProjectSettings.asset

merge `release/152.0.0` into main

---

nekoyume/Assets/Resources/Character/UI_Avatar.prefab

1. UI_Avatar 프리팹을 복구합니다
1. UI_Avatar 를 열어보고 제대로 렌더링되는지 확인합니다
https://github.com/planetarium/NineChronicles/issues/4301

fix ui avatar prefab

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CollectionBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/StakingMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionEffectPopup.cs

- resolve issues
- #4278 
- #4279 
- #4280 
- #4282

fix required level bugs

---

nekoyume/Assets/Resources/UI/Animations/UIPopupController@Close.anim
nekoyume/Assets/Resources/UI/Animations/UIPopupController@Show.anim

- resolve https://github.com/planetarium/NineChronicles/issues/4273

fix UIPopupController animations

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab

ui/sweep_result_popup-edit
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=53055653

[Design]UI_SweepResultPopup_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab

ui/stageinfo-edit
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=55341573

[Design]UI_StageInformation_Prefabs_Edit

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
nekoyume/Assets/_Scripts/UI/Module/Lobby/StakingMenu.cs

- resolve #4349 
- 스테이킹 안한경우 new 띄워주기
- 레벨과 얼마 넣었는지 보여주기
- 보상까지 남은 블록 및 시간

resolve #4349, polish Ingame monster collection UI(in lobby)

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RewardScreen.prefab
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs

1. resolve #4350 
2. update crystal and rune stones.
3. use RewardScreen when render `ClaimStakeReward`.
https://github.com/planetarium/NineChronicles/assets/48484989/5c2a916b-559b-4ac4-a07d-28629e62ee07

use RewardScreen when render `ClaimStakeReward`

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/CostItemView.prefab

ui/material_buy_popup-edit
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=52205269

[Design]ItemView_2_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneCombineResultScreen.cs

1. remove invoking OneLineSystem.Push()
2. resolve #4274 
https://github.com/planetarium/NineChronicles/assets/48484989/73efe993-fad6-4b3d-8cc6-84fd3963e1cc

remove invoking OneLineSystem.Push()

---

nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_01.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_02.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_03.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_01.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_02.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_03.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_01.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_02.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_03.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_01.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_02.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_03.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_01.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_02.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_03.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_01.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_02.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_03.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_01.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_02.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_03.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_01.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_02.prefab
nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_03.prefab

fix aura effect flip issue

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
nekoyume/Assets/_Scripts/Blockchain/StateGetter.TryGet.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/StakingMenu.cs

1. unnecessary object enable/disable
2. and etc
please check StakingMenu.cs

bugfix about `StakingMenu`

---

nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs

iap 에러팝업노출시 타이틀, 버튼 번역키 그대로 노출되는 현상 수정.

iap error popup l10n fix

---

nekoyume/Assets/_Scripts/Game/Arena.cs
nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
nekoyume/Assets/_Scripts/Game/RaidStage.cs
nekoyume/Assets/_Scripts/Game/Stage.cs

아레나쪽에 신규스킬 트윈어택 연출을위해서 추가한내용입니다. lib9c 수정사항도 같이 적용되어야합니다.

fix double attack arena effect

---

nekoyume/Assets/Editor/Testbed/TestbedCreateAvatar.asset
nekoyume/Assets/Resources/VFX/Prefabs/ShatterStrike_casting.prefab
nekoyume/Assets/Resources/VFX/Prefabs/ShatterStrike_magical.prefab
nekoyume/Assets/_Scenes/Game.unity
nekoyume/Assets/_Scripts/Game/Arena.cs
nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
nekoyume/Assets/_Scripts/Game/RaidStage.cs
nekoyume/Assets/_Scripts/Game/Stage.cs

apply shatter strike effect

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv

1. resolve #4429
2. just edit UI prefab and common.csv 
임시 이미지입니다.

adjust l10n to StakingPopup

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
nekoyume/Assets/_Scripts/Extensions/InventoryExtensions.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

resolve #4120

---

nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialNavigationPopup.prefab

ui/material_navigation_popup-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=51832549

[Design]UI_MaterialNavigationPopup_Prefab_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Alert.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_BlockFailTitleOneButtonSystem.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ConfirmConnectPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ConfirmPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_DccSettingPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_InputBoxPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_PetSelectionPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ProfileSelectPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RedeemCode.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab

ui/popup_title-edit
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=51728494

[Design]PopupTitle_Prefabs_Text_Edit

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/MailCell.prefab

ui/receive_button_effect-edit
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=51832758

[Design]MailCell_Prefabs_Edit

---

nekoyume/Assets/_Scripts/Extensions/SkillExtensions.cs
nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs

fix new skill text info

---

nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs

add message log

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs

- resolve #4446 
- 게스트 로그인옵션 비활성화시
- 게스트 로그인옵션 활성화시

Enable guest login button check options

---

nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs

구매버튼 누를때 구매가능한 상품인지 한번 더 체크하고 결제모듈띄우도록 수정.

double check when purchase product

---

nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs

모바일상점 노티사라지지않는문제 수정.
구매시 로컬기준 상품데이터의 구매횟수가 갱신되지않아서 발생하는문제로 확인.

product local value refresh

---

.github/workflows/android-build-and-release.yml
nekoyume/ProjectSettings/ProjectSettings.asset

fix google-services.json path at android build ci

fix google-services.json path at android build ci

---

.github/workflows/android-build-and-release.yml
nekoyume/ProjectSettings/ProjectSettings.asset

Release/160.0.2 to prepare/160.0.x
이후 RC에 문제 없도록 빌드스크립트수정한것 prepare로 백머지시킵니다.

Release/160.0.2 to prepare/160.0.x

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CollectionBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/PatrolBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/SeasonPassBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_StageProgressBar.prefab
nekoyume/Assets/Resources/VFX/Prefabs/PraiseVFX.prefab
nekoyume/Assets/Resources/VFX/Prefabs/StageProgressBarVFX.prefab
nekoyume/Assets/Resources/VFX/Prefabs/UI_patrolreward_000102.prefab

1. resolve #4395 
2. change material of UI Particle, and resize, etc.

resolve #4395, fix UI Particle prefabs

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs

크래프트 UI의 컬렉션 버튼에 컬랙션 페이지로 이동시키는 기능을 추가합니다
크래프트 UI에서 좌하단의 컬랙션 버튼을 클릭합니다. 
https://github.com/planetarium/NineChronicles/issues/4480

add go to collection in craft ui

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

1. resolve #4359 
2. add loading indicator to Claim Reward button
https://github.com/planetarium/NineChronicles/assets/48484989/399b9327-5dde-42e0-85ff-fa43cf2e0639

condition setting to claim reward button of StakingPopup

---

nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneCombineResultScreen.cs

1. resolve #4274 
2. remove CoWorkshopItemMove at RuneCombineResultScreen
https://github.com/planetarium/NineChronicles/assets/48484989/0649c0e0-e5b4-4bff-82f9-ba63cadad18a

remove CoWorkshopItemMove at RuneCombineResultScreen

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

1. resolve #4534 
2. change tutorial target object to real button from dummy

change tutorial target object to real button from dummy

---

nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.cs
nekoyume/Assets/Resources/AddressableAssetsContainer.asset
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs
nekoyume/Assets/_Scripts/Game/TableSheets.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs

- bump lib9c related https://github.com/planetarium/lib9c/pull/2468

Bump lib9c for DeBuffLimit

---

nekoyume/Assets/_Scripts/UI/Widget/Collection.cs

1. ID 정렬 기능이 제대로 동작하도록 수정합니다
1. ID 오름차순 / 내림차순 테스트를 진행합니다
https://github.com/planetarium/NineChronicles/issues/4504

Add Id Sort in collection

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab

ui/qa_combination_slot_popup_button-eidt
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=56806071

[Design]UI_CombinationSlotPopup_Prefabs_Edit

---

nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab

ui/qa_worldboss_mylevel_bg-edit
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=56739006

[Design]Tabs_Rank_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab

PC Shop 검색 기능을 복구합니다 
PC Shop에서 검색을 해봅니다.
https://github.com/planetarium/NineChronicles/issues/4535

fix ui_Shopbuy prefab for item search

---

nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs

Add log when fail product available check

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab

ui/qu_tooltip_popup-edit
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=56756282

[Design]UI_ItemTooltip_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs

StatDebuff Limit 표시를위한 L10n키 추가.
StatDebuff가 걸려있고 GroupID가 DebuffLimitSheet에 있으면 표기도 추가됩니다.

add statdebuffLimitDiscription

---

nekoyume/ProjectSettings/ProjectSettings.asset

chore 160.0.3

---

nekoyume/Assets/Resources/VFX/Prefabs/UI_patrolreward_03.prefab

1. resolve #4395 
2. fix patrolreward_03 vfx for UI Particle

fix patrolreward_03 vfx for UI Particle

---

nekoyume/Assets/Resources/ScriptableObject/UI_BonusBuffViewData.asset
nekoyume/Assets/_Scripts/Editor/EnumToStringAttribute.cs
nekoyume/Assets/_Scripts/Editor/EnumToStringAttribute.cs.meta
nekoyume/Assets/_Scripts/Editor/EnumToStringDrawer.cs
nekoyume/Assets/_Scripts/Editor/EnumToStringDrawer.cs.meta
nekoyume/Assets/_Scripts/Game/ScriptableObject/BonusBuffIconData.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/BonusBuffViewDataScriptableObject.cs

1. resolve #4560 
2. [introduce EnumToStringAttribute and drawer](https://github.com/planetarium/NineChronicles/commit/f5d7722d13bfe20e56ab2e30c8eb6abfc89bb8b7)
3. [adjust EnumToString to bonus buff view data](https://github.com/planetarium/NineChronicles/commit/4d1f80dee02789d98501fca553a194ff4551a390)

resolve #4560 

---

nekoyume/Assets/AddressableAssets/UI/Module/StakingBonus.prefab

1. resolve #4130 
2. add staking level 8 icon and object

add staking level 8 icon and object

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

fix seasonpass info list

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

fix SeasonPassPremium purchase fail bug

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs

fix event dungeon last stage again button

fix event dungeon last stage again button

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

1. resolve #4269 
2. add color changing to staking input field
https://github.com/planetarium/NineChronicles/assets/48484989/99a6b9a2-26b6-46f7-b888-9abed1770736

add color changing to staking input field

---

nekoyume/Assets/ExternalDependencyManager/Editor/1.2.177/Google.IOSResolver.dll.meta
nekoyume/Assets/Firebase/Editor/Firebase.Editor.dll.meta

https://github.com/googlesamples/unity-jar-resolver/issues/412
1. First step.

disable dll auto referencing and validating

---

nekoyume/Assets/_Scripts/UI/Widget/Collection.cs

콜랙션의 기본 정렬순서를 오름차순으로 변경합니다
콜랙션의 기본 정렬순서가 오름차순인지 확인합니다 
https://github.com/planetarium/NineChronicles/issues/4596

change default sort option

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/Cheat.cs

remove StageSimulatorV2

---

nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs

fix guestButton enable error
clo에 enalbeGuestButton추가되면서 다른플로우가 고려되지않아 정상동작하지않는 문제로 파악했습니다.
게스트버튼을 최종적으로 보여주는부분에서 clo을 직접참조하여 버튼의 유무를 체크하는것으로 변경했습니다.
추가로 소셜버튼과 게스트버튼이 겹처지는부분 겹쳐지지않도록 위치 조정하였습니다.

fix guestButton enable error

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_Electric_01_sprite_UI.mat
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_Electric_01_sprite_UI.mat.meta
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_ob_water_02_UI.mat
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_ob_water_02_UI.mat.meta
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_smoke_02_UI.mat
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_smoke_02_UI.mat.meta
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_smoke_fire_sprite_UI.mat
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_smoke_fire_sprite_UI.mat.meta
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_star_04_UI.mat
nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_star_04_UI.mat.meta
nekoyume/Assets/Resources/VFX/Prefabs/UI_Lobby_bg_main_WorldBossVFX.prefab
nekoyume/Assets/Resources/VFX/Prefabs/UI_Lobby_bg_main_fireVFX.prefab
nekoyume/Assets/Resources/VFX/Prefabs/UI_main_light.prefab

1. [fix broken UI_main_light vfx](https://github.com/planetarium/NineChronicles/commit/253f78cd527554fb1069f7c0d5a5661695b13a4d)
2. [fix UI_Lobby_bg_main_fireVFX](https://github.com/planetarium/NineChronicles/commit/d756ec223f01c64d1ae4c63070327a28a106ea2c)
3. [fix UI_Lobby_bg_main_WorldBossVFX](https://github.com/planetarium/NineChronicles/commit/06daf17bf706fc88e645e7733be089c19dfb64c9)
#4395 , #4604 
https://github.com/planetarium/NineChronicles/assets/48484989/460793b8-7253-4f2c-876a-ef1f1c7c0ec7

fix broken VFX(s)

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs

마켓에서 spd 관련 food 버튼들이 보이지않는 문제 수정.

show food spd button in market

---

nekoyume/ProjectSettings/ProjectSettings.asset

Prepare 160.0.5

---

nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab

툴팁 위치가 변경됨에 따라 튜토리얼에서 사용하는 툴팁 버튼위치 조정.

change dummy position

---

nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/WorldButton.prefab

UI effect 요소의 크기 때문에 버튼인풋을 가로채고 있는 문제 수정.

fix worldbutton input bug

---

nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs

신규스킬 범위표시 및 만분율 적용관련 수정.
공방표현
인벤표현

fix new skill description allow rage

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

ui 오브젝트가 처음초기화됬을때 토글관련 콜백이 불리지않는문제로 초기화실패하는부분 명시적으로 불러서 수정.

fix not initialize toggle flag

---

nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs

아우라 스킬 설명 에러 수정.
신규스킬추가하면서 아우라스킬이 따로 분기를 타지않게되어서 정상분기타도록 수정.

fix aura skill description error

---

nekoyume/Packages/manifest.json
nekoyume/Packages/packages-lock.json

update iap pakage 4.9.3 -> 4.11.0

---

nekoyume/ProjectSettings/ProjectSettings.asset

chore 160.1.1

---

nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs

기존 IOS 메모리 최적화를 위해 만들었던 기능 적용시 생기는 문제를 파악하기 위한 디버그심볼 추가

add ios memory optimization debug symbol

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionRegistrationPopup.cs

컬랙션 등록 연출을 기달립니다.
단일장비 아이템을 등록하고 연출이 실행되는지 확인합니다 
https://github.com/planetarium/NineChronicles/issues/4519
https://github.com/planetarium/NineChronicles/assets/58686228/b00159c5-60d7-44b9-87a1-cb9bb9dd04f8

add delay on RegisterMaterials

---

nekoyume/Assets/AddressableAssets/UI/Module/Collection/CollectionCell.prefab
nekoyume/Assets/Resources/UI/Animations/CollectionCell.controller
nekoyume/Assets/Resources/UI/Animations/CollectionCell.controller.meta
nekoyume/Assets/Resources/UI/Animations/CollectionCell@Show.anim
nekoyume/Assets/Resources/UI/Animations/CollectionCell@Show.anim.meta
nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Scroller/CollectionCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/CollectionScroll.cs

- resolve #4520
https://github.com/planetarium/NineChronicles/assets/63496908/ab3f2e7d-84e7-4993-812e-8dc6695a9b1a

add collection scroll view animation

---

nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs

이거 뭐 그냥 url domain만 남기면 안되나 싶은데 하여튼 코드에 하드코딩되어있던 값까지 마저 assets.nine-chronicles.com을 바라보게 수정했습니다.

change const string url

---

nekoyume/Assets/_Scripts/Game/AssetManagement.meta
nekoyume/Assets/_Scripts/Game/AssetManagement/ResourceManager.cs
nekoyume/Assets/_Scripts/Game/AssetManagement/ResourceManager.cs.meta
nekoyume/Assets/_Scripts/Game/Game.cs

1. 어드레서블로 에셋을 로드하기 위한 리소스 매니저를 추가합니다.
실 적용 및 테스트는 아래 이슈에서 처리하겠습니다
https://github.com/planetarium/NineChronicles/issues/4138

Add Resource manager

---

nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/Cheat.cs

ShatterStrikeMaxDamage 없이 Simulator생성하는부분 수정.

add gameconfig value when simulator init

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

add ShatterStrikeMaxDamage argument to BattleArena rendering
https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1712888521801839

add ShatterStrikeMaxDamage argument to BattleArena rendering

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/L10n/L10nManager.cs

L10n테이블을 원격으로 받아서 추가및 덮어사용할수있도록 기능 추가.
https://docs.google.com/spreadsheets/d/1y4U98LCOQc9K4uttylSwSjoQrI6sE-M9B-olBm5cvFg/edit?usp=sharing
구글 시트연결하여 버튼 누를시 업로드.

add remote l10n file

---

nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RuneCombineResultScreen.prefab

ui/rune_combine_screen-eidt
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=58240658

[Design]UI_RuneCombineResultScreen_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab

ui/patrol_reward_title-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=56722433

[Design]UI_PatrolRewardPopup_Prefabs_Edit

---

nekoyume/Assets/_Scripts/L10n/Editor/L10nManagerEditor.cs
nekoyume/Assets/_Scripts/L10n/Editor/Nekoyume.L10n.Editor.asmdef
nekoyume/Assets/_Scripts/L10n/L10nManager.cs

add remote table download when bake font glyph
폰트 글리프 빌드시 리모트 번역 테이블도 다운받아서 같이 참조 할 수 있도록 수정.

add remote table download when bake font glyph

---

nekoyume/Assets/_Scripts/Game/Character/PrologueCharacter.cs
nekoyume/Assets/_Scripts/Game/Character/StageMonster.cs

기존 스파인 리소스 로드하는 부분들을 어드레서블로 로드되도록 변경하였습니다.
StageMonster의  Set함수를 삭제한이유는 로드부분을 변경하면 ChangeSpineResource 함수와 동일해지기 때문에 정리를 위해서 지웠습니다~!

fix monster spine load path

---

nekoyume/Assets/AddressableAssets/UI/Module/EnhancementInventory.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab

fix grade filter ui at enhancement

---

nekoyume/ProjectSettings/ProjectSettings.asset

- update bundle version to 170.0.0
- update android bundle code to 180

update bundle version to 170.0.0

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

1. reflect about https://github.com/planetarium/lib9c/pull/2525
2. fix ResolveAvatarState about deserialize questList. Check Dictionary or List.
1. Enter game
2. Try render HAS
3. or etc.
https://planetariumhq.slack.com/archives/C011716SDTM/p1713747390443369

fix ResolveAvatarState about deserialize questList

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs

1. add `.ObserveOn(Scheduler.ThreadPool)` to DailyReward renderer
2. add ObserveOnMainThread() to GameConfigStateSubject subscribing
1. try to render DailyReward action

fix threading at render DailyReward action

---

nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset

Update UI_RuneData.asset Change
- New Rune Add
- sortingOrder Change

Update Rune Data Change

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs

인벤토리 내 룬을 소지시 거래가능 텍스트가 출력되게 수정합니다.
소유한 인벤토리 내 룬 조각이 거래가능 텍스트로 출력되는지 확인합니다.
https://github.com/planetarium/NineChronicles/issues/4820

fix tradeable text in inventory

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
nekoyume/Assets/_Scripts/UI/Widget/Rune.cs

- closes https://github.com/planetarium/NineChronicles/issues/4803
- closes https://github.com/planetarium/NineChronicles/issues/4802
- closes https://github.com/planetarium/NineChronicles/issues/4817

fix Rune UI bugs

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs

delete level text in CombinationSlotPopup ItemView

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionResultPopup.cs

- resolve https://github.com/planetarium/NineChronicles/issues/4801
- resolve https://github.com/planetarium/NineChronicles/issues/4804
스크린샷은 아직 못찍었는데, 인게임에서 직접 테스트 해서 이슈 수정된 것 확인했습니다.

fix rune level bonus CP bugs

---

nekoyume/Assets/_Scripts/Game/Battle/BattleRenderer.cs

몬스터 로드를 제대로 기달리도록 수정합니다.
몬스터가 제대로 로드되지 않는 케이스가 있는지 확인합니다.
https://github.com/planetarium/NineChronicles/issues/4842
유사 이슈
https://github.com/Cysharp/UniTask/issues/49

await monster load

---

nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
nekoyume/Assets/_Scripts/UI/Widget/Rune.cs

- resolve https://github.com/planetarium/NineChronicles/issues/4834

fix KeyNotFoundException when get rune level bonus coef

---

nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs

컬랙션에 포함되어있지않는 아이템의 제작탭에서 컬랙션상태표시 되지않도록 수정.

fix SubRecipeView collection state

---

nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs
nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs

1. 키 백업 버튼을 누르면 비밀번호가 설정됐는지 여부를 체크한 뒤, 설정이 안돼있으면 비밀번호 설정 화면으로 넘깁니다.
2. 비밀번호 설정 화면에서는 submit이 되면 모바일 환경인지 체크, 모바일 환경의 경우 항상 qrcode share를 띄웁니다.
resolve #4853

integrate key backup and passphrase setting

---

nekoyume/Assets/_Scripts/Helper/Util.cs

change download texture to use UWR

change download texture to use UWR

---

nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs

지난시즌보상수령 기능이 프리미엄 결제유저만 뜨도록 변경.

fix button visible condition

---

nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs

유니티 l10n 요청이 유니티메인스레드에서 동작하지 않는 경우가있어 스레드 세이프하도록 수정.

fix l10n unity thread safe

---

nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs

시즌패스서비스 초기화 실패시 3번정도 재시작하도록 보완코드 작성.

SeasonPassService Initialize retry

---

nekoyume/Assets/_Scripts/Game/Game.cs

fix nre introscreen

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/new-feature.yml

Delete default assignees

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs

add MainStatViews in CombinationSlotPopup

---

nekoyume/Assets/Editor/Builder.cs
nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs

add languageKey to clo for k version

---

.github/workflows/ios-build-and-release-for-9ck.yml
nekoyume/Assets/Airbridge/Scripts/Editor/AirbridgeSettingsWindow.cs
nekoyume/Assets/Editor/Builder.cs

1. 9cM와 같은 식으로 9cK가 CICD를 통해 Test flight에 업로드되는 gh actions를 추가했습니다.
check it https://github.com/planetarium/NineChronicles/actions/runs/9167625616/job/25205362242
resolve #4920

9cK iOS CICD

---

nekoyume/Assets/Resources/ScriptableObject/BuffVFXData.asset

Update Buff Icon Add

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/PetDescriptionView.prefab

ui/pet_description_list-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=58497799

[Design]PetDescriptionView_Prefabs_Edit

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

아레나 인포 갱신시 버그를 수정합니다.
1. 아레나에서 playerScoreAddr로 접근한 플레이어의 Score정보가 없는 경우 예외가 발생하며 로직이 터지는 경우가 있어서 해당 경우 스코어에 0값을 넣어주는 방법으로 수정했습니다
1. playerArenaInfo데이터가 갱신될 때 관련있는 UI들도 변경되는데 유니티 UI는 메인쓰레드에서만 변경되는데 다른 쓰레드에서 UI에 접근하는 경우가 있어서 수정해두었습니다
아레나 인포 갱신시 에러 로그나 문제가 없는지 확인합니다 
#4944

fix arena info

---

nekoyume/Assets/_Scripts/Extensions/ActionBaseExtensions.cs
nekoyume/Assets/_Scripts/Game/Battle/Stage.cs

stage에서 배틀로그 이벤트 처리시 로그기능을 추가합니다
https://github.com/planetarium/NineChronicles/issues/4898

add battle log

---

nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs

fix mobile function to prepare if failed

fix mobile function to prepare if failed

---

nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

fix patrol reward reddot

---

nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs

add logs and check permission

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab

신규 소환 컨텐츠에서 사용하는 네이밍을 루비 소환으로 통일합니다.
#5000

fix red rune/aura name

---

nekoyume/Assets/_Scripts/Game/Aura/AuraIceShield.cs
nekoyume/Assets/_Scripts/Game/Aura/AuraPrefabBase.cs
nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs

아레나에서 아이스실드 연출이 제대로 적용되지 않던 문제를 해결합니다.
#4999

fix ice shield aura in arena

---

nekoyume/Assets/_Scripts/Game/Battle/Stage.cs
nekoyume/Assets/_Scripts/Game/Character/Actor.cs

스테이지가 클리어되면 버프 정보를 초기화시킵니다
https://github.com/planetarium/NineChronicles/issues/5012

clear vfx on stage clear

---

nekoyume/Assets/StreamingAssets/Localization/error.csv
nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

- closes 
- #4991
- #5010
- #4897

fix mobile issues

---

nekoyume/Assets/_Scripts/Extensions/StatExtensions.cs
nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs

- close https://github.com/planetarium/NineChronicles/issues/4993
https://planetariumhq.slack.com/archives/C011716SDTM/p1717490108316939?thread_ts=1717487102.508349&cid=C011716SDTM

fix rune skillvalue formatting

---

nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs

- closes https://github.com/planetarium/NineChronicles/issues/5017

fix arena event container

---

nekoyume/Assets/Editor/Builder.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Model/AdventureBossData.cs
nekoyume/Assets/_Scripts/UI/Module/AdventureBoss/BossRewardCell.cs
nekoyume/Assets/_Scripts/UI/Module/WorldMapAdventureBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBossPreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBossResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossBattlePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossEnterBountyPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossFullBountyStatusPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossNcgRandomRewardPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossOpenInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossParticipantBonusPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossStartNotificationPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBoss_UnlockLockedFloorPopup.cs

어드벤처보스 standalone 빌드실패 로그 자세히확인하기위하여 로그를 추가하여 action을 돌려봅니다.
사용하지않는 namespace 로 인해 컴파일에러나는부분확인했고 수정하였습니다.

add build fail log for test

---

nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
nekoyume/Assets/_Scripts/UI/Widget/AdventureBossPreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs

add adventureboss loading screen type

---

tools/installer/installer.iss

`Build-misc/build installer/'Run ISCC tools/installer/installer.iss'`
형변환이 안되는 것 같길래 수정했습니다.
관련 슬랙 스레드 : https://planetariumhq.slack.com/archives/C01KB9AQTUN/p1718263537164009

fix ci - `Build-misc/build installer`

---

nekoyume/Assets/AddressableAssets/UI/Module/AdventureBoss/BossRewardCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossEnterBountyPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossRewardInfoPopup.prefab
nekoyume/Assets/_Scripts/UI/Module/AdventureBoss/BossRewardCell.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossEnterBountyPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossFullBountyStatusPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardInfoPopup.cs

UI 변경사항에 맞추어 충돌 및 에러로그 수정하였습니다.
보스 이미지를 body와 face에 맞게 로드하도록 변경하였습니다.

fix UI conflict

---

nekoyume/ProjectSettings/ProjectSettings.asset

- bundleVersion: 190.0.0
- AndroidBundleVersionCode: 212

Update bundle version

---

nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type8.controller
nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type8.controller.meta
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBoss.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossBattlePopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossEnterBountyPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossNcgRandomRewardPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossOpenInfoPopup.prefab

adventureboss_polishing_button-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=67605224

[Design]UI_AdventureBoss_Prefabs_Edit

---

nekoyume/Assets/Resources/ScriptableObject/LiveAssetEndpoint.asset
nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/LiveAssetEndpointScriptableObject.cs

- https://github.com/planetarium/NineChronicles/issues/5032
- add clo-default to liveasset  
https://github.com/planetarium/NineChronicles.LiveAssets/commit/8ced0c998c9c99fa9b7759766356e21dbf5c04b5

add clo prefix, clo default to LiveAssetEndpoint

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_ShopCart.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs

fix shop item view bugs

---

nekoyume/Assets/_Scripts/Blockchain/Agent.cs

Fix agent initialization to use result state of latest block.

Fix agent initialization to use result state

---

nekoyume/Assets/Resources/UI/Prefabs/UI_LoginDetail.prefab

- resolve this issue #5106 
Create button 테두리 오브젝트에 `LoginClick` 을 실행시키는 버튼 컴포넌트가 붙어있었습니다.

fix duplicate create button component

---

nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs

add exception handle

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/QuestCell.prefab

quest_popup_button_effect-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=60281431

[Design]QuestCell_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RuneLevelBonusEffectPopup.prefab

rune_level_bonus_info_popup-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=61396854

[Design]UI_RuneLevelBonusEffectPopup_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab

worldboss_result_button-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=67082950

[Design]UI_WorldBossResultPopup_Prefabs_Edit

---

nekoyume/Assets/Resources/ScriptableObject/UI_CharacterTitle.asset

character_title-add
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=55642764

[Design]UI_CharacterTitle_Asset_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab

staking_button-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=59125514

[Design]UI_StakingPopup_Prefab_Edit

---

nekoyume/Assets/_Scripts/Extensions/GetStateExtensions.cs
nekoyume/Assets/_Scripts/UI/Module/WorldMapAdventureBoss.cs

RPC Agent로 붙는경우 스테이트조회시 Bencodex 타입 체크 문제가발생하여 수정한내용입니다.
널체크가 안되고 Bencodex 널타입이 따로 와서 조건을 디테일하게 수정하였습니다.

fix rpc agent state value condition

---

nekoyume/Assets/_Scripts/Extensions/StatExtensions.cs

https://planetariumhq.slack.com/archives/C06UMQR34GZ/p1718692882507629
크리룬 추가로인해 모든 크리스텟 표기방식 변경.

fix cri stat view

---

nekoyume/Assets/AddressableAssets/Character/Monster/211000/211000_Material.mat
nekoyume/Assets/AddressableAssets/Character/Monster/211001/211001_Material.mat
nekoyume/Assets/AddressableAssets/Character/Monster/211002/211002_Material.mat
nekoyume/Assets/AddressableAssets/Character/Monster/211003/211003_Material.mat

신규로 추가된 스파인 리소스의 메터리얼의 셰이더 Spine/Skeletion Tint 사용하도록 수정.

fix mat apply tint

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/States.cs

Get avatar balance from evaluation

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

Use unique floorId to create AdventureBossSimulator.
With this PR, we can see proper monsters in Adventure boss tower.
---
This resolves #5166

Use floorId instead of floor

---

nekoyume/Assets/_Scripts/Blockchain/BlockManager.cs
nekoyume/Assets/_Scripts/EventChannelComponents/AnimatorEventChannel.cs
nekoyume/Assets/_Scripts/EventChannelComponents/GameObjectEventChannel.cs
nekoyume/Assets/_Scripts/EventChannelComponents/TouchHandlerEventChannel.cs
nekoyume/Assets/_Scripts/Game/Battle/Stage.cs
nekoyume/Assets/_Scripts/Game/Character/Actor.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/TestbedSellScriptableObject.cs
nekoyume/Assets/_Scripts/L10n/L10nManager.cs
nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs
nekoyume/Assets/_Scripts/PlatformUtility/Platform.cs
nekoyume/Assets/_Scripts/PushNotifier.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
nekoyume/Assets/_Scripts/UI/Widget/Development/CombinationSimulator.cs

분기처리로 인해 NcDebugger가 사용되지 않았던 부분을 수정했습니다.
https://github.com/planetarium/NineChronicles/issues/5036

apply ncdebugger

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

RxProps에서 반복적으로 호출되는 property를 정리합니다 
https://github.com/planetarium/NineChronicles/issues/5071

RxProps Property Clean up

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventurebossPreparation.prefab

- closes https://github.com/planetarium/NineChronicles/issues/5167

add grimoire slot in AdventurebossPreparation

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

전부받기 실행시 메일 읽음 처리가 초기화되는 문제 해결

---

nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

모바일과 PC 샵에서 Close버튼의 동작을 정상화합니다
#5183

fix close button on shop

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Blockchain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs

- resolve #5117 
rpc retry 성공 시 아바타 상태와 AvatarBalance(fav 아이템) 상태를 갱신하도록 수정했습니다.

update - set states(AvatarBalance, AvatarState) when success rpc retry

---

nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_AdventureBoss.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_AdventureBossResult.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Arena.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_ArenaResult.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_ButtonPress.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Guild.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Indicator.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Lobby_NPC.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Login.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_LoginDetail.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_PFP.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Screen.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Seasonpass.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Staking.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Summon.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Tutorial.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBossResult.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBossWave.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldClear.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldClear2.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Worldmap.spriteatlas

IOS 빌드 실패 의심포인트 수정
https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1719569202777499

fix sprite atlas setting to none compress

---

nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_AdventureBoss.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_AdventureBossResult.spriteatlas

신규 스프라이트 아틀라스의 ios 빌드옵션수정 1024 -> 2048

fix ios override option

---

nekoyume/Assets/Resources/UI/Animations/AdventureBossWing@Loop.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossRewardInfoPopup.prefab

adventureboss_wing_ani-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=69276543

[Design]UI_AdventureBossRewardInfoPopup_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs

1. disable action button at MaterialNavigationPopup when set by NCG
https://github.com/planetarium/NineChronicles/assets/48484989/5bc4d18a-6234-4dc6-956f-438cec74b701

disable action button at MaterialNavigationPopup when set by NCG

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
nekoyume/Assets/_Scripts/UI/Widget/Battle.cs

튜토리얼 진행시 어드벤처보스관련 UI가 제거되지않는상태로 나오는 문제 수정.

fix battle ui initialize when tutorial

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossEnterBountyPopup.prefab

fix adventureboss text align bug

fix adventureboss text align bug

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

- https://github.com/planetarium/NineChronicles/issues/5267
- 원인과 수정 과정에 대해 위의 이슈에 자세히 설명해두었습니다.

fix RetryRpc works even after OnDestroy in RPCAgent invokes

---

nekoyume/Assets/Resources/VFX/Prefabs/UI_sweep_attack_VFX.prefab
nekoyume/Assets/Resources/VFX/Prefabs/UI_sweep_attack_VFX.prefab.meta

add ui sweep attack vfx

---

nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs

edit timeout of market http client 10->30

---

nekoyume/Assets/_Scripts/UI/Widget/Battle.cs

fix adventure boss speed toggle issue

fix adventure boss speed toggle issue

---

nekoyume/Assets/_Scripts/UI/Module/WorldMapAdventureBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardInfoPopup.cs

fix block refreshissue
BlockIndexSubject는 단순 subject이기 때문에 Subscrib시점에 호출되지는 않아서 내용 수정하였습니다.

fix block refreshissue

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

운영및 참여를 하지않은 어드벤처보스 시즌 보상팝업이 보이는 문제
실 보상계산에서 보상이 없을 경우에도 팝업이 보이지않도록 추가 예외처리진행함.

adventurebossRewardPopup only open when has rewards

---

nekoyume/Assets/_Scripts/UI/Module/AdventureBossFloor.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBoss_UnlockLockedFloorPopup.cs

adjust adventurebossData refresh timing consider sloth

adjust adventurebossData refresh timing consider sloth

---

nekoyume/Assets/_Scripts/UI/Model/AdventureBossData.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossEnterBountyPopup.cs

바운티팝업 이슈들 수정
- 캐릭터 변경시 이전 캐릭터 운영보상 나오는문제
- 아무 바운티를 안걸었을경우 기대보상 아이템 표시 뜨지않던문제
- 보유 ncg초과로 입력할수있는문제

fix adventureboss bounty popup issue

---

nekoyume/Assets/_Scripts/UI/Widget/AdventureBossResultPopup.cs

fix adventureboss result popup rundata amount issue

---

nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/MailRewardItemView.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBossResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

adventureboss reward apply decimal point

---

nekoyume/Assets/_Scripts/Game/Character/BreakthroughCharacter.cs

fix effect position and scale

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

룬조각아이템 보상이 인벤토리에 갱신되지않는 문제 수정.

update rune data

---

nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
nekoyume/Assets/_Scripts/UI/Module/Stat/StatView.cs

fix stat view param type to decimal

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

https://github.com/planetarium/NineChronicles/assets/3193043/36a07094-eddb-4fc1-92d1-c0fcd8da54cc
---
- resolve #5306 
- 아우라와 다르게 즉시 완료가 되는게 아닌 일정 블록이후 사용이 가능해지는 장비의 경우 메일을 읽어도 인벤토리에서 바로 반영이 안되는 케이스가 있는데, 이건 최적화 이슈때문에 블록높이에 따른 인벤토리 갱신을 비활성화해둬서 그렇습니다. 이 케이스는 인벤토리창을 닫았다 새로 열면 변경사항이 반영되있습니다.

아이템 강화후 메일 읽음 처리시 인벤토리 업데이트가 안되는 문제 수정

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Game/Battle/Stage.cs
nekoyume/Assets/_Scripts/UI/Module/AdventureBossFloor.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

rpc test PR 리뷰에서 나온 이슈들 수정하였습니다.

fix review issue

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs

- https://github.com/planetarium/NineChronicles/issues/5311
https://github.com/planetarium/NineChronicles/assets/63496908/f5fabfdf-0275-4146-91be-76b773da3368

add banner, update - TryOpenBanner when enter to UI_Craft, UI_WorldMap

---

nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_adventure_boss_01.prefab
nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_adventure_boss_lobby.prefab

fix audio default setting

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossEnterBountyPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossEnterBountyPopup.cs

add l10n key

---

nekoyume/Assets/_Scripts/UI/Model/CollectionModel.cs
nekoyume/Assets/_Scripts/UI/Widget/Collection.cs

ReactiveAvatarState의 인벤토리 업데이트시 해당 데이터로 인벤토리를 업데이트합니다

update inventory from reactive property

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab

add star image to stat view in item tooltip

---

nekoyume/Assets/_Scripts/UI/Widget/Hud/HudContainer.cs

hud컨테이너가 어드벤처보스의 UI에 가려지지 않도록 위치를 수정합니다.

add custom hud container height on adventure boss

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs

https://github.com/planetarium/NineChronicles/issues/5316
토글 설정 전체가 아니라 토글만 가려지는 문제 수정하였습니다.

fix setting hide object

---

nekoyume/Assets/AddressableAssets/UI/Module/Collection/CollectionCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionRegistrationPopup.prefab

button_common_collection
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=69801276

[Design]UI_Collection_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Widget/AdventureBossResultPopup.cs

https://github.com/planetarium/NineChronicles/issues/5371
어드벤처보스 결과창에서 메인페이지 이동시 데이터 갱신 타이밍에 따라 도전 팝업 수치가 잘못나오는 문제 수정.
해당 수정 진행하면서 결과창에서 어드벤처 메인페이지 이동시 로딩스크린이 뜨지않는 문제도 같이 수정하였습니다.
로딩스크린관련해서 Game.Event.OnRoomEnter.Invoke(true); 와 특정시점사이까지 로딩스크린을 띄워야하는경우 리팩토링이 필요합니다. 
Game.Event.OnRoomEnter.Invoke(true); 호출 내부적으로 특정 타이밍에 로딩스크린을 끄는 경우가 있는데, 일단 다른 구현에 영향가지 않도록 어드벤처보스에서만 주기적으로 로딩스크린을 다시 키는식으로 수정하였습니다.
Game.Event.OnRoomEnter.Invoke(true); 와 특정시점사이까지 로딩스크린을 띄워야하는 패턴의경우 다른 곳에서도 사용하고있는 부분(기존 배틀 결과창에서 준비화면이동 등등) 문제없는지 확인하고 구조 변경 및 리팩토링이 필요해보입니다.

fix loading adventurebos main ui until finished data refreshing.

---

nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_adventure_boss_01.prefab
nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_adventure_boss_lobby.prefab

fix adventureboss music resource setting

fix adventureboss music resource setting

---

nekoyume/Assets/_Scripts/UI/Widget/AdventureBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

1미만 리워드 보이지 않던 문제 수정.  MajorUnit이 1미만일떄 0이어서 분기벗어나는 문제로 확인 및 수정하였습니다.

fix lower then 1 reward not displayed

---

nekoyume/Assets/_Scripts/Extensions/BlockIndexExtensions.cs
nekoyume/Assets/_Scripts/UI/Module/WorldMapAdventureBoss.cs

푸쉬알림 메세지에  남은시간 및 예상 시점 인자 추가.

add adventureboss push noti next season time data

---

nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/RuneTooltip.cs

fix TotalValueAsLong -> TotalValue at rune stat value to string

---

nekoyume/Assets/_Scripts/Game/Battle/Stage.cs

clear memory on room enter

---

nekoyume/Assets/_Scripts/UI/Widget/AdventureBoss.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

수량이 1이하 0이상인 아이템이 정상적으로 나오도록 수정하였습니다.

fix reward hided

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossEnterBountyPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossEnterBountyPopup.cs

운영 참가 인풋필드 포커스시 연출을 추가합니다 
#5285

add OnBountyInputAreaFocus

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs
nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
nekoyume/Assets/_Scripts/UI/Widget/System/QuitSystem.cs

1. 기존 로직의 변화가 최대한 없는 상태로 기능들을 함수 단위로 빼려고 정리한 pr입니다
2. 중복되는 로직을 함수로 정리하였습니다
기존 기능에 영향을 줄 수 있는 부분은 추후 수정을 위해 아래 discussion에 정리하였습니다
https://github.com/planetarium/NineChronicles/discussions/5118

game class, 로그인 로직 정리

---

nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
nekoyume/Assets/_Scripts/ApiClient/ApiClients.cs

로컬에서 서비스 초기화시 생기는 예외를 방지합니다.
#5445

fix service init on local

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/RxProps.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs

fix `WorldBossStates.Set` to GetState with OutputState hash

---

nekoyume/Assets/_Scripts/Game/Game.cs

에러 팝업에서 exit callback을 제거합니다
#5457

remove exit callback on error popup

---

nekoyume/Assets/_Scripts/Game/Game.cs

1. remove setting cancelCallback about key backup
resolve #5383

remove setting cancelCallback about key backup

---

.github/workflows/9c-projects.yml

change action for issue create

---

nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AddHammerPopup.cs

- bump lib9c to `origin/refactor/hammer` branch https://github.com/planetarium/lib9c/pull/2686
- fix GetHammerExp method 
- `Equipment.GetHammerExp` -> `EnhancementCostSheetV3.GetHammerExp`

bump lib9c to `origin/refactor/hammer`

---

nekoyume/Assets/_Scripts/UI/Widget/Summon.cs

fix to update header menu asset when summon UI is enable

---

nekoyume/Assets/Resources/UI/Animations/UICombinationController_Grind.controller

- fix this #5363 
https://github.com/user-attachments/assets/630d0072-e8dc-46c7-ab40-ebb091bd5097

fix grind animator state

---

nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab

fix Grimoire slot default image in FriendInfoPopup

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/PreviousSeasonReportPopup.cs

입찰 참여 안했을시 어드벤쳐보스 이전시즌 팝업 뜨지않는 문제 수정.

입찰 참여 안했을시 어드벤쳐보스 이전시즌 팝업 뜨지않는 문제 수정.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab

change summer event id to 1011

change summer event id to 1011

---

nekoyume/Assets/Resources/ScriptableObject/EventData.asset

add summer event id 10110001

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

fix arena participant ordering

---

nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

- fix #5506 
- 이외에 아우라와 비슷한 특성을 가진 그리모어가 핸들링 되어야 하는 부분들을 추가해줬습니다.
- [delete wrong condition(check it is aura)](https://github.com/planetarium/NineChronicles/commit/de4fff74deb9e6cc9680ef0eb952b349b88318da)
- [add condition (check it is aura)](https://github.com/planetarium/NineChronicles/commit/a481a14e50d7ea1a182b155a00c91acd7a697d0c)

handle Griomoire when it remove or add item in local layer

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AddHammerPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
nekoyume/Assets/_Scripts/UI/Module/EnhancementExpSlider.cs
nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs

- fixed
- #5520
- #5516 
- #5501
- #5515 
- #5505 
https://github.com/user-attachments/assets/4d6ce80e-e846-47bc-8e70-d0d2d6094bee

fix enhancement, hammer bugs

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/SummonDetailCell.prefab

fix item name text size

---

nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs

로컬레이어 관련 수정으로 인한 사이드이펙트로 추정
근데 애초에 5번 튜토리얼만 재화체크해서 진행하는게 이상하다 판단되어 해당 부분 제거
#5354

remove redundant tuto option

---

nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs

add UpdateEquipmentEquipped on UpdateInventory

---

nekoyume/Assets/_Scripts/UI/Module/EnhancementExpSlider.cs

- resolve #https://github.com/planetarium/NineChronicles/issues/5546
https://github.com/user-attachments/assets/b4ef408e-036c-49ec-9988-92c26dfdd73a

fix exp value text

---

nekoyume/ProjectSettings/ProjectSettings.asset

모바일 가로모드 방향 고정되어있던 부분 해제

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/PreviousSeasonReportPopup.cs

이전 시즌정보 표기시 공헌도% 및 NCG 보상 내용 보이지않던문제 수정.

fix PreviousSeasonReportPopup show ncg and contribution percent

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBoss.prefab
nekoyume/Assets/_Scripts/UI/Widget/AdventureBoss.cs

어드벤처보스 배틀참여하지않거나 참여보드데이터가 없을때 기본값이 잘못 출력되는 문제 수정.

fix usedApPotion text

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs

간헐적으로 이벤트던전 멈추는 문제 의심포인트 수정 및 문제파악을위해 로그추가.

fix event-dungeon-freeze point of doubt and add log

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/AddHammerPopup.cs

이미 선택된 해머 선택시 nre와 함께 아이템 정보가 갱신되지 않는 현상을 수정합니다
#5554

fix hammer exp nre

---

nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs

fix enhancement `GetModels()` method

---

nekoyume/Packages/manifest.json
nekoyume/Packages/packages-lock.json

구글 결제 라이브러리 버전 지원 중단 대응을 위한  Unity IAP 패키지 버전 업데이트

update unity iap package

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs
nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs

- #5565 
\* 백머지 후 development에 넣을 예정입니다.
https://github.com/user-attachments/assets/fe0cd396-4610-439f-876c-00fb3b60e709

improve upgrade shortcut

---

nekoyume/Assets/_Scripts/Lib9c/Lib9c.asmdef

lib9c asmdef에 root name space를 추가합니다

add root name space in lib9c asmdef

---

nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

플렛폼별 sku 사용 함수 리팩토링입니다.
- 중복코드제거
- 오타 수정
- sku로 프로덕트 찾을때 현재 사용중인 플렛폼기준으로 못찾으면 다른플렛폼에 동일한 sku가 있는지 한번더 찾도록 수정.

refactoring sku search method

---

nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductSchema.cs
nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

다른 플렛폼에서 결제한 내용도 이메일에서 정상표현하기위해서 sku 조건 확장.

check Sku another platform

---

nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs

결과화면창 뜨도록 하는 콜백 실행되지않는 부분 체크위해서 로그수집.

add additional log

---

nekoyume/Assets/_Scripts/Extensions/EnumerableExtensions.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. handle the case about outfit random selecting at CustomCraft
2. 외형을 랜덤으로 결정하면 얻을 수 있는 외형이 순서대로 번갈아가며 나오는 연출과 관련 처리를 추가했습니다.
3. 외형 스크롤에 정렬을 추가했습니다. 요구 친밀도 -> 랜덤only 순서로 정렬됩니다.
resolve #5616

handle the case about outfit random selecting at CustomCraft

---

nekoyume/Assets/_Scripts/Extensions/InventoryExtensions.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
nekoyume/Assets/_Scripts/UI/Module/Button/SimpleCostButton.cs
nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
nekoyume/Assets/_Scripts/UI/Module/Currency/ApPotion.cs
nekoyume/Assets/_Scripts/UI/Module/Currency/Hourglass.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossRank.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CostTwoButtonPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs

(cherry picked from commit efd5cc585de6e16cf63bb17595883365a3553dab)
인벤토리에서 아이템의 개수를 세는 코드가 개별적으로 구현되어 있어 한 메서드로 통일했습니다.
#5585 에서 수정하다가 나온 변경사항인데, 해당 feature와 관계가 없는 것 같아 분리합니다.

refactor to replace `get count...` to `GetUsableItemCount`

---

nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraft.prefab
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. change craftButton to ConditionalCostButton
2. 일반 버튼이었던 제작 버튼을 ConditionalCostButton으로 바꾸는 PR입니다.
resolve #5624

change craftButton to ConditionalCostButton

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RelationshipInfoPopup.cs

1. 액션 날릴때 슬롯 캐싱하게 추가했습니다.
2. 액션 렌더에서 불필요한 코드를 지웠습니다.
3. RequiredItemView에서 인벤토리가 갱신될때마다 반영될 수 있도록 CustomCraft에서 구독, 라이프사이클을 관리하게 했습니다.
4. 액션을 날릴때 슬롯이 비어있어야 날릴 수 있게 반영했는데... 로컬 레이어 처리는 덜 된 것 같습니다

Refactor codes about CustomCraft 

---

nekoyume/Assets/_Scripts/Extensions/ActionBaseExtensions.cs
nekoyume/Assets/_Scripts/Game/Battle/Stage.cs

스테이지 이벤트 로그에 (인덱스/전체 이벤트 수)
를 표기합니다

add event index to stage action log

---

CODEOWNERS

1. change _Scripts code owners to client engineer
resolve #5649

change _Scripts code owners to client engineer

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/RelationshipInfoCell.prefab
nekoyume/Assets/_Scripts/UI/Scroller/RelationshipInfoCell.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RelationshipInfoPopup.cs

1. add focusObject to RelationshipInfoCell
resolve #5637

add focusObject to RelationshipInfoCell

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

액션 이전의 아바타상태로 시뮬레이터돌려서 이격사라지도록 다른 simulator를 사용하는 액션핸들러 아바타갱신 변경.

apply previous avatar state for simulator

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/Recipe/RequiredItemRecipeView.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. [fix not interactable callback logic](https://github.com/planetarium/NineChronicles/commit/34e75f2b88d42665db35f548624d91c2ee10b55a)
2. [update button state when on submit](https://github.com/planetarium/NineChronicles/commit/891b9b9f3fbbecd385bafe2a79d57a54ce007b3f)
3. [fix condition of conditional cost button at CustomCraft](https://github.com/planetarium/NineChronicles/commit/dd8c9386ff546c116b47f526b57db45afd901bf3)
4. [refactor RequiredItemRecipeView](https://github.com/planetarium/NineChronicles/commit/68cb690ead8953721edfab1cdcec222c2a06e887)
resolve #5643 #5651

fix something about CustomCraft

---

nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_GrindModule_Reward.prefab
nekoyume/Assets/Resources/UI/Animations/Item_GrindModule_Reward.controller
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Module/Item/GrindReward.cs

- resolve https://github.com/planetarium/NineChronicles/issues/5639
https://github.com/user-attachments/assets/679dc72c-4fc0-464d-8b53-9b517863f411

fix ui bugs in grind reward

---

nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs

1. fix qr code import/export size to 800*800
resolve #5617

fix qr code import/export size to 800*800

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

fix reward view not hided

---

nekoyume/Assets/_Scripts/ApiClient/ApiClients.cs
nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
nekoyume/Assets/_Scripts/Multiplanetary/PlanetInfo.cs
nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

- resolve https://github.com/planetarium/NineChronicles/issues/5652
1. clo.json에 "ArenaServiceHost" 인자를 추가합니다.
형식: "{service host}/graghql"
2. 게임에 들어가 아레나 목록을 잘 불러오는지 확인합니다.
odin
heimdall

create arena service client

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossFullBountyStatusPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossFullBountyStatusPopup.cs

현상금 리스트 다시 오픈시 스크롤러 위치 맨위로 갱신되도록 수정

fix bounty board scrollView position reset

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

change SelectRecipientAddress to PickAddress

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraft.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. 커스텀 제작에서 쓰이는 로컬라이징 키 처리를 한 PR입니다. 아마 빼먹은게 있을수도 있습니다.
resolve #5635

custom craft l10n

---

nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/Vfx_BundledAssetGroupSchema.asset

remote로 설정되어있던 어드레서블 로드 패스를 local로 변경합니다

apply local addressable load path

---

nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs

- resolve #5312
https://github.com/user-attachments/assets/149edcab-b517-4752-8391-7f3880aa8779

fix backbutton error

---

nekoyume/Assets/_Scripts/Game/Scene/LoginScene.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

- resolve #5687 
시놉시스 또는 게임 로딩 후 캐릭터 선택 또는 게임 진입까지 갈 때 씬 이동하는 데에 보여주는 UI가 아무것도 없어서 발생함.
await가 걸리는 부분에 LoadingScreen을 추가했습니다.
https://github.com/user-attachments/assets/5c8e3094-cd16-4f59-90b7-5d3d3ffbfc77

add LoadingScreen in async EnterCharacterSelect, EnterGame

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossBattlePopup.prefab

fix text width "random reward"

---

nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

refactor CustomCraft

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs

UI와 SlotState의 Index가 불일치하던 버그를 수정합니다.

fix slot index

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CelebratesPopup.cs

퀘스트보상이 인벤토리에 갱신안되는 문제 수정.
로컬레이어에서 삭제해주는 구간 제거.

remove local layer refresh

---

nekoyume/Assets/_Scripts/UI/MainCanvas.cs

- resolve #5725 
https://github.com/user-attachments/assets/55178db2-086e-49bd-9e27-c7be3501a679

move SummonResultPopup order before PaymentPopup

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraftLoadingScreen.prefab
nekoyume/Assets/_Scripts/Game/Character/NPCAnimation.cs
nekoyume/Assets/_Scripts/UI/MainCanvas.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/CustomCraftLoadingScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/CustomCraftLoadingScreen.cs.meta

https://github.com/planetarium/NineChronicles/issues/5719

add CustomCraftLoadingScreen

---

nekoyume/Assets/AddressableAssets/UI/Module/GrindModule.prefab
nekoyume/Assets/AddressableAssets/UI/Module/StakingBonus.prefab
nekoyume/Assets/Resources/UI/Animations/GrindModule@FirstRegister.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab

grind-edit-240827
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=76516830

[Design]GrindModule_Prefabs_Edit

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
nekoyume/Assets/_Scripts/UI/Module/WorldMapAdventureBoss.cs

- https://github.com/planetarium/NineChronicles/issues/5632
https://github.com/user-attachments/assets/26af884b-a5c4-400f-8ffd-435e2fc0b581

add shortcut to Drawing, DrawingTool

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
nekoyume/Assets/StreamingAssets/Localization/enum_type.csv
nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs

- #5572 
- MarketService 에서 관련 작업 완료 후 재확인 필요
- https://github.com/planetarium/lib9c/pull/2788 <- 머지 후 클라이언트 내 대응 필요 (L10n 키 외에는 주의할 부분은 없음)
- 해당 작업 하면서 나온 리펙토링 관련 변경사항은 #5771 에 올렸습니다.
슬랙 스레드에 첨부

add Drawing, DrawingTool in ShopView Filter

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs

add shortcut(Worldboss, Stage) to Circle

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/SkillInformationCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraft.prefab
nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

- https://github.com/planetarium/NineChronicles/issues/5738
- https://github.com/planetarium/NineChronicles/issues/5804
- https://github.com/planetarium/NineChronicles/issues/5741
- https://github.com/planetarium/NineChronicles/issues/5806

fix CustomCraft UI layout

---

nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs

- update CostomCraftMail l10n message #5800 
- update NotificationSystem icon in CustomCraft #5801 
- update to use icon Id in Localize item name #5754

CustomCraft UI polishing

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/CustomCraftItemCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/_Scripts/Game/Battle/Stage.cs
nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
nekoyume/Assets/_Scripts/UI/Model/CustomOutfit.cs
nekoyume/Assets/_Scripts/UI/Module/CustomOutfitView.cs
nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

- https://github.com/planetarium/NineChronicles/issues/5735
- #5802

Custom Craft menu in Workshop

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs

add shortcut(Grind) to Drawing, DrawingTool #5632 

---

nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/InitializeUtil.cs
nekoyume/Assets/Tests/EditMode/AvatarStateTest.cs
nekoyume/Assets/Tests/EditMode/Battle/RankingSimulatorTest.cs
nekoyume/Assets/Tests/EditMode/State/Modifiers/AvatarInventoryItemEquippedModifierTest.cs
nekoyume/Assets/Tests/EditMode/StateModifierTest.cs

resolve https://github.com/planetarium/lib9c/pull/2780

Refactor AvatarState constructor

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

1. Fix the bug where the build fails on the development branch. ([HEAD](https://github.com/planetarium/NineChronicles/commit/01b2add67b496fc549e07ce9644ecbbad88cb852))
1. Check to see if the build succeeds.
- https://github.com/planetarium/NineChronicles/pull/5767
- @tyrosine1153 
None.

Replace CombinationResult popup with screen

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraft.prefab
nekoyume/Assets/_Scripts/UI/Module/RelationshipGaugeView.cs
nekoyume/Assets/_Scripts/UI/Module/RelationshipGaugeView.cs.meta
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. 친밀도 구간을 슬라이더 UI로 보여줄 수 있게 작업했습니다.
2. MAX값도 보여줍니다.
3. 끝.
resolve #5742

add RelationshipGaugeView

---

nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs

모바일상점 레드닷이 정상적으로 갱신되지않는 문제 수정하였습니다.
원인 : 무료상품 구매시 로컬상품정보에 구매카운트를 갱신하지않아서 레드닷이 같이 갱신안되는 문제로 확인되었습니다.

fix mobile shop red dot not refreshed

---

nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs

remove throwing exception

---

nekoyume/Assets/Resources/UI/Prefabs/UI_OutfitInfoListPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/OutfitInfoListPopup.cs

OutfitInfoListPopup의 close버튼에 닫기 이벤트를 추가합니다

add close event to close button

---

nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. 감정중에 기존 슬롯 배경 상태가 남아있던 버그 수정
2. 커스텀 크래프트 로컬 상태 적용

커스텀 크래프트 감정중에 UI 상태 수정 

---

nekoyume/Assets/_Scripts/State/States.cs

thread-safety-slotstate

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

1. AttachMail이 아니라서 LocalLayerModifier.AddAttachNewMail로 처리하던 부분을 수정했습니다.
2. RapidCombination에서도 분기를 쳐서 AddNewMail로 갈 수 있게 해놨습니다.
resolve #5845

fix bug about CustomCraftMail

---

nekoyume/Assets/_Scripts/UI/Model/CustomOutfit.cs

- https://github.com/planetarium/NineChronicles/issues/5802

fix custom outfit reddot condition

---

nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraft.prefab

add ruby dust to ConditionalCostButton type2 and CustomCraft

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraft.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RelationshipLevelUpPopup.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/Game/TableSheets.cs
nekoyume/Assets/_Scripts/UI/Module/CustomCraftResultView.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. 친밀도 구간이 올라갈때 안내해주는 팝업 추가
2. lib9c 대응

bump lib9c and add relationship section info popup

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossRewardScreen.prefab
nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Reward.prefab
nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossGradeRewardItem.prefab
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Game/Battle/RaidStage.cs
nekoyume/Assets/_Scripts/UI/Model/WorldBossRewards.cs
nekoyume/Assets/_Scripts/UI/Model/WorldBossRewards.cs.meta
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossGradeReward.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossGradeRewardItem.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/WorldBossRewardScreen.cs

worldboss_reward-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=79202618

update WorldbossRewards and reward UI

---

nekoyume/Assets/_Scripts/UI/Scroller/RelationshipInfoCell.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CustomCraftInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RelationshipInfoPopup.cs
nekoyume/ProjectSettings/ProjectSettings.asset

fix relationship

---

nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossGradeRewardItem.prefab

worldboss_grade_reward-edit240913
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=79671491

[Design]WorldBossGradeRewardItem_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Animations/UI_CustomCraftEvaluationCompleted@Show.anim
nekoyume/Assets/Resources/UI/Animations/UI_CustomCraftEvaluationCompletedPopup.controller
nekoyume/Assets/_Scripts/UI/Widget/Popup/CustomCraftResultPopup.cs

아이콘이 랜덤으로 정해진 경우와 아닌 경우 다른 애니메이션을 나오게하기 위해 미작업했던 애니메이션을 추가한 PR입니다.
https://github.com/planetarium/NineChronicles/issues/5760

add missing animation to CustomCraftResultPopup

---

nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs

hide item view on appraise

---

nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraft.prefab
nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

CustomCraft tutorial

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

- #5914
- bump lib9c https://github.com/planetarium/lib9c/pull/2841

fix to update inventory when ClaimRaidReward action render

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
nekoyume/Assets/_Scripts/L10n/L10nManager.cs
nekoyume/Assets/_Scripts/UI/Module/Stat/CustomEquipmentStatView.cs
nekoyume/Assets/_Scripts/UI/Scroller/RandomOutfitCell.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

- https://github.com/planetarium/NineChronicles/issues/5911

fix custom craft equipment L10n key

---

nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/AdventureBossWorldButton.prefab

ui/worldmap_touch_area-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=72987176

[Design]AdventureBossWorldButton_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab

ui/arena_text-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=71697885

[Design]UI_ArenaBattle_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraftLoadingScreen.prefab
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/CustomCraftLoadingScreen.cs

1. CustomCraftLoadingScreen에서 만들려고 하는 아이템의 아이콘이 나오게 작업했습니다.
2. 랜덤 아이콘 여부는 Equipment.CraftWithRandom 필드를 참조합니다.
#5919

add icon handling to CustomCraftLoadingScreen

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/SkillInformationCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraftInfoPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_OutfitInfoListPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RelationshipInfoPopup.prefab

ui/clock_sound-add
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=80844705

[Design]UI_CustomCraftInfoPopup_Prefabs_Edit

---

nekoyume/Assets/_Scripts/L10n/L10nManager.cs

1. L10nManager.ContainsKey가 dict 말고 additionalDict도 보도록 수정했습니다.
#5952

fix L10nManager.ContainsKey logic

---

nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. 랜덤에서만 얻을 수 있는 외형에서도 제작 횟수가 나올 수 있도록 수정했습니다.
#5970

show crafted count at random only outfit too

---

nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs

enable PriceText on shop item view enable

enable PriceText on shop item view enable

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab

ui/monstercollection-edit240924
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=69813653

[Design]UI_StakingPopup_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs

- https://github.com/planetarium/NineChronicles/issues/5948

fix SortFilter default Ascending in buyview

---

nekoyume/Assets/AddressableAssets/UI/Module/GrindModule.prefab
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs

https://github.com/planetarium/NineChronicles/issues/5955
https://github.com/user-attachments/assets/7c5bce41-39df-4a3d-87a1-10155123f9a6

fix grind button condition check

---

nekoyume/Assets/_Scripts/UI/Module/CustomCraftResultView.cs
nekoyume/Assets/_Scripts/UI/Module/Stat/CustomEquipmentStatView.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CustomCraftInfoPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RelationshipInfoPopup.cs

bump lib9c and reflect it

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab

- https://github.com/planetarium/NineChronicles/issues/5959

edit acquisition button to Scroll in MaterialTooltip

---

nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

아래 이슈들을 처리합니다 
https://github.com/planetarium/NineChronicles/issues/6006
https://github.com/planetarium/NineChronicles/issues/6000
https://github.com/planetarium/NineChronicles/issues/5999
https://github.com/planetarium/NineChronicles/issues/5998
https://github.com/planetarium/NineChronicles/issues/5987

재화 팝업 관련 이슈 처리

---

nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. 친밀도가 0인데 튜토리얼을 본적 없으면 나오게 하려고 했는데... 조건 설정을 잘못했었습니다. 그래서 수정했습니다.
2. 겸사겸사 스테이지 제한을 301로 바꿔달라고 하셔서 튜토리얼 바꾸는 김에 다 같이 바꿨습니다.
#5973 
#6014

fix custom craft tutorial level limit

---

nekoyume/Assets/StreamingAssets/Localization/item_name.csv

커스텀 랜덤 장비가 감정되기 전을 위한 키를 추가합니다

add empty random custom item key

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CraftResultPopup.cs

전투중이랑 튜토리얼중에 제작 완료 감정 팝업이 출력되지 않도록 수정합니다 (기획 확인 받은 방향입니다)

don't show craft result popup when tutorial and battle render

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

1. 커스텀 제작 메일을 전체 받기 가능한 메일로 타입 추가를 해줬습니다.
#5988

add CustomCraftMail to all-recievable mail

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

- https://github.com/planetarium/NineChronicles/issues/5969
- https://github.com/planetarium/NineChronicles/issues/5959
- https://github.com/planetarium/NineChronicles/issues/5971

fix material tooltip for Circle

---

nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
nekoyume/Assets/_Scripts/EnumType/PatrolRewardType.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs

1. 정찰 보상에 모래시계가 추가되면서 이를 대응하지 못한 UI가 고장을 일으켰고, 모래시계 UI를 추가했습니다.
resolve #6007

add hourglass to patrol reward

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CraftResultPopup.cs

일반 장비 감정 팝업에서 0으로 나누는 경우가 없게 수정합니다

prevent divide 0 in craft result popup

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

update rune stone balance on adventureboss explore render

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
nekoyume/Assets/_Scripts/Game/ScriptableObject/ItemViewDataScriptableObject.cs
nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBossResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

- https://github.com/planetarium/NineChronicles/issues/5971
- https://github.com/planetarium/NineChronicles/issues/6038

fix item tooltip for circle

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab

ui/workshop_botton-edit240926
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=81163963

[Design]UI_CombinationSlotsPopup_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab

- https://github.com/planetarium/NineChronicles/issues/6047

fix item tooltip to disable acquisitionGroup

---

nekoyume/Assets/_Scripts/UI/Widget/AdventureBossResultPopup.cs

https://planetariumhq.slack.com/archives/C011716SDTM/p1727337211721659

fix to disable item view in AdventureBossResultPopup

---

nekoyume/Assets/Resources/UI/Animations/UI_CraftResultPopup.controller

오브젝트의 기본 상태가 애니메이션 된 값을 덮어쓰는걸 방지합니다

craft result popup - disable write default in anim state

---

nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs
nekoyume/ProjectSettings/ProjectSettings.asset

fix bug about relationship info popup showing

---

nekoyume/Assets/_Scripts/Game/Game.cs

fix guest login button enable

---

nekoyume/Assets/_Scripts/Director/TimelineHelper.cs

remove timelinehelper log

---

nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_adventure_boss_coin.wav.meta
nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_adventure_boss_mon_collision.wav.meta
nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_adventure_boss_penetration.wav.meta
nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_adventure_boss_pop_up.wav.meta
nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_arenabattleloading.wav.meta

sound setting to streaming

---

README.md

Fix typo and icon link

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/ArenaSheetExtensions.cs
nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs

1. https://github.com/planetarium/lib9c/pull/2859
2. 이걸 클라에 반영합니다.
[#6001](https://github.com/planetarium/NineChronicles/issues/6001)

ProductCancelMail에 추가된 Product 반영

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepResultPopup.cs

기존 '스윕 연출 중' ESC를 눌러 창을 닫지 못하게 했는데 빈 틈이 있는 것 같습니다.
그냥 스윕 UI에서 E키 입력을 통한 창 닫기를 하지 못하게 수정하였습니다.

prevent skip on sweep result popup

---

nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

1. ssia
2. 스테이킹 마이그레이션이 필요할때 스테이킹 팝업에 들어가면 매번 안내팝업이 나오게끔 작업했습니다.
resolve #6131

add migrate notice to StakingPopup

---

nekoyume/Assets/Airbridge/Plugins/Editor/Dependencies.xml

update Airbridge ios sdk to 1.36.5

---

nekoyume/Assets/_Scripts/L10n/L10nManager.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs

fix worldboss ticker serialization

---

nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs

모바일샵 상품 셀 이미지크기 원본이미지로 나오도록 수정.

fix product image set native size

---

nekoyume/Assets/_Scripts/ApiClient/IAPServiceManager.cs

fix platform sku return

---

nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset

Update Rune Order Data

---

nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs

아래 두 이슈를 해결합니다
https://github.com/planetarium/NineChronicles/issues/6162
https://github.com/planetarium/NineChronicles/issues/6173

fix detail ui active

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/PetDescriptionView.prefab

ssia, dimmed 오브젝트가 버튼 클릭을 막고 있던걸 수정하였습니다.

disable raycast target on dimmed object

---

nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs

펫 정렬 기준 중 '등급을 기준으로 내림차순 정렬'옵션을 제거합니다.

change pet sort condition

---

nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset

Update Rune Order Change
+ RUNESTONE_ATK
+ RUNESTONE_DEF

Update Rune Order Change

---

nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Reward.prefab
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossBattleRewardItem.cs

- close #6174
- close #6027
#6027
https://github.com/user-attachments/assets/0045d0eb-853f-4c8a-a325-c14177be7f0d

fix world boss reward

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs

change conditon to mouse position

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/PetDescriptionView.prefab

펫 버튼 영역을 버튼이미지에서 펫 아이템 전체로 변경합니다

change pet item button

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonCell.prefab
nekoyume/Assets/UIResources/Font/Black Drama SDF Material - SeasonTItle Number.mat

ui/arena_championship_number-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=84618334

[Design]ArenaJoinSeasonCell_Prefab_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/UI/Module/CollectionMaterialInfo.cs

- close #6224 
https://github.com/user-attachments/assets/0e83dbcb-c0be-4b5c-9aec-3751c4913dd3

add skill not contains label

---

nekoyume/nekoyume.sln.DotSettings

참고
https://github.com/planetarium/lib9c/pull/2970

apply auto generated code rules

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab

ui/grind-edit241106
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=85621587&issue=planetarium%7CNineChronicles%7C6252

[Design]UI_Grind_Prefabs_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
nekoyume/Assets/_Scripts/ApiClient/PatrolRewardQuery.cs
nekoyume/Assets/_Scripts/ApiClient/PatrolRewardQuery.cs.meta
nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
nekoyume/Assets/_Scripts/UI/Model/PatrolRewardModel.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
nekoyume/Assets/_Scripts/UI/Module/PatrolRewardModule.cs
nekoyume/Assets/_Scripts/UI/Module/PatrolRewardModule.cs.meta
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventRewardPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventRewardPopup.cs.meta
nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs

- class `PatrolReward`에서 `PatrolRewardQuery`를 분리해 가져왔습니다.
- `PatrolRewardQuery` : 외부 서비스에 쿼리 날리고 받는 메서드만 모았습니다.
- `PatrolReward` : 현재 방치보상에 대한 값을 갖고 있습니다. static으로 수정했습니다.
- `PatrolRewardPopup` 에서 `PatrolRewardModule`을 분리해 가져왔습니다.
`PatrolRewardModule` : `PatrolRewardPopup`, `EventRewardPopup` 에 들어가는 방치보상 관련 UI 스크립트

Refactor patrol reward

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SummonDetailPopup.prefab

ui/summon_detail_popup-edit241107
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=86306942

[Design]UI_SummonDetailPopup_Resource_Edit

---

nekoyume/Assets/_Scripts/ApiClient/ThorSchedule.cs
nekoyume/Assets/_Scripts/Extensions/BlockIndexExtensions.cs
nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Model/AdventureBossData.cs
nekoyume/Assets/_Scripts/UI/Module/Common/BlocksAndDatesPeriod.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs

- gameConfig에 있던 SecondsPerBlock 을 제거합니다
- 기존에 사용하던 secondsPerBlock이 최종적으로 double로 형변환되어 사용되고 있어 관련 파라메터 타입을 double로 변경하였습니다

remove SecondsPerBlock in gameconfig

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CustomCraft.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab

ui/customcraft_title-edit
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=85794120&issue=planetarium%7CNineChronicles%7C6256

[Design]UI_CustomCraft_Resource_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab
nekoyume/Assets/_Scripts/ApiClient/SeasonPassServiceManager.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs

보상 실수령 받기전까지 레드닷 나오는방식으로 레드닷 갱신 진행하였습니다.

seasonpass red dot

---

nekoyume/Assets/_Scripts/ApiClient/SeasonPassServiceManager.cs
nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs

https://github.com/planetarium/NineChronicles/pull/6280 코드리뷰 수정사항 반영

fix for code review

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab
nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs

시즌 정보가 없는 경우 준비중 UI가 나오도록 수정하였습니다.

add coming soon exception

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

시즌패스 프리미엄 상품이 iap 서비스에 없을 경우 팝업 분기처리.
시즌패스 상품 이름규칙 수정 season id -> season index

add premium sku branching

---

nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

- bump lib9c
- https://github.com/planetarium/lib9c/pull/2982 <- 해당 pr에서 수정된 인터페이스에 대한 반영

bump lib9c, resolve compile error

---

nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset

Update Rune Order
10039 Thor Stun Rune (Adventure)
10040 Thor Stun Rune (Arena)
10041 Loki Vampiric Rune (Adventure)
10042 Loki Vampiric Rune (WorldBoss)

Update v200250 Rune Order

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/EventRewardBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ClaimGiftsResultScreen.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_EventRewardPopup.prefab
nekoyume/Assets/Resources/UI/Shaders/AdditiveAlphaBlend.shader
nekoyume/Assets/_Scripts/Game/Lobby.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventRewardPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/ClaimGiftsResultScreen.cs

https://github.com/planetarium/NineChronicles/issues/6318

event feature polishing

---

nekoyume/Assets/_Scripts/UI/Widget/LobbyMenu.cs

메인 로비에서 토르 안내 텍스트에 잘못 들어간 괄호를 제거합니다

fix thor time text

---

nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
nekoyume/Assets/Resources/UI/Prefabs/UI_EventRewardPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_LobbyMenu.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
nekoyume/Assets/_Scripts/UI/Widget/LobbyMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventRewardPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs

- HasRead를 PlayerPrefs로 저장을 안해서 로비 진입 시 계속 보이는 문제 수정
- ClaimedGiftIds를 Deserialize하는 과정에서 Cast 실패하는 원인으로 선물 수령 -> 재실행 -> 진입이 안되는 문제 수정
- 이벤트 팝업을 보여줄 때 대신 보여줄 방치 보상 튜토리얼 추가

fix event reward popup errors

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab

- 사용하지 않는 레이블(grade granted) 비활성화
- 누락된 l10n key 적용

fix summon lables

---

nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs

fix introscreen prefab

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs

fix crystal value format remove decimal point

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassNewPopup.cs

시즌패스 진입시 데이터갱신을 시도하기때문에 이전에 데이터확인후 진입막는케이스 제거.

fix seasonpass show popup not work

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

seasonpass product migration handle

seasonpass product migration handle

---

nekoyume/Assets/AddressableAssets/UI/Module/PatrolRewardModule.prefab
nekoyume/Assets/_Scripts/EnumType/PatrolRewardType.cs
nekoyume/Assets/_Scripts/EnumType/PatrolRewardType.cs.meta
nekoyume/Assets/_Scripts/UI/Module/PatrolRewardModule.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Widget/LobbyMenu.cs

- close https://github.com/planetarium/NineChronicles/issues/6351
\+ https://github.com/planetarium/NineChronicles/issues/6032
- close #6355
- close #6367

fix patrol reward issues

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab

disable skill icon at 'skilless required' text

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/UI/Model/Rank.cs
nekoyume/Assets/_Scripts/UI/Model/RankCategory.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs

- close #3932 
---
- https://app.asana.com/0/0/1206062708009555

Add category aura, grimoire to rank popup

---

nekoyume/Assets/_Scripts/Game/Battle/BattleRenderer.cs
nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs

티켓 구매 행동을 제외하고는 재화부족팝업으로 전투 중에 나갈 수 없게 설정합니다

prevent move on battle

---

nekoyume/Assets/Resources/AddressableAssetsContainer.asset

이름 바뀐 테이블에 맞추어 스크립터블오브젝트의 레퍼런스 수정.

apply table name change BuffLimitSheet

---

nekoyume/Assets/_Scripts/Debugger/NcDebug.cs
nekoyume/ProjectSettings/ProjectSettings.asset

editor가 아닌 경우 debug.log가 무조건 호출되도록 변경합니다

change debug condition

---

nekoyume/Assets/_Scripts/ApiClient/GeneratedApi/SeasonPassServiceClient.cs

시즌패스 api 업데이트입니다. 토르쪽 이넘타입이 추가되어 갱신합니다.

seasonpass api update

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs

- 인앱결제 상품 이미지 정렬 및 크기 수정
- 마일리지 부족시 안내문구 및 예외처리

fix shop list popup detail

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EquipmentTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab

ui/summon_ditail_cp-add
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=87755844&issue=planetarium%7CNineChronicles%7C6414

[Design]UI_ItemTooltip_Prefab_Edit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EquipmentTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab

Reverts planetarium/NineChronicles#6417

Revert "[Design]UI_ItemTooltip_Prefab_Edit"

---

nekoyume/Assets/_Scripts/ApiClient/MarketServiceClient.cs
nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs

- close https://github.com/planetarium/NineChronicles/issues/6364

fix `GetBuyProducts` param

---

nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs

bump lib9c for buff limit sheet

bump lib9c 1.20.0

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SummonDetailPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/SummonDetailPopup.cs

- close https://github.com/planetarium/NineChronicles/issues/6388

add cp text in SummonDetailPopup

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EventRewardPopup.prefab
nekoyume/Assets/_Scripts/UI/Module/PatrolRewardModule.cs

- close https://github.com/planetarium/NineChronicles/issues/6400

fix set patrol reward view

---

nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs

현재 선택된 행성이 토르인 경우에만 new마크를 표기하도록 변경합니다

control new mark

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

시즌패스 상품 구매시 현재 시즌패스창 갱신되도록 수정.

fix seasonpass premium refresh

---

nekoyume/Assets/_Scripts/Game/Lobby.cs
nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs

fix seasonpass guide popup

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab

fix seasonpass button layout

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/EventRewardPopup.cs

- close https://github.com/planetarium/NineChronicles/issues/6447

edit to show nessesary tab

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepResultPopup.cs

스윕에서 다른 타입의 경험치정보를 보여줬던 문제 수정.

fix seasonpass exp amount

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

시즌패스 프리미엄 상품에 룬이 추가되면서 툴팁 기능 추가.

add tool tip for FavList

---

nekoyume/Assets/_Scripts/ApiClient/GeneratedApi/SeasonPassServiceClient.cs
nekoyume/Assets/_Scripts/ApiClient/SeasonPassServiceManager.cs

apply season pass service change

---

nekoyume/Assets/_Scripts/UI/Module/Currency/IAPMileage.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs

fix mileage amount expression

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

fix seasonpass product naming rule

fix seasonpass product naming rule

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab

fix seasonpass layout
노치관련 조정컴포넌트가 적절하지 않은 오브젝트에 포함되어있어서 제거했습니다

fix seasonpass layout

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/LibplanetEditor.cs
nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/BlockManager.cs
nekoyume/Assets/_Scripts/Blockchain/StateGetter.TryGet.cs
nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs

Fixes BlockManager.ProposeGenesisBlock to use proper validator set

Fix BlockManager.ProposeGenesisBlock to use proper validator set

---

nekoyume/Assets/Resources/UI/Prefabs/UI_OutfitInfoListPopup.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv

1. 번역어를 추가했습니다.
2. `UI_OUTFIT_INFO_TEXT`
resolve #6227

add l10n key to OutfitInfoListPopup

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SummonProbabilityPopup.prefab
nekoyume/Assets/_Scripts/UI/Scroller/SummonDetailCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/SummonDetailScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SummonProbabilityPopup.cs

1. SummonProbabilityPopup에서 아예 쓰이지 않는 재료는 비활성화하도록 코드를 변경했습니다.
resolve #6309

Polish SummonProbabilityPopup

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs

fix SeasonPassMenu hide reddot in locked

fix SeasonPassMenu hide reddot in locked

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab

마이그레이션 버튼에 레드닷 항상 보이도록 프리팹 수정.

add reddot icon in staking migrate button

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab

텍스트 변경
1. Resolve a part of #6536

랭크탭 텍스트 변경

---

nekoyume/Assets/_Scripts/UI/Module/ItemTooltipDetail.cs

스크롤, 써클아이템의경우 생성되는형식으로 들어오면 ITradableItem 인터페이스를 안탈수있으므로 추가 타입체크하도록 수정.

exception handle tradable check scroll, circle items

---

nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs

인벤토리 룬갱신이슈 수정.
https://planetariumhq.slack.com/archives/C062ZS68A21/p1733646198426869

fix runslot state

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

1. 커스텀 제작 메일이 워크샵 탭에 포함되도록 했습니다
resolve #5977

feat: add CustomCraft MailType to MailTabState.Workshop

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossRewardInfoPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardInfoPopup.cs

어드벤쳐보스 보상팝업 스크롤로 변경하여 층별 보상 정보 보이도록 수정.

fix adventureboss reward popup scroll change

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab

fix arenaboard notch handle

---

nekoyume/Assets/_Scripts/UI/Module/SynthesisModule.cs

합성 신규 기능 (튜토리얼 제외)

---

nekoyume/Assets/_Scripts/ApiClient/IAPServiceManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs

iap 서비스 상품이름 변경된 l10nkey 규칙으로 변경

fix iap product name rule

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs

내 랭킹 정보가 없을 시 리스트까지 갱신 안되는 문제  수정.

fix ranking board exception handle

---

nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs

튜토리얼이 나올 수 있게 tutorial id를 추가합니다

add synthesize tutorial id

---

nekoyume/Assets/_Scripts/ApiClient/IAPServiceManager.cs

스팩상 판매시간이 없는 상품들도 같은 메소드를 사용함으로 로그래밸을 다운그레이드해야함.

log level down

---

nekoyume/Assets/_Scripts/Game/Lobby.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventRewardPopup.cs

이벤트가 없는 경우 이벤트 팝업을 띄우려 하지 않습니다

add has event property

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

- bump lib9c dev
- avoid compiler exception

Bump lib9c development

---

nekoyume/Packages/manifest.json
nekoyume/Packages/packages-lock.json

add cursor ide pakage

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/EventRewardBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/SeasonPassBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_LobbyMenu.prefab
nekoyume/Assets/_Scripts/UI/Model/EventRewardPopupData.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Widget/LobbyMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventRewardPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs

patrol reward popup 관련 프리팹 정리 pr입니다.

sweep patrol reward popup

---

.github/workflows/check-qa

이슈상태가 QA로 변경되면 이슈 어사인에 @Geonpyo999 님을 추가합니다.

이슈상태가 QA로 변경되면 어사인 추가 처리

---

.github/workflows/check-qa.yml

Run assign when projects card move QA column

---

.github/workflows/check-qa.yml

Fix column id

---

.github/workflows/check-qa.yml

disable schedule

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

- resolve #6580 
- https://github.com/planetarium/NineChronicles.Headless/pull/2677 와 함께 동작합니다.

stageTransaction 응답이 실패일 경우 에러 팝업 처리

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

Update gas price 1 * mead -> 0.00001 * mead

Update gas price

---

.github/workflows/9c-projects.yml

마일스톤 필드가 비어있을 경우에만 마일스톤 필드를 업데이트하도록 수정

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Synthesis.prefab

This pull request includes several changes to the `nekoyume/Assets/Resources/UI/Prefabs/UI_Synthesis.prefab` file, focusing on the `GameObject` and `RectTransform` components, as well as `PrefabInstance` properties. The most important changes include activating the `GameObject`, adjusting anchor and position properties in `RectTransform`, and modifying the `PrefabInstance` properties for better alignment.
Changes to `GameObject`:
* Activated the `GameObject` by setting `m_IsActive` to 1. [[1]](diffhunk://#diff-f2e83504eeaccb72886d1f12858b1bec363dc96e28d0693cdb46681ecb86aa86L22-R22) [[2]](diffhunk://#diff-f2e83504eeaccb72886d1f12858b1bec363dc96e28d0693cdb46681ecb86aa86L16468-R16468)
Changes to `RectTransform`:
* Adjusted `m_AnchorMin`, `m_AnchorMax`, `m_AnchoredPosition`, and `m_SizeDelta` …

코스튬 칭호 합성 탭 추가

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
nekoyume/Assets/_Scripts/UI/Widget/Workshop/Craft.cs

크레프트의 탭버튼 순서 변경하였습니다.
기존 : 스패셜 부터
변경 : 무기 부터

fix craft tab button order

---

nekoyume/Assets/_Scripts/ApiClient/ArenaServiceManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/Agent.cs
nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

이 PR은 Action Pipeline의 여러 부분을 개선하는 내용을 포함하고 있습니다. 주요 변경 사항은 다음과 같습니다:
1. **비동기 처리 추가**: `ProcessAction` 메서드에 `onTxIdReceived` 콜백을 추가하여, 트랜잭션 ID 수신 후 비동기적으로 처리할 수 있도록 개선했습니다. 이를 통해 아레나 서비스와의 통신이 더 원활해졌습니다.
2. **코드 정리**: 불필요한 주석 및 코드 중복을 제거하여 가독성을 높였습니다. 특히, `EnqueueAction` 메서드의 시그니처를 변경하여, 추가적인 콜백을 받을 수 있도록 했습니다.
3. **에러 처리 개선**: 아레나 서비스 요청 실패 시, 오류 로그를 남기고 메인 화면으로 돌아가는 로직을 추가하여 사용자 경험을 개선했습니다.

fix action pipeline

---

nekoyume/Assets/_Scripts/UI/Widget/Workshop/Summon.cs

코스튬 소환시 결과창에 아이템 정렬이안되는문제 수정하였습니다.

fix sort issue

---

nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs

어드벤쳐보스 진입불가시 월드맵에서 해더에 재화표시 정상적으로 되도록 수정.

fix HeaderMenuStatic to adventureboss

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

This pull request includes significant updates to the `ResponseStake` method in the `ActionRenderHandler` class, focusing on handling stake state and calculating rewards. The key changes involve initializing the previous stake state, updating the UI on the main thread, and calculating and displaying rewards based on the stake state.
* Added initialization of `nullablePrevStakeState` to keep track of the previous stake state before updating it.
* Ensured that UI updates occur on the main thread by adding `await UniTask.SwitchToMainThread()`.
* Implemented reward calculation logic based on the stake state, including determining reward steps and calculating both fixed and regular rewards.
* Added code to aggregate item rewards and create a list of `MailReward` objects to display the rewards …

add reward popup for reward

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

This pull request includes a change to the `SetView` method in the `StakingPopup` class to improve the logic for handling the edit button click event.
* [`nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs`](diffhunk://#diff-a70936507caa2abe09369bcc28e19289dbba0a92d9812a33bea641c5bacbdd48L380-R381): Modified the `OnClickEditButton` method to check if the `deposit` is zero and if the gold balance is less than 50 before displaying a system message.

fix monster collection issues

---

nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

add sort grind event

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerScroll.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerScroll.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonInfo.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

신규 아레나 추가 UI폴리싱작업.
- 아레나보드 셀간격, 동적크기 변경대응가능하도록 레이아웃 변경
- 아레나 보드 스크롤러 숨김처리
- 액션포인트 갱신안되는문제 수정
- 메달 아이콘 수정
- 상금 표기
- 상금 url 주소 버튼연결
- 메달 제한 표기

Feature/new arena service UI polishing

---

nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
nekoyume/Assets/UIResources/Atlas_image/Common/UI_Arena/Rank_bg_10.png.meta

fix ArenaBoardPlayerCell layout

---

.github/workflows/android-build-and-release-for-9ck.yml
.github/workflows/android-build-and-release.yml
.github/workflows/build.yml
.github/workflows/ios-build-and-release-for-9ck.yml
.github/workflows/ios-build-and-release.yml
nekoyume/Assets/_Scripts/Editor/ArenaJwtGenerator.cs
tools/pack/pack.py

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
artifact v3이 1월 30일부로 사용중단되어 마이그레이션 진행합니다.

artifactv3 to artifactv4 migrate

---

nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

refresh board notice popup

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

add courage reward icon in offseason

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab

아레나 보드창에 레이아웃 문제들 수정한 PR입니다.
- 클랜 랭킹확인만있을때 배경레이아웃 같이 줄도록 수정
- 보드 상단이 해더메뉴와 겹치는부분 수정
- 갱신버튼 왼쪽에 padding이 없는부분 수정.

fix arena board layout

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

exception handling get arena season

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

아레나 보드 요청시 응답대기시간동안 페이지를 나갔다 다시들어올수있어서 관련 예외처리 진행했습니다.

exception-handling-waiting-refresh-arena-board

---

nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs

remove unused CommandLineOptions

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs

arena-battle-result-score-exception-handle

---

nekoyume/Assets/_Scripts/ApiClient/GeneratedApi/ArenaServiceClient.cs
nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/ErrorCode.cs
nekoyume/Assets/_Scripts/Game/Battle/Arena.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonCell.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonCellChampionship.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs

시즌넘버 별개표시 작업 및 기타 예외처리진행
배틀토큰 폴링 예외처리 수정
아레나 라운드 종료시 예외처리(join 화면으로 이동하도록)
아레나 보드 현재 라운드 승리 패배 숫자 표현 변경

arena-season-number-exception-handle

---

nekoyume/Assets/Editor/OpenAPIGenerator.cs
nekoyume/Assets/_Scripts/ApiClient/ArenaServiceManager.cs
nekoyume/Assets/_Scripts/ApiClient/GeneratedApi/ArenaServiceClient.cs

url이 아예 세팅이 안되어있는경우 인스턴스자체가없어서 nre 문제가 날수있는 문제 수정.

exception handling service url is null

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

인터널 종료시 로비화면이 닫혀있지않아 베틀화면이 가려졌던 문제 수정.

fix arena round ending widget control

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

fix arena board font change

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ClanRankPopup.prefab
nekoyume/Assets/_Scripts/UI/Scroller/ClanRankCell.cs

fix default clan image

---

nekoyume/Assets/AddressableAssets/UI/Module/GrindModule.prefab
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

Reverts planetarium/NineChronicles#6845
과도한 연산이 일어나는 버그가 발생하여 revert. 290타겟으로 재 작업 예정

Revert "Feature/auto select grind"

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ClanRankPopup.prefab
nekoyume/Assets/_Scripts/UI/Scroller/ClanRankCell.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

clan-rankpopup-exception-handling

---

nekoyume/Assets/_Scripts/UI/Scroller/SelectPlanetScroll.cs

비활성화 Cell을 선택할시 조건에 따라 Select을 시켜서 활성화 Cell로 만들어 주거나, 접속불가 팝업을 띄워야하는데 바로 접속불가팝업을띄우는 문제 수정.

fix planet-select-diabled-error

---

nekoyume/Assets/Resources/UI/Animations/Sweep_Result.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab

fix sweep result popup

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs

fix food-metarial-short-cut

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ClanRankPopup.prefab
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

클랜이미지 갱신관련 문제 수정
다운로드전 빈이미지보이는문제 수정
동시에 같은 이미지 다운로드시 이미지 렌더링 실패하는 문제 수정.

fix arena-clan-image-download-issue

---

nekoyume/Assets/Plugins/StateViewer/Editor/Features/StateAndBalanceFeature.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPopup.cs
nekoyume/ProjectSettings/ProjectSettings.asset

Hotfix/280.1.0 to Main

---

nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
nekoyume/Assets/_Scripts/UI/Model/EventBannerData.cs
nekoyume/Assets/_Scripts/UI/Model/EventNoticeData.cs
nekoyume/Assets/_Scripts/UI/Module/EventNotice/EventView.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs

- IsMainnet 속성으로 네트워크별 공지 활성화 분기 처리를 추가합니다.
- WithSIgn 속성으로 필요할경우 9c address로 서명을 통한 정보를 링크에 추가합니다.

계정인증 처리 및 네트워크별 공지 분기 추가

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossBattlePopup.cs

누락된 l10n키를 추가합니다.
https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1740568049903289

add missed l10n

---

nekoyume/Assets/_Scripts/ApiClient/ArenaServiceManager.cs
nekoyume/Assets/_Scripts/ApiClient/GeneratedApi/ArenaServiceClient.cs
nekoyume/Assets/_Scripts/Game/Battle/Arena.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

1. Arena 인터페이스 변경
- Arena 관련 인터페이스 구조 개선
- Arena 참여 상태에 따른 로비 티켓 UI 표시 로직 수정

Fix/arena interface change lobby ticket UI

---

nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

set rank maintanance

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPopup.cs

fix arena-ticket-count

---

.github/workflows/ios-build-and-release-for-9ck.yml
.github/workflows/ios-build-and-release.yml

upgrade macos 13 -> 15 for xcode version upgrade

upgrade macos 13 -> 15 for xcode version upgrade

---

.github/workflows/auto-project-assign.yml

Add dev daily project when assigned dev

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionItemFilterPopup.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv

This pull request includes several changes to the `nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionItemFilterPopup.prefab` and `nekoyume/Assets/StreamingAssets/Localization/common.csv` files. The changes primarily focus on adding new UI elements, modifying existing UI properties, and updating localization strings.
UI modifications:
* Added a new toggle for grade 64 in `MonoBehaviour` section.
* Updated `RectTransform` to include a new file ID.
* Modified `PrefabInstance` properties to change anchor and position values.
* Added a new `PrefabInstance` with several modifications including anchor, position, and text properties.
Localization updates:
* Added a new localization entry for `UI_ITEM_GRADE_7` with translations in multiple languages.

add mythic filter

---

nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs

슬라이더 애니메이션이 중간에 끊킬경우 텍스트표기가 정상적으로 나오지않는 문제 수정.

fix ap text correct

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
nekoyume/Assets/_Scripts/ApiClient/ApiClients.cs
nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
nekoyume/Assets/_Scripts/Multiplanetary/PlanetInfo.cs
nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs
nekoyume/Assets/_Scripts/UI/Model/Rank.cs
nekoyume/Assets/_Scripts/UI/Model/RankingModel.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
nekoyume/nekoyume.sln.DotSettings

This pull request includes changes to the `UI_RankPopup` prefab and the addition of a new client for the Mimir service. The most important changes include modifications to the `UI_RankPopup` prefab's properties and the integration of the Mimir client into the API client system.
Changes to `UI_RankPopup` prefab:
* Updated the `m_IsActive` property to be inactive by default. [[1]](diffhunk://#diff-325d1f326b666537ee2175de0d3437a447c7ff3170661a2ea1098ad99f53ee27L5716-R5716) [[2]](diffhunk://#diff-325d1f326b666537ee2175de0d3437a447c7ff3170661a2ea1098ad99f53ee27L11794-R11794)
* Changed the `m_AnchorMax.y` and `m_AnchorMin.y` properties to 1 for various targets to adjust the UI anchoring. [[1]](diffhunk://#diff-325d1f326b666537ee2175de0d3437a447c7ff3170661a2ea1098ad99f53ee27L5741-R5741) …

add mimir rank

---

nekoyume/Assets/Plugins/iOS/OpenUrlPlugin.m
nekoyume/Assets/Plugins/iOS/OpenUrlPlugin.m.meta
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Game/Scene/LoginScene.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonInfo.cs
nekoyume/Assets/_Scripts/UI/Module/Button/OpenUrlButton.cs
nekoyume/Assets/_Scripts/UI/Module/Currency/Gold.cs
nekoyume/Assets/_Scripts/UI/Module/EventNotice/EventView.cs
nekoyume/Assets/_Scripts/UI/Module/ExternalWebsiteButton.cs
nekoyume/Assets/_Scripts/UI/Widget/ChainInfoItem.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ChatPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ConfirmConnectPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs

SSIA, help from https://discussions.unity.com/t/application-openurl-doesnt-work-on-ios-18/1553960/12

feat: add ios OpenURL plugin and change for all

---

nekoyume/Assets/_Scripts/UI/Model/Rank.cs
nekoyume/Assets/_Scripts/UI/Model/RankingModel.cs

- Nullable한 스키마들에 대한 핸들링 처리
- ArmorId만 사용하고 PortraitId 는 사용하지 않고 있는 상황이라 쿼리와 class 생성자에서 제거 처리

미미르 랭킹 오류 핸들링

---

nekoyume/Assets/Resources/AddressableAssetsContainer.asset
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/ProjectSettings/ProjectSettings.asset

합성관련 csv assets 누락 처리 & 버전 업데이트

---

nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs

비밀번호 재설정 기능 복구전까지 임시로 비밀번호 찾기 기능을 비활성화시켜둡니다

Disable find passphrase

---

nekoyume/Assets/_Scripts/Multiplanetary/PlanetContext.cs

오류정보를 찍으려다 발생하는 NullReferenceException으로 진행이 안되는 문제를 해결합니다.

모바일 로그인시 오류 수정

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SummonDetailPopup.cs

Set CP in rune detail popup

---

nekoyume/Assets/Resources/Recipe/EquipmentSubRecipeTab.json

chore: Add more recipe tab names

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/AvatarExtensions.cs
nekoyume/ProjectSettings/ProjectSettings.asset

코스튬 장착 갱신 버그 수정

---

nekoyume/Assets/Resources/Recipe/EquipmentSubRecipeTab.json

Add more recipe tab names

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab

Disable redeem code button

---

nekoyume/Assets/_Scripts/ApiClient/SeasonPassServiceManager.cs

Enhanced condition checks for premium season pass claims to ensure valid timestamps are considered.
1. First step.

Enhanced condition checks for premium season pass claims

---

nekoyume/Assets/Resources/Recipe/EquipmentSubRecipeTab.json

Add sub recipe tabs

---

nekoyume/Assets/AddressableAssetsData/AssetGroups/CharacterSpine.asset
nekoyume/Assets/_Scripts/L10n/L10nManager.cs

- #7124 에서 누락된 어드레서블에셋 설정
- 다이얼로그 번역시 원격업로드한 번역파일 지원

다이얼로그 번역에서 원격 csv파일도 확인하도록 처리

---

nekoyume/Assets/AddressableAssets/UI/Module/AdventureBoss/AdventureProgressFill.mat
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBoss.prefab

Increase adv boss floor

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBoss.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossBattlePopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossResultPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_AdventureBossRewardInfoPopup.prefab

Fix adv boss floor resources

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EventReleaseNotePopup.prefab
nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/UI/Model/EventBannerData.cs
nekoyume/Assets/_Scripts/UI/Model/EventNoticeData.cs
nekoyume/Assets/_Scripts/UI/Module/Button/CallbackButton.cs
nekoyume/Assets/_Scripts/UI/Module/Button/CallbackButton.cs.meta
nekoyume/Assets/_Scripts/UI/Module/EventNotice/EventView.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Workshop/Summon.cs

Implement ingame navigation banner

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/RuneTooltip.cs
nekoyume/Assets/_Scripts/UI/Widget/Workshop/Rune.cs

- RuneCostSheet 구조 변경으로 맥스레벨 계산방식 수정

Fix rune max level calculate

---

nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Model/ArenaParticipantModel.cs
nekoyume/Assets/_Scripts/UI/Model/RankingModel.cs
nekoyume/Assets/_Scripts/UI/Model/ShopEquipments.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardBillboard.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerCell.cs
nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardSO.cs

Use long type instead int

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

Refactor update state on ExploreAdeventureBoss

---

.github/workflows/ios-build-and-release.yml

Downgrade mac version 15 -> 14

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Game/Battle/Stage.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs

Fix invalid battle end dispose

---

nekoyume/Assets/_Scripts/ApiClient/ArenaServiceManager.cs
nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

Fix invalid cp on arena board

---

nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/NcuPopup.cs

- 배너 초기화시 이미지 다운로드가 끝날때까지 대기하지않아서 꼬이는 문제를 이미지 다운로드가 완료될때까지 대기하도록 처리합니다.

Fix banner initialize
