.github/workflows/pack.yml

This PR adjusts `.github/workflows/pack.yaml` to skip `pack` during PR.

Skipping pack on PR

---

nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeCellView.cs

@Namyujeong and @planetarium/nine-chronicles-engineers 
- Delete all `PlayerPrefs` and create new character.
- Proceed to stage 3.
- Enter equipment combination tutorial and unlock recipe.
- Stop the client.
- Reconnect to the created character.
- Re-enter to the equipment combination tutorial and check if the recipe selection is not skipped.

Fix bug in skipping recipe selection in tutorial.

---

tools/installer/installer.iss

- [런처 아이콘 제대로 나오도록 복구하기](https://app.asana.com/0/1199193534352239/1199574035843077/f)
@planetarium/9c-dev 중 1분 이상

Fix icon of installer

---

tools/Updater/Updater/Program.cs

This PR updates the snapshot download path to the latest. (it's a temporary fix and it will be removed by #42 😅)

Update snapshot download path

---

.github/bin/check-libplanet-version.sh
.github/workflows/build.yml

The `check-libplanet-version` step faileds in some pull requests. And the log is like below:
```
fatal: not a git repository: '.github/bin/../../nekoyume/Assets/_Scripts/Lib9c/Lib9c/.Libplanet/.git'
Libplanet was updated at .
Libplanet.RocksDBStore.dll seems outdated (2021-03-08 18:05:57 +0900).
Libplanet.Stun.dll seems outdated (2021-03-08 18:05:57 +0900).
Libplanet.dll seems outdated (2021-03-08 18:05:57 +0900).
```
The log said there is no `.Libplanet` and `Build` workflow didn't checkout submodules recursively. And the path `Lib9c` was incorrect also so this pull request fixed them.
After this pull request...
```
Libplanet was updated at 2021-02-17 13:19:16 +0900.
Libplanet.RocksDBStore.dll seems up-to-date (2021-03-17 14:43:51 +0900).
Libplanet.Stun.dll seems up-to-date (2021-03-17 …
```

ci(gh-actions): checkout submodule recursively

---

tools/installer/installer.iss

This PR divides the installation events for Mixpanel tracking to assess potential drop-offs.
Mixpanel events will be sent for the following Wizard page events sequentially:
**1. Select Directory**
**2. Select Tasks**
**3. Ready**
**4. Installing**
**5. Finished**
Also, I've set up an [Installation Detailed Report](https://mixpanel.com/s/3k0FCn) on Mixpanel.

divide installation events for mixpanel tracking

---

tools/installer/installer.iss

It has come to attention that the `Mixpanel UUID` value might not be consistent during the installation process and that this is the reason why install conversion rates on Mixpanel appear to be low. This PR minimizes the `UseUUID()` function call to reduce the possibility of inconsistent UUID values.

minimize UUID function call

---

nekoyume/Assets/_Scripts/Game/ScriptableObject/ItemViewDataScriptableObject.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs

1. Prevent NRE on displaying dummy data equipment (10100000, 10200000) and equipment that its grade is outside bound of the background data.
1. Launch game on editor mode.
2. Open inventory and check if NRE is not occurring.
@Namyujeong and @planetarium/9c-dev

Apply fallback background data of Item's grade on ItemView.

---

nekoyume/Assets/_Scripts/UI/Mail.cs

SSIA
-[ [마켓] 2개 이상의 모래시계, AP 포션 판매 취소 시 우편함에서 획득되는 아이템 수량이 1로 노출되는 현상](https://app.asana.com/0/1133453747809944/1200363092960895/f)

Add quantity to sell cancellation mail

---

nekoyume/Assets/_Scripts/UI/RankingBoard.cs

1. Make arena cached info updated on `Show()` in `RankingBoard`.
1. Open `RankingBoard` and do some battle action. (ex. `HackAndSlash`, `RankingBattle`, `MimisbrunnrBattle`)
2. Check if the current player's arena info is correctly match with scroll and bottom cell.

Make arena cached info updated on `Show()` in `RankingBoard`.

---

nekoyume/Assets/_Scripts/State/States.cs

- Fixed the avatar state to be updated when entering the lobby with another character.
- [[몬스터콜렉션] 캐릭터 2개 이상 보유 중일 경우 몬스터콜렉션 보상이 획득되지 않는 현상](https://app.asana.com/0/1133453747809944/1200413250524054/f)
- @planetarium/9c-dev , @Namyujeong

Update avatar state when entering the lobby

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/State/Subjects/GameConfigStateSubject.cs
nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs

1. Fixed unrender(render) to work only when the action avatar address and the current avatar address are the same
2. Bind Action Point Status by Avatar
- [[캐릭터] 번영도 사용으로 행동력 충전 타이밍에 캐릭터 교체 시 캐릭터가 복제 되는 현상](https://app.asana.com/0/1133453747809944/1200433573439997/f)
- https://github.com/planetarium/NineChronicles/issues/234

Fixed issue with dailyReward action

---

tools/installer/installer.iss

This is a debug version for installer. We've learned that the installer has been creating new UUID's each time `UseUUID()` is called. Therefore, I've made the UUID variable to a global variable and the `UseUUID()` function is called just once during the `InitializeSetup` stage.

introduce debug version for installer

---

nekoyume/Assets/_Scripts/UI/CelebratesPopup.cs

Set the translation key appropriate for the menu name in the new menu opening celebration window.
새 메뉴 오픈될때, 25렙때 아레나 열렸다고 해야되는데 랭킹으로 보이고 있어서, 메인화면에서 쓰는 레이블 그대로 가져왔습니다.
Just check the file changes

fix celebrate popup localization

---

nekoyume/Assets/_Scripts/UI/Rank.cs

1. SSIA
1. Add error message in error situation on loading ranking.
1. To check if UI blocking is fixed, go to Rank.cs and add this line like this. (line 58)
`await Task.Delay(100000);`
```cs
return Task.Run(async () =>
{
var sw = new Stopwatch();
sw.Start();
await Task.Delay(100000);
LoadAbilityRankingInfos(displayCount);
await Task.WhenAll(
LoadStageRankingInfos(apiClient, displayCount),
LoadMimisbrunnrRankingInfos(apiClient, displayCount)
);
IsInitialized = true;
sw.Stop();
UnityEngine.Debug.LogWarning($"total elapsed : {sw.Elapsed}");
});
```
Then, ranking will be loaded after 100 seconds(100000 ms).
You can adjust the delay by changing the integer value.
1. Start game and go to ranking before the delay is over.
1. Check if clicking equipment ranking tab doesn't block UI anymore.
1. …

Fix UI blocking on loading ranking information.

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopSell.cs

Update shop sell state whenever `sell` and `sellCancellation` actions are called in Render and Unrender
- sell item
- [[마켓] 코스튬 판매 등록 하였는데 장착중인 장비 UI에 그대로 남아있는 현상](https://app.asana.com/0/1133453747809944/1200564162338390/f)
- [(일정추적용) 판매&판매취소만 랜더,언랜더에서 쪽 갱신 될 때마다 판매 매대를 업데이트되게 수정](https://app.asana.com/0/958521740385861/1200569616769910/f)
@Namyujeong, @plafina2 , @planetarium/9c-dev

Refresh shop sell

---

nekoyume/Assets/Resources/UI/Prefabs/UI_LoginPopup.prefab

In the previous LoginPopup-CreateAccount UI, the size of the password text entered and the size of the reconfirmation text were different, which made it uncomfortable.
1. Check that the password text entered in the CreateAccount UI and the reconfirm text are the same size.
__Before__
__After__

Improve text size in login popup - CreateAccount

---

nekoyume/Assets/_Scripts/UI/StageProgressBar.cs

1. Sometimes, `StageProgressBarVfx` was freeze.
2. When `Time.timeScale` was larger than normal size, vfx did not seem to catch up with `offset`'s position.
3. Now, vfx follow the position of the offset unconditionally regardless of `Time.timeScale`.
1. Increase the time.timeScale.
2. Play any stage
3. Check vfx in StageProgressBar
[[UI] 스테이지 달성도 바 이펙트 포인터가 중간에 멈춰 있는 현상](https://app.asana.com/0/1141562434100787/1200344973096674/f)

Fix stage progress bar vfx freezing

---

nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlots.cs

1. In the past, if there were not enough slots to equip the ring on, the first ring was detached.
2. Now, If there is a lack of slots when mounting the ring, the ring with a lower CP will be de-equipped.
1. Equip a ring in second slot that has lower CP than a ring in first slot.
2. Wear any ring and check if the ring in the second slot has been replaced.
@planetarium/9c-dev @Namyujeong 
[반지 갈아 낄 때 슬롯 두 개 중 낮은 CP 쪽을 갈아 끼도록](https://app.asana.com/0/1141562434100787/1199226930849869/f)

Improve de-equip ring system

---

nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResult.prefab
nekoyume/Assets/Resources/VFX/Prefabs/BattleWin01VFX.prefab
nekoyume/Assets/Resources/VFX/Prefabs/BattleWin02VFX.prefab
nekoyume/Assets/_Scripts/Game/VFX/VFX.cs

1. In the past, VFX of battle result are rendered above the Help UI.
2. Fixed VFX.cs, add bool field `isLayerInitializedWithChild`. Default value is `true`.
3. If that is false, initialize children particle systems like root particle system.
1. Eneter any stage
2. Open help Popup in Battle result UI
3. Check above the Help UI
[[UI] 스테이지 결과 UI 의 도움말 팝업에서 별 이펙트가 노출되는 현상](https://app.asana.com/0/1141562434100787/1197211236908617/f)
before
after

Fix abnormal VFX position bugs

---

nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/AvatarInfo.cs
nekoyume/Assets/_Scripts/UI/BattleResult.cs
nekoyume/Assets/_Scripts/UI/CombinationMain.cs
nekoyume/Assets/_Scripts/UI/CombinationSlots.cs
nekoyume/Assets/_Scripts/UI/Craft.cs
nekoyume/Assets/_Scripts/UI/Login.cs
nekoyume/Assets/_Scripts/UI/Mail.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/Module/ItemInformation.cs
nekoyume/Assets/_Scripts/UI/Module/Stat/StatView.cs
nekoyume/Assets/_Scripts/UI/Quest.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs
nekoyume/Assets/_Scripts/UI/RankingBoard.cs
nekoyume/Assets/_Scripts/UI/Settings.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/StageInformation.cs
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Tween/TransformLocalScaleTweener.cs
nekoyume/Assets/_Scripts/UI/UpgradeEquipment.cs
nekoyume/Assets/_Scripts/UI/WorldMap.cs

1. Restore and fix bug in `HelpPopup`.
2. Add `+` mark on additional option.
1. Check if help popup of first entrance is working properly.
2. Check if `+` mark is added on additional option in item description popup.

Restore and fix bug in `HelpPopup`, add `+` mark on additional option.

---

nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs

SSIA
- Play Action (MimisbrunnrBattle , HackAndSlash)
- [[전투 준비 화면] 전투 준비화면에서 Start 버튼은 연속적으로 클릭할 시 AP가 사라짐](https://app.asana.com/0/1133453747809944/1200719401875914/f)

Fixed battle start button to be clickable only once

---

nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
nekoyume/Assets/_Scripts/UI/Widget.cs

1. Sometimes, position of HUD is abnormal.
2. and Enter any stage - enter lobby - enter menu 'character' - unequip title - equip title, player can not show character title when follow this step.
3. and Somtimes player don't show character title. no.2 is some example.
1. `DisableHUD()` (in CharacterBase.cs) did disable/destroy if `HPBar` has enabled. Now, if HudContainer is enable it destroy that.
2. `HUDWidget` is not target of Object pooling. It causes bugs.
3. Do not call `DisableHUD()` in `RoomEntering.cs`. This is a useless method call and causes the problem of not displaying HUD.
1. Enter any stage.
2. Check HP bar's position. (issue no.1)
3. Enter lobby, check character's title. (issue no.2)
[전투 진행 시 첫번째 몹의 HP바 대신 플레이어의 HP가 표시되는 …

Fix HUD bugs

---

nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlots.cs

1. Preblem : If enter mimis brunnr preparation UI with one or more of the two rings are not fire type, you can change ring only first slot.
2. Now, you try to equip a ring in mimis brunnr preparation, it will use new getting slot pipeline.
1. Equip rings, one or more of the two should not be a fire type.
2. Enter mimis brunnr preparation UI.
3. Check can change rings normally.
[[미미르의 샘] 반지 두개를 모두 장착한 채로 진입시 준비 UI에서 첫번째 반지만 교체되어 진입 불가](https://app.asana.com/0/1141562434100787/1200727618925461/f)

Fix changing ring bug in MimisBrunnr Preparation

---

nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/ItemInformationTooltip.cs

SSIA
1. Check if item information tooltip's position is right on first open.
2. Check if there's no elemental icon on `SubRecipeView`'s item name.
https://app.asana.com/0/958521740385861/1200676985132223
https://app.asana.com/0/958521740385861/1200799644540996

Fix bug in item information tooltip position.

---

nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/QuestPreparation.cs

SSIA
1. Play any stage.
2. Reduce action points to the extent that you cannot enter the quest.
[[전투 준비] 행동력이 부족할 때 버튼 클릭시 행동력 부족 안내가 나오지 않음](https://app.asana.com/0/1141562434100787/1200904787622242/f)
before
after

Fix issue that can not interact to quest button when action point is insufficient

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/AvatarInfo.cs

SSIA
1. Use AP-potion
[[UI] AP포션 사용하면 행동력 바에 번영도 클릭 충전시와 동일하게 로딩서클 그려주기](https://app.asana.com/0/958521740385861/1200888226950630/f)

Add loading circle when use ap potion

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/RankingBoard.cs

1. Check rendered information of `HackAndSlash`, `MimisbrunnrBattle` and `RankingBattle` for render correct battle results.
2. Fix minor bug of `RankingBoard` UI
1. [[전투 랜더] HAS, 미미르의샘 로딩 중에 정확히 기다리고 있는 전투의 랜더만 동작시키기](https://app.asana.com/0/1141562434100787/1200814851909847/f)
2. [HAS Repeat 사용할 때 다른 아바타의 전투 스테이지 기록이 그대로 사용되어 전투하는 경우](https://app.asana.com/0/1141562434100787/1200867409730006/f)

Bug fix/render correct battle

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattleLoadingScreen.prefab
nekoyume/Assets/_Scripts/UI/Battle.cs
nekoyume/Assets/_Scripts/UI/HeaderMenu.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/RankingBoard.cs
nekoyume/Assets/_Scripts/UI/Widget.cs

1. [아레나 전투 로딩 화면 이미지 깨짐](https://app.asana.com/0/1141562434100787/1200887083113949/f)
2. [아레나 보드에서 상단메뉴 뜨고, 전투에서는 상단메뉴 안떠야 하는데 반대로 동작함](https://app.asana.com/0/1141562434100787/1200888226950609/f)

Fix `UI_ArenaBattleLoadingScreen` prefab

---

nekoyume/Assets/_Scripts/UI/CombinationSlots.cs
nekoyume/Assets/_Scripts/UI/Module/EquipmentInventory.cs

- Fixed to keep filtering even after upgrade item
- Change the timing of calling the blur.show()
[[development] 필터링 건 후 강화하면 인벤토리 필터가 자동으로 풀림](https://app.asana.com/0/1133453747809944/1200978734286987/f)
[[development] 강화 쪽에서 지속적으로 Coroutine 에러 잡힘](https://app.asana.com/0/1133453747809944/1200978734287003/f)

Bugfix for v100078

---

nekoyume/Assets/_Scripts/UI/Combination.cs
nekoyume/Assets/_Scripts/UI/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget.cs

1. Change type of `Widget.AnimationState` to `ReactiveProperty`.
2. Subscribe AnimationState, Can interact to `Selectable` objects when AnimationState equals `AnimationStateType.Shown`.
[UI 위젯 연출 주기 상 Shown일 때에만 버튼이 눌리게 하기](https://app.asana.com/0/1141562434100787/1172671756968572/f)
before
after

Improve to be interact only when the `AnimationState` was 'Shown'.

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs

Key : `Unity/HackAndSlash`
Prop : `WorldId`, `StageId`, `PlayCount`
[믹스패널 붙이기](https://app.asana.com/0/958521740385861/1201063060219329/f)

Add booster-related mixpanel prop

---

nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

Bug fix/nre occured in combination slots

---

nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs

SSIA
1. Try any action in shop with `backspace`.
[[마켓] 마켓 - 검색 입력 중 백스페이스 입력할 경우 메인로비 상단 UI가 노출되는 현상](https://app.asana.com/0/1133453747809944/1201392367298205/f)
[[마켓] 다중 구매중 마켓 뒤로가기 버튼을 클릭할 경우 메인 UI를 불러오게 되어 마켓에 갇히는 현상](https://app.asana.com/0/1133453747809944/1201392367298199/f)

Fix issue that exiting to lobby with backspace in shop 

---

nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs

- Improve entering to combination UI by header menu.
- If enter to combination UI in header menu, close other widgets.
1. Enter to combination UI in other UI.
2. Exit combination UI.
3. Check your screen and UI.
[[UI] 월드맵 씬에서 워크샵 슬롯으로 공방 진입 뒤 뒤로가기 버튼을 연타하여 다른 메뉴로 복귀할 경우 메인 로비 UI가 노출되는 현상](https://app.asana.com/0/1133453747809944/1201425663841552/f)
[특정 스텝을 통해 제작/강화를 시도하면 npc가 겹쳐보임](https://app.asana.com/0/1141562434100787/1201456475650182/f)

Fix bugs about combination UI in header menu

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs

There is no separate animation that turns off in the battle UI, but it simply turns off after a certain period of time.
As a result, there was a problem that the UI overlapped, so the animation was ignored.
1. Enter to any stage.
2. Back to main lobby.
3. Fastly click worldmap or mimis brunnr.
[[UI] 스테이지(월드맵, 미미르) 씬 진입 시 UI가 깨지는 현상](https://app.asana.com/0/1133453747809944/1201398508893244/f)

Ignore closing animation of battle UI when go to main lobby

---

nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs

1. SSIA
2. To prevent overlapping cameras, they were asked to recycle them when lobby cameras were not used.
1. Enter to preparation UI any stage.
2. Try to check other player character in rank board.
[[랭킹] 전투 준비 화면에서 랭킹 상세 정보 팝업 출력 시 다른 유저의 캐릭터와 플레이어의 캐릭터가 겹쳐서 노출되는 현상](https://app.asana.com/0/1133453747809944/1201425497955028/f)

Fix overlapping spine in FriendInfoPopup

---

nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

SSIA
1. Check character spine in `FriendInfoPopup` in selecting world/stage UI.
[[랭킹] 전투 준비 화면에서 랭킹 상세 정보 팝업 출력 시 다른 유저의 캐릭터와 플레이어의 캐릭터가 겹쳐서 노출되는 현상](https://app.asana.com/0/1133453747809944/1201425497955028/f)

Fix overlapping character spine

---

nekoyume/Assets/_Scripts/State/States.cs

- Fix SetCombinationSlotStatesAsync() to be called whenever an avatar is selected
[[공방] 제작, 강화가 작동하지 않는 현상](https://app.asana.com/0/1133453747809944/1201540375240617/f)

Fix SetCombinationSlotStatesAsync() to be called whenever an avatar is selected

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs

1. In the past, has an issue about can not enter to workshop by header menu after arena battle.
2. So, add invoking `OnRoomEnter` in closing arena result popup for `IsInStage = false;`
1. Do ranking battle.
2. Try enter to workshop by header menu.
[[아레나] 아레나 전투 진행 후 워크샵 슬롯을 이용하여 공방 이동 시도 시 전투 중이라는 문구가 출력됨](https://app.asana.com/0/1133453747809944/1201530071102752/f)

Fix an issue about can not enter to workshop by header menu after arena battle

---

nekoyume/Assets/_Scripts/UI/Widget/QuestPreparation.cs

SSIA
1. Enter to preparation UI of any stage.
2. Try to click start button.
[[UI] 전투 준비에서 스타트 버튼 누르면 텍스트가 회색으로 변함](https://app.asana.com/0/1141562434100787/1201617172433215/f)

Fix an issue about color of quest button changing

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/SpineEditor.cs

SSIA
1. Throw any exception in `CreateSpinePrefabInternal` and try using it.
https://app.asana.com/0/958521740385861/1201200786778979

Show alert on exception thrown while creating spine prefab.

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs

1. Even after the battle of Arena, there was a problem that the battle was not over. #1104 
2. As a result of fixing the problem, there was a problem that the UI of the Arena and the main lobby overlapped.
3. I fixed that.
1. Try to any battle in arena
[(에디터에서 발생) 아레나 전투 시 간헐적으로 메인화면에서 전투함.](https://app.asana.com/0/1141562434100787/1201623508971434/f)

Fix a bug about overlapping UI by arena exitting

---

.gitmodules

1. Github removed supporting for all DSA keys.
2. So, We change url of submodules.
1. Check CI : lib9c build

Fix CI about submodules url

---

nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs

Fix to be modified only when it matches the current avatar state
[[행동력] 행동력 리필 후 전투 진입 시도 시 행동력이 부족한 상태로 보임](https://app.asana.com/0/1133453747809944/1200937999314478/f)

Fix to be modified only when it matches the current avatar state

---

nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Sub.prefab
nekoyume/Assets/_Scripts/UI/Tween/MaskedRectTransformXRoller.cs

1. Fixed issue about didn't pause when `isInfiniteScroll` is false.
2. Fixed start position bug when `isInfiniteScroll` is true.
[텍스트 롤러가 의도와 다르게 동작함](https://app.asana.com/0/1141562434100787/1201643214366283/f)
@planetarium/9c-dev @Namyujeong @BBeom06

Improve `MaskedRectTransformXRoller`

---

nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

1. SSIA
1. Make new genesis block.
2. Set `GameConfig.IsEditor` to false.
3. Try to enter to synopsis.
[제네시스 새로 찍고 시놉시스를 넘어갈 수 없음](https://app.asana.com/0/1141562434100787/1201684868189284/f)
@planetarium/9c-dev @ipdae @area363

Fix not closed loading screen in synopsis of new user

---

.github/workflows/build.yml

Currently, the failed step `Build for macOS on version 2020.3.4f1` seems successful with green light though its *macOS* builds were failed. It occurred because [`actions/upload-artifact`](https://github.com/actions/upload-artifact) action doesn't throw error. The action has `if-no-files-found` input and its default value is `warn` so it didn't throw an error but outputs as `warn` level.
So I think it can make people look illusion that the build for macOS was succeeded! Of course, it doesn't. I suggest making it fail when there are no files.
Compare workflows' steps:
- Before this pull request: https://github.com/planetarium/NineChronicles/runs/4892388956?check_suite_focus=true 
- After this pull request: https://github.com/planetarium/NineChronicles/runs/4904160441?check_suite_focus=true …

ci(gh-actions): fail step when failed to upload artifact

---

.github/workflows/build-misc.yml
nekoyume/Assets/Editor/Builder.cs
nekoyume/Assets/Editor/SpineSettings.asset
nekoyume/Assets/Packages/runtimes/linux-x64/native/librocksdb.so.meta
nekoyume/Assets/Packages/runtimes/linux-x64/native/libsecp256k1.so.meta
nekoyume/Assets/Packages/runtimes/osx-arm64/native/libgflags.2.2.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-arm64/native/liblz4.1.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-arm64/native/librocksdb.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-arm64/native/libsnappy.1.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-arm64/native/libzstd.1.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-x64/native/libgflags.2.2.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-x64/native/liblz4.1.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-x64/native/librocksdb.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-x64/native/libsecp256k1.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-x64/native/libsnappy.1.dylib.meta
nekoyume/Assets/Packages/runtimes/osx-x64/native/libzstd.1.dylib.meta
nekoyume/Assets/Packages/runtimes/win-x64/native/rocksdb.dll.meta
nekoyume/Assets/Packages/runtimes/win-x64/native/secp256k1.dll.meta
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Worldmap.spriteatlas

This fixes several build errors during plugins (_lib\*.dylib_ binaries) on macOS:
It caused because there are pairs of the same libraries for both Intel (_osx-x64_) and Apple Silicon (_osx-arm64_).  I explicitly specified the architecture for Intel binaries (⬅️ _left_), and temporarily excluded Apple Silicon binaries (_right_ ➡️):
I also added a build method for Apple Silicon, but it's commented out as of now.  We would be possible to re-enable the build method when we upgrade the Unity Editor to a recent version.

Fix macOS build

---

nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs

SSIA
1. Fix `EquipmentItemRecipeSheet.csv`, change `unlock_stage` value to 999.
2. Enter to game-Craft UI.
3. Click changed recipe.
[레시피 해금 999일 경우 UI에서 그리지 않기](https://app.asana.com/0/958521740385861/1201819934871252/f)

Remove stage requirement label in recipe when requirement stage is 999

---

nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
nekoyume/Assets/_Scripts/UI/Widget/MimisbrunnrPreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs

1. Fix banner that doesn't work.
2. Fix max boost count in mimis brunnr. (6 to 12)
3. Add missing Block syncing message.
1. Try to click event banner.
2. Try to mimis brunnr battle with booster.
[[UI] 로비 베너가 작동하지 않습니다.](https://app.asana.com/0/1133453747809944/1201824497981370/f)
[[전투] 미미르의 샘 Booster 전투 시 MaxAP 사용량이 월드 스테이지와 다르게 60AP로 설정되어 있는 현상](https://app.asana.com/0/1133453747809944/1201797611190199/f)
[블록 싱크 텍스트가 나오지 않음](https://app.asana.com/0/1141562434100787/1201856647592880/f)

Fix minor bugs about UI

---

nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs

- In previous PR(https://github.com/planetarium/NineChronicles/pull/1236), To Check the tutorial was completed, I edited `GetCheckPoint()` method public from private. But that change was Dangerous.
So I Fixed it to make a new property to check `GetCheckPoint()` and `IsPlaying` internally.
- Fix the blur in NoticePopup, Because Blur's contents from `development` and `previewnet` branches are different.
Detail Description : [튜토리얼 진행 여부 안전하게 확인하기](https://app.asana.com/0/958521740385861/1201959332771026/f)
https://github.com/planetarium/NineChronicles/pull/1236#discussion_r825542225

Check tutorial is complete safely

---

tools/installer/installer.iss

1. Current uninstaller doesn't remove files at `%APPDATA%\Nine Chronicles` which has configuration and snapshot caches.
2. This PR removes them when running an uninstaller.
1. Install Nine Chronicles using the newly built installer.
2. Launch the launcher at least once.
3. Try to uninstall.
4. Check if `%APPDATA%\Nine Chronicles` is gone.
* https://jrsoftware.org/ishelp/topic_uninstalldeletesection.htm

Remove settings folder at uninstall

---

nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

1. There was a problem that the header HUD was turned off when the backspace key was pressed on any screen.
1. In Any screen, Input `backspace`.
2. Check header HUD.
https://planetariumhq.slack.com/archives/CBU2JFAF3/p1647927892387849
https://discord.com/channels/539405872346955788/653951482395361301/955719466619121684

Override CanHandleInputEvent to false in HeaderMenuStatic

---

nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs

1. change locking requirement to stage cleared id from avatar level
1. Check Shop acquisition place button when stage cleared id is 20-21.
2. Check Arena acquisition place button when stage cleared id is 24-25.
[[Previewnet] 아레나가 개방이 되었음에도 획득처 화면 내 획득 경로 이동 버튼이 잠긴 상태로 노출되는 현상](https://app.asana.com/0/1133453747809944/1202023403019987/f)

Fix locking logic about acquisition place button

---

nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs

Go to the shop. And then check purchase page index per block
[[Previewnet] 상점 페이지가 자동으로 1페이지로 돌아가는 현상](https://app.asana.com/0/1133453747809944/1202077560125799/f)

Fix not to update the purchase page per block

---

.github/workflows/release.yaml

Besides _v\*_ tag pushes, now every push to _rc-v\*_ branches also trigger Submodule Updater.
Note that this patch is almost equivalent to <https://github.com/planetarium/lib9c/pull/920> & <https://github.com/planetarium/NineChronicles.Headless/pull/1178>.

Trigger Submodule Updater on every push to rc-v* branches

---

nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs

1. Fixed bug on caching fullcostume tooltip.
1. Go to shop and try to view costume tooltip.
2. Check if it's appearing.
https://app.asana.com/0/1133453747809944/1202098904856159/f

Remove filtering inventory on caching skeleton objects.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab

- Add button component droped at https://github.com/planetarium/NineChronicles/commit/cbdafc8647d8432ad289cf2ef898d3d6bee3e90b
[[로딩 페이지] 상점과 아레나 로딩 씬 중 화면 터치 시 랜덤 도움말 텍스트가 작동하지 않는 현상](https://app.asana.com/0/1133453747809944/1202098904856167/f)

Fix data loading screen

---

nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs

1. Fix `RankingBoard.UpdateWeeklyCache`
1. First step.

Fix RankingBoard infinity loading

---

nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs

- Fix shop page refresh logic
- Create  `_removedOrderIds` list for refresh logic
go to the store. and click on a category
[상점 페이지가 자동으로 1페이지로 돌아가는 현상](https://app.asana.com/0/1141562434100787/1202077560125799/f)

Fix shop page refresh logic

---

nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs

- Edit to unify difference key names
- Other key was not deleted
[AP가 부족할 때 부스터 버튼과 스타트 버튼을 눌렀을 때 나오는 메시지가 다릅니다.](https://app.asana.com/0/1141562434100787/1201890796390902/f)

Fix different alert message

---

nekoyume/Assets/_Scripts/Game/Character/Player.cs
nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs

1. SSIA
1. Go to arena.
2. Try to open any player's avatar information and click on another one before previous one opens.
3. Check if character is not overlapping.
https://app.asana.com/0/1133453747809944/1201690393623287

Prevent avatar overlapping on displaying `FriendInfoPopup`.

---

nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab

In UI coordinate system, we requires the use of the Rect Mask 2D component.
overlap the item information tooltip and event banner
[[UI] 10강 이상 장비 툴팁 상단 이펙트 일부가 깨져있는 현상](https://app.asana.com/0/1133453747809944/1202114534196917/f)
@planetarium/9c-dev , @BBeom06

change event banner mask

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/CompileHelper.cs
nekoyume/Assets/Planetarium/Nekoyume/Editor/CompileHelper.cs.meta

> you: "How can I fix this?"
> me: "Just follow me."😁

Introduce CompileHelper

---

nekoyume/Assets/_Scripts/Editor.meta
nekoyume/Assets/_Scripts/Editor/ShowOnAttribute.cs
nekoyume/Assets/_Scripts/Editor/ShowOnAttribute.cs.meta
nekoyume/Assets/_Scripts/Editor/ShowOnAttributeDrawer.cs
nekoyume/Assets/_Scripts/Editor/ShowOnAttributeDrawer.cs.meta
nekoyume/Assets/_Scripts/Game/Util/PositionConstraints/Editor/PositionConstraintToScreenEditor.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs

1. Introduce new editor attribute which controls visibility of property in inspector.
```csharp
[SerializeField]
private bool handleTouchEvent = true;
#if UNITY_EDITOR
[ShowOn(nameof(handleTouchEvent), ShowOnAttribute.PropertyDrawOption.Disable)]
#endif
public TouchHandler touchHandler;
```
Also, you can hide a property completely.
```csharp
[ShowOn(nameof(handleTouchEvent), ShowOnAttribute.PropertyDrawOption.Hide)]
```
@boscohyun @hskim881028 @sonohoshi

Introduce `ShowOnAttribute`.

---

nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs

- Apply updated Sweep action 
- before : It can't sweep on challenging stage.
- after : It support sweep on challenging stage. 
without Yggdgrasil(1st world) and 1st stage
[스윕 개선 2차 UI 적용](https://app.asana.com/0/958521740385861/1202305628351985/f)

Support challenge stage sweep

---

.github/workflows/build.yml

1. Publish Unity Player on also 2022q2 branch.
1. Check whether the Unity player is published or not.

Publish Unity Player on also 2022q2 branch

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs

- `async void` -> `async UniTask` or `async UniTaskVoid`
- `async Task` -> `async UniTask`
- `async Tack<T>` -> `async UniTask<T>`
- Invoke `UniTask.Forget()` extension function when a async function which is not await.
- Rename async functions which suffix is not contains `Async`.
- Minor cleanup related to `CreateAvatar` action.
- Cover the failure case of `CreateAvatar` action in `LoginDetail` UI.

Clean up some of login logics

---

.github/bin/inject-mixpanel-client-data.sh
.github/workflows/build.yml
nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs

We need to identify which network the client is targeting through the analyzer event.
- `MixpanelValueFactory` contains `target-network` value ref the `MixpanelTargetNetwork.txt` file.
- `inject-mixpanel-client-data.sh` make the `MixpanelTargetNetwork.txt` file on the unity project.
- Make `target_network` value when the GitHub action progress `build > inject mixpanel client data` step.
This pull request needs kind reviews because I'm beginner like these CI jobs.

Add new event value to Analyzer

---

nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs

1. Implement skipping prologue with certain registry value.
[skipsynopsis.txt](https://github.com/planetarium/NineChronicles/files/8859982/skipsynopsis.txt)
1. Download this file and change extension to `.reg` and open it.
3. Check if newly created account can skip prologue.

Skip prologue with certain registry value.

---

nekoyume/Assets/_Scripts/Extension/BigIntegerExtensions.cs
nekoyume/Assets/_Scripts/Extension/BigIntegerExtensions.cs.meta
nekoyume/Assets/_Scripts/Extension/FungibleAssetValueExtensions.cs
nekoyume/Assets/_Scripts/Extension/FungibleAssetValueExtensions.cs.meta
nekoyume/Assets/_Scripts/UI/Module/Crystal.cs

1. I made extension method of `BigInteger` and `FungibleAssetValue`.
2. It makes currency fixed string from number. It not surpports `1K`, `1M`, `1B`.
3. Apply to Crystal.
[헤더 재화 자릿수 줄임 기능 개발](https://app.asana.com/0/958521740385861/1202524314445279/f)

Introcude `ToCurrencyNotation` extension method

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs

- Fixed the skill name to be displayed correctly
- Upgrade items with skill options
[[공방] 마나링(바람)의 스킬레이블이 깨지는 현상](https://app.asana.com/0/1133453747809944/1202517192622620/f)

Fixed the skill name to be displayed correctly

---

.github/workflows/activate-unity.yaml

It's needed for configuring CI build for newer Unity versions

New workflow to request Unity license activation files

---

.github/workflows/activate-unity.yaml

Continued from <https://github.com/planetarium/NineChronicles/pull/1701>.
It was typo.

Fix missing `inputs` on `workflow_dispatch`

---

nekoyume/Assets/Resources/UI/Animations/UIBattleResultController@Show.anim
nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs

- If the player didn't clear the HAS stage, 
- Stage button will be appear in battle result popup.
Stage button : move to Battle Preparation widget on same stage.
- Disable automatic stage- process, repetition, return.
except - reserved exit, ap not enough
- If the player has consumables, set inventory default tab to consumable tab in HAS Preparation.
\+ **apply this feature also to the Mimisbrunnr stage**
[스테이지 1회성 버프 개선 - 게임 결과 화면 고도화](https://app.asana.com/0/0/1202603085251653/f)
Failed in HAS
Failed in Mimisbrunnr

Improve battle result popup

---

nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

- Edit equipment sorting in inventory
- Default : Best item > item sub type (weapon, armer...) > usable (requirement level) > CP (descending)
- Grinding : Revert to Default
[인벤토리&제작 그라인딩 정렬순서 조정](https://app.asana.com/0/0/1202656030952478/f)
Default inventory
Grinding Inventory

Edit equipment sorting in inventory

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs

- Fix arena avatar state sync bug
1. After equipping the equipments or costumes in the arena preperaion, play Arena Battle.
2. Register equipped equipments or costumes in the shop.
3. Check the registered equipments or costumes are unquipped in the arena preperation.
[[아레나] 아레나 전투 준비에 등록된 장비를 상점에 등록할 경우 장착 해제가 되지 않고 출력되는 현상](https://app.asana.com/0/1133453747809944/1202610071912915/f)
1. After equipping the equipments or costumes in the arena preperaion, play Arena Battle.
2. Register equipped equipments or costumes in the shop.
3. Check the registered equipments or costumes are unquipped in the arena preperation.

Fix arena avatar state sync bug

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

Resolve [[전투] 이벤트 던전 11스테이지 이후 스테이지 클리어 시 경험치가 +1 증가하는 현상](https://app.asana.com/0/1133453747809944/1202819833912150/f)

Fix exp bug on render handler of `EventDungeonBattle` action

---

nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

Resolve [[이벤트 던전] 이벤트 던전 티켓 구매 팝업의 티켓 이미지 옆 문구가 잘못 표시된 현상](https://app.asana.com/0/1133453747809944/1202819833912159/f)

Fix cost text when buying event dungeon tickets

---

nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs

Resolve [[이벤트 던전] 공방에서 이벤트 아이템 재료 획득처 숏컷으로 이동 시 헤더에 이벤트 티켓 표시가 되지 않습니다.](https://app.asana.com/0/1133453747809944/1202819929425860/f)

Fix shortcut for material items related with event dungeon rewards

---

nekoyume/Assets/_Scripts/UI/Module/ItemTooltipDetail.cs

Resolve [[인벤토리] 이벤트 아이템 터치 후 다른 요리 아이템 선택 시 메인 스탯이 2개 있는 걸로 표시됩니다.](https://app.asana.com/0/1133453747809944/1202819929425877/f)

Fix stat view list of `ItemTooltipDetail`

---

nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs

Resolve [[전투] 전투 준비화면에서 음식을 등록 후 해제할 경우 증가한 능력치가 남아있는 현상](https://app.asana.com/0/1133453747809944/1202827628141703/f)

Fix stats does not updated bug related to consumable

---

nekoyume/Assets/_Scripts/State/RxProps.Event.cs

Resolve [[이벤트던전] 월드 목록에서 남은 기간 표시가 제대로 되지 않는 현상](https://app.asana.com/0/1133453747809944/1202845469995708/f)

Fix remaining time of event dungeon

---

nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
nekoyume/Assets/_Scripts/Analyzer.cs
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Character/Player.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Game/Prologue.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

This PR adds `agentAddress` and `avatarAddress` properties to the Mixpanel events so that we can view the stats based on these addresses and not the `distinct ids` which currently seem to be malfunctioning.
Viewing the stats based on the `avatarAddress` will look something like this:

Enrich Mixpanel properties with `agentAddress` and `avatarAddress`

---

nekoyume/Assets/_Scripts/Analyzer.cs
nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

1. Now, guide quest doesn't pass to stage.
2. It works the same as Acquisition place button(Shortcut).
~~- **There may be variations in the log.**~~
~~`Unity/Click Guided Quest Enter Dungeon`~~
~~`Unity/Click Guided Quest Enter Event Dungeon`~~
~~Previously, there was Analyzer invoking at the same time as action tx.~~
~~Now, After analyzer invoking, player may not send a tx. We need check it.~~
1. Click any stage guide quest or event dungeon quest.
[가이드 퀘스트 및 숏컷 동작 개선 및 리팩토링](https://app.asana.com/0/958521740385861/1202847454522981/f)

Unify working of guide quest with Shortcut

---

nekoyume/Assets/AddressableAssets/NoticeInfo.meta
nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset
nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset.meta
nekoyume/Assets/AddressableAssetsData/AddressableAssetSettings.asset
nekoyume/Assets/AddressableAssetsData/AssetGroups/RemoteAssets.asset
nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs.meta
nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs

1. Add: Using addressable asset to `NoticePopup`.
2. Add: Addressable Asset Label `"notice"`.
[NoticePopup AddressableAsset화](https://app.asana.com/0/958521740385861/1202927199415140/f)
@planetarium/nine-chronicles-engineers

Use Addressables asset in NoticePopup

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/AddressToolWindow.cs
nekoyume/Assets/Planetarium/Nekoyume/Editor/AddressToolWindow.cs.meta

If you need to know derived `Address`, you can use `Tools/Address Tool` menu.

Introduce `Tools/Address Tool`

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs

1. Previously, there was a problem that all UIs turned off when using quest shortcuts.
2. Fixed that.
1. Open any material tooltip.
2. Click 'Quest' shortcut.

Remove other ui closing in quest shortcut

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

Disable the avatar info icon in the battle preparation
- [[월드 보스] 전투 준비 화면과 상단 UI에서의 장비 변경이 공유되는 현상](https://app.asana.com/0/1133453747809944/1202992445149638/f)

Disable the avatar info icon in the battle preparation

---

nekoyume/Assets/_Scripts/UI/Module/AvatarCP.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs

- Fix AvatarInfo popup to show difference value with cp effect when equip another equipment.
1. Equip in AvatarInfo popup and Check CP change effect.
[장비 교체시, 장착하던 장비와 교체하는 장비의 차이값 만큼 CP상승 효과 숫자로 보여야 하는데, 교체하는 장비의 총 CP가 통째로 CP상승 효과에서 보이고 있음](https://app.asana.com/0/1141562434100787/1202734295506681/f)

Fix equip cp effect

---

nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
nekoyume/Assets/_Scripts/UI/Scroller/RectScroll.cs
nekoyume/ProjectSettings/EditorSettings.asset

- Scroll Down so that the last unlocked Equipment Recipe is at the bottom of the Scoll View in Equipment Tap of Craft.
- Edit Prefab UI Environment settings for Game scene
[크래프트 자동 스크롤 추가](https://app.asana.com/0/958521740385861/1202984408005437/f)

Add auto scroll for last unlocked equipment recipe

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs

- Grind pop-up display when there are not enough crystals to enter the world boss
- Bugfix world boss enter button
[[월드 보스] 크리스탈이 부족한 상태로 시작 버튼을 클릭할 경우 크리스탈 부족 팝업이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1203018991450425/f)

Modify raid related buttons

---

nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

- Fix inventory notification
The inventory notification(red dot) appears when the player doesn't equip the best equipments.
but, item requirement level check was not included in the best equipment.
- lib9c PR : https://github.com/planetarium/lib9c/pull/1383
1. Equip all best equipments.
2. Check the inventory icon of header menu has not red dot.
[CP가 높더라도 장착불가 템이면 인디케이터 안보여줘야 하는데, 인벤토리 아이콘에서 인디케이터를 보여주는 문제](https://app.asana.com/0/1141562434100787/1202619716401117/f)

Fix inventory notification

---

nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs

1. [Remove slider interactable in item options](https://github.com/planetarium/NineChronicles/commit/e5b54fda39e8b744caa2caec1a8ec136c1f43151)
2. [Remove activating progress circle when item enhancement](https://github.com/planetarium/NineChronicles/commit/7ab0afc12b2847b7b17ec4d9b93a12ac6e1f78ee)
[슈퍼 크래프트 게이지 슬라이더 조절이 되는 문제](https://app.asana.com/0/1141562434100787/1202847515700338/f)
[강화시 크리스탈 인디게이터 표시 없애기](https://app.asana.com/0/958521740385861/1202852976182376/f)

Fix minor craft ui

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

Now, some button will transfer to launcher with Staking UI.
**It will work at upper version of launcher than v100290.**
1. (+) button of StakingPopup
2. `Started` button of StakingPopup
3. `Get` button of StakingPopup
4. Shortcut about monster collection
Try to open url `"ninechronicles-launcher://open/monster-collection"`.
[몬스터 콜렉션 게임에서 런처로 연결 DEV](https://app.asana.com/0/958521740385861/1202890739639223/f)
https://github.com/planetarium/9c-launcher/pull/1887
@planetarium/9c-dev @BasixKOR

Use `ninechronicles-launcher` protocol when move to staking

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs

1. Improve: If an item can be obtained from the stage being challenged, the stage is shown as the first priority.
2. Fix: A bug about not show locked acquisition place stages.
1. Check acquisition place tab by material tooltip.
[[획득처] 스테이지 획득경로 우선 순위가 기획 의도와 상이한 현상](https://app.asana.com/0/1141562434100787/1202515747791531/f)

Fix acquisition place button bug and improve priority

---

nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs

- Fix craft button
- to disable if it can't replaced with crystal
[레시피 제작 불가 처리 예외 현상](https://app.asana.com/0/1141562434100787/1202588760044684/f)
Before
After

Fix craft button disable check

---

nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs

change: Items deleted from the inventory were also deleted from the grinding slot.
1. Enter to Grind menu.
2. Add any items to grinding slots.
3. Open your inventory, and turn on grind mode.
4. Try to grind items there added at Grind menu.
5. Check item slots at Grind menu.
[[Previewnet] 공방에서 그라인딩 장비 선택 후 인벤토리 그라인딩으로 그라인딩 후 공방에서 그라인딩이 가능한 현상](https://app.asana.com/0/1141562434100787/1202402217651509/f)

Clean up grinding slots when delete item

---

nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs

Solved #2016. 
Implemented price-per-unit text in Shop item display UI.
1. Connect to main RPC node.
2. Open shop menu.
3. Click Material tab button.
4. View price text.
None
@Atralupus

Add price-per-unit marker on shop item price text

---

nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Character/Player.cs
nekoyume/Assets/_Scripts/Game/Prologue.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

This PR adds an `AgentAddress` property to all mixpanel events that we are currently tracking.
A similar PR: https://github.com/planetarium/NineChronicles/pull/1860

add agent address to mixpanel tracking

---

nekoyume/Assets/_Scripts/Extensions/BigIntegerExtensions.cs

1. before: `1000001` => `1M`
2. now: `1000001` => `1000K`

Fix CurrencyNotation expression

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

Edit arena participants order so that the local player is at the top of the tie.
[아레나 참가자 정렬 수정](https://app.asana.com/0/958521740385861/1203264848476233/f)

Edit arena participants order

---

nekoyume/Assets/Resources/Sentry/SentryOptions.asset
nekoyume/Assets/Resources/Sentry/SentryOptionsConfiguration.asset
nekoyume/Assets/Resources/Sentry/SentryOptionsConfiguration.asset.meta
nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs
nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs.meta

1. Add `SentrySampleRate` CommandLineOptions to control sample rate dynamically
2. but in the sentry `Configure` function, it needs to load all unnecessary options to use `SentrySampleRate` option only.
because it isn't related to the game object where the commandlineoptions loaded on.
if there is better way to get only one option, please let me know
config sentry from code
https://docs.sentry.io/platforms/unity/configuration/options/#programmatic-configuration
9c-launcher will inject the option like below
https://github.com/planetarium/9c-launcher/pull/1970/files

get sentry sample rate from command options

---

nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs

In Arena Join, disable the mission button when it is OffSeason after the Championship.
[아레나 참가 화면에서 챔피언십에 포함되지 않은 OffSeason 표시할 때 미션 버튼 비활성화](https://app.asana.com/0/958521740385861/1203423892583175/f)
Before Championship
After Championship

Add check offseason for mission button

---

nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
nekoyume/Assets/_Scripts/Game/VFX/Skill/BuffVFX.cs
nekoyume/Assets/_Scripts/Game/VFX/VFX.cs

1. Fix lifecycle of Bleed VFX.
1. Equip Fenrir bleed rune and enter a battle.
2. Cast bleed on same enemy twice and check if vfx is properly vanished.
[[룬] 펜리르 출혈의 룬이 적용된 몬스터가 사망할 경우 출혈 이펙트가 사라지지 않는 현상](https://app.asana.com/0/1133453747809944/1203506202018244)

Fix lifecycle of Bleed VFX

---

nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/EnumType/ShopSortFilter.cs
nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
nekoyume/Assets/_Scripts/UI/Shop/SellView.cs

1. SSIA
2. `Crystal` sorting option: Sort shop items with Crystal per price
[샵 크리스탈 소팅 추가](https://www.notion.so/planetarium/7961a929ddfd4813ad97946f69333fc5#408310c593184f0aa8bdac679322271b)

Add crystal per gold sorting to Shop UI

---

nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
nekoyume/Assets/_Scripts/Game/VFX/Skill/BuffController.cs

1. Enter raid battle with damage reduction rune (optional) and enough gears to pass wave 1.
2. When wave 1 defeated, check if damage reduction buff vfx or bleed vfx follows character properly.
@planetarium/devops

[Bugfix] Persistenting vfx follow target position

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs

Fix gold to be updated after purchasing event dungeon tickets
[이벤트 던전 추가 티켓 구매시 NCG 갱신 안되는 현상](https://app.asana.com/0/1133453747809944/1203605612434782/f)

Fix gold to be updated after purchasing event dungeon tickets

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPurchasePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/TicketPurchasePopup.cs

SSIA
[티켓 구매 팝업에서 Cost인 0.05NCG가 0.5NCG로 표시됨](https://app.asana.com/0/1141562434100787/1203616987717568/f)
**Before**
In practice, normal cost(0.05) are used..
**After**

Fix cost text in TicketPurchasePopup

---

nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs

Minimize Sentry SampleRate only for errors because it sends too many errors so that we cannot raise sample rates for more traces

Minimize Sentry SampleRate only for errors

---

nekoyume/Assets/_Scripts/UI/ComboText.cs

Fix ComboText to initialize at the start of the battle
[전투에서 콤보 숫자가 다음 세션에서도 지속되는 문제 (최초 공격이 2콤보나 3콤보부터 시작하는 등의 현상)](https://app.asana.com/0/1141562434100787/1198998806481877/f)
Fixed...

Fix combo text not reset

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs

1. SSIA
2. Prevents event popup showing when the tutorial is not finished.
[튜토리얼 해야하는데 이벤트 배너 팝업 나옴](https://app.asana.com/0/1141562434100787/1203670290382034/f)

Add condition to `EventReleaseNotePopup.Show()` about tutorial

---

nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs

1. SSIA, Invoke `Find<Synopsis>().Show()` when get false from `Util.TryGetStoredAvatarSlotIndex()`.
1. Remove registry.
2. Execute game with active agent.
https://github.com/planetarium/NineChronicles/issues/2336

Fix if statement about skipSynopsys

---

nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs

lazy close and widget stack issue
1. try grinding with zero ap
[강화했거나 혹은 스킬이 붙은 아이템을 그라인딩하려고 할 때 ap가 부족하면 포션을 사용하면서 그라인딩 진행하는 기능이 막히는 현상](https://app.asana.com/0/1141562434100787/1204004868855608/f)

fix bug about IconAndButtonSystem

---

nekoyume/Assets/_Scripts/UI/Scroller/RecipeRow.cs
nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs

Fix craft recipe scroll error when show by QuestGuide
1. Enter Craft ui twice by QuestGuide
[[가이드퀘스트] 이벤트 탭 클릭 후 가이트 퀘스트 진입 시 하단의 레시피가 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204036280897303/f)

Fix craft recipe scroll

---

nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs

When we save a balance(i.e., FungibleAssetValue), it may have the same `Address` but a different `Currency`.
Make the `Game.CachedBalance` consider this.

fix: `Game.CachedBalance` bug.

---

nekoyume/Assets/_Scripts/Game/Character/Pet.cs
nekoyume/Assets/_Scripts/Game/RaidStage.cs

- Fix pet animation in worldboss
- to sync it with character animation of appear cutscene
- it was written in hardcoding...
[[펫] 월드보스 전투 연출에서 Battle Start 모션이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204172051496798/f)

Fix pet animation at worldboss

---

nekoyume/Assets/_Scripts/UI/Model/RuneItem.cs

I changed the maximum level of Adventure Runes to 2 and tested it.
[[공방] 최대 레벨의 룬 선택 시 보유 룬조각이 0개로 출력되는 현상](https://app.asana.com/0/1133453747809944/1204061585905560/f)

Fix rune display

---

nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs

[[상점] 아이템 등록 시 룬조각/영혼석의 배경과 글씨가 노멀 등급으로 출력되는 현상](https://app.asana.com/0/1133453747809944/1204222023874606/f)

Modify the font of the Rune sell popup.

---

nekoyume/Assets/_Scripts/Game/Character/PrologueCharacter.cs

Fixed an issue where the Fenrir Finisher skill was not activating properly. Additionally, a forced activation logic has been implemented.
[시놉시스에서 캐릭터 스파인 나올때(시놉시스16, 17~) 전체 파츠 이어진 스파인 파일 없어서 진행 불가](https://app.asana.com/0/1133453747809944/1204009886813855/f)

Fix prologue

---

nekoyume/Assets/_Scripts/UI/Scroller/GridScroll.cs

1. introduce `fillWithNullToEmptyCellGroup` to `GridScroll`
2. It fills null to empty cell group.
not use(count 10):
use(count 10):

introduce fillWithNullToEmptyCellGroup

---

nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Abstractions.dll.meta
nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Abstractions.xml.meta
nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Memory.dll.meta
nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Memory.xml.meta
nekoyume/Assets/Packages/Microsoft.Extensions.Options.dll.meta
nekoyume/Assets/Packages/Microsoft.Extensions.Options.xml.meta
nekoyume/Assets/Packages/Microsoft.Extensions.Primitives.dll.meta
nekoyume/Assets/Packages/Microsoft.Extensions.Primitives.xml.meta
nekoyume/Assets/Plugins/BalanceTool/Editor/BalanceToolWindow.cs
nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.cs
nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeView.cs
nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerWindow.cs
nekoyume/Assets/Plugins/StateViewer/Runtime/BlacksmithMaster.cs
nekoyume/Assets/Plugins/StateViewer/Runtime/BlacksmithMaster.cs.meta
nekoyume/Assets/Plugins/StateViewer/Runtime/ContentKind.cs
nekoyume/Assets/Plugins/StateViewer/Runtime/ContentKind.cs.meta
nekoyume/Assets/Plugins/StateViewer/Runtime/StateTreeViewItemModel.cs

- Use test values for example.
- Remove children rows.
- Select the content type to inventory.
- Click add button and click context menu you want. I'll click the consumable button.
- Something's changed.(Based on sheet data)
- I'll change the "id" value from 105000 to 100000.
- The item hierarchy has been changed to fit 100000.(Based on sheet data)
- Change again to 10111000 and it changed to a equipment now.
- I was change the id to 10144000 and now I'll change the level. Before that, check the stats and skills.

feat: Improve UX of manipulate inventory state in State Viewer

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/AddressToolWindow.cs

- Add `Use Addresses as Original` toggle.
- The `Original Address` UI will be changed when you toggled on the toggle.
- Let's select the Blacksmith address.
- And derive some item address.

Use Addresses in AddressToolWindow

---

nekoyume/Assets/_Scripts/UI/Module/Item/InventoryItemView.cs

SSIA
1. Check ItemView OptionTag in Invetory Equipment Tab
2. Click Rune Tab
3. Click Invetory Equipment Tab, Check ItemView OptionTag again
[[상점] Sell 탭에서 3번째 줄까지 장비의 별이 출력되지 않는 현상](https://app.asana.com/0/1133453747809944/1204279738898089/f)

Fix Inventory ItemView

---

nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs

1. remove `TutorialController.IsCompleted`. This is a meaningless code.
2. change logic of `EventReleaseNotePopup.Show()`. Check world information, not PlayerPrefs.
[튜토리얼 도중에 공지사항/이벤트 팝업이 나오는 현상](https://app.asana.com/0/1141562434100787/1204387310593487/f)

change logic of `EventReleaseNotePopup.Show()`

---

nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

1. It will not modify `States.Instance.CurrentAvatarState.MailBox`.
2. not notify `ReactiveAvatarState.MailBox`.
3. Wrapped `States.Instance.CurrentAvatarState.MailBox` to `LocalMailHelper.MailBox` and `LocalMailHelper.ObservableMailBox`.
4. It will fix many bug about `MailBox.Serialize()`.
https://app.asana.com/0/1133453747809944/1204361983054631/f

Re-develop `LocalMailHelper`

---

tools/pack/pack.py

remove `9c_BurstDebugInformation_DoNotShip` folder when during the pack step

ci: Add clean debug dir

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs
nekoyume/Assets/Planetarium/Nekoyume/Editor/LibplanetEditor.cs
nekoyume/Assets/_Scripts/Game/Game.cs

Makes Unity editor to play in `Agent`(not `RPCAgent`) when `Use Local Headless` is `false`.

Use local `Agent` in unity editor

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs

Fix button condition in SuperCraftPopup
[[공방] 레전드리 장비를 슈퍼크래프트 진행 시 레시피를 선택하지 않아도 제작이 가능한 현상](https://app.asana.com/0/1133453747809944/1204646076868485/f)

Fix button condition in SuperCraftPopup

---

nekoyume/Assets/Resources/UI/Materials/Distortion_Additive_Maskable.shader
nekoyume/Assets/Resources/UI/Materials/Distortion_Additive_Maskable.shader.meta
nekoyume/Assets/UIResources/Content/Effect/Grade/Distortion_RecipeSlotOpen_eff.mat

Add new shader("Custom/Distortion_Additive_Masked") with **stencil** added to "Custom/Distortion_Additive" shader
to fix recipe slot's legendary effect in Craft ui
[[공방] 레전드리 장비 레시피의 이펙트가 장비 종류 탭 하단에 출력되는 현상](https://app.asana.com/0/1133453747809944/1204627454773842/f)
Before
After

Fix shader for recipe slot's legendary effect

---

nekoyume/Assets/_Scripts/UI/Tween/MaskedRectTransformXRoller.cs

- Fix MaskedRectTransformXRoller for uninitialized value(first enabled RectTransform's X position)
[[메일] 다인슬레이프의 스킬 효과가 증가할 경우 스킬효과와 증가한 스킬 효과 수치가 겹치는 현상](https://app.asana.com/0/1133453747809944/1204664465756572/f)

Fix MaskedRectTransformXRoller for uninitialized value

---

nekoyume/Assets/Resources/ScriptableObject/LiveAssetEndpoint.asset
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/LiveAssetEndpointScriptableObject.cs
nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs

Add command line option - RpcServerHosts
```
{
"GenesisBlockPath": "https://download.nine-chronicles.com/genesis-block-9c-main",
"NoMiner": true,
"RpcClient": true,
"RpcServerHosts": [
"9c-main-rpc-1.nine-chronicles.com",
"9c-main-rpc-2.nine-chronicles.com",
"9c-main-rpc-3.nine-chronicles.com"
],
"RpcServerPort": 31238,
"ApiServerHost": "https://api.9c.gg/graphql",
"DataProviderUrl": "https://api.9c.gg/graphql",
"OnboardingPortalUrl": "https://world-boss.9c.gg",
"MarketServiceHost": "https://market.9c.gg",
"Development": true
}
```
https://app.asana.com/0/958521740385861/1204951963817787/f

Add command line option - RpcServerHosts

---

nekoyume/Assets/_Scripts/UI/Widget/System/VersionSystem.cs

add application version
Only the application version added.
Since Unity does not provide the function to access the corresponding value at run time for the bundled version code, it is necessary to modify the code before compiling or to store the value somewhere, which can affect CI, so further work.
Related forum posts
https://forum.unity.com/threads/how-can-i-get-bundle-version-and-bundle-version-code-through-script.68331/

add application version in android platform

---

nekoyume/Assets/Plugins/StateViewer/Editor/Features/StateAndBalanceFeature.cs
nekoyume/Assets/Plugins/StateViewer/Editor/Features/TrackStateFeature.cs
nekoyume/Assets/Plugins/StateViewer/Runtime/StateProxy.cs
nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/Agent.cs
nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
nekoyume/Assets/_Scripts/Extensions/AvatarStateExtensions.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/State/States.cs

This work has a little complex. Because the implementation of `IAgent.GetBalance` using `Game.CachedBalance` in the `RPCAgent`. This is why the behavior of the two `GetBalanceAsync` methods I added is different.
- Introduce `IAgent.GetBalanceAsync` methods.
- Rename async methods  of `IAgent` to `XyzAsync`.
- Apply above to `StateViewer`.
- Fix `TrackStakeFeature` of `StateViewer`.
```cs
// Use GetBalanceAsync(address, currency, blockIndex) instead of self implementation.
FungibleAssetValue GetBalance(Address address, Currency currency);
// Implement with `Game.CachedBalance` that had contained in `GetBalance` method.
Task<FungibleAssetValue> GetBalanceAsync(
Address address,
Currency currency,
long? blockIndex = null);
// Implement without `Game.CachedBalance`.
Task<FungibleAssetValue> …
```

feat(IAgent): implement async methods for get balance

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

Increase the default `RpcConnectionRetryCount` from `20` to `50` because the mobile version's reconnection interval is twice faster than the PC version and therefore, fails to reconnect every time the RPC node restarts.

increase rpc reconnection attempt count from `20` to `50`

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

Using GQL on `RPCAgent` is not good on both sides: performance and code sanitization.
So we introduced `GetBlockHash` with GRPC on #3042.

fix: use `BlockChainService.GetBlockHash` instead of GQL

---

nekoyume/Assets/Plugins/StateViewer/Editor/Features/StateAndBalanceFeature.cs
nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionTimeoutException.cs
nekoyume/Assets/_Scripts/Blockchain/ErrorCode.cs
nekoyume/Assets/_Scripts/State/LocalLayer.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

- introduce `LocalLayer.ModifyInventoryOnly(avatarState)` method.
- introduce `ActionHandler.UpdateCurrentAvatarInventory<T>(eval)` method.
- rendering the `ClaimItems` action.
- rendering the `TransferAssets` action.
- improve `StateViewer`.
- change test shortcuts on lobby.

feat: render `ClaimItems`, `TransferAssets`

---

nekoyume/Assets/Tests/EditMode/Blockchain.meta
nekoyume/Assets/Tests/EditMode/Blockchain/BlockHashCacheTest.cs
nekoyume/Assets/Tests/EditMode/Blockchain/BlockHashCacheTest.cs.meta
nekoyume/Assets/Tests/EditMode/Blockchain/BlockchainCacheTest.cs
nekoyume/Assets/Tests/EditMode/Blockchain/BlockchainCacheTest.cs.meta
nekoyume/Assets/_Scripts/Blockchain/BlockHashCache.cs
nekoyume/Assets/_Scripts/Blockchain/BlockchainCache.cs
nekoyume/Assets/_Scripts/Blockchain/BlockchainCache.cs.meta
nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

This pull request based on https://github.com/planetarium/NineChronicles/pull/3192.
We have many `Currency`. But those `Currencies`'s handling is all different.
For the future proof, we need to make robust state handling.
In this PR, as the first step, to overhaul the state cache, we introduce `BlockChainCache`.
Do not have a usage in this PR but we prepared a follow-up PR which using this.
relate proposal: [internal notion](https://www.notion.so/planetarium/3a64d250faca4a4c9d8eb2cba46ad794?pvs=4#c85fa6f1e3a64d96b233e59ba4fa650b)

feat: introduce `BlockchainCache`

---

nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerWindow.cs
nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Blockchain/Agent.cs
nekoyume/Assets/_Scripts/Blockchain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/State/Subjects/AgentStateSubject.cs
nekoyume/Assets/_Scripts/UI/Model/ItemCountAndPricePopup.cs
nekoyume/Assets/_Scripts/UI/Shop/CartView.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs

There is the [GoldCurrencyState] which is contains the `NCG` currency of a Nine Chronicles blockchain network.
It means the `NCG` currency can be different between another networks.([ref][mainnet-ncg])
For this reason, clients need to get the `NCG` currency that are stored in the blockchain state each time.
[GoldCurrencyState]: https://github.com/planetarium/lib9c/blob/1.3.0/Lib9c/Model/State/GoldCurrencyState.cs
[mainnet-ncg]: https://github.com/planetarium/lib9c/blob/1.3.0/Lib9c.Utils/BlockHelper.cs#L60C49-L60C59
- Get the `NCG` currency from blockchain state and store to `States` each time.
- Remove `ActionHandler.GoldCurrency`.
- Use `States.NCG` instead of others.

feat: introduce and apply `States.NCG`

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/Agent.cs
nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
nekoyume/Assets/_Scripts/State/States.cs

- store the agent's staked NCG as a `FungibleAssetValue` type not `GoldBalanceState` type.

feat: introduce `States.AgentStakedNCG`

---

nekoyume/Assets/Editor/TutorialPresetScriptableObjectEditor.cs
nekoyume/Assets/Editor/TutorialPresetScriptableObjectEditor.cs.meta
nekoyume/Assets/Editor/TutorialScenarioScriptableObjectEditor.cs
nekoyume/Assets/Editor/TutorialScenarioScriptableObjectEditor.cs.meta
nekoyume/Assets/Resources/Tutorial/Data/TutorialPreset.asset
nekoyume/Assets/Resources/Tutorial/Data/TutorialPreset.asset.meta
nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset.meta
nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialPresetScriptableObject.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialPresetScriptableObject.cs.meta
nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialScenarioScriptableObject.cs
nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialScenarioScriptableObject.cs.meta
nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs

목표 : 튜토리얼 수정을 쉽게 하기
1. 튜토리얼 수정 과정을 개선한다
- 기준 : 대부분의 튜토리얼 수정이 오직 유니티 에디터에서 이루어지도록  
2. 튜토리얼 수정 과정을 문서화한다
1. TutorialScenario, TutorialPreset을 ScriptableObject로 대체한다.
- ScriptableObject를 정의함. Custom Editor로 기존의 json파일에서 데이터를 가져오고 내보낼 수 있도록 버튼 추가. ([commit](https://github.com/planetarium/NineChronicles/commit/8b99b4bb2fef673db3bbba57e4efb5796ba41f5f))
- TutorialController에서 json 대신 ScriptableObject로 튜토리얼 데이터를 가져올 수 있도록 수정. ([commit](https://github.com/planetarium/NineChronicles/commit/70cbe1542f2dd45276c1c75d4617a76d1ce04b01))

Improve tutorial scripting - json to SO

---

nekoyume/Assets/_Scripts/PlatformUtility/Platform.cs

When using constants conditions, `UNITY_EDITOR` must be considered first if possible.

fix persistent data path on editor(android)

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Planet/PlanetContext.cs
nekoyume/Assets/_Scripts/Planet/PlanetContext.cs.meta
nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs.meta

This pull request based on #3253.
- introduce `PlanetContext`, `PlanetSelector`.
- initialize `Planets` and `CurrentPlanetInfo`, and apply to `CommandLineOptions`.

feat: initialize `PlanetContext` in `Game`

---

nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Extensions/GraphQlHttpClientExtensions.cs
nekoyume/Assets/_Scripts/Extensions/GraphQlHttpClientExtensions.cs.meta
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/GraphQL/GraphTypes.meta
nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AgentGraphType.cs
nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AgentGraphType.cs.meta
nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AvatarGraphType.cs
nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AvatarGraphType.cs.meta
nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AvatarsGraphType.cs
nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AvatarsGraphType.cs.meta
nekoyume/Assets/_Scripts/GraphQL/GraphTypes/StateQueryGraphType.cs
nekoyume/Assets/_Scripts/GraphQL/GraphTypes/StateQueryGraphType.cs.meta
nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
nekoyume/Assets/_Scripts/Planet/PlanetAccountInfo.cs
nekoyume/Assets/_Scripts/Planet/PlanetAccountInfo.cs.meta
nekoyume/Assets/_Scripts/Planet/PlanetContext.cs
nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
nekoyume/Assets/_Scripts/Planet/Planets.cs
nekoyume/Assets/_Scripts/PlatformUtility/Platform.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
nekoyume/nekoyume.sln.DotSettings

- update genesis block for `0x000000000001`(Heimdall).
- fix `Planetform.PersistentDataPath` for `UNITY_EDITOR`.
- rename `CommandLineOptions.DefaultPlanetId` w/ comment.(from `PlanetId`)
- introduce `PlanetAccountInfo`.
- introduce several graph types.(Agent, Avatar, Avatars)
- introduce `GraphQlClientExtensions`.
- improve `Planets` and `PlanetSelector` w/ `PlanetContext`.

feat: provide planet data

---

nekoyume/Assets/Resources/HelpPopupData/HelpPopupData.json
nekoyume/Assets/Resources/UI/Prefabs/UI_HelpTooltip.prefab

- 도움말에서 의미 없는 이미지 영역 삭제
- 텍스트를 충분히 전달할 수 있도록 영역 확보
- 가로비 대응에 어울리는 비율 적용
Just check the file changes
https://app.asana.com/0/958521740385861/1205892581083283/f

fix helppopup prefap and json

---

nekoyume/Assets/Editor/OpenAPIGenerator.cs

OpenApiGenerator.cs의 폴더가 에디터 하위로 수정되면서 어셈블리도 에디터로 바뀌어 클레스이름으로 타입검색에 실패하는 문제입니다. 
전체 어셈블리를 돌면서 동일한 클레스네임에 제너레이션된 코드가 가지고있어야하는 필드 _client, url 조건 체크를 하는방식으로 타입검색하도록 수정하였습니다.

find all assembly and check field

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs
nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs

-시즌패스 매뉴 레벨텍스트 Max나오지않는문제 수정.
-시즌패스 30달성시 받기버튼 비활성화 버그 수정
---
- https://app.asana.com/0/0/1205912551311626

change seasonpass menu level text

---

nekoyume/Assets/_Scripts/Planet/Planets.cs

list<string> 에서 contains로 값을 찾지못해서 에디터에서 플레닛이 세팅되지않는 문제 수정.

fix TryGetPlanetInfoByHeadlessGrpc

---

nekoyume/Assets/StreamingAssets/Localization/button.csv
nekoyume/Assets/StreamingAssets/Localization/sentence.csv
nekoyume/Assets/_Scripts/Native.meta
nekoyume/Assets/_Scripts/Native/SystemSettingsOpener.cs
nekoyume/Assets/_Scripts/Native/SystemSettingsOpener.cs.meta
nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs

(kor)
- 플레이어가 명시적으로 기능에 대한 권한을 거부하는 경우에 시스템 설정으로 안내합니다.
- `SystemSettingsOpener`를 도입합니다.
- QR 코드 가져오기 과정에서 `SystemSettingsOpener`를 사용합니다.
(eng)
- If a player explicitly denies permission to a feature, direct them to the system settings.
- introduce `SystemSettingsOpener`.
- Use `SystemSettingsOpener` during the QR code import process.
---
- https://app.asana.com/0/0/1205912720216535

feat: [Android] open native system settings for permission

---

nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs

This PR fixes the wrong endpoint assigning for DataProvider GQL.
---
- https://app.asana.com/0/0/1205946822998724

Fix wrong endpoints for DataProvider GQL

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs

월드보스 연습모드일경우 용기경험치 보이지않도록 수정.
---
- https://app.asana.com/0/0/1205946068107188

fix seasonpass obj hide when worldboss practicemode

---

nekoyume/Assets/_Scripts/Helper/Util.cs

이미지 다운로드시 mipmap이설정되어 퀄리티세팅에영향받아 이미지해상도가 하프로나오는 문제 수정(모바일상점 다운로드이미지가 영향이있었음.)
---
- https://app.asana.com/0/0/1205934580544047

unlock texture DownloadTextureRaw mipmap limit

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattleLoadingScreen.prefab

- https://github.com/planetarium/NineChronicles/pull/3594/files# 여기에서 지운 파일 중 단 한군데 쓰고 있어서 리소스가 미싱남
- https://planetariumhq.slack.com/archives/C062ZS68A21/p1700495893585969 아레나 전투 진입할때 흰색이 뜨는 문제가 생김
- 미싱난 텍스쳐를 신규 아레나 배경을 적용하여 문제를 해결합니다.
에디터에서 가라 플레이 해보고 전투로딩 진입시 흰색배경 더이상 안뜨는지 체크

add missing resource

---

nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs

시즌패스 reward cell이 초기화되지않는 경우가 아예 없도록 대응.

season pass cell view bugfix

---

nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Discount_Bg.png.meta
nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
nekoyume/Assets/_Scripts/L10n/L10nManager.cs
nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopDynamicGridLayoutView.cs
nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs

[모바일 샵 패키지에 남은 시간 표기해주기](https://app.asana.com/0/0/1206021378847065)
---
- https://app.asana.com/0/0/1206021378847065

Add TimeLimitText at mobile shop product ui

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

seasonpass_icon-edit
https://app.asana.com/0/958521740385861/1206007066225384

[Design]UI_Menu_Prefabs_Edit

---

nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs
nekoyume/Assets/Planetarium/Nekoyume/Editor/LibplanetEditor.cs
nekoyume/Assets/Tests/EditMode/Extensions/PrivateKeyExtensionsTest.cs
nekoyume/Assets/Tests/EditMode/Extensions/PrivateKeyExtensionsTest.cs.meta
nekoyume/Assets/_Scripts/Extensions/PrivateKeyExtensions.cs
nekoyume/Assets/_Scripts/Extensions/PrivateKeyExtensions.cs.meta
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs

[cherry pick]fix: private key hex with zero paddings

---

nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

[갈아낄 장비가 없는데 레드닷을 계속 띄워주는 문제](https://app.asana.com/0/958521740385861/1205988121943677/f)

Fix headmenu inventory to check cleared stage for notification(red-dot)

---

nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RecipeSlot.prefab
nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeView.cs

[장비 레시피 오픈됐을때 장착레벨정보 변경](https://app.asana.com/0/958521740385861/1203863020824790/f)
- Update Recipe view prefab to level text format `<size=14px>Lv</size>\n20` for union and clean texts
- Update normalLevelText to display unique stat, disable lockedLevelText

Update Recipe view in Craft

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab

setting_popup_text-edit
https://app.asana.com/0/958521740385861/1205964990418930

[Design]UI_SettingPopup_Prefabs_Edit

---

nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs

EffectToString 에서 스킬관련 변환을 모두 해주기 때문에 따로 SkillType 분기를 타지않도록 수정.
PowerRatio대신 Power가 표기되어 0이 나오던 문제 수정.
---
- https://app.asana.com/0/0/1206088796073259

clear upgrade description branch

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

간헐적으로 메일이 읽음처리되는 부분 의심포인트 수정.
액션렌더링을할때 해당 액션이 만든 메일을 찾는 과정에서 동일 블록인덱스와 액션타입만바라보기 때문에 여러개가 있을 경우 무시될수있는 부분 수정.
ID값은 그냥 랜덤한값을 넣어서 맞춰주고있지않기때문에 메모값 비교로 추가 확인하는방식으로 대응.
---
- https://app.asana.com/0/0/1206031536512753

fix mail find condition

---

nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeView.cs

[공방 레시피에서 스피드가 메인 스탯인 장비 아이콘에서 /100 처리가 안된 문제](https://app.asana.com/0/958521740385861/1206134962292318/f)

Fix stat value string at recipe view

---

nekoyume/Assets/_Scripts/UI/Widget/Summon.cs

[룬 소환 결과화면 소팅 순서 같은 등급 내에서는 ID 역순으로.](https://app.asana.com/0/958521740385861/1206136783593028/f)
Fix rune order at summon result popup : grade > sorting order (UI_RuneData)

Fix rune summon result order

---

nekoyume/Assets/_Scripts/Game/Stage.cs

[모바일환경에서 stage 17 클리어 시 shop 언락 언출 나오지 않도록 처리](https://app.asana.com/0/958521740385861/1206125891349824/f)
define `RUN_ON_MOBILE` used this ⬇️
```cs
#if !RUN_ON_MOBILE
if (stageId == LiveAsset.GameConfig.RequiredStage.Shop)
{
menuNames.Add("UI_MAIN_MENU_SHOP");
}
#endif
```
(Stage.cs, line.1364)

Fix disable unlock shop popup in stage 17, mobile

---

nekoyume/Assets/_Scripts/GeneratedApi/SeasonPassServiceClient.cs
nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs

시즌패스 서비스에 event_dungeon Enum값 추가로 필요한 부분 수정한 내용입니다.
기존 배포된 내용에는 Adventure 경험치와 동일하게 계산되어있어 문제없으나 추후 지원을 위해서 추가했습니다.

apply EventDungeonCourageAmount

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

기존 IAP 등에서 만들어주는 ClaimItemsMail 등이 새 메일이 추가될 경우 기존 메일이 날아가는듯한 모습을 보이고 있었습니다. 이를 직접 mailbox를 set하는 코드의 문제로 보고, `currentAvatarState.Mailbox = variable` 과 같은 형태의 코드를 삭제했습니다.
1. modify `ClaimItems` action for test.
2. execute it.
3. check mailbox and mail popup ui.
https://app.asana.com/0/958521740385861/1206261558282586/f
check asana issue

remove directly setting mailbox

---

nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs

SSIA
1. 여러 플래닛에 거쳐 게임을 할 때, 같은 에이전트로 게임을 플레이하면 타 플래닛에서 캐싱된 월드보스 보상 정보가 보이는 경우가 있었습니다. (e.g. 오딘에서 월드보스 시즌 1 보상이 캐싱된 후 헤임달에서 월드보스 시즌 1이 끝난 뒤에 접속)
2. 이 때문에 캐싱하는 키에 월드보스 시즌, 아바타 주소와 함께 현재 접속해있는 플래닛 id를 추가했습니다.
https://app.asana.com/0/958521740385861/1206269194413999/f

add planet id argument to raid reward caching key

---

nekoyume/Assets/_Scripts/Game/Character/TouchHandler.cs

처음 접속시 선택된 터치핸들러가 없어서 툴팁 닫는것에 실패하는 문제로 확인되었습니다.
일단 터치핸들러가 활성화될때 선택된 터치핸들러가 없다면 본인을 넣도록 수정하여 문제해결된것 확인했습니다.
시즌패스에서 여는 툴팁말고도 다른곳에서도 동일한 문제 발생하는부분 다같이 수정될것으로 예상됩니다.
---
- https://app.asana.com/0/0/1206089527062271

set first touch handler obj

---

nekoyume/Assets/_Scripts/Multiplanetary/PlanetContext.cs

> English
Fill in the missing values in the blurb for unsupported error cases that occur during the portal login process.
> 한글
포탈 로그인 과정에서 발생하는 지원하지 않는 에러 케이스에 대한 안내 문구에 누락된 값을 채워 넣습니다.

fix: error message

---

.github/workflows/ios-build-and-release.yml

Git Action Runner의 저장소 용량부족으로 Ci 빌드 실패하는 문제를 수정한 내용입니다.
Library- 로 추가적으로 안드로이드의 캐시키까지 가져와서 용량이 부족했던 문제로 확인되었습니다.
---
- https://app.asana.com/0/0/1206346337699012

remove github action cache resotre key

---

nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentInventoryItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/InventoryItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/MailRewardItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ShopCartItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/SweepItemView.cs
nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs
nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
nekoyume/Assets/_Scripts/UI/Scroller/RuneStoneEnhancementInventoryCell.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

신규로 프리팹에 추가된 RuneNotificationObj의 래퍼런스가없는 아이템 뷰에서 참조시 에러가나는부분 수정.
시즌패스 IAP 상품 갱신이 정상적으로되지않던 문제의 원인.
---
- https://app.asana.com/0/0/1206378987676419

fix seasonpass iap item refresh failed

---

nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs

룬강화화면에서 스텟표기시 SPD 소수점표시안되는부분 수정.
---
- https://app.asana.com/0/0/1206400686470807

fix rune enhancement stat

---

nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs

[공방] Grind 아이템 등록 시 화면에 표시되는 크리스탈 수량이 올라가는 중 아이템을 제거할 경우 잘못된 크리스탈 수량이 출력되는 현상
---
- https://app.asana.com/0/0/1206216956155581

Fix crystal text animation in grind

---

nekoyume/Assets/_Scripts/Helper/WorldMapDataHelper.cs

1. 월드맵에서 이벤트 아이콘과 보스 아이콘의 우선순위를 변경합니다. 보스 아이콘이 우선적으로 출력됩니다.
이벤트 던전의 보스 스테이지 아이콘이 제대로 표시되는지 확인합니다

change worldmap icon priority

---

nekoyume/Assets/_Scripts/Helper/WorldMapDataHelper.cs
nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapWorld.cs

1. 이벤트 던전과 일반 던전의 아이콘을 구분하는 로직을 추가합니다
2. 이벤트 던전의 20번째 스테이지에 최종 보스 아이콘을 적용합니다 (임시)
1. 월드맵에서 스테이지 아이콘을 확인합니다.
#4133

update event dungeon ui

---

nekoyume/Assets/_Scripts/Game/Character/Player.cs
nekoyume/Assets/_Scripts/UI/Widget/Hud/AreaAttackCutscene.cs

1. 컷씬 연출을 비활성화합니다.
2. 임시처리로 컷씬 리소스 수정 후 복구시키겠습니다.
1. 전투 연출에 문제가 없는지 확인합니다

disable area attack cutscene

---

nekoyume/Assets/_Scripts/UI/Widget/Craft.cs

1. 장비 제작 탭으로 이동시 기존의 애니메이션 트리거 상태를 초기화시킵니다
1. 관련 이슈에 상세히 적혀있습니다
https://github.com/planetarium/NineChronicles/issues/4183

resolve #4183 - reset consumableClick trigger on set equipment trigger

---

nekoyume/ProjectSettings/GraphicsSettings.asset

1. 150 release 브랜치에서 skeleton black tint 셰이더가 빌드로그에 포함되어 있지 않은것으로 보였습니다
2. 해당 쉐이더가 항상 빌드에 포함 될 수 있도록 추가해두었습니다
3. 스파인 쉐이더는 스크립트로 쉐이더를 변경하는 경우가 있는데, 이 경우에도 안전하게 적용될 수 있을 것으로 예상됩니다.
인게임 (특히 윈도우 빌드) 로비에서 dcc 위젯을 활성화시킵니다
https://github.com/planetarium/NineChronicles/issues/4197

add spine shader to always included shader

---

nekoyume/Assets/_Scripts/UI/Widget/Rune.cs

1. resolve #4196 
2. remove usecase of RuneCombineResultScreen when render RuneEnhancement. anyway use RuneEnhancementResultScreen
3. use RuneCombineResultScreen when send RuneEnhancement action.
https://github.com/planetarium/NineChronicles/assets/48484989/6387e1ce-7469-44d5-aae5-e789bd4062ee
https://github.com/planetarium/NineChronicles/assets/48484989/e7af0c97-ac82-4d00-b41b-bfad880a7923

use RuneEnhancementResultScreen anyway

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs

1모바일 빌드의 워크샵 팝업에서 펫 버튼을 활성화합니다.
모바일 빌드의 워크샵 팝업을 활성화한 후, 펫 버튼을 터치합니다.
수정 전 이미지입니다

모바일 워크샵 팝업에서 펫 버튼 활성화

---

nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs

awake 시점이 달라져서 슬롯 요구래밸 세팅이 되기전 렌더링되버리는 이슈로 확인되었습니다.
요구래밸 세팅직후에 lock 렌더세팅을 한번더해주는것으로 수정하였습니다.

add slot update timing

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs

1. resolve #3951 
2. insert PlayerArenaInfo to first index of between last Rank
1. Enter to arena board with no-arena-play avatar

insert PlayerArenaInfo to first index of between last Rank

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs

전투중에서는 펫 버튼 클릭시 dcc collection으로 이동하지 않도록 막습니다
전투중에 제작 슬롯에서 펫 팝업을 활성화시킨 후 펫을 클릭합니다.
https://github.com/planetarium/NineChronicles/issues/4263

add isInWorld check to item of petInventory

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs

Fix to use only equipped rune state in FriendInfoPopup.UpdateStatViews
- #4259

Fix Stat View in FriendInfoPopup

---

nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs

1. 아레나에서 선택한 상대의 cp값을 캐싱하여, 뷰가 업데이트 될 때 해당 값이 유지되도록 하였습니다.
1. 아레나에서 아무 상대나 선택합니다
2. 탑 메뉴에서 장비 팝업을 실행시켰다 종료합니다
3. 나의 cp정보 색상이 정상적인지 확인합니다 
https://github.com/planetarium/NineChronicles/issues/4275

Caching enemy cp value

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs

강제로 이벤트 탭으로 이동시 UI초기화를 위한 메서드를 추가합니다
1. 공지 팝업을 열고 release note tap을 활성화합니다
2. 그 상태로 공지 팝업을 닫습니다
3. 다시 공지 팝업을 활성화 했을 때 이벤트 탭이 제대로 렌더링 되고 있는지 확인합니다 
https://github.com/planetarium/NineChronicles/issues/4296

add on force toggle on event tap method

---

nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs

결과창이 뜨는 시점에서는 이미 플레이어의 마지막으로 성공한 스테이지의 값이 갱신되어있어서 최초로 월드 마지막을 깬것인지 다시 깬것인지 여부를 확인할수없어서 LastClearedStageIdBeforeResponse 라는 변수를 새로 만들어 수정하였습니다.

save last stage clear before response and check

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs

1. 이벤트던전 바로가기가 가능하게 수정합니다
1. 이벤트아이템 등 이벤트던전인 수급처인 아이템에서 수급처 바로가기를 확인합니다 
https://github.com/planetarium/NineChronicles/issues/4507

fix event dungeon shortcut condition

---

nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs

획득처가 소환인 아이템에 아이콘을 적용합니다.
아우라같이 '소환' 으로 획득할 수 있는 아이템의 아이콘을 확인합니다
https://github.com/planetarium/NineChronicles/issues/4510

fix acquisition place icon name

---

nekoyume/Assets/_Scripts/UI/Widget/Collection.cs

1. 장비 레벨순 정렬에 대한 탭 아이템의 텍스트 키를 변경합니다.
1. 컬랙션에서 장비 레벨순 정렬 텍스트를 확인합니다. 
https://github.com/planetarium/NineChronicles/issues/4503

change level tap l10n key

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionItemFilterPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemFilterPopupBase.cs

1. 아이템 필터 팝업에 l10n 키를 적용합니다
2. 업그레이드 옵션 시작 레벨을 0으로 설정합니다.
1. 영어가 아닌 다른 언어로 아이템 필터 팝업을 확인합니다
2. 0강 필 옵션이 제대로 작용되는지 확인합니다
https://github.com/planetarium/NineChronicles/issues/4500
https://github.com/planetarium/NineChronicles/issues/4502

change upgrade start level(0 -> 1), apply l10n key (4500 & 4502)

---

nekoyume/Assets/_Scripts/UI/Module/CollectionMaterialInfo.cs

컬랙션에서 메터리얼 아이템 상세정보의 텍스트 표시 방법을 변경합니다.
1. 업그레이드가 필요 없는 장비 / 칭호 / 코스튬의 경우 보유수량 / 필요업그레이드에 대한 텍스트가 표시되지 않습니다.
2. 필요 텍스트 표기 조건: 도감을 활성화하기 위한 아이템의 갯수가 2개 이상이거나 필요 강화수치가 1 이상
3. 현재 보유 수량 텍스트 표기 조건: 필요 텍스트 조건이 표시된 상태에서 해당 아이템을 갖고 있는 경우
컬랙션에서 아이템 정보를 확인합니다
https://github.com/planetarium/NineChronicles/issues/4485

change collection materialinfo active condition

---

nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs

_page 값이 초기화되지않아서 해당값을참조하고있는곳에서 이전값을 그대로사용하여 발생했던 문제.

fix market page index unreset

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

아바타 생성시 룬 인벤토리 상태를 초기화해줍니다.
아바타를 새로 생성하고 인벤토리를 확인합니다.
https://github.com/planetarium/NineChronicles/issues/4623

init avatar state after avatar created

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
nekoyume/Assets/_Scripts/UI/Module/Lobby/StakingMenu.cs

1. 인게임 몬스터콜렉션 메뉴의 VFX가 알림이 있을때만 뜨도록 변경했습니다.
2. 블록인덱스를 구독하여 정보를 업데이트하던 부분을 enable 되어있을때만 처리하게 disposable 관리를 추가했고, 매 OnEnable마다 다음 BlockIndexSubject의 OnNext를 기다리지 않고 tip을 가져다가 한번씩 업데이트를 하도록 바꿨습니다.
resolve #4592 , #4615

fix staking menu UI update logic and vfx

---

.github/workflows/ios-build-and-release.yml

1. change ios cicd runner image to `macos-13`
2. resolve #4393 
3. iOS SDK 버전을 17.* 로 올리기 위해 Xcode 버전을 14.* 이상으로 올려야 합니다. Xcode 버전을 올리기 위해선 macos 버전이 올라가야 합니다. macos 13부터 Xcode 14를 지원하는데, 저희가 사용하던 macos-latest는 macos 12인 상태여서 https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources 를 참고하여 runner image를 변경하였습니다.
check it https://github.com/planetarium/NineChronicles/actions/runs/8463902410/job/23188203100#step:6:292 and action

change ios cicd runner to macos-13

---

nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs

fix combination slot null exception
모래시계 사용시 제작슬롯에서 state가 없어서 null exception이나는 부분 처리입니다.
case SlotType.Appraise: 부분에서도 state 관련 null체크가 있어서 동일하게 체크 추가해주었습니다.

fix combination slot null exception

---

.github/workflows/build.yml

Add Naver cloud API Keys for update CI pipeline.
9c-toolbelt will purge Naver Cloud global CDN instead of AWS Cloudfront

Add Naver cloud api key for CDN Invalidation

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

아바타 생성시 'await RxProps.SelectAvatarAsync(eval.Action.index);' 를 추가적으로 호출해줌에 따라 불필요하게 두번 초기화되는 것같은 로직들을 정리합니다.
- 기존 초기화하는 부분이 다릅니다
- 기본 초기화 로직은 현재스레드(매우 높은 확률로 메인스레드)에서 돌지만, 해당 로직들은 스레드 풀에서 돕니다
- 기존 제거한 로직과 RxProps.SelectAvatarAsync메서드 안에서 실행시켜주는 룬 초기화 방식이 다릅니다.
캐릭터를 새로 생성하고 상태에 문제가 없는지 확인합니다.
https://github.com/planetarium/NineChronicles/issues/4623

remove redundant avatar init logic

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Blockchain/BlockRenderHandler.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Game/Stage.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/State/Subjects/HammerPointStatesSubject.cs
nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
nekoyume/Assets/_Scripts/UI/Module/Button/SimpleCostButton.cs
nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
nekoyume/Assets/_Scripts/UI/Module/Currency/DailyBonus.cs
nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/BoosterPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs

1. resolve #4656 
2. https://github.com/planetarium/lib9c/pull/2502 의 내용을 클라이언트에 반영하는 PR입니다.
3. 하드포크로 인해 더 이상 `AvatarState.actionPoint`와 `AvatarState.dailyRewardReceivedIndex`를 사용하지 않습니다. 이를 클라이언트에서 반영하고, 액션 렌더에서 갱신할 수 있도록 수정했습니다.
4. 앞으로는 현재 아바타의 ActionPoint를 클라이언트에서 알고싶거나 관리하고 싶다면 `ReactiveAvatarState.ActionPoint`와 `ReactiveAvatarState.ObservableActionPoint`를 사용하면 됩니다. 기존에 `States.Instance.CurrentAvatarState.actionPoint` 를 통해 접근하던 코드는 모두 변경했습니다.
5. dailyRewardReceivedIndex 또한 `ReactiveAvatarState.DailyRewardReceivedBlockIndex`와 `ReactiveAvatarState.ObservableDailyRewardReceivedBlockIndex`을 통해 관리되도록 수정했습니다.
6. ChargeAp와 DailyReward는 예외 없이 실행될 경우 무조건 `DailyReward.ActionPointMax`로 값이 갱신되는 것을 알기에, GetState 없이 Update하도록 변경했습니다. 더 이상 DailyReward의 action render에서 AvatarState를 갱신하지 않습니다.
7. 기존에 …

reflect Hardforking of DailyReward and ActionPoint

---

nekoyume/Assets/Resources/ScriptableObject/LiveAssetEndpoint.asset

1. 싹 다 https://assets.nine-chronicles.com/live-assets/ 를 바라보게 바꿉니다.
2. 해당 url은 github.com/planetarium/NineChronicles.LiveAssets 저장소의 내용과 동기화된 파일 서빙 페이지입니다.
1. 실행하고 잘 나오나 보면 됩니다. 잘 나옵니다.
resolve #4679

change live asset url

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs

1. 조사 결과, HAS 렌더에서 1회성 버프를 적용하는 로직이 전혀 클리어하지 못한 HAS 액션을 클리어한것처럼 보여주는 버그를 유발하고 있었습니다.
2. 이에, HAS 렌더를 할 때는 1회성 버프가 정상적으로 적용될 수 있는 케이스에만 올바른 버프를 적용하도록 고쳤습니다.
3. 추가로, 클라이언트에서 선택한 1회성 버프를 캐싱하고 가져오는 로직이 있어서 이때 stage id에 대해서도 검증을 하도록 수정했습니다.
resolve #4355

fix bug about HAS simulate and CrystalRandomSkill

---

nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs

1. Apply `GameConfigState.ShatterStrikeMaxDamage` to `StageSimulator`.

fix: shatter strike max damage of rendering `HackAndSlash` action

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

1. 현재 클라이언트의 아레나 리스트는 헤드리스에서 arenaParticipants 쿼리를 통해 가져온 모델을 토대로 렌더하고 있습니다.
2. 그런데 이 리스트는 액션을 즉시 반영하진 않아, 전투 후에 갱신하려고 해도 갱신되지 않은 점수를 보여주는 현상이 있었습니다.
3. 그래서 RxProps.Arena.UpdateArenaInformationOrderedWithScoreAsync()에서 점수를 다시 GetState하고 등수를 재계산하는 로직을 추가했습니다
4. 추가로 BattleArena 액션 렌더시 각 상태를 업데이트하는 로직이 Forget으로 비동기 처리되고 있었는데, await으로 기다리고 렌더하도록 변경했습니다.
resolve #4584

add updating player arena score and rank when render BattleArena

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

1. 1회성 버프 상태가 존재할때, skillIds에 값이 있는지 체크하지 않고 무작정 1회성 버프를 가져오는 버그가 있었습니다.
2. HackAndSlashRandomBuff 따위의 액션으로 skillIds에 값이 채워졌을때만 스킬을 가져오도록 변경했습니다.

fix condition checking about crystal random skill state

---

nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs

base.OnClickButton에서 OnSubmit...이 실행된 뒤 CheckCost를 하는 바람에 LocalLayer가 적용된 뒤 비용을 계산해서 경고를 띄우는 로직으로 돌아가고 있었습니다.
resolve #4756

fix ConditionalCostButton.OnClickButton

---

nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
nekoyume/Assets/_Scripts/Helper/Util.cs
nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs

1. LiveAssetManager가 리소스를 다운로드하는데 실패했을 경우, 추후 재시도 할 수 있게 코드를 변경했습니다.
2. `Util.DownloadTexture` 메소드가 null로 텍스쳐를 만들어 캐싱하는 경우가 없도록 코드를 수정했습니다.
3. PatrolReward가 쿼리 실패로 초기화되지 않았을때, 필요한 경우 다시 쿼리를 이용해 초기화를 할 수 있도록 변경했습니다.
resolve #4753

retry initializing when fail to connect to services

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

1. 스테이지 클리어 후 결과 화면에서 스테이지-이후 뒤로가기를 통해 월드맵에 가면 월드맵 UI의 정보가 업데이트 안되는 문제가 있었습니다.
2. WorldMap의 ViewModel이 업데이트 안되는 문제라서 액션 렌더에서 뷰모델 업데이트를 하도록 수정했습니다
resolve #4396

add invoking SetWorldInformation at HAS rendering

---

nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
nekoyume/Assets/StreamingAssets/Localization/common.csv
nekoyume/Assets/_Scripts/Blockchain/Agent.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs
nekoyume/ProjectSettings/ProjectSettings.asset

1. 게임 접속 전 타이틀 화면에서 키를 백업할 수 있도록 했습니다.
2. 게임에 정상적으로 접속하지 못하는 상황(점검, 업데이트 필요 등)에서 키를 백업할 수 있도록 했습니다.
3. 비밀번호가 설정되지 않은 QR코드를 임포트하면 자동으로 로그인되도록 수정했습니다.
resolve #4770

add keystore backup to many case

---

nekoyume/Assets/_Scripts/Game/Battle/Stage.cs

처음 stage에 입장하는 경우, 이전에 출력되었던 위젯이 잠깐 보이는 현상이 있어 stage입장시 던전의 background의 alpha값을 1로 고정하도록 수정하였습니다.
던전 입장시 배경이 크로스페이드되지 않고 alpha값이 1로 바로 적용되는지 확인합니다 
https://github.com/planetarium/NineChronicles/issues/4650

fix crossfade-background on enter stage

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

1. move SetWorldInformation invoking at HAS rendering for avoid exception.
2. onEnterToStageEnd의 콜백이 UniTask.Void 안에서 실행되고 있어서 WorldMap.SetWorldInformation을 실행할때 예외를 발생시키고 있었습니다.
1. try to render HAS action

move SetWorldInformation invoking at HAS rendering

---

nekoyume/Assets/Resources/UI/Icons/Item/100000.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/200000.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201000.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201001.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201002.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201003.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201004.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201005.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201006.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201007.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201008.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201009.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201010.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201011.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201012.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/201013.png.meta
nekoyume/Assets/Resources/UI/Icons/Item/202001.png.meta
nekoyume/Assets/Resources/UI/Materials/Distortion_Stencil.shader
nekoyume/Assets/Sprites/Background/Combination/Combination_Upgrade/bg_combination_Upgrade.png.meta
nekoyume/Assets/Sprites/Background/MainMenu/Event/Valentine/bg_valentine_bg_00.png.meta
nekoyume/Assets/Sprites/Background/MainMenu/Event/Valentine/bg_valentine_bg_01.png.meta
nekoyume/Assets/Sprites/Background/MainMenu/Event/Valentine/bg_valentine_bg_02.png.meta
nekoyume/Assets/Sprites/Background/MainMenu/Event/Valentine/bg_valentine_bg_08.png.meta
nekoyume/Assets/Sprites/Background/MainMenu/Event/Valentine/bg_valentine_bg_12.png.meta
nekoyume/Assets/Sprites/Background/MainMenu/Event/Valentine/bg_valentine_bg_13.png.meta
nekoyume/Assets/Sprites/Background/MainMenu/Event/Valentine/bg_valentine_bg_14.png.meta
nekoyume/Assets/Sprites/Background/MainMenu/Event/Valentine/bg_valentine_monster_01.png.meta
nekoyume/Assets/UIResources/Content/Effect/Common/Fx_Helix_01.png.meta

문제가 발생한 이미지의 IOS 포맷설정이 따로 오버라이드되어있어 제거해주었습니다.
빌드에 포함해서 테스트진행해봐야합니다.

unused override for ios

---

nekoyume/Assets/Resources/Video/21-9_render_texture.renderTexture
nekoyume/Assets/Resources/Video/intro_video.renderTexture

안드로이드 특정 기기에서 사용할 수 없는 렌더텍스처 포멧을 사용하는 경우가 있어 수정하였습니다.
이슈가 발생한 기기(HUAWEI Y7 Prime 2019)에서 룬 조각 소환 연출이 제대로 진행되는지 확인합니다.
https://github.com/planetarium/NineChronicles/issues/4811

change render texture depth stencil format for android

---

nekoyume/Assets/_Scripts/Game/AssetManagement/ResourceManager.cs
nekoyume/Assets/_Scripts/Game/Game.cs

지금 어드레서블을 따로 초기화해주고있지 않아 처음 리소스를 로드할 때 어드레서블 초기화 작업이 진행되고 있습니다.
이로 인해 처음 리소스 로드가 느려질 수 있어 앱 시작시 어드레서블을 초기화하도록 수정합니다.
https://github.com/planetarium/NineChronicles/issues/4830

initailize addresable on app start

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionRegistrationPopup.prefab

콜랙션 아이템 팝업의 텍스트 정렬을 수정합니다.
콜랙션 아이템 팝업의 텍스트 정렬이 정상적인지 확인합니다.
https://github.com/planetarium/NineChronicles/issues/4828

fix item tooltip popup layout in collection

---

nekoyume/Assets/_Scripts/Game/Battle/Stage.cs
nekoyume/Assets/_Scripts/Game/Character/StageMonster.cs

전투 종료시 몬스터 리소스를 제거합니다.
전투에서 패배 후 다시하기 & 로비로 돌아간 후 다시 해당 스테이지에 진입하여 문제가 없는지 확인합니다.
https://github.com/planetarium/NineChronicles/issues/4842

remove monster asset when lose player

---

nekoyume/Assets/_Scripts/L10n/L10nManager.cs

모바일 환경에서 접속시 번역어테이블을 받는과정에서 간헐적으로 Task 가 깨지는 문제 로그추가 및 로드 재시도 추가.
관련에러로그 확인시 상세정보가 안나와서 추적불가.
```
[2024-4-24 08:59:08] System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Net.Http.MonoWebRequestHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00000] in <00000000000000000000000000000000>:0 
at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in <00000000000000000000000000000000>:0 
at …
```

add task cancel log and retry when fail load

---

nekoyume/Assets/_Scripts/L10n/L10nManager.cs

HttpClient를 UnityWebRequest로 변경
HttpClient 인스턴스가 많아지면서 소켓제한으로 요청실패하는것이 의심되어 수정.

change http request method

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs

언제부터인가 IntroScreen오브젝트의 초기화시점이 당겨지면서 게스트진입 버튼 초기화가 CommandLIneOption 이 세팅되기전에 실행되며 정상적으로 초기화되지않는문제로 확인되었습니다.
게스트진입 버튼 초기화 시점을 CommandLineOption 이후 시점으로 변경하고 추가 로그및 중복실행방지코드를 작성하였습니다.
OnLoadCommandlineOptions이 여러번불리는경우가 생기는것같은데 정리가 한번 필요해보입니다.

fix guest button refresh timing

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
nekoyume/Assets/_Scripts/Game/Game.cs

1. State 캐싱에 버그가 있었습니다. 캐싱할때 AccountAddress를 무시하고 그냥 address만 캐싱하다보니, 다른 account에 같은 address로 상태를 캐싱하는 경우 잘못된 값을 캐시에서 가져오는 문제가 있었습니다.
2. 그래서 Dictionary의 키가 AccountAddress와 Address를 같이 저장하도록 수정했습니다.
3. 수정 이후 링크된 이슈와 관련된 버그는 재발하지 않았습니다.
resolve #4871

bug fix about cached state

---

nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionRegistrationPopup.prefab

- closes #4208 
`Widget`을 상속받은 ui는 `Show` 메서드 호출 시점에서 object 순위를 맨 위로 올려주도록 하고 있습니다. (모바일 한정)
`CollectionRegisterationPopup` 안에서 사용하던 `EquipmentTooltip도 Widget을 상속받아서 오브젝트 순위를 맨 위로 올려주다가 layout 순서가 꼬인 것으로 보입니다.
1. BuildSettings 에서 target platform을 android, ios 중 하나로 설정합니다. (clo 파일 세팅 필요)
2. Collection UI에서 등록 팝업을 열 때 확인 가능합니다.

fix CollectionRegisterationPopup layout

---

nekoyume/Assets/_Scripts/Game/Battle/RaidStage.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Game/Prologue.cs
nekoyume/Assets/_Scripts/Timeline/TimeScale/TimeScaleBehaviour.cs
nekoyume/Assets/_Scripts/Timeline/TimeScale/TimeScaleTrack.cs
nekoyume/Assets/_Scripts/UI/Widget/Menu.cs

월드보스 전투가 끝나고 타임스케일을 1로 리셋합니다
월드보스 연출에서 속도가 느려지는 부분(에디터의 경우 RaidStage 오브젝트의 하위 오브젝트로 생성된 연출 오브젝트를 클릭한 후 타임스케일이 변경되는 타이밍을 확인가능)에 스킵을 하여 속도가 느려지지 않는지 확인합니다.
https://github.com/planetarium/NineChronicles/issues/4892
https://github.com/planetarium/NineChronicles/issues/4470

reset time scale on clear battle

---

nekoyume/Assets/_Scripts/UI/Module/Button/SimpleCostButton.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs

루비 더스트 재화 관련 팝업 / 코스트 제한 체크 로직을 추가합니다.
1. 루비더스트가 부족한 경우 루비더스트를 재화로 사용하는 재화에 재화가 부족하다는 표시가 뜨는지 확인합니다.
2. 상단 메터리얼 UI에서 루비더스트 재화 클릭시 정보가 표시되도록 변경합니다.
3. 루비더스트 구매 관련 정보는 골드더스트와 같이 Shop으로 표시되도록 설정하였습니다.
https://github.com/planetarium/NineChronicles/issues/4841

add ruby dust material control

---

.github/workflows/android-build-and-release-for-9ck.yml
.github/workflows/ios-build-and-release-for-9ck.yml

1. release 브랜치에 커밋을 쌓거나 다른데서 태그를 달면 9cK 빌드 및 내부테스트 배포가 올라가도록 구축했습니다.
1. check this https://github.com/planetarium/NineChronicles/actions/runs/9204570897/job/25319251866
resolve #4950

android CICD for 9cK

---

nekoyume/Assets/_Scripts/UI/Widget/Hud/HudContainer.cs

전투시에만 hud컨테이너 최대높이 지정하도록 수정합니다.
(캐릭터 선택창 등에서 칭호가 hud컨테이너로 조정되고있기 떄문에 이에 영향을 주지 않기 위함입니다)
https://github.com/planetarium/NineChronicles/issues/4970

set maxheight on battle render

---

nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab

클라이언트 시작후 처음 룬 정보 텍스트가 활성화될때 l10n키에 있던 기본 값(UI level up)으로 인포 텍스트 정보가 갱신되어 '룬 제작' 텍스트가 출력되어야 할 상황에도 룬 업그레이드 텍스트가 출력되던 현상을 수정합니다.
#4998

remove default l10n key from info text of ui_rune

---

nekoyume/Assets/_Scripts/Game/Character/Actor.cs

같은 종류의 버프 캐스팅을 여러번 하는 경우(예: 광역 디버프)
캐스팅 연출을 1회만 수행하도록 변경합니다.
https://github.com/planetarium/NineChronicles/issues/5008

remove duplicate buff cast

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs

ResponseUnloadFromMyGarages, ResponseClaimItems, ResponseMintAssets
세가지 액션을 통해 데이터를 받아오는 경우, 최신 상태의 아바타 값으로 데이터를 셋팅하는 것이 아닌 액션의 결과로 데이터를 셋팅하는 것으로 변경하였습니다. 다만 현재 구현상 메일함을 통해 새로운 메일이 왔다는 레드닷이 뜨고 메일을 수령하여 어떤 아이템을 획득했는지에 대해 확인할 수 없고, 클라이언트가 체인과 연결이 일시적으로 끊긴 경우 보상이 수령 안되는 이슈가 또 발생할 가능성이 남아있습니다.
연결 끊김 관련 이슈는 아래 이슈에서 별도 처리 예정입니다
https://github.com/planetarium/NineChronicles/issues/5117
https://github.com/planetarium/NineChronicles/issues/5135
https://github.com/planetarium/NineChronicles/issues/5129

fix get item from mail on service

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs

- resolve #5124 #5140, etc
- 렌더시점에 FAV를 가져오는 부분을 액션의 실행결과가 반영된 OutputState를 쓰도록 수정
- AP포션, 모래시계, 조합 재료와 같은 액션 스테이징 시점에 미리 차감시켜두고 렌더 시점에 수량을 복구시킬때 상태 정리가 안되는 문제를 해결하기 위해 OutputState에서 꺼내온 아바타를 반영하기전에 레이어를 미리 제거하도록 처리

렌더 시점의 재화 잔고, 아이템 재료 수량이 맞지않는 버그 수정

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CelebratesPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs

- 메일읽음처리시 블록높이따라 상태 초기화를 호출하도록 처리
- 퀘스트완료처리시 상태 초기화를 비활성화
- 축하팝업에서 상태 초기화를 비활성화
- resolve #5133 #5124

로컬레이어의 상태 초기화처리 수정

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Game/Battle/Arena.cs

아레나 전투 후 인벤토리가 정상적으로 리프레쉬 되도록 변경합니다
#5164

fix refresh inventory after arena

---

nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs

- resolve #5188
- AddNewMail에서 AvatarState를 Modify하지 않아서 해당 메일에 New flag가 바뀌지 않는게 원인이었습니다.
https://github.com/planetarium/NineChronicles/assets/3193043/803fe8e9-933d-4946-b069-895508894e57

ClaimItems, UnloadFromMyGarages 에서 메일 알림처리 버그 수정

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs

1. change QuestPopup._questList set to use SetValueAndForceNotify, and update _questList when on invoking ReceiveAll()
2. _questList의 set 방식을 .value = ... 에서 SetValueAndForceNotify를 쓰게 바꿨고, Receive all을 한 뒤 QuestPopup이 갖고있는 _questList를 갱신하지 않고 있어서 이를 갱신하게 수정했습니다.
1. receive all at QuestPopup.
resolve #5180 (https://github.com/planetarium/NineChronicles/issues/5180#issuecomment-2188770097)
https://github.com/planetarium/NineChronicles/assets/48484989/aebc4f1f-cea2-42eb-b10f-2df6b8c76837

Fix bug about 'receive all' at QuestPopup

---

nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs

- resolve #5176
아레나에서 다른 유저의 정보를 볼 수 있는 Friend Info Popup의 Stat 수치에 룬 레벨 보너스가 적용되지 않은 것이 원인. (CP에는 룬 레벨 보너스 적용됨)
같은 장비, 룬으로 UI에서 표시해주는 수치를 확인함
인벤토리 내 스탯 확인(AvatarInfoPopup)
아레나 목록의 친구 스탯 확인(FriendInfoPopup)
**Before**
**After**

apply rune level bonus to AvatarStats in FriendInfoPopup

---

nekoyume/Assets/_Scripts/Extensions/InventoryExtensions.cs
nekoyume/Assets/_Scripts/Helper/UnlockHelper.cs
nekoyume/Assets/_Scripts/Helper/UnlockHelper.cs.meta
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

- to resolve #5205 
- move unnessesary methods(`GetAvailableEquipmentSlots`...) from lib9c to client
(https://github.com/planetarium/lib9c/pull/2657)
- add grimoire to `GetAvailableEquipmentSlots`
슬랙에 첨부합니다

fix grimoire bug in inventory

---

nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

1. remove _questList at QuestPopup.cs
2. QuestPopup이 모델을 ReactiveAvatarState같은데서 가져다 쓰지 않고 혼자 갖고있길래 지워버리고 무조건 ReactiveAvatarState에서 관리하도록 했습니다.
1. First step.

remove _questList at QuestPopup.cs

---

nekoyume/Assets/_Scripts/Game/Battle/RaidStage.cs

RaidStage 스크립트에서 _isPlaying = true인 경우 이미 전투중이므로 새로 전투를 하지 못하도록 막고 있는데, 해당 플래그를 true로 설정해주고 ClearBattle스크립트가 호출되면서 바로 _isPlaying이 false로 바뀌며 이와 같은 방지처리를 하지 못하고 있었습니다.
#5177

fix duplicate battle bug

---

nekoyume/Assets/_Scripts/Game/VFX/Skill/BuffController.cs

아이스 실드 타입의 스킬만 아레나에서 캐릭터 반전시 좌우반전 되도록 설정합니다.
아레나에서 Bleed와 같은 액션 캐스트 이펙트가 좌우반전되는지 확인
https://github.com/planetarium/NineChronicles/issues/5101

only flip ice shield vfx

---

nekoyume/Assets/_Scripts/UI/Model/AdventureBossData.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossRewardPopup.cs

입력값 순서가 뒤집혀있어서 정상적으로 수량이 갱신되지 않던 문제 수정하였습니다.

fix adventure boss reward miss calculate

---

nekoyume/nekoyume.sln.DotSettings

프로젝트에서 사용중인 북유럽신화 관련 단어가 오타로 처리되지 않도록 사전에 단어를 추가합니다
https://github.com/planetarium/NineChronicles/issues/5212

add domain name of Norse mythology

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/GetStateExtensions.cs
nekoyume/Assets/_Scripts/UI/Model/AdventureBossData.cs

어드벤처보스 상태갱신 슬로스대응에 맞춰서 최신상태로만 갱신되도록 수정
- 시즌 최초 바운티 시작시 상태갱신이안되어서 시즌이 열리지 않는 것처럼 보이는문제
- 시즌 종료 후 보상수령정보 상태갱신이안되어서 결과보상 팝업이 여러번 다시 뜨는 문제
슬로스로 발생한 두 문제 수정된 것 확인하였습니다.

fix adventurebossdata apply sloth

---

nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs

1. fix key backup feature at main blocking popup
2. 메인화면에서 키 백업을 할 때 Agent initialize가 안돼있어서 address를 못찾고 뻗는 버그를 고쳤습니다.
resolve #5232

fix key backup feature at main blocking popup

---

.github/workflows/android-build-and-release-for-9ck.yml

1. use another secret at 9cK android build
2. 9cK 안드로이드에서 firebase 통계가 안잡히고 있어서 불확실한 env 대신 아예 다른 secret key를 쓰게 변경했습니다.

use another secret at 9cK android build

---

nekoyume/Assets/_Scripts/Extensions/GetStateExtensions.cs
nekoyume/Assets/_Scripts/UI/Model/AdventureBossData.cs
nekoyume/Assets/_Scripts/UI/Module/WorldMapAdventureBoss.cs

어드벤처보스 관련 GetState 실패 관련 문제 수정.
sloth 대응으로 캐싱하는 최신 블록인덱스를 roothash로 갱신하지않는경우 현재블록인덱스에서 하나를뺸것으로 캐싱하도록 수정.
rootHash없이 스테이트를 가져오는경우 캐싱된 블록인덱스와 현재인덱스가 같거나 캐싱된블록인덱스가 큰 경우 캐싱된 rootHash를 사용하여 갱신하는데 현재인덱스로만 갱신을 두번연속하게되는경우 문제가발생할수있었음.
---
gpt요약
문제점: 기존 로직에서 rootHash 없이 상태를 요청할 때 현재 블록 인덱스와 캐싱된 블록 인덱스를 비교하지 않고 직접 갱신하였을 때 문제 발생 가능성 확인
수정 내용:
stateRootHash가 null일 경우 캐싱된 rootHash와 블록 인덱스를 이용하여 안전하게 상태를 조회
현재 블록 인덱스가 캐싱된 블록 인덱스보다 클 경우, 캐싱된 블록 인덱스를 현재 블록 인덱스에서 하나 뺀 값으로 갱신하여 동기화 문제 해결
이러한 변경을 통해 상태 조회의 안정성을 높이고, 잠재적인 동기화 오류를 방지함.

5238 adventureboss getstate bug fix

---

nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/Craft.cs

- resolve #5260 
- avoid collection was modified when select avatar
---
렌더등을 통해 아바타가 업데이트됐을때 ReactiveAvatarState.Address를 구독하고 있는곳에서 상태를 갱신하려다 발생하는 버그로, 원래 의도로 보이는 게임에서 선택된 아바타가 변경됐을때만 상태를 초기화하고 그 이후에는 렌더러에서 업데이트한 상태만 사용하도록 변경합니다.

슈퍼크래프트 갱신 버그 수정

---

nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs
nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

1. change ordering at EnhancementInventory: order by grade -> then by cp
2. 더스트, ap포션에 이어 새 아이템이 상위 목록에 추가될 수 있도록 추가함
resolve #5226

improve inventory ordering

---

nekoyume/Assets/_Scripts/State/States.cs

- resolve #5282
---
`InitRuneSlotStates` 가 호출된 시점에는 아바타 목록이 업데이트될일이 없는걸 기대하고 있는데, 현재 `AddorReplaceAvatarStateAsync`의 비동기처리와 함께 산발적으로 호출되는 문제가 원인으로 추정되어 오류가 발생하고 있습니다.

아바타목록 collection modified 문제 회피

---

nekoyume/Assets/_Scripts/UI/Module/WorldMapAdventureBoss.cs

월드맵 진입시 어드벤처보스 블록갱신이 바로되지않는문제 수정
블록인덱스 갱신을 CurrentState변경에서 예외처리로 초기화해주는부분에서 덮어쓰고있어서 순서변경한것으로 수정진행

fix refresh timing

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AdventureBossNcgRandomRewardPopup.cs

fix popup update timing

---

nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs

ap 포션 부족시 어드벤처보스 전투버튼입력되지않도록 수정.

fix ap potion conditionalbutton cost check

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

플로어 잠금 해제시 헤더매뉴 숫자가 갱신되지 않던 문제 수정

unlockfloor refresh headerdata

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab

1. 스탯 옵션의 아이콘이랑 스킬 옵션의 아이콘 위치가 안맞아서 불편했던 문제를 해결합니다.

update skill option icon position

---

nekoyume/Assets/_Scripts/UI/Model/AdventureBossData.cs
nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
nekoyume/Assets/_Scripts/UI/Widget/AdventureBossResultPopup.cs

어드벤처보스관련 스테이트갱신이 끝나기전에 갱신하는경우 기다리도록 lock처리 및 로딩스크린 제거안되던이슈 수정.
메인페이지에서 리워드 정상적으로 보이지않던 문제 수정

어드벤처보스관련 스테이트갱신이 끝나기전에 갱신하는경우 기다리도록 lock처리 및 로딩스크린 제거안되던이슈 수정.

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

https://github.com/planetarium/NineChronicles/assets/3193043/87d7d09a-597d-4188-b225-7f92d771fb96
---
- resolve #5306
- 아이템 강화시 재료 레이어만 정리를 하고 강화에 사용한 아이템의 레이어를 정리하지 않는게 원인으로 보여서 수정했습니다.

아이템 강화시 결과 아이템이 보이지 않는 문제 수정

---

.gitmodules

`git fetch`, `git submodule update` 와 같은 명령어 실행시 .libplanet 의 fetch 작업을 하지 않도록 합니다.
이는 근본적으로 .libplanet 이 lib9c 에서 checkout 되는 것을 막지는 않습니다.
원래 의도는 `git clone https://github.com/planetarium/ninechronicles --recurse` 혹은 `git submodule update --recursive --` 명령 실행시 .libplanet 이 lib9c 에서 checkout 이 안되게끔 하는것이 목표였습니다.
하지만 이런 기능은 없는 관계로 fetch 기능만 제한하도록 하였습니다.

Prevent updating submodule `.Libplanet` in `Lib9c`

---

nekoyume/Assets/_Scripts/Game/Aura/AuraIceShield.cs

스킬 순서가 꼬였을 때 발생할 수 있는, ice shield버프가 끝났는데 frostbite 애니메이션을 수행하고 굳는 현상을 방지합니다
#5398

fix frostbite animation on disapper aura

---

nekoyume/Assets/_Scripts/State/PetStates.cs

- resolve #5415
- 펫스테이트 업데이트시 잠금처리를 해둔 모든 상태를 풀어버리고 있는데, 대상만 잠금을 풀도록 처리합니다.

Remove target locked pet only

---

nekoyume/Assets/_Scripts/UI/Module/CollectionEffect.cs

- fix #5414 
캐릭터 정보 화면의 스탯 순서와 같은 순서로 정렬함

fix collection effect ordering by stattype

---

nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/AddHammerPopup.cs

아래 오류 수정했습니다.
- 해머만 재료로 넣었을 때 버튼이 눌리지 않음
- 재료로 넣었던 해머의 개수를 수정할 때 예상 경험치가 잘못 계산됨

fix add hammer popup bugs

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/States.cs

1. HAS 렌더시 로컬의 상태와 체인상의 상태가 불일치해서 전투의 재현 결과가 다를 수 있는 문제가 있었습니다.
2. AvatarState, AllRuneState, CollectionState를 강제로 previousState로 갱신한 뒤 전투를 재현하도록 수정했습니다.
resolve #4355 
@ipdae @eugene-doobu @tyrosine1153 @jonny-jeahyunchoi

add force-updating for HAS rendering

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab

- #5392 
메뉴와 워크샵의 버튼마다 EventMark를 추가했습니다. 나중에 LiveAsset에서 원격으로 on/off 하려고 미리 붙여둡니다.
붙여둔 EventMark의 EventContainer key와 적용한 스크린샷은 아래 문서에 정리해두었습니다.
- https://www.notion.so/planetarium/f53b8832189d4457a4069877648e9e0e?v=3e84c0237bb542668f583a692118d0df
- EventContainer 작업 당시 PR : https://github.com/planetarium/NineChronicles/pull/3921

add eventmark to Menu, WorkShop

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs

PromotionContainer에서 예상하지못하는 타이밍에 이벤트팝업을 띄우는 경우가 있음.
이경우 이벤트베너팝업 초기화 타이밍이 어긋나는게될경우 버튼에 이벤트가 안물릴수도있을것같아서 초기화 여부 확인 및 안되있는경우 초기화 하도록 보완.

이벤트 팝업 닫지 못하는 문제 수정

---

nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs

eventDungeonInfo.Value NRE check
eventDungeonInfo.Value가 null인 시점에 shortcuthelper에서 사용하는부분이있어서 예외처리진행.

eventDungeonInfo.Value NRE check

---

nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/WorldBossRewardScreen.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs

1. 월드보스 리워드 UI에서 무조건 WorldBoss UI로 향하던 기능을 제거합니다(Close시 Callback 초기화)
2. UI갱신을 통해 월드보스 상태를 강제 갱신시키는 부분을 마지막으로 갱신된 blockIndex와 비교하여 업데이트하는것으로 변경합니다.
#5481

fix refresh world boss state

---

nekoyume/Assets/Resources/UI/Prefabs/UI_AddHammerPopup.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab

UI Partcle에서 지원하지않는 메터리얼을 사용하여 경고로그가 계속 뜨는 문제 수정하였습니다.
로그빈도가 너무 높아서 퍼포먼스에 저해를 끼칠수있을정도의 이슈입니다.

fix ui particle materials

---

nekoyume/Assets/_Scripts/Game/ActionCamera.cs

연속해서 화면흔들기 연출이나올때 카메라 y위치가 뒤틀리는 문제 수정.
화면흔들기 끝나기 전 y위치로 갱신해야되는데 타겟이있을경우 현재위치 기준으로 y위치를 갱신하면서 틀어지는 문제로 확인.
y값은 기준점이 변하지않으므로 갱신하지않는것으로 수정.

fix y position refresh while shake

---

nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs
nekoyume/Assets/_Scripts/Extensions/GetStateExtensions.cs
nekoyume/Assets/_Scripts/State/States.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs

StateGetter.GetCombinationSlotState로 가져오던 상태를 agent.GetStateBulkAsync로 가져오도록 변경합니다.
그리고 lib9c 수정사항을 적용합니다
https://github.com/planetarium/lib9c/pull/2766
https://github.com/planetarium/lib9c/pull/2768

fix Combination slot migration

---

nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs

모바일상점 페이지를 한번도 들어가지않고 시즌패스 결제를 하는 경우 구매 완료처리시 NRE 로인해 ConfirmPendingPurchase 이 정상적을 불리지 않는 문제 수정.
빈문자열로 카테고리 딕셔너리를 참조하다가 NRE 발생.

fix iap refresh nre

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
nekoyume/Assets/_Scripts/State/States.cs

1. CustomEquipmentCraft 액션을 렌더할때 상태를 병렬로 가져오지 않고 순차적으로 가져오는데, 이때 LoadingHelper의 값이 갱신되면서 제작은 가능해졌지만 실제로 드는 비용 따위는 늦게 갱신되는 경우가 있어 이를 수정했습니다.
resolve #5718

fix rendering sequence about CustomEquipmentCraft action

---

nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs

QR코드 Read시 Backbutton 동작안하는 문제 수정PR입니다.
Back버튼에 지워진 ShowMobile 함수를 사용하고있는것 확인했고, 임포트창 다시띄우는 버튼 불러주는방식으로 수정하였습니다.

qr reader backbbutton fix

---

nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs

- 클라이언트에서 장비 제작 관련 액션을 보내고 나면 해당 슬롯에 또 액션을 보낼 수 없도록 감정 상태가 됩니다.
- 감정상태일 때에는 클라이언트에서 임시로 설정한 아이템이 표시되어야 하고, 이를 액션의 응답이 오면 업데이트 합니다.
- 지금 클라이언트에서 액션을 보내고 슬롯에 임시 장비 상태를 업데이트하는거까지는 되어있는데, 슬롯 업데이트 과정에서 이전에 작업했던 장비 상태를 가져와서 렌더하고 있습니다.
- 이전에 있던 상태를 가져와서 렌더하는거 자체가 불필요한 동작이라 판단하고 제거하였습니다.

remove slot update in Appraise state

---

nekoyume/Assets/_Scripts/Game/Battle/Stage.cs
nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs

이벤트 던전에서 간헐적으로 결과창이 나오지 않아서 진행이 불가한문제 예외처리작업진행 및 원인 분석로그 추가하였습니다.
```battle.ClearStage(stageIdToClear, cleared => done = true);```
의 콜백체인에서 cleared 콜백이 불리지않거나 중간에 익셉션이 불려 콜백체인이 끊킨다거나하는 이슈로  결과창이 안나올수 있는문제가있어, 5초정도 기다린뒤에도 콜백이 불리지않으면 일단 결과창띄워 진행을 막지않는 방식으로 예외처리 추가하였습니다.

fix eventDungeon result not shown

---

nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceEndpoints.cs
nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs

iap 초기화로 인해서 구매요청시 NRE체크 및 예외처리작업

iap exception handle

---

nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs

월드보스 상태가 없는 경우 월드보스 진입시 위 팝업을 통해 크리스탈 체크를 하는 로직을 추가하였습니다.

add check raid enter popup

---

README.md

- It removes deprecated devforum link.
- It replaces docs.nine-chronicles.com link with nine-chronicles.dev (Developer Portal).
1. Read README

Remove deprecated devforum link

---

README.md

1. Replace Discord server invitation links with bitly links to track Discord users from README.
1. Read README and test new bitly links.

Track Discord users from README

---

nekoyume/Assets/_Scripts/UI/Widget/CustomCraft.cs

1. RelationshipSheet의 구조가 바뀌면서 정리해야했던걸 못해서 반영했습니다.
2. 친밀도 구간 MAX를 찾는 로직을 First에서 FirstOrDefault로 바꿨고, `row.relationship >= relationship` 에서 `row.relationship > relationship` 으로 바꿔서 다음 구간을 찾을 수 있게 수정했습니다.
#5967

fix RelationshipGaugeView max value

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

1. lib9c의 변경사항을 반영합니다. lib9c#2854, lib9c#2855
2. MarketService에서 더 이상 판매된 아이템을 저장하지 않기에, 이 정보를 Mail에 저장하기로 했습니다. 이 내용을 클라에서 처리합니다.
3. 액션 렌더도 마켓 서비스에 의존하고 있었어서 고쳤습니다.
#6001 #6003 #6004

bump lib9c and fix ProductMail

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/SeasonPassItemView.prefab
nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs

1. BaseItemView에서 SetActiveSafe를 써서 null 체크를 하게 했습니다.
2. SeasonPassItemView에서 없어서 NRE가 뜨는 오브젝트에 빈 오브젝트를 넣어놨습니다.
#6037

use SetActiveSafe for customCraftArea and fix SeasonPassItemView prefab

---

nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
nekoyume/ProjectSettings/ProjectSettings.asset

https://planetariumhq.slack.com/archives/C062ZS68A21/p1727681386327479?thread_ts=1727681353.965519&cid=C062ZS68A21
가이드 퀘스트가 동작하지 않아서 고쳤습니다.

hotfix 230.1.1

---

nekoyume/Assets/Editor/Builder.cs
nekoyume/ProjectSettings/ProjectSettings.asset

ssia
해당 pr의 Action에서 나온 빌드(iOS M, Android M)로 테스트 진행했습니다.
설정 자체는 Android쪽만 수정하긴 했는데, ci빌드 과정에서 이전 빌드 옵션을 그대로 사용하는건지 iOS에도 영향이 있었습니다.
후에 안전코드용으로 builder에서 옵션 설정 코드 추가하였습니다.

fix mute other audio sources on android

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ConsumableTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_CostumeTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_EquipmentTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_FungibleAssetTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
nekoyume/Assets/Resources/UI/Prefabs/UI_RuneTooltip.prefab
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs
nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs

툴팁을 인식하는데 필요한 부분인 제일 상위의 Detail을 제외하고 하위 오브젝트에 달려있던 EventTrigger들을 모두 제거했습니다.
- close https://github.com/planetarium/NineChronicles/issues/6058
- close https://github.com/planetarium/NineChronicles/issues/6025

delete EventTrigger component in ItemTooltips without Detail, SkillTooltip

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

1. 200230 이후로 계속 판매 메일을 읽어도 읽음 처리가 안되고 있는 상태였습니다. 이걸 고치는 pr이고
2. 판매 메일이 마켓 서비스를 불러서 가격을 로딩하는 대신 Product 정보에 포함된 가격으로 처리하게 바꿨습니다.
resolve #6104

remove MarketServiceClient calling at Read(ProductSellerMail)

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab

1. 몬콜 보상 아이템이 8개까지만 나오고 있어서 10개까지 나오게 프리팹 수정을 했습니다
resolve #6102

add missing reward item view at StakingPopup

---

nekoyume/nekoyume.sln.DotSettings

lib9c/headless에 맞게 코드 규칙을 추가합니다.

apply roslyn-code-rule

---

nekoyume/Assets/_Scripts/UI/Shop/CartView.cs

1. CartView를 닫을때 내용물을 비우지 않아서, 끈 뒤에 다른 상품을 추가하면 합계 가격에 합산되는 버그를 고쳤습니다.
2. 그냥 내용물을 null로 set하게 했습니다.
resolve #6213

add cartItems[i].Set(null,null)

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/PetDescriptionView.prefab
nekoyume/Assets/Resources/ScriptableObject/PetRenderingData.asset
nekoyume/Assets/_Scripts/Game/ScriptableObject/PetRenderingScriptableObject.cs
nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
nekoyume/Assets/_Scripts/UI/Module/PetDescriptionView.cs
nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs
nekoyume/Assets/_Scripts/UI/Widget/PetSelectionPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs

아래 이슈의 사이드이펙트 수정입니다.
https://github.com/planetarium/NineChronicles/pull/6212
기존에는 PetDescriptionView프리팹을 사용하는 프리팹에서 수동으로 이거저거 바꿔서 썻나.. 싶은데
뭔가 기존 동작하고 동적으로 생성할 PetDescriptionView 프리팹과 동작이 안 맞는 것들이 있어서
기존 동작과 동일하게 동작하도록 프리팹 구조와 코드를 수정했습니다.

fix pet inventory

---

nekoyume/nekoyume.sln.DotSettings

- lib9c/headless등에 적용된 StyleCop 코드 규칙에 맞게 코드 변경을 진행 후 추가적으로 수정되는 스타일입니다.
- StyleCop 규칙에서 using문에 적용된 namespace를 작성할 때 무조건 namespace의 풀 네임을 적용해야 하는 규칙이 있습니다
- 이를 대비하기 위해 라이더에서 'PreferQualifiedReference' 옵션을 True로 설정해두었는데 이로 인해 필드의 클래스를 지정할때에도 자동적으로 full namespace가 들어가는 케이스가 있고 이게 신경쓰이는 상황이 반복되어 False로 옵션을 변경해두었습니다
```
SA1210: Using directives should be ordered alphabetically by the namespaces.
SA1135: Using directive for namespace 'Lib9c.Tests.Action' should be qualified
```

fix code style for namespace

---

nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs

월드버튼의 경우 모바일에서 터치인풋을했을경우 애니메이션상태가 초기화되지않는부분 보완
터치인풋의경우 ObservablePointerExitTrigger가 누르자마자 다른오브젝트로 가려지게되면 호출이안될수있음.

Fix WorldButton  touch input handling

---

nekoyume/Assets/_Scripts/Blockchain/BlockManager.cs

- 안드로이드 32비트가 아닌 경우 로컬 제네시스가 없는 경우 웹에서 제네시스를 받아오지 못하는 현상을 수정합니다.
- 32비트인경우는 고려하지 않았습니다.

fix android exception handling

---

nekoyume/Assets/AddressableAssets/UI/Module/Lobby/SeasonPassBtn.prefab

시즌패스버튼 잠겨있을경우 이름중복해서 나오는문제 수정.

fix seasonpass title duplicated when locked

---

nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
nekoyume/Assets/_Scripts/Game/Character/FriendCharacter.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/ClaimGiftsResultScreen.cs

- close https://github.com/planetarium/NineChronicles/issues/6387

fix full constume preview

---

nekoyume/Assets/_Scripts/UI/Widget/Summon.cs

1. Summon*** 액션 렌더에 헤더메뉴의 재화를 갱신하는 코드를 넣었더니, Summon UI가 꺼져있어도 각종 가루들이 나오는 버그가 생겼습니다.
2. 그래서 그걸 Summon Widget이 활성화 되어있을때만 갱신하도록 수정했습니다.
resolve #6402

update headermenu when only enabled state

---

nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs

시즌패스 프리미엄 상품 구매시 프리미엄상품이 하나만있는경우(plus, all 없이) 기존 프리미엄플러스 UI 에 프리미엄상품을 랜더링하는방향으로 수정하였습니다.

fix seasonpass premium popup layout

---

nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs

1. 이미 다른 플래닛에서 플렛지가 된적이 있지만, 소셜로그인 없이 타 플래닛에서 새로 시작하려는 유저는 플렛지를 못하는 상태였습니다.
2. 그래서 소셜로그인이 안된 상태로 플렛지를 시도하는 경우, 백엔드에서 이미 가입한적 있는 유저인지 체크한 뒤 플렛지를 해주는 api를 만들어주셨습니다.
3. 이에 대한 대응을 추가한 PR입니다.
resolve #6401 
확인과정: https://planetariumhq.slack.com/archives/CBU2JFAF3/p1732066705422459

split pledge api for no token

---

nekoyume/Assets/_Scripts/Extensions/ArenaSheetExtensions.cs

1. 헤임달 시즌이 다음부터 10으로 나와야하는데, 계산식때문에 이미 지나간 9가 한번 더 나오고 있어서 수정한 PR입니다.
2. 기존 코드를 억지로 뜯어고쳐서 돌아가게만 만든거라 리팩토링이 필요한 상태입니다.
resolve #6408

fix GetSeasonNumber method

---

nekoyume/Assets/_Scripts/Game/Scene/LoginScene.cs

1. 키 임포트를 해서 소셜로그인을 스킵한 경우엔 애시당초 플렛지를 안하고있어서 그거랑 별개로 플렛지 체크는 하도록 고쳤습니다
resolve #6401

fix pledge check

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs

- PrepareHackAndSlash 액션전의 아바타스테이트를 갱신한뒤 착용정보를 outputstate로 현재 AvatarState를 갱신시키는 과정에서 정상적으로 착용정보가 갱신되지않는것으로 파악됨.
- UpdateCurrentAvatarItemSlotState함수에서는 CurrentItemSlotStates 정보만을 갱신시킴.
- 스테이지 시뮬레이터에서 착용정보를 찾는방식은 AvatarState의 아이템중 착용된 아이템을 확인하는 방식으로 진행됨. ([Player.Equip 메소드](https://github.com/planetarium/lib9c/blob/4e68199dd3aee71b0f0b984af0a4bc97a6b352b8/Lib9c/Model/Character/Player.cs#L283))
- UpdateCurrentAvatarItemSlotState시 AvatarState의 인벤토리에 착용정보도 갱신시키는 방향으로 수정
- 에디터에서 수정 확인 완료.
- 나름 히스토리를 파악해보려했으나 전부 수정된지 오래된코드로보여 언제부터 해당상황이 발생했는지는 확인하기 어려움.
- 기존에는 시뮬레이터에서 아이템슬롯정보를 직접 넣었던것이 바뀌면서 발생한문제인것같기도함.
- 수정이 사이드이팩트가 없을지 확인 필요.
- 클라에서는 코스튬뿐만아니라 장비까지도 액션이전의것으로  시뮬레이션하기때문에 스팩이 확달라지는경우 결과가 달라졌을수있었음.

fix costume equipment error

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/SummonItemView.prefab
nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs

110뽑시 소환 아이템의 등급 배경이 정상 적용되지않는 문제 수정.
hsv 관련스크립트가 오브젝트가 많은 경우 정상동작하지않는문제로 보임. 등급별이미지를 직접사용하는식으로 변경.

fix summon itemview grade color error

---

nekoyume/Assets/AddressableAssets/UI/Module/ItemView/SummonItemView.prefab

소환창결과화면 아이템 버튼 안눌리던 문제 수정
hsv 작업진행하며 사용하지않는 이미지 제거했더니 raycast타겟이 켜져있는게 하나도없어서 안눌렸던 문제였습니다.

fix item view raycast

---

nekoyume/Assets/_Scripts/UI/Module/Currency/IAPMileage.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

마일리지 카테고리가 없더라도 iap 상점에서 헤더메뉴에 마일리지 항상보이도록 변경
(토르에서 마일리지상품이 없더라도 마일리지 적립은되는 상태로 진행하는것을 보완하기위함)
헤더메뉴 클릭시 수량 전체 표시방식으로 변경

fix header mileage

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

sloth업데이트 이후 현재 상태를 가져오기 위해 10초 대기 후 상태를 가져오던 로직을 수정합니다.

remove wait 10 seconds logic

---

nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
nekoyume/Assets/_Scripts/UI/Widget/LobbyMenu.cs

null체크가 안되있던 부분을 보강합니다.
(해당 케이스 제외하고 null체크 되어있는 것 확인했습니다)

fix thor schedule null check

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs

월드보스에서 연습결과창에서 아이템나오는문제 수정하였습니다.
기존 아이템표현하는 프리팹을 2종류로 나누면서 발생한문제로 보입니다.

fix worldboss practice reward

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

- 노드와 통신해서 시트를 가져올때 블록해쉬대신 StateRootHash를 사용하도록 변경합니다.
- resolve #6582 
- https://github.com/planetarium/NineChronicles.Headless/pull/2658 와 함께 머지되야합니다.

GetSheets Use StateRootHash instead of BlockHash

---

nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
nekoyume/Assets/_Scripts/Blockchain/Agent.cs
nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
nekoyume/Assets/_Scripts/Extensions/GetStateExtensions.cs
nekoyume/Assets/_Scripts/State/States.cs

- GetStateBulkAsync에서 블록팁해쉬대신 StateRootHash를 쓰도록 변경합니다.

Use GetBulkStateByStateRootHash instead of GetBulkStateByBlockHash

---

nekoyume/Assets/_Scripts/Multiplanetary/PlanetId.Define.cs
nekoyume/Assets/_Scripts/Multiplanetary/PlanetId.cs
nekoyume/Assets/_Scripts/PushNotifier.cs

add planet name to push text

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

메세지팩 역직렬화 실패관련 익셉션 헨들링 코드를 추가합니다.
원인 에러
```
[RPCAgent] OnRender()... Failed to deserialize ActionEvaluation. MessagePack.MessagePackSerializationException: Failed to deserialize Nekoyume.Action.NCActionEvaluation value. ---> System.NotSupportedException: MessagePackWriter/Reader overload is not supported in MessagePackSerializer.NonGenerics.
at MessagePack.MessagePackSerializer+CompiledMethods.ThrowRefStructNotSupported () [0x00001] in C:\Planetarium_Corp\NineChronicles\nekoyume\Library\PackageCache\com.neuecc.messagepack@0c02b688ab\MessagePackSerializer.NonGeneric.cs:325 
at MessagePack.MessagePackSerializer+CompiledMethods+<>c.<.ctor>b__13_5 (MessagePack.MessagePackReader& reader, MessagePack.MessagePackSerializerOptions options) [0x00001] in …
```

add messagepack exception handle

---

nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs

https://planetariumhq.slack.com/archives/CBU2JFAF3/p1734678311600799
클라이언트 액션 타임 아웃 시간이 너무 길어서(6분) 장애 발생 시 로딩이 멈춘 것 처럼 보일 수 있는 여지가 있어 해당 시간을 1분으로 조정합니다.

change action time out 360 to 60 sec

---

nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs

아레나 로딩스크린 등장후 배틀아레나 요청을 넣기전에 혹시 모를 이슈가 생길경우 로비화면으로 나오도록 예외처리 진행합니다.

add battlearena exception handle

---

nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs
nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs

- resolve #6668 
- 코스튬 장착시 에셋 로드에 실패하면 장비 장착 로직으로 폴백되도록 처리합니다.
- 장비 장착로직에선 기본적인 폴백(기본값)이 설정되있기 때문에 추가 처리는 하지 않았습니다.

코스튬 장착 실패시 장비 장착 로직을 타도록 처리

---

nekoyume/Assets/_Scripts/Game/Battle/Stage.cs
nekoyume/Assets/_Scripts/Game/Character/BreakthroughCharacter.cs
nekoyume/Assets/_Scripts/Game/Controller/VFXController.cs
nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/UI/Widget/Animation/ItemMoveAnimation.cs
nekoyume/Assets/_Scripts/UI/Widget/Hud/HpBar.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/CelebratesPopup.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs

vfx 로드 실패시에도 게임이 진행되도록 처리

---

.github/workflows/check-qa.yml

Ipdae patch 8

---

nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

fix inventory item order in pc shop

---

nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

문제가 발생할 수 있는 지점 수정 
- 해당 변경으로 기존에 동작하던 현상을 완벽하기 막을 순 없습니다
- 이벤트 구독 순서 꼬이는 경우 발생할 수 있는 케이스를 제거합니다

fix update assets

---

.github/bin/check-libplanet-version.sh
.github/workflows/build-misc.yml

- resolve #6692 
- lib9c가 libplanet을 서브모듈로 사용하지 않게 되면서 필요없어진 해당 job을 제거합니다.

Remove build_lib9c job

---

nekoyume/Assets/_Scripts/Debugger/NcDebug.cs
nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs

This pull request includes several changes to improve debugging and logging in the `nekoyume` project. The most important changes involve adding a new debug channel constant and updating logging statements to use this constant for better consistency and clarity.
* [`nekoyume/Assets/_Scripts/Debugger/NcDebug.cs`](diffhunk://#diff-ef736f9dd0a4fda6c8d7a9202ec11979e52c13d7cbf3423019503022648c9ddaR8-R9): Added a new constant `ChannelWidget` to the `NcDebug` class for consistent logging related to widgets.
* [`nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs`](diffhunk://#diff-0c360ad6d529f44edc57c42388189618342bbb2e258516541be0928df9f831abL278-R278): Updated the `Show` and `Close` methods to use the new `NcDebug.ChannelWidget` constant in their logging statements. …

add updateAssets log

---

nekoyume/Assets/_Scripts/Blockchain/Agent.cs

This pull request makes changes to the `nekoyume/Assets/_Scripts/Blockchain/Agent.cs` file. Specifically, it replaces `NotImplementedException` with placeholder return statements for several methods related to blockchain operations.
Changes to method implementations:
* [`GetUnbondClaimableHeightByStateRootHashAsync`](diffhunk://#diff-cff46460fbcaac73136d987df4ea3882b837d8217b9c988d4d41bce3d61c7f86L435-R454): Replaced `throw new NotImplementedException()` with a placeholder return statement (`return new Integer()`).
* [`GetClaimableRewardsByStateRootHashAsync`](diffhunk://#diff-cff46460fbcaac73136d987df4ea3882b837d8217b9c988d4d41bce3d61c7f86L435-R454): Replaced `throw new NotImplementedException()` with a placeholder return statement (`return new List()`).
* …

fix local agent rpc call func

---

nekoyume/Assets/_Scripts/Game/Scene/LoginScene.cs
nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs

This pull request includes several changes to the `LoginScene` class in `nekoyume/Assets/_Scripts/Game/Scene/LoginScene.cs` to improve the asynchronous processing and logging. The changes primarily involve converting coroutine methods to use `UniTask` for better performance and readability.
Conversion to `UniTask` for asynchronous processing:
* `private async UniTask CoLoginMobile(PlanetContext planetContext, Action<bool> loginCallback)`: Removed `.ToUniTask()` call for `HasPledgedAccountProcess` method.
* `private async UniTask HasPledgedAccountProcess(PlanetContext planetContext, Action<bool> loginCallback)`: Changed from `IEnumerator` to `UniTask` and updated the method calls within to use `await` instead of `yield return`. [[1]](diffhunk://#diff-29e19aadb2f6c1eedf49bfe71d5d2b7eb817e546 …

fix wait start button

---

nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
nekoyume/Assets/_Scripts/UI/Module/SynthesisInventory.cs

This pull request includes several changes to the `SpriteAtlas` in the `nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas` file and a small update to the `SynthesisInventory` script. The most important changes are the addition of new sprite references and the ordering of costume items based on their CP value.
Changes to `SynthesisInventory`:
* Added `using Nekoyume.Game;` to the imports in `SynthesisInventory.cs`
* Updated the `GetModels` method to order costume items by their CP value using the `CostumeStatSheet` from `TableSheets.Instance`.

sort costume items in synthesis popup

---

nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs

This pull request includes changes to enhance error handling in the `LoadPolicyInfo` method within the `PatrolReward` model. The most important changes are:
Error handling improvements:
* [`nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs`](diffhunk://#diff-6cc13713b2ef0880cb12c9056ebee94cb9939359e6f96901395b158a7ffedbe2R76-R77): Added a try-catch block to handle potential `InvalidOperationException` when no activated policy matches the criteria, logging an error message in such cases. [[1]](diffhunk://#diff-6cc13713b2ef0880cb12c9056ebee94cb9939359e6f96901395b158a7ffedbe2R76-R77) [[2]](diffhunk://#diff-6cc13713b2ef0880cb12c9056ebee94cb9939359e6f96901395b158a7ffedbe2R98-R102)

add try catch for patrol reward sheet

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

This pull request includes significant changes to the `Read` method in the `MailPopup` class to handle `PatrolRewardMail` objects. The changes involve implementing the previously unimplemented method to properly process and display rewards from patrol reward mails.
Key changes include:
* [`nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs`](diffhunk://#diff-7250c9b4338dfeac7f3eb05262cba0280ceffb634d2707fc71aafd3fcde3b4cfL967-R1018): Implemented the `Read` method for `PatrolRewardMail` to mark the mail as read, update the mailbox state, and log the mail read action.
* Added logic to extract and convert fungible asset values and items from `PatrolRewardMail` into `MailReward` objects, including handling material and item sheets to create the appropriate reward objects.
* Updated the …

implement patrol reward mail

---

nekoyume/Assets/StreamingAssets/Localization/common.csv

This pull request includes a minor localization update to the `common.csv` file. The change corrects the translation for the `UI_STAKING_SHARE_POWER_FORMAT` key in the Korean language.
Localization update:
* [`nekoyume/Assets/StreamingAssets/Localization/common.csv`](diffhunk://#diff-98d1566ff25314daa2b2a12f07f1c2f68f26b3466b72020b9be70b7059bd1748L2059-R2059): Corrected the translation for `UI_STAKING_SHARE_POWER_FORMAT` from "STAKING {0}%" to "STAKING Share {0}%".

fix staking share local key

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/MailReward.cs

This pull request includes several changes to the `nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs` and `nekoyume/Assets/_Scripts/UI/Module/MailReward.cs` files aimed at improving type consistency and handling nullable values more effectively. The most important changes include modifying the `MailReward` class to use `long` instead of `int` for the `Count` property and updating related code to accommodate this change.
Type consistency improvements:
* [`nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs`](diffhunk://#diff-0f08e40ec628cdd4aa728e0b0b4cff7bf842254e3ba68679d2883d0569ac14a2L2695-R2695): Changed the type of `Count` from `int` to `long` in various methods to ensure consistency and prevent potential overflows. …

fix mail reward in monster collection

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs

This pull request includes changes to the `ResponseStake` method in the `Blockchain/ActionRenderHandler.cs` file to improve the handling of staking data. The most important changes involve moving the retrieval of `stakingLevel` and `stakedNcg` variables to an earlier point in the method.
Changes to `ResponseStake` method:
* Moved the retrieval of `stakingLevel` and `stakedNcg` variables to before the `UpdateStakeStateAsync` and `UpdateAgentStateAsync` method calls.
* Removed the redundant retrieval of `stakingLevel` and `stakedNcg` variables later in the method.

fix staking level

---

nekoyume/Assets/_Scripts/UI/Module/Inventory.cs

This pull request includes changes to the sorting logic in the `SortInventoryInShop` method in the `Inventory.cs` file. The modifications ensure that items are now additionally sorted by their `ItemSubType`.
Improvements to inventory sorting:
* [`nekoyume/Assets/_Scripts/UI/Module/Inventory.cs`](diffhunk://#diff-7ccd62049e45fec5dc5fd35188609a0043e467fe8f376d0841cc184e06d390cfR1112): Added sorting by `ItemBase.ItemSubType` to the `SortInventoryInShop` method for both general and costume items. [[1]](diffhunk://#diff-7ccd62049e45fec5dc5fd35188609a0043e467fe8f376d0841cc184e06d390cfR1112) [[2]](diffhunk://#diff-7ccd62049e45fec5dc5fd35188609a0043e467fe8f376d0841cc184e06d390cfR1139)

add shop sort condition

---

nekoyume/Assets/_Scripts/UI/Module/Slider/SweepSlider.cs

슬라이더 최대 숫자가 0으로 세팅되는경우 숫자가 깨져서 슬라이더컴포넌트를 더 이상 사용하지 못하는 문제 수정.

fix unity slider nan value setting bug

---

nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs

This pull request includes multiple changes to the `UI_StakingPopup.prefab` file in the `nekoyume/Assets/Resources/UI/Prefabs` directory. The changes involve adjustments to various UI elements, including modifications to `RectTransform`, `MonoBehaviour`, and `PrefabInstance` components. Below are the most important changes grouped by theme:
* Added a new `unbondButton` element to the `MonoBehaviour` section.
* Adjusted the `m_AnchoredPosition` of a `RectTransform` element for more precise positioning.
* Updated the `m_Father` property of a `RectTransform` element to change its parent, and adjusted its `m_RootOrder`.
* Modified the `m_TransformParent` of multiple `PrefabInstance` elements to change their parent in the hierarchy. [[1]](diffhunk://#diff-90bcb6d299d520d5abcc79a6aab36ec75e062ec …

fix staking popup for unbond button

---

nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

- 아레나인포 캐싱제거(블록단위로 캐싱데이터를 먼저 확인하도록되어있어서 동일블록내의 갱신처리가 안되는문제가있었음)
- 아레나 join창 진입시 메달정보 캐싱되지않도록 수정
- 인터벌종료시 아레나인포 강제 갱신되도록 수정

remove arena info caching

---

nekoyume/Assets/_Scripts/Game/Game.cs
nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
nekoyume/Assets/_Scripts/Helper/FileHelper.cs
nekoyume/Assets/_Scripts/PlatformUtility/Platform.cs

- resolve #6902 
- 이 코드가 동작하기위해선 PlanetId별로 시트 데이터를 직접 서빙해야합니다.
- 지정된 버킷/PlanetId 경로에 있는 시트 데이터를 다운 받아서 저장시키고 노드에서 GetSheets를 호출하는대신 해당 시트를 사용하도록 처리합니다.

Download remote bucket sheet instead of GetSheets from node

---

nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs

- https://github.com/planetarium/NineChronicles.Headless/pull/2703 의 변경에 맞춰 grpc GetState로 받아온 IValue 압축을 해제합니다.

Decompress in get state

---

nekoyume/Assets/_Scripts/UI/Module/Stat/StatView.cs

This pull request includes a minor change to the `StatView` class in the `nekoyume/Assets/_Scripts/UI/Module/Stat/StatView.cs` file. The change ensures that the game object is deactivated when the `Hide` method is called.
* [`nekoyume/Assets/_Scripts/UI/Module/Stat/StatView.cs`](diffhunk://#diff-b9573291e9050c89573a4efa9f398bdabf68c4c60e437943d741ce6d4845df04R42): Added `gameObject.SetActive(false);` to the `Hide` method to deactivate the game object.

fix item view hide

---

nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs

1. Arena 라운드 정보 표시 기능 추가
- 현재 라운드와 전체 라운드 수를 표시하는 텍스트 UI 추가
- `UI_ARENA_ROUND_TEXT` L10n 키를 사용하여 다국어 지원
- 현재 라운드 인덱스와 전체 라운드 수를 계산하여 표시
- 블록 인덱스를 기반으로 현재 진행 중인 라운드 계산

add arena round text

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs

빌드 새로 뽑히는 경우 290에 머지, 아닌 경우 대기했다 백머지 후 dev에 머지하겠습니다
This pull request includes changes to the handling of world boss reward mails in the `ActionRenderHandler` and `MailPopup` classes. The most important changes include the removal of specific methods and the deprecation of a method.
Changes to `ActionRenderHandler`:
* Removed calls to `LocalLayerModifier.AddNewMail` and `OneLineSystem.Push` after claiming a world boss reward. (`nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs`)
Changes to `MailPopup`:
* Deprecated the `Read(WorldBossRewardMail worldBossRewardMail)` method and removed its body, indicating it should no longer be used. (`nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs`)

remove worldboss reward mail

---

nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossSeasonReward.cs

This pull request includes an update to the `WorldBossSeasonReward` class to improve the handling of user total damage calculations and display.
Changes to damage calculation and display:
* [`nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossSeasonReward.cs`](diffhunk://#diff-20d09ba02a5c9bf2c10d3de6384152fce6099a89a5f4fa41ece569f74b8b0371R87-L109): Moved the `userTotalDamage` assignment earlier and added a check for zero damage to set the `userTotalDamageText` and return early if either `userTotalDamage` or `worldBossTotalDamage` is zero. This ensures the damage text is properly formatted and avoids unnecessary calculations.

fix ui on userTotalDamage is 0

---

nekoyume/Assets/Resources/UI/Prefabs/WorldMapWorld.prefab
nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapStage.cs
nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapWorld.cs
nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs

1. 월드맵의 페이지와 토글을 요구사항에 맞게 동적으로 생성하고 관리하는 기능을 추가했습니다.
2. 페이지 인덱스가 3을 초과할 때 배경 이미지가 1~3 범위에서 순환되도록 수정했습니다.
3. 동적으로 생성된 페이지의 스테이지 버튼에 이벤트 핸들러 연결 기능을 개선했습니다.
- `EnsureEnoughPagesAndToggles()` 메서드 추가: 요구사항에 따라 페이지와 토글을 동적으로 생성/관리합니다.
- 필요한 경우 새 페이지와 토글을 생성하고, 요구사항보다 많은 경우 비활성화 처리합니다.
- 새 페이지의 스테이지 버튼에 이벤트 핸들러를 연결하여 기존 페이지와 동일하게 동작하도록 했습니다.
- 토글 그룹을 적절히 처리하여 활성화된 페이지 토글만 포함되도록 했습니다.
- `GetWorldMapBackground()` 메서드 수정: 페이지 인덱스가 3을 초과하고 해당 리소스가 없을 때 1~3 범위 내에서 순환되도록 처리했습니다.
- 원본 리소스가 있으면 그대로 사용하고, 없을 때만 순환 처리하여 호환성을 유지했습니다.
- 월드맵의 스테이지 버튼과 StageInformation 위젯 간의 이벤트 연결 코드를 개선했습니다.
- 새로 추가된 페이지의 스테이지 버튼에도 이벤트 핸들러가 연결되도록 개선했습니다.
1. 페이지와 토글 수를 자동으로 관리하여 다양한 스테이지 수에 유연하게 대응할 수 있습니다.
2. 페이지가 3개를 초과해도 배경 이미지가 제대로 표시됩니다.
3. 모든 스테이지 버튼이 올바르게 동작하여 UI의 일관성이 유지됩니다.
4. 불필요한 게임 오브젝트를 비활성화하여 리소스 사용을 최적화했습니다.
이 …

change-stage-page-dynamic

---

nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs

+ 아에 새로운 월드보스 시즌이 시작되기 전까지 worldBossState의 값은 바뀌지 않는 걸로 보여 새로 클라이언트에 캐싱된 worldBossState를 업데이트 하기 전에 worldBossState를 미리 가져온 다음 해당 값이 null이면 상태 업데이트 후 다시 가져오는걸로 구현해두었습니다.
This pull request includes significant changes to the `ActionRenderHandler` and `WorldBossStates` classes, focusing on refactoring and improving the handling of world boss rewards and states. The most important changes include removing the `WorldBossRewardMail` dependency, adding new methods for state retrieval, and replacing `Task` with `UniTask` for asynchronous operations.
Refactoring and dependency removal:
* [`nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs`](diffhunk://#diff-0f08e40ec628cdd4aa728e0b0b4cff7bf842254e3ba68679d2883d0569ac14a2L3451-L3478): Removed the dependency on `WorldBossRewardMail` in the …

remove world boss mail

---

nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs

This pull request includes changes to the `UpdateCommandLineOptions` method in the `PlanetSelector.cs` file to improve null safety. The changes ensure that the code does not throw a `NullReferenceException` when accessing properties of `rpcEndpoints`.
Improvements to null safety:
* [`nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs`](diffhunk://#diff-d3dbcd944b7797a9393f644f9cb8148382ee15bcc00eaa890f851f807fe60578L358-R374): Modified the conditions to use the null-conditional operator (`?.`) and the null-coalescing operator (`??`) to safely check for null values before accessing the properties of `rpcEndpoints`.

updaer init services

---

.github/workflows/build.yml

This pull request includes updates to the GitHub Actions workflow configuration to use a newer version of the Ubuntu runner.
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L160-R160): Updated the `runs-on` parameter from `ubuntu-20.04` to `ubuntu-24.04` in two places to ensure the workflow uses the latest Ubuntu version. [[1]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L160-R160) [[2]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L210-R210)

build ubuntu version update

---

nekoyume/Assets/AddressableAssets/UI/Module/EnhancementInventory.prefab

This pull request includes a minor adjustment to the `EnhancementInventory.prefab` file in the `RectTransform` configuration. The `m_SizeDelta` property was updated to increase the height of the UI element.
* [`nekoyume/Assets/AddressableAssets/UI/Module/EnhancementInventory.prefab`](diffhunk://#diff-60a5c25bcdf27a542ed97f3f59d07f408a37dac287f2b4735eaa758b46e08d5bL11616-R11616): Changed `m_SizeDelta` from `{x: 0, y: 300}` to `{x: 0, y: 350}` to increase the vertical size of the UI element.

fix enhancement inventory filter size delta

---

nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs

This pull request refactors the initialization logic in the `LiveAssetManager` and `EventBanner` classes to improve asynchronous handling and ensure better code maintainability. The most significant changes include converting coroutine-based methods to use `UniTask`, renaming variables for consistency, and updating the `EventBanner` initialization process.
* Converted `InitializeEvent` to an asynchronous method `InitializeEventAsync` using `UniTask`, replacing coroutine-based calls with `UniTask.WhenAll` for parallel asynchronous operations. (`LiveAssetManager.cs`, [[1]](diffhunk://#diff-f6e54e53a3bf13357244a21a674ac3f4511c1a7e3a50a7d27ed69408f6d4ac51L104-R103) [[2]](diffhunk://#diff-f6e54e53a3bf13357244a21a674ac3f4511c1a7e3a50a7d27ed69408f6d4ac51L120-R122)
* Updated the `Start` method in …

fix main net notice

---

nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs

This pull request refactors the logic for determining the number of worlds that can be unlocked and introduces helper methods to improve code readability and maintainability in the `WorldMap` class. The changes focus on modularizing calculations and ensuring consistent behavior when determining stage gaps and unlockable worlds.
* **Refactored `ShowManyWorldUnlockPopup` logic**: Adjusted the condition to return early if the last cleared stage ID is not found or if fewer than two worlds can be unlocked. The calculation for the number of unlockable worlds now uses a dynamic `stageGap` instead of a fixed value. (`[nekoyume/Assets/_Scripts/UI/Widget/WorldMap.csL426-R453](diffhunk://#diff-11f2bed614853e5f068842566577382f6c2d481522edb0218f5da0746eac41a3L426-R453)`)
* **Introduced …

fix ShowManyWorldUnlockPopup

---

nekoyume/Assets/StreamingAssets/Localization/world_name.csv
nekoyume/Assets/_Scripts/L10n/L10nManager.cs
nekoyume/nekoyume.sln.DotSettings

This pull request introduces support for a new world, "Vanaheim," in the game. The changes include adding localization data, updating the world ID mapping, and extending the user dictionary for spell-checking.
* Added "Vanaheim" (`WORLD_NAME_VANAHEIM`) to the localization file `world_name.csv` with translations for multiple languages.
* Updated the `LocalizeWorldName` method in `L10nManager.cs` to include a mapping for the world ID `9` to "Vanaheim."
* Added "VANAHEIM" to the user dictionary in `nekoyume.sln.DotSettings` to ensure proper handling of the term in development tools.

add WORLD_NAME_VANAHEIM

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs

This pull request refactors the `EventReleaseNotePopup` class to improve initialization and handling of asynchronous operations. The changes ensure that the popup's dependencies are fully initialized before proceeding with its functionality, using `UniTask` for asynchronous workflows. The most important changes include adding asynchronous initialization and refactoring the `Show` methods to handle these updates.
* Added `InitializeAsync` method to handle asynchronous initialization of the `LiveAssetManager`. This method waits until the manager is fully initialized before calling the synchronous `Initialize` method. (`[nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.csR178-R192](diffhunk://#diff-bf48ee0a66b8dbc88bb6124513bd04d6afe3aecdd041494083bdd874ea9441faR178-R192)`)
* …

fix event release note popup

---

nekoyume/ProjectSettings/ProjectSettings.asset

This pull request updates the icon assets in the `PlayerSettings` configuration for multiple platforms, including iPhone, iPad, Android, and App Store. The changes involve replacing old GUID references with new ones and adding new icon sizes and configurations for better platform compatibility.
* **iPhone/iPad Icons**: Updated GUID references for existing icons and added new icon configurations for sizes such as 60x60, 40x40, and 20x20, along with a new 1024x1024 App Store icon.
* **Android Icons**: Updated GUID references for existing icons and replaced them with new ones for various sizes (e.g., 432x432, 324x324).

rollback app icon from 1st anniversary

---

nekoyume/Assets/_Scripts/UI/Model/Rank.cs

This pull request refactors ranking-related methods in the `Rank.cs` file to improve code readability and consistency. The most significant changes involve updating how `AvatarAddress` is formatted and simplifying LINQ expressions by removing unnecessary code blocks.
* Changed the `AvatarAddress` field in both `FetchMyAdventureCpRanking` and `FetchMyStageRanking` methods to use a formatted string (`$"0x{myRecord.UserDocument.Id}"`) instead of directly accessing the `Address` property. [[1]](diffhunk://#diff-e7cba330640229d50bd2cbe6e1e3c8bec2de7cb40cc24c8dd77c7dbd554273c7L131-R131) [[2]](diffhunk://#diff-e7cba330640229d50bd2cbe6e1e3c8bec2de7cb40cc24c8dd77c7dbd554273c7L219-R219)
* Refactored the `LoadCraftRankingInfos` method by replacing multi-line LINQ `Select` expressions with …

fix mimir rank

---

nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab

- content size fitter를 제거해서 CP가 레벨 범위로 벗어나는걸 막습니다.

랭킹정보창에서 CP 영역 벗어나는 문제 해결

---

nekoyume/Assets/_Scripts/UI/Widget/Popup/SummonProbabilityPopup.cs

소환 정보창에서 코스튬 정렬이 제대로 안되는 버그 수정

코스튬 소환 정렬 버그 수정
